import {
  ProyekInfrastrukturItem,
  RowUtilitasItem,
  RowPenghijauanItem,
  RuasJaringanJalanItem,
  LaporanProgresKonstruksiItem,
  PematanganTanahItem,
} from './types';

// ==========================================
// DATASET NO. 6: PEMBANGUNAN INFRASTRUKTUR BP BATAM
// ==========================================
export const DATASET_6_PEMBANGUNAN_INFRASTRUKTUR: ProyekInfrastrukturItem[] = [
  {
    id: 'INF-01',
    kodePaket: 'BPB-INF-2025-001',
    namaPekerjaan: 'Pelebaran Jalan Sudirman Menjadi 5 Lajur (Tahap 4 Koridor Simpang KDA - Simpang Hang Nadim)',
    jenisPekerjaan: 'Peningkatan Jalan & Jembatan',
    lokasi: 'Jl. Jenderal Sudirman, Batam Centre',
    wilayah: 'Batam Centre',
    koordinat: { lat: 1.1275, lng: 104.0543, x: 55, y: 44 },
    paguAnggaran: 124500000000,
    nilaiKontrak: 118250000000,
    kontraktor: 'PT Wijaya Karya (Persero) Tbk - KSO',
    konsultanPengawas: 'PT Virama Karya (Persero)',
    tahunAnggaran: 2025,
    sumberDana: 'Multi-Years PNBP',
    waktuPelaksanaanHari: 360,
    progresRencana: 78.5,
    progresRealisasi: 81.2,
    deviasi: 2.7,
    progresKeuangan: 75.0,
    statusProgres: 'Ahead',
    volumePekerjaan: '4.8 Km (2 Jalur 10 Lajur + Median + Jalur Pedestrian)',
    keterangan: 'Pekerjaan pengaspalan lapis AC-WC dan instalasi box culvert utilitas sedang berjalan lancar.',
  },
  {
    id: 'INF-02',
    kodePaket: 'BPB-INF-2025-002',
    namaPekerjaan: 'Pembangunan Flyover Sei Ladi & Penataan Simpang U-Turn Sei Ladi',
    jenisPekerjaan: 'Peningkatan Jalan & Jembatan',
    lokasi: 'Simpang Sei Ladi - Sekupang',
    wilayah: 'Sekupang',
    koordinat: { lat: 1.1205, lng: 104.0042, x: 42, y: 46 },
    paguAnggaran: 142000000000,
    nilaiKontrak: 136800000000,
    kontraktor: 'PT Adhi Karya (Persero) Tbk',
    konsultanPengawas: 'PT Ciriajasa Engineering Consultants',
    tahunAnggaran: 2025,
    sumberDana: 'Multi-Years PNBP',
    waktuPelaksanaanHari: 420,
    progresRencana: 86.0,
    progresRealisasi: 88.4,
    deviasi: 2.4,
    progresKeuangan: 85.0,
    statusProgres: 'Ahead',
    volumePekerjaan: 'Bentang Jembatan 120 M + Oprit 850 M',
    keterangan: 'Ereksi PCI Girder selesai 100%, pengecoran slab lantai jembatan dan parapet barrier.',
  },
  {
    id: 'INF-03',
    kodePaket: 'BPB-INF-2025-003',
    namaPekerjaan: 'Pembangunan Saluran Drainase Utama Batam Centre & Kolam Retensi Baloi Indah',
    jenisPekerjaan: 'Pembangunan Drainase Utama & Pengendalian Banjir',
    lokasi: 'Koridor Baloi Indah - Taman Kota Mas',
    wilayah: 'Batam Centre',
    koordinat: { lat: 1.1352, lng: 104.0255, x: 48, y: 41 },
    paguAnggaran: 48500000000,
    nilaiKontrak: 45700000000,
    kontraktor: 'PT Bumi Duta Batam',
    konsultanPengawas: 'PT Yodya Karya (Persero)',
    tahunAnggaran: 2025,
    sumberDana: 'PNBP BP Batam',
    waktuPelaksanaanHari: 240,
    progresRencana: 64.0,
    progresRealisasi: 62.8,
    deviasi: -1.2,
    progresKeuangan: 58.0,
    statusProgres: 'On Schedule',
    volumePekerjaan: '2.400 M Saluran U-Ditch 4x3 M + Kolam Retensi 2,5 Ha',
    keterangan: 'Pemasangan sheet pile penahan tebing dan galian dasar kolam retensi.',
  },
  {
    id: 'INF-04',
    kodePaket: 'BPB-INF-2025-004',
    namaPekerjaan: 'Revitalisasi & Perpanjangan Dermaga Utara Pelabuhan Kargo Batu Ampar (Tahap 2)',
    jenisPekerjaan: 'Pembangunan Dermaga & Ponton Pelabuhan',
    lokasi: 'Kawasan Pelabuhan Batu Ampar',
    wilayah: 'Batu Ampar',
    koordinat: { lat: 1.1582, lng: 104.0028, x: 41, y: 32 },
    paguAnggaran: 215000000000,
    nilaiKontrak: 208500000000,
    kontraktor: 'PT PP (Persero) Tbk',
    konsultanPengawas: 'PT Indra Karya (Persero)',
    tahunAnggaran: 2025,
    sumberDana: 'Multi-Years PNBP',
    waktuPelaksanaanHari: 480,
    progresRencana: 58.0,
    progresRealisasi: 46.5,
    deviasi: -11.5,
    progresKeuangan: 42.0,
    statusProgres: 'Kritis (SCM)',
    volumePekerjaan: 'Perpanjangan Dermaga 350 M + Container Yard 4,2 Ha',
    keterangan: 'Terlambat karena kendala pemancangan tiang pancang pipa baja akibat batuan keras dasar laut. Diterbitkan SCM Tahap 1.',
  },
  {
    id: 'INF-05',
    kodePaket: 'BPB-INF-2025-005',
    namaPekerjaan: 'Peningkatan Jalan Koridor Akses KEK Nongsa Digital Park & Bandara Hang Nadim',
    jenisPekerjaan: 'Peningkatan Jalan & Jembatan',
    lokasi: 'Jl. Hang Jebat - Nongsa',
    wilayah: 'Nongsa',
    koordinat: { lat: 1.1645, lng: 104.0955, x: 67, y: 31 },
    paguAnggaran: 89000000000,
    nilaiKontrak: 84300000000,
    kontraktor: 'PT Marinda Utamaputra Subur',
    konsultanPengawas: 'PT Bina Karya (Persero)',
    tahunAnggaran: 2025,
    sumberDana: 'PNBP BP Batam',
    waktuPelaksanaanHari: 270,
    progresRencana: 72.0,
    progresRealisasi: 68.5,
    deviasi: -3.5,
    progresKeuangan: 65.0,
    statusProgres: 'Waspada',
    volumePekerjaan: '6.2 Km Pelebaran Menjadi 4 Lajur + Median',
    keterangan: 'Relokasi tiang utilitas PLN & pipa SPAM memerlukan percepatan koordinasi lintas dinas.',
  },
  {
    id: 'INF-06',
    kodePaket: 'BPB-INF-2025-006',
    namaPekerjaan: 'Pematangan Lahan (Cut & Fill) dan Akses Kawasan Industri Galang Rempang Eco-City',
    jenisPekerjaan: 'Pematangan Lahan & Cut/Fill Kawasan BSW',
    lokasi: 'Kawasan Sembulang & Dapur Enam, Pulau Rempang',
    wilayah: 'Rempang',
    koordinat: { lat: 0.8854, lng: 104.1482, x: 78, y: 82 },
    paguAnggaran: 185000000000,
    nilaiKontrak: 177400000000,
    kontraktor: 'PT Hutama Karya (Persero) Infrastruktur',
    konsultanPengawas: 'PT Virama Karya Wilayah Kepri',
    tahunAnggaran: 2025,
    sumberDana: 'APBN',
    waktuPelaksanaanHari: 365,
    progresRencana: 62.0,
    progresRealisasi: 65.2,
    deviasi: 3.2,
    progresKeuangan: 60.0,
    statusProgres: 'Ahead',
    volumePekerjaan: 'Area Cut & Fill 140 Hektar + Akses Jalan 8.5 Km',
    keterangan: 'Pekerjaan tanah galian dan timbunan subgrade berjalan sesuai target masterplan investasi.',
  },
  {
    id: 'INF-07',
    kodePaket: 'BPB-INF-2025-007',
    namaPekerjaan: 'Pembangunan Gedung Parkir Terpadu BIFZA & Pusat Pengendalian Operasi BP Batam',
    jenisPekerjaan: 'Pembangunan Gedung & Fasilitas Kawasan',
    lokasi: 'Komplek Kantor BP Batam, Batam Centre',
    wilayah: 'Batam Centre',
    koordinat: { lat: 1.1302, lng: 104.0531, x: 54, y: 42 },
    paguAnggaran: 62000000000,
    nilaiKontrak: 59100000000,
    kontraktor: 'PT Total Bangun Persada Batam KSO',
    konsultanPengawas: 'PT Artefak Arkindo',
    tahunAnggaran: 2025,
    sumberDana: 'PNBP BP Batam',
    waktuPelaksanaanHari: 300,
    progresRencana: 91.0,
    progresRealisasi: 92.5,
    deviasi: 1.5,
    progresKeuangan: 88.0,
    statusProgres: 'Ahead',
    volumePekerjaan: 'Gedung 6 Lantai (Kapasitas 650 Mobil & 1.200 Motor)',
    keterangan: 'Finishing arsitektur, instalasi lift, dan commissioning sistem smart parking barcode.',
  },
  {
    id: 'INF-08',
    kodePaket: 'BPB-INF-2025-008',
    namaPekerjaan: 'Pelebaran Jalan Yos Sudarso (Simpang Sengkuang - Simpang Batu Ampar)',
    jenisPekerjaan: 'Peningkatan Jalan & Jembatan',
    lokasi: 'Jl. Yos Sudarso, Batu Ampar',
    wilayah: 'Batu Ampar',
    koordinat: { lat: 1.1512, lng: 104.0152, x: 44, y: 35 },
    paguAnggaran: 74000000000,
    nilaiKontrak: 70800000000,
    kontraktor: 'PT Sumber Pembangunan Kepri',
    konsultanPengawas: 'PT Ciriajasa Engineering',
    tahunAnggaran: 2025,
    sumberDana: 'PNBP BP Batam',
    waktuPelaksanaanHari: 240,
    progresRencana: 100.0,
    progresRealisasi: 100.0,
    deviasi: 0.0,
    progresKeuangan: 100.0,
    statusProgres: 'Selesai',
    volumePekerjaan: '3.6 Km 5 Lajur Kanan-Kiri + Trotoar Granit',
    keterangan: 'Telah Provisional Hand Over (PHO) dan masuk masa pemeliharaan 365 hari kalender.',
  },
  {
    id: 'INF-09',
    kodePaket: 'BPB-INF-2025-009',
    namaPekerjaan: 'Pemasangan PJU Tenaga Surya Cerdas (Smart Solar Streetlight) Koridor Mukakuning - Tembesi',
    jenisPekerjaan: 'Pemasangan PJU & Utilitas Terpadu',
    lokasi: 'Jl. Letjen R. Suprapto, Mukakuning - Batu Aji',
    wilayah: 'Mukakuning',
    koordinat: { lat: 1.0712, lng: 104.0321, x: 50, y: 58 },
    paguAnggaran: 28500000000,
    nilaiKontrak: 26900000000,
    kontraktor: 'PT Surya Citra Batam Energi',
    konsultanPengawas: 'PT Virama Karya',
    tahunAnggaran: 2025,
    sumberDana: 'PNBP BP Batam',
    waktuPelaksanaanHari: 180,
    progresRencana: 95.0,
    progresRealisasi: 96.2,
    deviasi: 1.2,
    progresKeuangan: 90.0,
    statusProgres: 'Ahead',
    volumePekerjaan: '820 Titik Tiang PJU Hotdip Galvanized + IoT CMS Monitoring',
    keterangan: 'Instalasi solar battery pack dan commissioning sensor lux otomatis.',
  },
  {
    id: 'INF-10',
    kodePaket: 'BPB-INF-2025-010',
    namaPekerjaan: 'Pembangunan Normalisasi Saluran Pembuang Kali Harapan & Penggantian Box Culvert',
    jenisPekerjaan: 'Pembangunan Drainase Utama & Pengendalian Banjir',
    lokasi: 'Sei Harapan, Sekupang',
    wilayah: 'Sekupang',
    koordinat: { lat: 1.1122, lng: 103.9685, x: 32, y: 48 },
    paguAnggaran: 36000000000,
    nilaiKontrak: 33800000000,
    kontraktor: 'PT Riau Prima Perkasa',
    konsultanPengawas: 'PT Yodya Karya',
    tahunAnggaran: 2025,
    sumberDana: 'PNBP BP Batam',
    waktuPelaksanaanHari: 210,
    progresRencana: 80.0,
    progresRealisasi: 79.1,
    deviasi: -0.9,
    progresKeuangan: 75.0,
    statusProgres: 'On Schedule',
    volumePekerjaan: '3.100 M Pasangan Batu Kali Beton Bertulang + Crossing Double Box 3x2.5 M',
    keterangan: 'Pekerjaan pasangan batu kali dan normalisasi debit air menuju muara.',
  },
  {
    id: 'INF-11',
    kodePaket: 'BPB-INF-2025-011',
    namaPekerjaan: 'Pelebaran Jalan Akses Pelabuhan Telaga Punggur - Kabil Industrial Estate',
    jenisPekerjaan: 'Peningkatan Jalan & Jembatan',
    lokasi: 'Jl. Patimura, Kabil - Nongsa',
    wilayah: 'Nongsa',
    koordinat: { lat: 1.1395, lng: 104.1352, x: 74, y: 40 },
    paguAnggaran: 68000000000,
    nilaiKontrak: 64900000000,
    kontraktor: 'PT Modern Widya Tehnikal',
    konsultanPengawas: 'PT Bina Karya',
    tahunAnggaran: 2025,
    sumberDana: 'PNBP BP Batam',
    waktuPelaksanaanHari: 240,
    progresRencana: 55.0,
    progresRealisasi: 42.0,
    deviasi: -13.0,
    progresKeuangan: 38.0,
    statusProgres: 'Kritis (SCM)',
    volumePekerjaan: '5.1 Km Rigid Pavement Beton FS 45 untuk Muatan Sumbu Terberat (MST 10 Ton)',
    keterangan: 'Keterlambat pengiriman semen curah dan kendala lalu lintas trailer berat. Dilakukan Rapat SCM Tahap 2.',
  },
  {
    id: 'INF-12',
    kodePaket: 'BPB-INF-2025-012',
    namaPekerjaan: 'Pembangunan Dermaga Ponton Penumpang & Revitalisasi Ruang Tunggu Domestik Sekupang',
    jenisPekerjaan: 'Pembangunan Dermaga & Ponton Pelabuhan',
    lokasi: 'Pelabuhan Domestik Sekupang',
    wilayah: 'Sekupang',
    koordinat: { lat: 1.1189, lng: 103.9515, x: 28, y: 47 },
    paguAnggaran: 42000000000,
    nilaiKontrak: 39800000000,
    kontraktor: 'PT Marina Cipta Pratama',
    konsultanPengawas: 'PT Indra Karya',
    tahunAnggaran: 2025,
    sumberDana: 'PNBP BP Batam',
    waktuPelaksanaanHari: 210,
    progresRencana: 92.0,
    progresRealisasi: 94.0,
    deviasi: 2.0,
    progresKeuangan: 90.0,
    statusProgres: 'Ahead',
    volumePekerjaan: '2 Unit Ponton HDPE Terapung + Gangway Aluminium 32 M + Canopy Terminal',
    keterangan: 'Fabrikasi ponton terapung telah terpasang, instalasi mechanical electrical rampung.',
  },
];

// Rekap Total Pembangunan Berdasarkan Jenis Pekerjaan (JNS_PEK)
// Dataset No. 6: Digunakan untuk visual chart & breakdown
export const REKAP_JENIS_PEMBANGUNAN = [
  {
    jenisPekerjaan: 'Peningkatan Jalan & Jembatan',
    singkatan: 'Jalan & Jembatan',
    jumlahProyek: 22,
    totalPagu: 1248500000000, // Rp 1,24 T
    persentaseAnggaran: 44.0,
    panjangVolume: '68,4 Km Jalan + 3 Jembatan/Flyover',
    statusSelesai: 8,
    statusOnTrack: 11,
    statusKritis: 3,
    warna: '#0284c7', // Sky blue
  },
  {
    jenisPekerjaan: 'Pembangunan Drainase Utama & Pengendalian Banjir',
    singkatan: 'Drainase & Banjir',
    jumlahProyek: 14,
    totalPagu: 482000000000, // Rp 482 M
    persentaseAnggaran: 17.0,
    panjangVolume: '34,2 Km U-Ditch + 4 Kolam Retensi',
    statusSelesai: 5,
    statusOnTrack: 8,
    statusKritis: 1,
    warna: '#06b6d4', // Cyan
  },
  {
    jenisPekerjaan: 'Pembangunan Gedung & Fasilitas Kawasan',
    singkatan: 'Gedung & Kawasan',
    jumlahProyek: 8,
    totalPagu: 395000000000, // Rp 395 M
    persentaseAnggaran: 13.9,
    panjangVolume: '62.500 M² Lantai Bangunan Publik',
    statusSelesai: 3,
    statusOnTrack: 5,
    statusKritis: 0,
    warna: '#8b5cf6', // Purple
  },
  {
    jenisPekerjaan: 'Pematangan Lahan & Cut/Fill Kawasan BSW',
    singkatan: 'Pematangan Lahan',
    jumlahProyek: 5,
    totalPagu: 325000000000, // Rp 325 M
    persentaseAnggaran: 11.4,
    panjangVolume: '280 Hektar Area Siap Bangun',
    statusSelesai: 1,
    statusOnTrack: 4,
    statusKritis: 0,
    warna: '#f59e0b', // Amber
  },
  {
    jenisPekerjaan: 'Pembangunan Dermaga & Ponton Pelabuhan',
    singkatan: 'Dermaga & Pelabuhan',
    jumlahProyek: 5,
    totalPagu: 285000000000, // Rp 285 M
    persentaseAnggaran: 10.0,
    panjangVolume: '620 M Dermaga + 4 Ponton',
    statusSelesai: 2,
    statusOnTrack: 2,
    statusKritis: 1,
    warna: '#10b981', // Emerald
  },
  {
    jenisPekerjaan: 'Pemasangan PJU & Utilitas Terpadu',
    singkatan: 'PJU & Utilitas',
    jumlahProyek: 4,
    totalPagu: 104500000000, // Rp 104,5 M
    persentaseAnggaran: 3.7,
    panjangVolume: '2.140 Titik Lampu Solar + Ducting',
    statusSelesai: 2,
    statusOnTrack: 2,
    statusKritis: 0,
    warna: '#64748b', // Slate
  },
];

// ==========================================
// DATASET NO. 1: PERIZINAN PEMANFAATAN ROW UTILITAS
// ==========================================
export const DATASET_1_ROW_UTILITAS: RowUtilitasItem[] = [
  {
    id: 'ROW-U-001',
    nomorIzin: '503/BPB-DPI/ROW-UTL/0142/2025',
    tanggalTerbit: '2025-02-14',
    namaPemohon: 'PT Telekomunikasi Selular (Telkomsel) Tbk',
    jenisUtilitas: 'Fiber Optik (Telekomunikasi)',
    lokasiRuasJalan: 'Jl. Sudirman (Simpang KDA - Simpang Bandara Hang Nadim)',
    wilayah: 'Batam Centre',
    panjangGelaranMeter: 4800,
    kedalamanGalianMeter: 1.5,
    statusIzin: 'Dalam Pengawasan Konstruksi',
    masaBerlakuTahun: 5,
  },
  {
    id: 'ROW-U-002',
    nomorIzin: '503/BPB-DPI/ROW-UTL/0141/2025',
    tanggalTerbit: '2025-02-08',
    namaPemohon: 'PT Moya Indonesia (Air Batam Hilir - SPAM)',
    jenisUtilitas: 'Pipa Air Bersih / SPAM',
    lokasiRuasJalan: 'Jl. R.E. Martadinata - Koridor Pelabuhan Sekupang',
    wilayah: 'Sekupang',
    panjangGelaranMeter: 3250,
    kedalamanGalianMeter: 2.0,
    statusIzin: 'Berlaku',
    masaBerlakuTahun: 10,
  },
  {
    id: 'ROW-U-003',
    nomorIzin: '503/BPB-DPI/ROW-UTL/0138/2025',
    tanggalTerbit: '2025-01-22',
    namaPemohon: 'PT Perusahaan Gas Negara (PGN) Tbk SOR II',
    jenisUtilitas: 'Pipa Gas Bumi (PGN)',
    lokasiRuasJalan: 'Jl. Ahmad Yani (Simpang Panbil - Kawasan Industri Batamindo)',
    wilayah: 'Mukakuning',
    panjangGelaranMeter: 2100,
    kedalamanGalianMeter: 2.5,
    statusIzin: 'Selesai Rekondisi Aspal',
    masaBerlakuTahun: 15,
  },
  {
    id: 'ROW-U-004',
    nomorIzin: '503/BPB-DPI/ROW-UTL/0135/2025',
    tanggalTerbit: '2025-01-15',
    namaPemohon: 'PT Pelayanan Listrik Nasional Batam (PLN Batam)',
    jenisUtilitas: 'Kabel Listrik Bawah Tanah (PLN)',
    lokasiRuasJalan: 'Jl. Yos Sudarso (Simpang Kabil - Sengkuang)',
    wilayah: 'Batu Ampar',
    panjangGelaranMeter: 3700,
    kedalamanGalianMeter: 1.8,
    statusIzin: 'Dalam Pengawasan Konstruksi',
    masaBerlakuTahun: 10,
  },
  {
    id: 'ROW-U-005',
    nomorIzin: '503/BPB-DPI/ROW-UTL/0129/2024',
    tanggalTerbit: '2024-11-28',
    namaPemohon: 'PT Mora Telematika Indonesia (Moratelindo)',
    jenisUtilitas: 'Fiber Optik (Telekomunikasi)',
    lokasiRuasJalan: 'Jl. Hang Jebat - Kawasan KEK Nongsa Digital Park',
    wilayah: 'Nongsa',
    panjangGelaranMeter: 5400,
    kedalamanGalianMeter: 1.5,
    statusIzin: 'Berlaku',
    masaBerlakuTahun: 5,
  },
  {
    id: 'ROW-U-006',
    nomorIzin: '503/BPB-DPI/ROW-UTL/0122/2024',
    tanggalTerbit: '2024-10-14',
    namaPemohon: 'PT Indosat Ooredoo Hutchison Tbk',
    jenisUtilitas: 'Fiber Optik (Telekomunikasi)',
    lokasiRuasJalan: 'Jl. Brigjen Katamso (Tanjung Uncang - Simpang Basecamp)',
    wilayah: 'Batu Aji',
    panjangGelaranMeter: 4100,
    kedalamanGalianMeter: 1.4,
    statusIzin: 'Selesai Rekondisi Aspal',
    masaBerlakuTahun: 5,
  },
];

// Ringkasan Dataset No. 1
export const SUMMARY_ROW_UTILITAS = {
  totalPerizinan: 142,
  totalIzinTerbit: 142,
  totalPanjangGalianKm: 381.1,
  tingkatRekondisiPersen: 70.4,
  kategori: [
    { nama: 'Fiber Optik (Telekomunikasi)', jumlah: 64, persentase: 45.1, panjangTotalKm: 184.2 },
    { nama: 'Pipa Air Bersih / SPAM', jumlah: 38, persentase: 26.8, panjangTotalKm: 92.5 },
    { nama: 'Pipa Gas Bumi (PGN)', jumlah: 22, persentase: 15.5, panjangTotalKm: 48.0 },
    { nama: 'Kabel Listrik PLN Bawah Tanah', jumlah: 18, persentase: 12.6, panjangTotalKm: 56.4 },
  ],
  statusKonstruksi: {
    selesaiRekondisi: 98,
    dalamKonstruksi: 28,
    izinBaruTerbit: 16,
  },
};

// ==========================================
// DATASET NO. 2: PERIZINAN PEMANFAATAN ROW PENGHIJAUAN
// ==========================================
export const DATASET_2_ROW_PENGHIJAUAN: RowPenghijauanItem[] = [
  {
    id: 'ROW-P-001',
    nomorIzin: '503/BPB-DPI/ROW-HIJ/0086/2025',
    tanggalTerbit: '2025-02-18',
    namaPemohon: 'PT Batamindo Investment Management',
    kategoriPenghijauan: 'Adopsi Taman Korporasi CSR',
    lokasiRuasJalan: 'Median Jl. Ahmad Yani (Depan Pintu 1 - Pintu 3 Kawasan Industri)',
    wilayah: 'Mukakuning',
    luasAreaM2: 12500,
    jumlahPohonDitanam: 450,
    jenisTanaman: 'Pohon Tabebuya Kuning & Bougenville Rimbun',
    statusIzin: 'Aktif Terawat',
    masaBerlakuTahun: 3,
  },
  {
    id: 'ROW-P-002',
    nomorIzin: '503/BPB-DPI/ROW-HIJ/0085/2025',
    tanggalTerbit: '2025-02-05',
    namaPemohon: 'PT Panbil Sukses Mandiri (Panbil Industrial Estate)',
    kategoriPenghijauan: 'Penataan Jalur Hijau Median Jalan',
    lokasiRuasJalan: 'Jl. Kolonel Soegiono (Simpang Panbil - Duriangkang)',
    wilayah: 'Mukakuning',
    luasAreaM2: 9800,
    jumlahPohonDitanam: 320,
    jenisTanaman: 'Pohon Ketapang Kencana & Rumput Gajah Mini',
    statusIzin: 'Dalam Penanaman',
    masaBerlakuTahun: 3,
  },
  {
    id: 'ROW-P-003',
    nomorIzin: '503/BPB-DPI/ROW-HIJ/0081/2025',
    tanggalTerbit: '2025-01-20',
    namaPemohon: 'PT Citra Buana Prasida Tbk (Harbour Bay)',
    kategoriPenghijauan: 'Penataan Jalur Hijau Median Jalan',
    lokasiRuasJalan: 'Jl. Duyung & Koridor Depan Kawasan Harbour Bay',
    wilayah: 'Batu Ampar',
    luasAreaM2: 7400,
    jumlahPohonDitanam: 260,
    jenisTanaman: 'Palem Ekor Tupai & Pucuk Merah',
    statusIzin: 'Aktif Terawat',
    masaBerlakuTahun: 5,
  },
  {
    id: 'ROW-P-004',
    nomorIzin: '503/BPB-DPI/ROW-HIJ/0078/2024',
    tanggalTerbit: '2024-12-10',
    namaPemohon: 'PT Nongsa Digital Park (Kinema)',
    kategoriPenghijauan: 'Buffer Zone Konservasi',
    lokasiRuasJalan: 'Koridor Hijau Jl. Hang Lekiu Nongsa',
    wilayah: 'Nongsa',
    luasAreaM2: 18200,
    jumlahPohonDitanam: 680,
    jenisTanaman: 'Pohon Trembesi, Merbau Laut & Mahoni',
    statusIzin: 'Monitoring Triwulanan',
    masaBerlakuTahun: 5,
  },
  {
    id: 'ROW-P-005',
    nomorIzin: '503/BPB-DPI/ROW-HIJ/0074/2024',
    tanggalTerbit: '2024-11-05',
    namaPemohon: 'PT Sinarmas Land (Nongsa Sinar Mas Golf & Residence)',
    kategoriPenghijauan: 'Adopsi Taman Korporasi CSR',
    lokasiRuasJalan: 'Median Simpang Jam - Simpang Frengky Batam Centre',
    wilayah: 'Batam Centre',
    luasAreaM2: 8600,
    jumlahPohonDitanam: 310,
    jenisTanaman: 'Pohon Bungur Sakura & Puring Hias',
    statusIzin: 'Aktif Terawat',
    masaBerlakuTahun: 3,
  },
];

// Ringkasan Dataset No. 2
export const SUMMARY_ROW_PENGHIJAUAN = {
  totalPerizinan: 86,
  totalIzinTerbit: 86,
  totalLuasRuangHijauM2: 342600, // 34,2 Hektar
  totalLuasPenghijauanHa: 34.2,
  totalPohonDitanam: 14850,
  kategori: [
    { nama: 'Penataan Jalur Hijau Median Jalan', jumlah: 35, persentase: 40.7, luasM2: 138000 },
    { nama: 'Adopsi Taman Korporasi CSR', jumlah: 26, persentase: 30.2, luasM2: 104500 },
    { nama: 'Penanaman Pohon Pelindung Koridor', jumlah: 15, persentase: 17.5, luasM2: 58200 },
    { nama: 'Buffer Zone Konservasi Lingkungan', jumlah: 10, persentase: 11.6, luasM2: 41900 },
  ],
  status: {
    aktifTerawat: 68,
    dalamPenanaman: 12,
    monitoringEvaluasi: 6,
  },
};

// ==========================================
// DATASET NO. 3: RUAS JARINGAN JALAN BP BATAM
// ==========================================
export const DATASET_3_RUAS_JARINGAN_JALAN: RuasJaringanJalanItem[] = [
  {
    id: 'RUAS-01',
    kodeRuas: 'BPB-RJ-001',
    namaRuasJalan: 'Jl. Jenderal Sudirman (Simpang Jam/Laluan Madani - Bundaran Punggur)',
    klasifikasiFungsi: 'Arteri Primer',
    panjangKm: 14.8,
    lebarMeter: 35.0,
    jumlahLajur: 10,
    kondisiMantapKm: 14.2,
    kondisiTidakMantapKm: 0.6,
    persentaseMantap: 95.9,
    indeksIri: 2.8,
    wilayah: 'Batam Centre',
    volumeLaluLintasHarian: 78500,
    tahunPeningkatanTerakhir: 2024,
  },
  {
    id: 'RUAS-02',
    kodeRuas: 'BPB-RJ-002',
    namaRuasJalan: 'Jl. Yos Sudarso (Batu Ampar - Simpang Kabil)',
    klasifikasiFungsi: 'Arteri Primer',
    panjangKm: 11.5,
    lebarMeter: 32.0,
    jumlahLajur: 8,
    kondisiMantapKm: 10.9,
    kondisiTidakMantapKm: 0.6,
    persentaseMantap: 94.8,
    indeksIri: 3.1,
    wilayah: 'Batu Ampar',
    volumeLaluLintasHarian: 64200,
    tahunPeningkatanTerakhir: 2024,
  },
  {
    id: 'RUAS-03',
    kodeRuas: 'BPB-RJ-003',
    namaRuasJalan: 'Jl. Letjen R. Suprapto (Simpang Panbil - Simpang Barelang)',
    klasifikasiFungsi: 'Arteri Primer',
    panjangKm: 16.2,
    lebarMeter: 30.0,
    jumlahLajur: 8,
    kondisiMantapKm: 14.1,
    kondisiTidakMantapKm: 2.1,
    persentaseMantap: 87.0,
    indeksIri: 4.2,
    wilayah: 'Mukakuning',
    volumeLaluLintasHarian: 82000,
    tahunPeningkatanTerakhir: 2023,
  },
  {
    id: 'RUAS-04',
    kodeRuas: 'BPB-RJ-004',
    namaRuasJalan: 'Jl. Gajah Mada (Simpang Sei Ladi - Pelabuhan Domestik Sekupang)',
    klasifikasiFungsi: 'Kolektor Primer',
    panjangKm: 9.4,
    lebarMeter: 24.0,
    jumlahLajur: 6,
    kondisiMantapKm: 8.8,
    kondisiTidakMantapKm: 0.6,
    persentaseMantap: 93.6,
    indeksIri: 3.4,
    wilayah: 'Sekupang',
    volumeLaluLintasHarian: 45000,
    tahunPeningkatanTerakhir: 2024,
  },
  {
    id: 'RUAS-05',
    kodeRuas: 'BPB-RJ-005',
    namaRuasJalan: 'Jl. Hang Jebat - Hang Lekiu (Kawasan Nongsa Sambau - KEK NDP)',
    klasifikasiFungsi: 'Kolektor Primer',
    panjangKm: 12.6,
    lebarMeter: 20.0,
    jumlahLajur: 4,
    kondisiMantapKm: 10.8,
    kondisiTidakMantapKm: 1.8,
    persentaseMantap: 85.7,
    indeksIri: 4.5,
    wilayah: 'Nongsa',
    volumeLaluLintasHarian: 28000,
    tahunPeningkatanTerakhir: 2023,
  },
  {
    id: 'RUAS-06',
    kodeRuas: 'BPB-RJ-006',
    namaRuasJalan: 'Jl. Trans Barelang (Jembatan 1 Fisabilillah - Jembatan 4 Rempang)',
    klasifikasiFungsi: 'Arteri Sekunder',
    panjangKm: 24.5,
    lebarMeter: 18.0,
    jumlahLajur: 4,
    kondisiMantapKm: 21.0,
    kondisiTidakMantapKm: 3.5,
    persentaseMantap: 85.7,
    indeksIri: 4.8,
    wilayah: 'Rempang',
    volumeLaluLintasHarian: 19500,
    tahunPeningkatanTerakhir: 2022,
  },
];

// Ringkasan Ruas Jaringan Jalan (Dataset No. 3)
export const SUMMARY_RUAS_JARINGAN_JALAN = {
  totalRuasJalan: 184, // Sesuai data resmi kewenangan BP Batam
  totalPanjangJalanKm: 542.8,
  kondisiJalan: {
    baikKm: 382.2,
    sedangKm: 103.1,
    rusakRinganKm: 41.2,
    rusakBeratKm: 16.3,
    totalMantapKm: 485.3, // Baik + Sedang
    persentaseMantap: 89.4, // % Kemantapan Jalan
  },
  klasifikasiFungsi: [
    { nama: 'Arteri Primer', jumlahRuas: 18, panjangKm: 126.4, mantapPersen: 94.2 },
    { nama: 'Kolektor Primer', jumlahRuas: 42, panjangKm: 168.0, mantapPersen: 90.8 },
    { nama: 'Arteri Sekunder', jumlahRuas: 54, panjangKm: 141.6, mantapPersen: 87.5 },
    { nama: 'Kolektor Sekunder & Akses Industri', jumlahRuas: 70, panjangKm: 106.8, mantapPersen: 84.1 },
  ],
  distribusiWilayah: [
    { wilayah: 'Batam Centre', ruas: 48, panjangKm: 132.5, kemantapan: 93.8 },
    { wilayah: 'Batu Ampar & Bengkong', ruas: 36, panjangKm: 98.2, kemantapan: 91.5 },
    { wilayah: 'Mukakuning & Batu Aji', ruas: 42, panjangKm: 124.6, kemantapan: 88.2 },
    { wilayah: 'Sekupang', ruas: 28, panjangKm: 84.5, kemantapan: 90.4 },
    { wilayah: 'Nongsa & Kabil', ruas: 20, panjangKm: 68.0, kemantapan: 86.7 },
    { wilayah: 'Barelang & Rempang', ruas: 10, panjangKm: 35.0, kemantapan: 84.0 },
  ],
};

// ====================================================================
// DATASET NO. 4: LAPORAN PROGRES PEKERJAAN KONSTRUKSI TAHUN BERJALAN
// ====================================================================
export const DATASET_4_PROGRES_KONSTRUKSI: LaporanProgresKonstruksiItem[] = [
  {
    id: 'PRG-001',
    nomorKontrak: '01/PPK-JALAN/KTR/BPB/2025',
    namaPaket: 'Pelebaran Jalan Sudirman Menjadi 5 Lajur (Tahap 4 Koridor KDA - Hang Nadim)',
    satkerPPK: 'PPK Peningkatan Jalan & Jembatan',
    kontraktor: 'PT Wijaya Karya (Persero) Tbk - KSO',
    konsultanSupervisi: 'PT Virama Karya (Persero)',
    nilaiKontrakMiliar: 118.25,
    tanggalMulai: '2025-01-15',
    targetSelesai: '2025-12-20',
    durasiHari: 340,
    sisaHari: 98,
    rencanaFisikPersen: 78.5,
    realisasiFisikPersen: 81.2,
    deviasiFisikPersen: 2.7,
    realisasiKeuanganPersen: 75.0,
    gapFisikKeuangan: 6.2,
    statusKurvaS: 'Ahead',
    tingkatKritis: 'Aman',
    isuKendala: 'Tidak ada kendala mayor. Pasokan aspal hotmix dan agregat dari quarry galang lancar.',
    tindakLanjut: 'Percepatan pekerjaan marka jalan termoplastik dan pedestrian ramah disabilitas.',
  },
  {
    id: 'PRG-002',
    nomorKontrak: '02/PPK-JEMBATAN/KTR/BPB/2025',
    namaPaket: 'Pembangunan Flyover Sei Ladi & Penataan Simpang U-Turn Sei Ladi',
    satkerPPK: 'PPK Peningkatan Jalan & Jembatan',
    kontraktor: 'PT Adhi Karya (Persero) Tbk',
    konsultanSupervisi: 'PT Ciriajasa Engineering Consultants',
    nilaiKontrakMiliar: 136.80,
    tanggalMulai: '2024-11-01',
    targetSelesai: '2025-11-30',
    durasiHari: 395,
    sisaHari: 78,
    rencanaFisikPersen: 86.0,
    realisasiFisikPersen: 88.4,
    deviasiFisikPersen: 2.4,
    realisasiKeuanganPersen: 85.0,
    gapFisikKeuangan: 3.4,
    statusKurvaS: 'Ahead',
    tingkatKritis: 'Aman',
    isuKendala: 'Pengaturan rekayasa lalu lintas saat jam sibuk pagi/sore Sekupang - Batam Centre.',
    tindakLanjut: 'Koordinasi pos pantau bersama Ditpam & Satlantas Polresta Barelang.',
  },
  {
    id: 'PRG-003',
    nomorKontrak: '03/PPK-DRAINASE/KTR/BPB/2025',
    namaPaket: 'Pembangunan Saluran Drainase Utama Batam Centre & Kolam Retensi Baloi Indah',
    satkerPPK: 'PPK Drainase & Pengendalian Banjir',
    kontraktor: 'PT Bumi Duta Batam',
    konsultanSupervisi: 'PT Yodya Karya (Persero)',
    nilaiKontrakMiliar: 45.70,
    tanggalMulai: '2025-02-01',
    targetSelesai: '2025-09-30',
    durasiHari: 240,
    sisaHari: 45,
    rencanaFisikPersen: 64.0,
    realisasiFisikPersen: 62.8,
    deviasiFisikPersen: -1.2,
    realisasiKeuanganPersen: 58.0,
    gapFisikKeuangan: 4.8,
    statusKurvaS: 'On Schedule',
    tingkatKritis: 'Normal',
    isuKendala: 'Tingginya curah hujan lokal pada sore hari sempat menaikkan elevasi muka air galian.',
    tindakLanjut: 'Penambahan 2 unit pompa dewatering kapasitas 150 liter/detik untuk percepatan cor dasar.',
  },
  {
    id: 'PRG-004',
    nomorKontrak: '04/PPK-PELABUHAN/KTR/BPB/2025',
    namaPaket: 'Revitalisasi & Perpanjangan Dermaga Utara Pelabuhan Kargo Batu Ampar (Tahap 2)',
    satkerPPK: 'PPK Fasilitas Pelabuhan & Laut',
    kontraktor: 'PT PP (Persero) Tbk',
    konsultanSupervisi: 'PT Indra Karya (Persero)',
    nilaiKontrakMiliar: 208.50,
    tanggalMulai: '2024-09-15',
    targetSelesai: '2026-01-15',
    durasiHari: 485,
    sisaHari: 142,
    rencanaFisikPersen: 58.0,
    realisasiFisikPersen: 46.5,
    deviasiFisikPersen: -11.5,
    realisasiKeuanganPersen: 42.0,
    gapFisikKeuangan: 4.5,
    statusKurvaS: 'Kritis (SCM)',
    tingkatKritis: 'SCM 1',
    isuKendala: 'Kekerasan lapisan batuan dasar laut menyulitkan penetrasi tiang pancang baja D=1000mm.',
    tindakLanjut: 'Penerbitan Surat Peringatan Kontrak Kritis (SCM-1), mobilisasi alat hydraulic drilling rig tambahan.',
  },
  {
    id: 'PRG-005',
    nomorKontrak: '05/PPK-JALAN/KTR/BPB/2025',
    namaPaket: 'Peningkatan Jalan Koridor Akses KEK Nongsa Digital Park & Bandara Hang Nadim',
    satkerPPK: 'PPK Peningkatan Jalan & Jembatan',
    kontraktor: 'PT Marinda Utamaputra Subur',
    konsultanSupervisi: 'PT Bina Karya (Persero)',
    nilaiKontrakMiliar: 84.30,
    tanggalMulai: '2025-02-15',
    targetSelesai: '2025-11-15',
    durasiHari: 270,
    sisaHari: 86,
    rencanaFisikPersen: 72.0,
    realisasiFisikPersen: 68.5,
    deviasiFisikPersen: -3.5,
    realisasiKeuanganPersen: 65.0,
    gapFisikKeuangan: 3.5,
    statusKurvaS: 'Waspada',
    tingkatKritis: 'Normal',
    isuKendala: 'Tiang PLN dan crossing pipa transmisi SPAM belum seluruhnya direlokasi pada segmen Sta 3+200.',
    tindakLanjut: 'Rapat koordinasi teknis percepatan relokasi bersama PLN Batam dan PT Air Batam Hilir.',
  },
  {
    id: 'PRG-006',
    nomorKontrak: '06/PPK-LAHAN/KTR/BPB/2025',
    namaPaket: 'Pematangan Lahan (Cut & Fill) dan Akses Kawasan Industri Rempang Eco-City',
    satkerPPK: 'PPK Pematangan Kawasan BSW',
    kontraktor: 'PT Hutama Karya (Persero) Infrastruktur',
    konsultanSupervisi: 'PT Virama Karya Wilayah Kepri',
    nilaiKontrakMiliar: 177.40,
    tanggalMulai: '2025-01-10',
    targetSelesai: '2026-01-09',
    durasiHari: 365,
    sisaHari: 135,
    rencanaFisikPersen: 62.0,
    realisasiFisikPersen: 65.2,
    deviasiFisikPersen: 3.2,
    realisasiKeuanganPersen: 60.0,
    gapFisikKeuangan: 5.2,
    statusKurvaS: 'Ahead',
    tingkatKritis: 'Aman',
    isuKendala: 'Area lereng bukit membutuhkan bio-engineering penahan erosi selama musim penghujan.',
    tindakLanjut: 'Pemasangan geosintetik matting dan hidroseeding rumput vetiver penahan longsor.',
  },
  {
    id: 'PRG-007',
    nomorKontrak: '07/PPK-GEDUNG/KTR/BPB/2025',
    namaPaket: 'Pembangunan Gedung Parkir Terpadu BIFZA & Pusat Pengendalian Operasi BP Batam',
    satkerPPK: 'PPK Bangunan Gedung & Kawasan',
    kontraktor: 'PT Total Bangun Persada Batam KSO',
    konsultanSupervisi: 'PT Artefak Arkindo',
    nilaiKontrakMiliar: 59.10,
    tanggalMulai: '2024-10-15',
    targetSelesai: '2025-08-15',
    durasiHari: 300,
    sisaHari: 28,
    rencanaFisikPersen: 91.0,
    realisasiFisikPersen: 92.5,
    deviasiFisikPersen: 1.5,
    realisasiKeuanganPersen: 88.0,
    gapFisikKeuangan: 4.5,
    statusKurvaS: 'Ahead',
    tingkatKritis: 'Aman',
    isuKendala: 'Tahap komisioning genset cadangan dan sensor okupansi smart parking.',
    tindakLanjut: 'Uji fungsi sistem proteksi kebakaran dan persiapan pra-PHO bersama tim teknis.',
  },
  {
    id: 'PRG-008',
    nomorKontrak: '08/PPK-JALAN/KTR/BPB/2025',
    namaPaket: 'Pelebaran Jalan Akses Pelabuhan Telaga Punggur - Kabil Industrial Estate',
    satkerPPK: 'PPK Peningkatan Jalan & Jembatan',
    kontraktor: 'PT Modern Widya Tehnikal',
    konsultanSupervisi: 'PT Bina Karya (Persero)',
    nilaiKontrakMiliar: 64.90,
    tanggalMulai: '2025-02-10',
    targetSelesai: '2025-10-10',
    durasiHari: 240,
    sisaHari: 52,
    rencanaFisikPersen: 55.0,
    realisasiFisikPersen: 42.0,
    deviasiFisikPersen: -13.0,
    realisasiKeuanganPersen: 38.0,
    gapFisikKeuangan: 4.0,
    statusKurvaS: 'Kritis (SCM)',
    tingkatKritis: 'SCM 2',
    isuKendala: 'Keterlambatan penyediaan batching plant beton mutu FS 45 dan intensitas trailer peti kemas.',
    tindakLanjut: 'Diberikan peringatan SCM-2, kontraktor wajib tambah shift kerja malam dan batching plant cadangan.',
  },
];

// Data Kurva S Agregat Bulanan (Monitoring Eksekutif Rencana vs Realisasi Kumulatif 2025)
export const KURVA_S_AGREGAT_TAHUN_BERJALAN = [
  { bulan: 'Jan', target: 5.2, realisasi: 5.8, keuangan: 5.0 },
  { bulan: 'Feb', target: 12.8, realisasi: 13.5, keuangan: 12.0 },
  { bulan: 'Mar', target: 22.4, realisasi: 24.1, keuangan: 20.5 },
  { bulan: 'Apr', target: 33.5, realisasi: 34.2, keuangan: 31.0 },
  { bulan: 'Mei', target: 45.0, realisasi: 44.8, keuangan: 40.2 },
  { bulan: 'Jun', target: 56.4, realisasi: 55.1, keuangan: 51.5 },
  { bulan: 'Jul', target: 68.0, realisasi: 67.2, keuangan: 62.0 },
  { bulan: 'Agt', target: 79.5, realisasi: 78.8, keuangan: 73.4 },
  { bulan: 'Sep (P)', target: 88.0, realisasi: 86.5, keuangan: 81.0 },
  { bulan: 'Okt (T)', target: 94.2, realisasi: null, keuangan: null },
  { bulan: 'Nov (T)', target: 98.0, realisasi: null, keuangan: null },
  { bulan: 'Des (T)', target: 100.0, realisasi: null, keuangan: null },
];

// ====================================================================
// DATASET NO. 5: PEMATANGAN TANAH (BSW) (Satu Data Hal. 50)
// Atribut: SRNSOS, METADATA, SRS_ID, OBJECTID, NAMOBJ, REMARK, FCODE,
// KD_ANGG, TGL_MUL, TGL_SEL, KTGR_PEK, JNS_PEK, NM_PPK, NPAGU_F, NHPS_S,
// NKON_S, KONTRAKTOR, NPAGU_S, NHPS, NKON_S, SUPERVISI, VOL_PEK
// ====================================================================
export const DATASET_5_PEMATANGAN_TANAH: PematanganTanahItem[] = [
  {
    id: 'BSW-001',
    kodeAnggaran: '023.01.12.6022.BSW01',
    namaLokasiBsw: 'Pematangan Lahan (Cut & Fill) & Akses Kawasan Industri Rempang Eco-City Zona 1A',
    wilayahBsw: 'Rempang Eco-City',
    kategoriPekerjaan: 'Pematangan Tanah (BSW)',
    jenisPekerjaan: 'Cut & Fill dan Land Clearing Kawasan',
    namaPPK: 'Ir. Heru Gunawan, S.T., M.Sc.',
    nilaiPaguFisikMiliar: 185.00,
    nilaiHpsMiliar: 180.50,
    nilaiKontrakMiliar: 177.40,
    kontraktor: 'PT Hutama Karya (Persero) Infrastruktur',
    konsultanSupervisi: 'PT Virama Karya (Persero) Wilayah Kepri',
    tanggalMulai: '2025-01-10',
    tanggalSelesai: '2026-01-09',
    luasAreaHektar: 120.0,
    volumeCutFillM3: 1850000,
    volumePekerjaan: '120 Ha / 1.850.000 m³ Tanah',
    progresRealisasiPersen: 65.2,
    progresRencanaPersen: 62.0,
    deviasiPersen: 3.2,
    statusProgres: 'Ahead',
    kendala: 'Kelerengan perbukitan butuh terasering dan instalasi retaining wall penahan erosi.',
    subdit: 'Subdit Pematangan Kawasan & Lingkungan BSW',
  },
  {
    id: 'BSW-002',
    kodeAnggaran: '023.01.12.6022.BSW02',
    namaLokasiBsw: 'Pematangan Lahan Industri Berat & Dermaga Logistik Kabil Industrial Estate',
    wilayahBsw: 'Kabil Industrial',
    kategoriPekerjaan: 'Pematangan Tanah (BSW)',
    jenisPekerjaan: 'Pematangan Lahan & Stripping Top Soil',
    namaPPK: 'Ir. Heru Gunawan, S.T., M.Sc.',
    nilaiPaguFisikMiliar: 98.50,
    nilaiHpsMiliar: 96.00,
    nilaiKontrakMiliar: 93.80,
    kontraktor: 'PT Wijaya Karya Rekayasa Konstruksi',
    konsultanSupervisi: 'PT Bina Karya (Persero)',
    tanggalMulai: '2025-02-01',
    tanggalSelesai: '2025-11-30',
    luasAreaHektar: 65.0,
    volumeCutFillM3: 920000,
    volumePekerjaan: '65 Ha / 920.000 m³ Tanah',
    progresRealisasiPersen: 74.5,
    progresRencanaPersen: 71.0,
    deviasiPersen: 3.5,
    statusProgres: 'Ahead',
    kendala: 'Mobilisasi dump truck tanah urug melintasi jalur padat pipa gas PGN dan utilitas kabel.',
    subdit: 'Subdit Pematangan Kawasan & Lingkungan BSW',
  },
  {
    id: 'BSW-003',
    kodeAnggaran: '023.01.12.6022.BSW03',
    namaLokasiBsw: 'Pematangan Lahan Fasilitas Galangan Kapal & Maritim Tanjung Sengkuang',
    wilayahBsw: 'Tanjung Sengkuang',
    kategoriPekerjaan: 'Pematangan Tanah (BSW)',
    jenisPekerjaan: 'Cut & Fill Batuan Keras & Perataan Tapak',
    namaPPK: 'Dedi Setiawan, S.T., M.T.',
    nilaiPaguFisikMiliar: 54.00,
    nilaiHpsMiliar: 52.80,
    nilaiKontrakMiliar: 51.20,
    kontraktor: 'PT Nindya Karya (Persero)',
    konsultanSupervisi: 'PT Yodya Karya (Persero)',
    tanggalMulai: '2025-03-01',
    tanggalSelesai: '2025-10-31',
    luasAreaHektar: 35.0,
    volumeCutFillM3: 540000,
    volumePekerjaan: '35 Ha / 540.000 m³ Batuan & Tanah',
    progresRealisasiPersen: 58.0,
    progresRencanaPersen: 60.5,
    deviasiPersen: -2.5,
    statusProgres: 'Waspada',
    kendala: 'Kekerasan formasi batuan granit membutuhkan breaker hidraulik kapasitas ekstra besar.',
    subdit: 'Subdit Pematangan Kawasan & Lingkungan BSW',
  },
  {
    id: 'BSW-004',
    kodeAnggaran: '023.01.12.6022.BSW04',
    namaLokasiBsw: 'Pematangan Lahan Kawasan Terpadu Pariwisata & Rumah Sakit RSBP Sekupang Makmur',
    wilayahBsw: 'Sekupang Makmur',
    kategoriPekerjaan: 'Pematangan Tanah (BSW)',
    jenisPekerjaan: 'Cut & Fill Kontur Perbukitan Berundak',
    namaPPK: 'Dedi Setiawan, S.T., M.T.',
    nilaiPaguFisikMiliar: 66.00,
    nilaiHpsMiliar: 64.50,
    nilaiKontrakMiliar: 63.20,
    kontraktor: 'PT Bumi Duta Batam',
    konsultanSupervisi: 'PT Artefak Arkindo',
    tanggalMulai: '2024-11-15',
    tanggalSelesai: '2025-08-30',
    luasAreaHektar: 42.0,
    volumeCutFillM3: 680000,
    volumePekerjaan: '42 Ha / 680.000 m³ Tanah Berundak',
    progresRealisasiPersen: 88.0,
    progresRencanaPersen: 86.5,
    deviasiPersen: 1.5,
    statusProgres: 'Ahead',
    kendala: 'Penataan drainase sementara pencegah limpasan air hujan ke area RSBP Batam.',
    subdit: 'Subdit Pematangan Kawasan & Lingkungan BSW',
  },
  {
    id: 'BSW-005',
    kodeAnggaran: '023.01.12.6022.BSW05',
    namaLokasiBsw: 'Pematangan Lahan Pengembangan Koridor Perkotaan Batam Centre Timur (Danau Baloi)',
    wilayahBsw: 'Batam Centre Timur',
    kategoriPekerjaan: 'Pematangan Tanah (BSW)',
    jenisPekerjaan: 'Cut & Fill dan Reklamasi Kolam Penampung',
    namaPPK: 'Ir. Heru Gunawan, S.T., M.Sc.',
    nilaiPaguFisikMiliar: 34.00,
    nilaiHpsMiliar: 33.20,
    nilaiKontrakMiliar: 32.50,
    kontraktor: 'PT Marinda Utamaputra Subur',
    konsultanSupervisi: 'PT Ciriajasa Engineering Consultants',
    tanggalMulai: '2025-02-15',
    tanggalSelesai: '2025-09-15',
    luasAreaHektar: 18.0,
    volumeCutFillM3: 280000,
    volumePekerjaan: '18 Ha / 280.000 m³ Tanah',
    progresRealisasiPersen: 71.0,
    progresRencanaPersen: 70.0,
    deviasiPersen: 1.0,
    statusProgres: 'On Schedule',
    kendala: 'Penyediaan jalan akses pengangkut material yang tidak mengganggu perkantoran Pemko & BP.',
    subdit: 'Subdit Pematangan Kawasan & Lingkungan BSW',
  },
];

export const SUMMARY_PEMATANGAN_TANAH = {
  totalLokasi: 5,
  totalLuasHektar: 280.0,
  totalVolumeM3: 4270000,
  totalPaguMiliar: 437.5,
  totalKontrakMiliar: 418.1,
  rataRataProgres: 71.3,
  sebaranWilayah: [
    { wilayah: 'Rempang Eco-City', luasHa: 120.0, volumeM3: 1850000, progres: 65.2, status: 'Ahead' },
    { wilayah: 'Kabil Industrial', luasHa: 65.0, volumeM3: 920000, progres: 74.5, status: 'Ahead' },
    { wilayah: 'Tanjung Sengkuang', luasHa: 35.0, volumeM3: 540000, progres: 58.0, status: 'Waspada' },
    { wilayah: 'Sekupang Makmur', luasHa: 42.0, volumeM3: 680000, progres: 88.0, status: 'Ahead' },
    { wilayah: 'Batam Centre Timur', luasHa: 18.0, volumeM3: 280000, progres: 71.0, status: 'On Schedule' },
  ],
};

