import { MitraKerjasama, KpiPengendalianDataset, RekomendasiEvaluasiItem, LaporanPengawasanItem, KpiTahunanItem } from './types';

// DATASET RESMI SATU DATA BP BATAM HALAMAN 14 - DIREKTORAT PENGENDALIAN PENGUSAHAAN
export const KPI_DATASETS_PENGENDALIAN: KpiPengendalianDataset[] = [
  {
    nomorDataset: 3,
    namaDataset: 'PERSENTASE HASIL EVALUASI PENGENDALIAN DAN PEMBINAAN BADAN USAHA YANG DITINDAKLANJUTI',
    label: 'KPI % Hasil Evaluasi Pengendalian & Pembinaan BU Ditindaklanjuti',
    capaian: 94.6, // Persentase realisasi pengawasan & pengendalian yang ditindaklanjuti
    target: 90.0,
    satuan: '%',
    trend: '+4.6% di atas target tahunan',
    status: 'optimal',
    deskripsi: 'Persentase butir hasil evaluasi pengendalian operasional, kepatuhan tata kelola, dan pembinaan berkala pada Badan Usaha yang telah selesai ditindaklanjuti dan disahkan.',
    formula: '(Jumlah Rekomendasi Hasil Evaluasi Pengendalian & Pembinaan BU yang Ditindaklanjuti / Total Rekomendasi Hasil Evaluasi Pengendalian & Pembinaan BU) × 100%',
    sumberData: 'Direktorat Pengendalian Pengusahaan - Subdit Evaluasi & Pembinaan Badan Usaha',
  },
  {
    nomorDataset: 4,
    namaDataset: 'PERSENTASE HASIL PERBAIKAN, DAN PERUBAHAN KERJASAMA USAHA YANG DITINDAKLANJUTI',
    label: 'KPI % Hasil Perbaikan & Perubahan Kerjasama Usaha Ditindaklanjuti',
    capaian: 91.8, // Persentase tindak lanjut hasil audit/evaluasi
    target: 88.0,
    satuan: '%',
    trend: '+3.8% melampaui standar mutu',
    status: 'optimal',
    deskripsi: 'Persentase butir perbaikan klausul PKS, restrukturisasi skema finansial/bagi hasil, dan permohonan addendum kerja sama usaha yang telah diselesaikan secara legal dan operasional.',
    formula: '(Jumlah Perbaikan dan Perubahan PKS Kerjasama Usaha yang Ditindaklanjuti / Total Permohonan Perubahan & Temuan Perbaikan Kerjasama Usaha) × 100%',
    sumberData: 'Direktorat Pengendalian Pengusahaan - Subdit Evaluasi & Restrukturisasi Kerjasama',
  },
  {
    nomorDataset: 1,
    namaDataset: 'REKOMENDASI EVALUASI DAN PENGENDALIAN KERJASAMA PENGUSAHAAN BADAN USAHA',
    label: 'Rekomendasi Evaluasi & Pengendalian Kerjasama Badan Usaha',
    capaian: 48,
    target: 45,
    satuan: 'Rekomendasi',
    trend: '44 Selesai Ditindaklanjuti (91.8%)',
    status: 'optimal',
    deskripsi: 'Data statistik per tahun butir rekomendasi evaluasi dan pengendalian kerjasama pengusahaan badan usaha dengan atribut data: Tanggal, Bulan, Tahun, Judul, dan Rekomendasi.',
    formula: 'Akumulasi Butir Rekomendasi Pengendalian Kerjasama Pengusahaan BU per Periode Tahunan',
    sumberData: 'Direktorat Pengendalian Pengusahaan - Sistem Informasi Pengendalian Mitra (SIMP-BP)',
  },
  {
    nomorDataset: 2,
    namaDataset: 'LAPORAN PENGAWASAN PENGENDALIAN PENGUSAHAAN',
    label: 'Laporan Pengawasan Pengendalian Pengusahaan (Bulanan)',
    capaian: 12,
    target: 12,
    satuan: 'Dokumen Digital',
    trend: '100% Terverifikasi Lengkap',
    status: 'optimal',
    deskripsi: 'Dokumen digital laporan pengawasan pengendalian pengusahaan yang disusun dan disahkan setiap bulan sebagai instrumen monitoring berkala bagi pimpinan.',
    formula: 'Jumlah Dokumen Digital Laporan Pengawasan Pengendalian Pengusahaan Disahkan per Periode Bulanan',
    sumberData: 'Direktorat Pengendalian Pengusahaan BP Batam',
  },
];

// DATA TREN TAHUNAN DUA KPI UTAMA (SESUAI ATRIBUT SATU DATA: TAHUN & PERSENTASE)
export const DATA_KPI_TAHUNAN: KpiTahunanItem[] = [
  { tahun: '2023', persentaseEvaluasiPembinaan: 89.8, persentasePerbaikanPerubahan: 85.2, target: 85.0 },
  { tahun: '2024', persentaseEvaluasiPembinaan: 91.2, persentasePerbaikanPerubahan: 87.0, target: 88.0 },
  { tahun: '2025', persentaseEvaluasiPembinaan: 93.4, persentasePerbaikanPerubahan: 89.5, target: 90.0 },
  { tahun: '2026 (YTD)', persentaseEvaluasiPembinaan: 94.6, persentasePerbaikanPerubahan: 91.8, target: 90.0 },
];

// DATASET #1: REKOMENDASI EVALUASI DAN PENGENDALIAN KERJASAMA PENGUSAHAAN BADAN USAHA
// Atribut Data: TANGGAL, BULAN, TAHUN, JUDUL, REKOMENDASI
export const DAFTAR_REKOMENDASI_EVALUASI: RekomendasiEvaluasiItem[] = [
  {
    id: 'REK-2026-001',
    tanggal: '18',
    bulan: 'Februari',
    tahun: '2026',
    judul: 'Kerjasama BTO Pengembangan & Pengoperasian Bandara Hang Nadim',
    badanUsaha: 'BU Bandar Udara',
    rekomendasi: 'Percepatan penyelesaian overlay runway kedua dan integrasi sistem baggage handling kargo otomatis sesuai standar ICAO.',
    status: 'Selesai',
    kategori: 'Operasional & Teknis',
  },
  {
    id: 'REK-2026-002',
    tanggal: '05',
    bulan: 'Februari',
    tahun: '2026',
    judul: 'KSO Sistem Penyediaan Air Minum (SPAM) Hilir Batam',
    badanUsaha: 'BU SPAM',
    rekomendasi: 'Penambahan instalasi booster pump di kawasan Sei Lekop & Tanjungkertang serta percepatan perbaikan kebocoran pipa distribusi.',
    status: 'Selesai',
    kategori: 'Operasional & Teknis',
  },
  {
    id: 'REK-2026-003',
    tanggal: '28',
    bulan: 'Januari',
    tahun: '2026',
    judul: 'KSO Pengelolaan Terminal Peti Kemas Batu Ampar',
    badanUsaha: 'BU Pelabuhan',
    rekomendasi: 'Penyelarasan target produktivitas STS Crane elektrik minimal 26 box/jam dan digitalisasi gate system untuk efisiensi dwell time.',
    status: 'Selesai',
    kategori: 'Finansial / Bagi Hasil',
  },
  {
    id: 'REK-2026-004',
    tanggal: '22',
    bulan: 'Januari',
    tahun: '2026',
    judul: 'Konsesi Pengoperasian Dermaga Curah Kargo Kabil (Kabil Port)',
    badanUsaha: 'BU Pelabuhan',
    rekomendasi: 'Penyusunan Addendum PKS penyesuaian batasan alur kedalaman draft kapal -12 meter LWS dan legal drafting pembagian tarif labuh tambat.',
    status: 'Dalam Proses',
    kategori: 'Legal & Amandemen PKS',
  },
  {
    id: 'REK-2026-005',
    tanggal: '15',
    bulan: 'Januari',
    tahun: '2026',
    judul: 'KSO Pengolahan Limbah B3 Kawasan KPLI Kabil',
    badanUsaha: 'BU Fasilitas & Lingkungan',
    rekomendasi: 'Pembaruan sertifikasi emisi insinerator temperatur tinggi dan penguatan verifikasi baku mutu pengolahan air lindi.',
    status: 'Selesai',
    kategori: 'Operasional & Teknis',
  },
  {
    id: 'REK-2026-006',
    tanggal: '10',
    bulan: 'Januari',
    tahun: '2026',
    judul: 'Sewa Aset Bangunan Komersial Pusat Bisnis Mega Batam Centre',
    badanUsaha: 'Aset Properti & Komersial',
    rekomendasi: 'Penetapan jadwal angsuran pembayaran termin kedua dan penandatanganan komitmen pelunasan denda administratif tertunggak.',
    status: 'Dalam Proses',
    kategori: 'Finansial / Bagi Hasil',
  },
  {
    id: 'REK-2025-007',
    tanggal: '12',
    bulan: 'Desember',
    tahun: '2025',
    judul: 'Kontrak Manajemen Terminal Penumpang Internasional Sekupang',
    badanUsaha: 'BU Pelabuhan',
    rekomendasi: 'Implementasi autogate imigrasi terintegrasi dan sistem e-Ticketing sentral serta perbaikan ruang tunggu VIP.',
    status: 'Selesai',
    kategori: 'Kualitas Layanan / Standar Mutu',
  },
  {
    id: 'REK-2025-008',
    tanggal: '20',
    bulan: 'November',
    tahun: '2025',
    judul: 'BTO Kawasan Wisata Bahari & Marina Resort Barelang',
    badanUsaha: 'Aset Properti & Komersial',
    rekomendasi: 'Penyesuaian batas sempadan pantai dan revisi dokumen AMDAL perlindungan pesisir sesuai ketentuan KKP.',
    status: 'Dalam Proses',
    kategori: 'Legal & Amandemen PKS',
  },
  {
    id: 'REK-2025-009',
    tanggal: '14',
    bulan: 'Oktober',
    tahun: '2025',
    judul: 'KSO Fasilitas Cold Storage & Logistik Ikan Sekupang',
    badanUsaha: 'BU Pelabuhan',
    rekomendasi: 'Peningkatan kapasitas cadangan genset otomatis guna menjamin stabilitas suhu komoditas ekspor perikanan.',
    status: 'Selesai',
    kategori: 'Operasional & Teknis',
  },
  {
    id: 'REK-2025-010',
    tanggal: '03',
    bulan: 'September',
    tahun: '2025',
    judul: 'Pemanfaatan Sentra Kuliner & UMKM Batam Tourism Park',
    badanUsaha: 'Aset Properti & Komersial',
    rekomendasi: 'Penyediaan sistem pembayaran non-tunai QRIS terpadu dan penataan instalasi pengolahan air limbah domestik.',
    status: 'Selesai',
    kategori: 'Kualitas Layanan / Standar Mutu',
  },
  {
    id: 'REK-2025-011',
    tanggal: '18',
    bulan: 'Agustus',
    tahun: '2025',
    judul: 'Pengoperasian Jembatan Timbang & Depo Kontainer Tanjung Uncang',
    badanUsaha: 'BU Pelabuhan',
    rekomendasi: 'Kalibrasi ulang timbangan oleh Balai Metrologi dan integrasi data muatan truk ke dashboard pengawasan BP Batam.',
    status: 'Selesai',
    kategori: 'Operasional & Teknis',
  },
  {
    id: 'REK-2025-012',
    tanggal: '29',
    bulan: 'Juli',
    tahun: '2025',
    judul: 'KSO Panel Surya Apung PLTS Waduk Tembesi',
    badanUsaha: 'BU SPAM',
    rekomendasi: 'Pengujian kekuatan tambat panel surya apung terhadap variasi pasang surut air waduk pada musim hujan ekstrem.',
    status: 'Dalam Proses',
    kategori: 'Operasional & Teknis',
  },
];

// DATASET #2: LAPORAN PENGAWASAN PENGENDALIAN PENGUSAHAAN (DOKUMEN DIGITAL PERBULAN)
export const DAFTAR_LAPORAN_PENGAWASAN: LaporanPengawasanItem[] = [
  { id: 'LAP-01', bulan: 'Januari', tahun: '2026', judulLaporan: 'Laporan Pengawasan Kemitraan BU & Kepatuhan PKS Bulan Januari 2026', badanUsaha: 'Semua Badan Usaha', status: 'Terverifikasi', tanggalTerbit: '05 Feb 2026' },
  { id: 'LAP-02', bulan: 'Februari', tahun: '2026', judulLaporan: 'Laporan Pengawasan Kemitraan BU & Kepatuhan PKS Bulan Februari 2026', badanUsaha: 'Semua Badan Usaha', status: 'Terverifikasi', tanggalTerbit: '04 Mar 2026' },
  { id: 'LAP-03', bulan: 'Maret', tahun: '2026', judulLaporan: 'Laporan Pengawasan Kemitraan BU & Kepatuhan PKS Bulan Maret 2026', badanUsaha: 'Semua Badan Usaha', status: 'Dalam Review', tanggalTerbit: '20 Mar 2026' },
  { id: 'LAP-04', bulan: 'Desember', tahun: '2025', judulLaporan: 'Laporan Tahunan Pengawasan & Pengendalian Pengusahaan Tahun 2025', badanUsaha: 'Semua Badan Usaha', status: 'Terverifikasi', tanggalTerbit: '15 Jan 2026' },
];

// REKAP DISTRIBUSI MITRA PER SEKTOR BADAN USAHA
export const SEKTOR_BADAN_USAHA_LIST = [
  'Semua Sektor BU',
  'BU Pelabuhan',
  'BU Bandar Udara',
  'BU Air Minum & Sanitasi (SPAM)',
  'BU Fasilitas Lingkungan & Limbah',
  'Aset Properti & Komersial',
];

// DAFTAR PERJANJIAN KERJASAMA & KONTRAK KEMITRAAN DIT. PENGENDALIAN PENGUSAHAAN
export const DAFTAR_MITRA_PENGUSAHAAN: MitraKerjasama[] = [
  {
    id: 'PKS-BU-001',
    nomorPks: 'PKS.12/KA-BP/BU-BANDARA/2021',
    judulPerjanjian: 'Kerjasama Bangun-Guna-Serah (BTO) Pengembangan & Pengoperasian Bandara Hang Nadim',
    namaMitra: 'PT Bandara Internasional Batam (Konsorsium Angkasa Pura - Incheon - WIKA)',
    badanUsahaTerkait: 'BU Bandar Udara',
    skemaKerjasama: 'BTO / BOT',
    tahunMulai: '2021',
    tahunBerakhir: '2046',
    nilaiInvestasiMitra: 6890, // Miliar (Rp 6,89 T)
    targetSharingRevenueTahunan: 145.0, // Miliar
    realisasiSharingRevenueTahunan: 154.2, // Miliar
    statusPengendalian: 'Terlaksana Penuh',
    skorKepatuhanOperasional: 96,
    statusKepatuhan: 'Sangat Patuh',
    jadwalInspeksiTerakhir: '12 Februari 2026',
    jumlahAuditEvaluasi: 4,
    jumlahRekomendasiPerbaikan: 12,
    jumlahRekomendasiSelesai: 12,
    persentaseTindakLanjut: 100,
    statusTindakLanjut: 'Selesai Ditindaklanjuti',
    statusAddendum: 'Addendum Selesai Diterbitkan',
    catatanStrategis: 'Tahap 1 Terminal Khusus Kargo dan Runway Overlay selesai tepat waktu; kepatuhan pelaporan keuangan auditan Triwulan IV 100%.',
  },
  {
    id: 'PKS-BU-002',
    nomorPks: 'PKS.08/KA-BP/BU-SPAM/2022',
    judulPerjanjian: 'Kerjasama Pengoperasian dan Pemeliharaan Sistem Penyediaan Air Minum (SPAM) Hilir Batam',
    namaMitra: 'PT Air Batam Hilir (Moya Group Konsorsium)',
    badanUsahaTerkait: 'BU Air Minum & Sanitasi (SPAM)',
    skemaKerjasama: 'KSO',
    tahunMulai: '2022',
    tahunBerakhir: '2037',
    nilaiInvestasiMitra: 1250, // Miliar
    targetSharingRevenueTahunan: 95.0,
    realisasiSharingRevenueTahunan: 98.4,
    statusPengendalian: 'Terlaksana Penuh',
    skorKepatuhanOperasional: 91,
    statusKepatuhan: 'Sangat Patuh',
    jadwalInspeksiTerakhir: '28 Januari 2026',
    jumlahAuditEvaluasi: 6,
    jumlahRekomendasiPerbaikan: 18,
    jumlahRekomendasiSelesai: 17,
    persentaseTindakLanjut: 94.4,
    statusTindakLanjut: 'Selesai Ditindaklanjuti',
    statusAddendum: 'Addendum Selesai Diterbitkan',
    catatanStrategis: 'Tindak lanjut perbaikan tekanan air di titik ujung jaringan Sei Lekop & Bengkong telah terpasang booster pump terintegrasi SCADA.',
  },
  {
    id: 'PKS-BU-003',
    nomorPks: 'PKS.34/KA-BP/BU-PEL/2023',
    judulPerjanjian: 'Kemitraan Pengelolaan Terminal Peti Kemas Modern Batu Ampar (Super Post Panamax STS Crane)',
    namaMitra: 'PT Persero Batam (Kerjasama Operasi Bersama)',
    badanUsahaTerkait: 'BU Pelabuhan',
    skemaKerjasama: 'KSO',
    tahunMulai: '2023',
    tahunBerakhir: '2038',
    nilaiInvestasiMitra: 850,
    targetSharingRevenueTahunan: 88.0,
    realisasiSharingRevenueTahunan: 96.5,
    statusPengendalian: 'Terlaksana Penuh',
    skorKepatuhanOperasional: 94,
    statusKepatuhan: 'Sangat Patuh',
    jadwalInspeksiTerakhir: '05 Maret 2026',
    jumlahAuditEvaluasi: 4,
    jumlahRekomendasiPerbaikan: 14,
    jumlahRekomendasiSelesai: 13,
    persentaseTindakLanjut: 92.9,
    statusTindakLanjut: 'Selesai Ditindaklanjuti',
    statusAddendum: 'Tidak Ada Revisi',
    catatanStrategis: 'Peningkatan produktivitas bongkar muat dari 14 Box/Hour menjadi 26 Box/Hour pasca operasional STS Crane elektrik.',
  },
  {
    id: 'PKS-BU-004',
    nomorPks: 'PKS.19/KA-BP/BU-PEL/2020',
    judulPerjanjian: 'Pengoperasian Dermaga Curah Kargo Kabil & Pelayanan Labuh Tambat Industri Berat',
    namaMitra: 'PT Citra Pembina Pengangkutan Industri (Kabil Port)',
    badanUsahaTerkait: 'BU Pelabuhan',
    skemaKerjasama: 'Konsesi',
    tahunMulai: '2020',
    tahunBerakhir: '2040',
    nilaiInvestasiMitra: 420,
    targetSharingRevenueTahunan: 38.0,
    realisasiSharingRevenueTahunan: 39.2,
    statusPengendalian: 'Terlaksana Penuh',
    skorKepatuhanOperasional: 88,
    statusKepatuhan: 'Patuh Bersyarat',
    jadwalInspeksiTerakhir: '18 Februari 2026',
    jumlahAuditEvaluasi: 3,
    jumlahRekomendasiPerbaikan: 8,
    jumlahRekomendasiSelesai: 7,
    persentaseTindakLanjut: 87.5,
    statusTindakLanjut: 'Dalam Proses Amandemen',
    statusAddendum: 'Legal Drafting',
    catatanStrategis: 'Penyelarasan tarif labuh tambat tongkang baja dan penyesuaian batas alur kedalaman draft -12 meter LWS.',
  },
  {
    id: 'PKS-BU-005',
    nomorPks: 'PKS.05/KA-BP/BU-LIMBAH/2022',
    judulPerjanjian: 'Pengelolaan & Pemanfaatan Fasilitas Pengolahan Limbah B3 KPLI Kabil',
    namaMitra: 'PT Desa Air Cargo Batam (Konsorsium Eco Green)',
    badanUsahaTerkait: 'BU Fasilitas Lingkungan & Limbah',
    skemaKerjasama: 'KSO',
    tahunMulai: '2022',
    tahunBerakhir: '2032',
    nilaiInvestasiMitra: 210,
    targetSharingRevenueTahunan: 16.5,
    realisasiSharingRevenueTahunan: 17.8,
    statusPengendalian: 'Terlaksana Penuh',
    skorKepatuhanOperasional: 92,
    statusKepatuhan: 'Sangat Patuh',
    jadwalInspeksiTerakhir: '10 Januari 2026',
    jumlahAuditEvaluasi: 4,
    jumlahRekomendasiPerbaikan: 9,
    jumlahRekomendasiSelesai: 8,
    persentaseTindakLanjut: 88.9,
    statusTindakLanjut: 'Selesai Ditindaklanjuti',
    statusAddendum: 'Tidak Ada Revisi',
    catatanStrategis: 'Sertifikasi ISO 14001 dan pembaruan sistem insinerator temperatur tinggi sesuai baku mutu KLHK telah terlaksana.',
  },
  {
    id: 'PKS-BU-006',
    nomorPks: 'PKS.41/KA-BP/KOMERSIAL/2021',
    judulPerjanjian: 'Pemanfaatan & Sewa Aset Bangunan Komersial Pusat Bisnis Mega Batam Centre',
    namaMitra: 'PT Batam Centre Mega Land',
    badanUsahaTerkait: 'Aset Properti & Komersial',
    skemaKerjasama: 'Sewa Aset',
    tahunMulai: '2021',
    tahunBerakhir: '2031',
    nilaiInvestasiMitra: 165,
    targetSharingRevenueTahunan: 22.0,
    realisasiSharingRevenueTahunan: 19.8,
    statusPengendalian: 'Terlaksana Sebagian',
    skorKepatuhanOperasional: 79,
    statusKepatuhan: 'Pengawasan Khusus',
    jadwalInspeksiTerakhir: '22 Januari 2026',
    jumlahAuditEvaluasi: 5,
    jumlahRekomendasiPerbaikan: 11,
    jumlahRekomendasiSelesai: 7,
    persentaseTindakLanjut: 63.6,
    statusTindakLanjut: 'Keterlambatan Komitmen',
    statusAddendum: 'Negosiasi Syarat Fiskal',
    catatanStrategis: 'SP-1 Diberikan terkait tunggakan denda keterlambatan pembayaran sewa termin kedua; dalam mediasi restrukturisasi jadwal angsuran.',
  },
  {
    id: 'PKS-BU-007',
    nomorPks: 'PKS.17/KA-BP/BU-PEL/2023',
    judulPerjanjian: 'Pengoperasian Terminal Penumpang Internasional Sekupang & Marina Teluk Senimba',
    namaMitra: 'PT Sekupang Ferry Port Management',
    badanUsahaTerkait: 'BU Pelabuhan',
    skemaKerjasama: 'Kontrak Manajemen',
    tahunMulai: '2023',
    tahunBerakhir: '2028',
    nilaiInvestasiMitra: 95,
    targetSharingRevenueTahunan: 14.0,
    realisasiSharingRevenueTahunan: 15.1,
    statusPengendalian: 'Terlaksana Penuh',
    skorKepatuhanOperasional: 93,
    statusKepatuhan: 'Sangat Patuh',
    jadwalInspeksiTerakhir: '14 Februari 2026',
    jumlahAuditEvaluasi: 3,
    jumlahRekomendasiPerbaikan: 7,
    jumlahRekomendasiSelesai: 7,
    persentaseTindakLanjut: 100,
    statusTindakLanjut: 'Selesai Ditindaklanjuti',
    statusAddendum: 'Addendum Selesai Diterbitkan',
    catatanStrategis: 'Pemasangan Autogate Imigrasi Terintegrasi dan sistem e-Ticketing sentral selesai 100% dengan kepuasan pengguna 94%.',
  },
  {
    id: 'PKS-BU-008',
    nomorPks: 'PKS.26/KA-BP/KOMERSIAL/2024',
    judulPerjanjian: 'Pengembangan Kawasan Pariwisata Terpadu & Marina Resort Barelang Bridge 1',
    namaMitra: 'PT Bahtera Wisata Nusantara',
    badanUsahaTerkait: 'Aset Properti & Komersial',
    skemaKerjasama: 'BTO / BOT',
    tahunMulai: '2024',
    tahunBerakhir: '2044',
    nilaiInvestasiMitra: 380,
    targetSharingRevenueTahunan: 11.5,
    realisasiSharingRevenueTahunan: 11.2,
    statusPengendalian: 'Terlaksana Penuh',
    skorKepatuhanOperasional: 86,
    statusKepatuhan: 'Patuh Bersyarat',
    jadwalInspeksiTerakhir: '02 Maret 2026',
    jumlahAuditEvaluasi: 2,
    jumlahRekomendasiPerbaikan: 6,
    jumlahRekomendasiSelesai: 5,
    persentaseTindakLanjut: 83.3,
    statusTindakLanjut: 'Menunggu Verifikasi Mitra',
    statusAddendum: 'Legal Drafting',
    catatanStrategis: 'Proses amandemen master layout pelindung pantai sempadan jembatan; dokumen AMDAL telah direvisi.',
  },
];

// DATA TREN TRIWULAN (PELAKSANAAN PENGAWASAN VS TINDAK LANJUT PERBAIKAN)
export const TREN_PENGENDALIAN_TRIWULAN = [
  { triwulan: 'Q1 2025', targetPengawasan: 90, realisasiPengawasan: 92.1, targetTindakLanjut: 85, realisasiTindakLanjut: 87.4, setoranMiliar: 94.2 },
  { triwulan: 'Q2 2025', targetPengawasan: 90, realisasiPengawasan: 93.4, targetTindakLanjut: 85, realisasiTindakLanjut: 88.8, setoranMiliar: 102.8 },
  { triwulan: 'Q3 2025', targetPengawasan: 90, realisasiPengawasan: 94.0, targetTindakLanjut: 88, realisasiTindakLanjut: 90.5, setoranMiliar: 108.5 },
  { triwulan: 'Q4 2025', targetPengawasan: 90, realisasiPengawasan: 95.8, targetTindakLanjut: 88, realisasiTindakLanjut: 93.2, setoranMiliar: 113.2 },
  { triwulan: 'Q1 2026 (YTD)', targetPengawasan: 90, realisasiPengawasan: 94.6, targetTindakLanjut: 88, realisasiTindakLanjut: 91.8, setoranMiliar: 116.4 },
];

// DATA DISTRIBUSI SKEMA KEMITRAAN & STATUS KEPATUHAN
export const DISTRIBUSI_SKEMA_KERJASAMA = [
  { skema: 'KSO (Kerjasama Operasi)', jumlahMitra: 14, nilaiInvestasi: 4850, pnbpTahunan: 182.4, color: '#1F3864' },
  { skema: 'BTO / BOT (Bangun Guna Serah)', jumlahMitra: 8, nilaiInvestasi: 8640, pnbpTahunan: 168.5, color: '#2E75B6' },
  { skema: 'Sewa Aset Komersial', jumlahMitra: 12, nilaiInvestasi: 820, pnbpTahunan: 48.6, color: '#0284C7' },
  { skema: 'Konsesi Pengoperasian', jumlahMitra: 5, nilaiInvestasi: 1150, pnbpTahunan: 52.0, color: '#0D9488' },
  { skema: 'Kontrak Manajemen', jumlahMitra: 4, nilaiInvestasi: 340, pnbpTahunan: 22.1, color: '#F59E0B' },
];

// DATA PIPELINE TAHAPAN PERBAIKAN & RESTUKTURISASI KERJASAMA
export const PIPELINE_TAHAPAN_TINDAK_LANJUT = [
  { tahap: '1. Temuan & Evaluasi PKS', count: 48, persentase: 100, color: 'text-slate-700 bg-slate-100', desc: 'Rekomendasi teknis, audit & finansial' },
  { tahap: '2. Pembahasan & Mediasi Mitra', count: 47, persentase: 97.9, color: 'text-sky-700 bg-sky-50', desc: 'Konsolidasi butir perubahan dengan mitra' },
  { tahap: '3. Legal Drafting & Uji Kepatuhan', count: 45, persentase: 93.7, color: 'text-indigo-700 bg-indigo-50', desc: 'Penyusunan naskah addendum & kajian hukum' },
  { tahap: '4. Selesai Ditindaklanjuti / Addendum', count: 44, persentase: 91.8, color: 'text-emerald-700 bg-emerald-50', desc: 'Amandemen disahkan & operasional diperbaiki' },
];
