import { MitraKerjasama, KpiPengendalianDataset } from './types';

// DATASET RESMI SATU DATA BP BATAM HALAMAN 14 - DIREKTORAT PENGENDALIAN PENGUSAHAAN
export const KPI_DATASETS_PENGENDALIAN: KpiPengendalianDataset[] = [
  {
    nomorDataset: 3,
    namaDataset: 'Pelaksanaan dan Pengendalian Pengusahaan dan Kerja Sama Badan Usaha',
    label: 'KPI % Pelaksanaan & Pengendalian Pengusahaan BU',
    capaian: 94.6, // Persentase realisasi pengawasan & pengendalian
    target: 90.0,
    satuan: '%',
    trend: '+4.6% di atas target tahunan',
    status: 'optimal',
    deskripsi: 'Rasio kegiatan monitoring, audit operasional berkala, inspeksi kepatuhan SOP, dan evaluasi perjanjian kerja sama usaha yang terlaksana sesuai rencana kerja tahunan pengawasan.',
    formula: '(Jumlah Kegiatan Pengendalian & Pengawasan Terlaksana / Total Rencana Pengendalian & Pengawasan Tahunan) × 100%',
    sumberData: 'Direktorat Pengendalian Pengusahaan - Subdit Pengawasan & Kepatuhan Usaha',
  },
  {
    nomorDataset: 4,
    namaDataset: 'Hasil Perbaikan dan Perubahan Kerjasama Usaha yang Ditindaklanjuti',
    label: 'KPI % Hasil Perbaikan & Perubahan Kerjasama Ditindaklanjuti',
    capaian: 91.8, // Persentase tindak lanjut hasil audit/evaluasi
    target: 88.0,
    satuan: '%',
    trend: '+3.8% melampaui standar mutu',
    status: 'optimal',
    deskripsi: 'Persentase butir rekomendasi evaluasi kerja sama, klausul amandemen PKS/KSO, restrukturisasi skema finansial, dan pembenahan operasional mitra yang telah tuntas ditindaklanjuti secara legal dan operasional.',
    formula: '(Jumlah Butir Perbaikan & Perubahan PKS yang Selesai Ditindaklanjuti / Total Rekomendasi Hasil Evaluasi & Permohonan Perubahan Kerjasama) × 100%',
    sumberData: 'Direktorat Pengendalian Pengusahaan - Subdit Evaluasi & Restrukturisasi Kerjasama',
  },
  {
    nomorDataset: 1,
    namaDataset: 'Tingkat Kepatuhan Regulasi & Tata Kelola Pengusahaan Mitra',
    label: 'Indeks Kepatuhan Tata Kelola Mitra Usaha',
    capaian: 89.4,
    target: 85.0,
    satuan: '%',
    trend: 'Kategori Sangat Baik (Tingkat Kepatuhan Tinggi)',
    status: 'optimal',
    deskripsi: 'Tingkat pemenuhan kewajiban regulasi, pelaporan berkala, kepatuhan pembayaran bagi hasil, audit independen tahunan, dan standar mutu pelayanan mitra terhadap klausul PKS BP Batam.',
    formula: '(Total Nilai Rata-rata Pemenuhan Indikator Kepatuhan Mitra / Target Bobot Kepatuhan Kumulatif) × 100%',
    sumberData: 'Direktorat Pengendalian Pengusahaan - Sistem Informasi Pengendalian Mitra (SIMP-BP)',
  },
  {
    nomorDataset: 2,
    namaDataset: 'Realisasi Kontribusi Finansial & Bagi Hasil (Revenue Sharing) Kemitraan',
    label: 'Efektivitas Kontribusi Pendapatan Bagi Hasil Mitra',
    capaian: 106.3, // Capaian 106.3% dari target
    target: 100.0,
    satuan: '%',
    trend: 'Rp 418,7 Miliar terkumpul (Surplus +6,3%)',
    status: 'optimal',
    deskripsi: 'Rasio pencapaian penerimaan bagian pendapatan (revenue sharing / fee konsesi / sewa aset kerja sama) yang disetorkan mitra usaha ke kas PNBP BP Batam dibandingkan target APBN/RKA.',
    formula: '(Realisasi Setoran Bagi Hasil Mitra (Rp) / Target Penetapan Kontribusi Tahunan (Rp)) × 100%',
    sumberData: 'Direktorat Pengendalian Pengusahaan bekerja sama dengan Biro Keuangan BP Batam',
  },
];

// REKAP DISTRIBUSI MITRA PER SEKTOR BADAN USAHA
export const SEKTOR_BADAN_USAHA_LIST = [
  'Semua Sektor BU',
  'BU Pelabuhan',
  'BU Bandar Udara',
  'BU Air Minum & Sanitasi (SPAM)',
  'BU Fasilitas Lingkungan & Limbah',
  'Aset Properti & Komersial',
];

// DAFTAR PERJANJIAN KERJASAMA & KONTRAK KEMITRAAN DIT. PENGENDALIAN PENGUSAHAAN
export const DAFTAR_MITRA_PENGUSAHAAN: MitraKerjasama[] = [
  {
    id: 'PKS-BU-001',
    nomorPks: 'PKS.12/KA-BP/BU-BANDARA/2021',
    judulPerjanjian: 'Kerjasama Bangun-Guna-Serah (BTO) Pengembangan & Pengoperasian Bandara Hang Nadim',
    namaMitra: 'PT Bandara Internasional Batam (Konsorsium Angkasa Pura - Incheon - WIKA)',
    badanUsahaTerkait: 'BU Bandar Udara',
    skemaKerjasama: 'BTO / BOT',
    tahunMulai: '2021',
    tahunBerakhir: '2046',
    nilaiInvestasiMitra: 6890, // Miliar (Rp 6,89 T)
    targetSharingRevenueTahunan: 145.0, // Miliar
    realisasiSharingRevenueTahunan: 154.2, // Miliar
    statusPengendalian: 'Terlaksana Penuh',
    skorKepatuhanOperasional: 96,
    statusKepatuhan: 'Sangat Patuh',
    jadwalInspeksiTerakhir: '12 Februari 2026',
    jumlahAuditEvaluasi: 4,
    jumlahRekomendasiPerbaikan: 12,
    jumlahRekomendasiSelesai: 12,
    persentaseTindakLanjut: 100,
    statusTindakLanjut: 'Selesai Ditindaklanjuti',
    statusAddendum: 'Addendum Selesai Diterbitkan',
    catatanStrategis: 'Tahap 1 Terminal Khusus Kargo dan Runway Overlay selesai tepat waktu; kepatuhan pelaporan keuangan auditan Triwulan IV 100%.',
  },
  {
    id: 'PKS-BU-002',
    nomorPks: 'PKS.08/KA-BP/BU-SPAM/2022',
    judulPerjanjian: 'Kerjasama Pengoperasian dan Pemeliharaan Sistem Penyediaan Air Minum (SPAM) Hilir Batam',
    namaMitra: 'PT Air Batam Hilir (Moya Group Konsorsium)',
    badanUsahaTerkait: 'BU Air Minum & Sanitasi (SPAM)',
    skemaKerjasama: 'KSO',
    tahunMulai: '2022',
    tahunBerakhir: '2037',
    nilaiInvestasiMitra: 1250, // Miliar
    targetSharingRevenueTahunan: 95.0,
    realisasiSharingRevenueTahunan: 98.4,
    statusPengendalian: 'Terlaksana Penuh',
    skorKepatuhanOperasional: 91,
    statusKepatuhan: 'Sangat Patuh',
    jadwalInspeksiTerakhir: '28 Januari 2026',
    jumlahAuditEvaluasi: 6,
    jumlahRekomendasiPerbaikan: 18,
    jumlahRekomendasiSelesai: 17,
    persentaseTindakLanjut: 94.4,
    statusTindakLanjut: 'Selesai Ditindaklanjuti',
    statusAddendum: 'Addendum Selesai Diterbitkan',
    catatanStrategis: 'Tindak lanjut perbaikan tekanan air di titik ujung jaringan Sei Lekop & Bengkong telah terpasang booster pump terintegrasi SCADA.',
  },
  {
    id: 'PKS-BU-003',
    nomorPks: 'PKS.34/KA-BP/BU-PEL/2023',
    judulPerjanjian: 'Kemitraan Pengelolaan Terminal Peti Kemas Modern Batu Ampar (Super Post Panamax STS Crane)',
    namaMitra: 'PT Persero Batam (Kerjasama Operasi Bersama)',
    badanUsahaTerkait: 'BU Pelabuhan',
    skemaKerjasama: 'KSO',
    tahunMulai: '2023',
    tahunBerakhir: '2038',
    nilaiInvestasiMitra: 850,
    targetSharingRevenueTahunan: 88.0,
    realisasiSharingRevenueTahunan: 96.5,
    statusPengendalian: 'Terlaksana Penuh',
    skorKepatuhanOperasional: 94,
    statusKepatuhan: 'Sangat Patuh',
    jadwalInspeksiTerakhir: '05 Maret 2026',
    jumlahAuditEvaluasi: 4,
    jumlahRekomendasiPerbaikan: 14,
    jumlahRekomendasiSelesai: 13,
    persentaseTindakLanjut: 92.9,
    statusTindakLanjut: 'Selesai Ditindaklanjuti',
    statusAddendum: 'Tidak Ada Revisi',
    catatanStrategis: 'Peningkatan produktivitas bongkar muat dari 14 Box/Hour menjadi 26 Box/Hour pasca operasional STS Crane elektrik.',
  },
  {
    id: 'PKS-BU-004',
    nomorPks: 'PKS.19/KA-BP/BU-PEL/2020',
    judulPerjanjian: 'Pengoperasian Dermaga Curah Kargo Kabil & Pelayanan Labuh Tambat Industri Berat',
    namaMitra: 'PT Citra Pembina Pengangkutan Industri (Kabil Port)',
    badanUsahaTerkait: 'BU Pelabuhan',
    skemaKerjasama: 'Konsesi',
    tahunMulai: '2020',
    tahunBerakhir: '2040',
    nilaiInvestasiMitra: 420,
    targetSharingRevenueTahunan: 38.0,
    realisasiSharingRevenueTahunan: 39.2,
    statusPengendalian: 'Terlaksana Penuh',
    skorKepatuhanOperasional: 88,
    statusKepatuhan: 'Patuh Bersyarat',
    jadwalInspeksiTerakhir: '18 Februari 2026',
    jumlahAuditEvaluasi: 3,
    jumlahRekomendasiPerbaikan: 8,
    jumlahRekomendasiSelesai: 7,
    persentaseTindakLanjut: 87.5,
    statusTindakLanjut: 'Dalam Proses Amandemen',
    statusAddendum: 'Legal Drafting',
    catatanStrategis: 'Penyelarasan tarif labuh tambat tongkang baja dan penyesuaian batas alur kedalaman draft -12 meter LWS.',
  },
  {
    id: 'PKS-BU-005',
    nomorPks: 'PKS.05/KA-BP/BU-LIMBAH/2022',
    judulPerjanjian: 'Pengelolaan & Pemanfaatan Fasilitas Pengolahan Limbah B3 KPLI Kabil',
    namaMitra: 'PT Desa Air Cargo Batam (Konsorsium Eco Green)',
    badanUsahaTerkait: 'BU Fasilitas Lingkungan & Limbah',
    skemaKerjasama: 'KSO',
    tahunMulai: '2022',
    tahunBerakhir: '2032',
    nilaiInvestasiMitra: 210,
    targetSharingRevenueTahunan: 16.5,
    realisasiSharingRevenueTahunan: 17.8,
    statusPengendalian: 'Terlaksana Penuh',
    skorKepatuhanOperasional: 92,
    statusKepatuhan: 'Sangat Patuh',
    jadwalInspeksiTerakhir: '10 Januari 2026',
    jumlahAuditEvaluasi: 4,
    jumlahRekomendasiPerbaikan: 9,
    jumlahRekomendasiSelesai: 8,
    persentaseTindakLanjut: 88.9,
    statusTindakLanjut: 'Selesai Ditindaklanjuti',
    statusAddendum: 'Tidak Ada Revisi',
    catatanStrategis: 'Sertifikasi ISO 14001 dan pembaruan sistem insinerator temperatur tinggi sesuai baku mutu KLHK telah terlaksana.',
  },
  {
    id: 'PKS-BU-006',
    nomorPks: 'PKS.41/KA-BP/KOMERSIAL/2021',
    judulPerjanjian: 'Pemanfaatan & Sewa Aset Bangunan Komersial Pusat Bisnis Mega Batam Centre',
    namaMitra: 'PT Batam Centre Mega Land',
    badanUsahaTerkait: 'Aset Properti & Komersial',
    skemaKerjasama: 'Sewa Aset',
    tahunMulai: '2021',
    tahunBerakhir: '2031',
    nilaiInvestasiMitra: 165,
    targetSharingRevenueTahunan: 22.0,
    realisasiSharingRevenueTahunan: 19.8,
    statusPengendalian: 'Terlaksana Sebagian',
    skorKepatuhanOperasional: 79,
    statusKepatuhan: 'Pengawasan Khusus',
    jadwalInspeksiTerakhir: '22 Januari 2026',
    jumlahAuditEvaluasi: 5,
    jumlahRekomendasiPerbaikan: 11,
    jumlahRekomendasiSelesai: 7,
    persentaseTindakLanjut: 63.6,
    statusTindakLanjut: 'Keterlambatan Komitmen',
    statusAddendum: 'Negosiasi Syarat Fiskal',
    catatanStrategis: 'SP-1 Diberikan terkait tunggakan denda keterlambatan pembayaran sewa termin kedua; dalam mediasi restrukturisasi jadwal angsuran.',
  },
  {
    id: 'PKS-BU-007',
    nomorPks: 'PKS.17/KA-BP/BU-PEL/2023',
    judulPerjanjian: 'Pengoperasian Terminal Penumpang Internasional Sekupang & Marina Teluk Senimba',
    namaMitra: 'PT Sekupang Ferry Port Management',
    badanUsahaTerkait: 'BU Pelabuhan',
    skemaKerjasama: 'Kontrak Manajemen',
    tahunMulai: '2023',
    tahunBerakhir: '2028',
    nilaiInvestasiMitra: 95,
    targetSharingRevenueTahunan: 14.0,
    realisasiSharingRevenueTahunan: 15.1,
    statusPengendalian: 'Terlaksana Penuh',
    skorKepatuhanOperasional: 93,
    statusKepatuhan: 'Sangat Patuh',
    jadwalInspeksiTerakhir: '14 Februari 2026',
    jumlahAuditEvaluasi: 3,
    jumlahRekomendasiPerbaikan: 7,
    jumlahRekomendasiSelesai: 7,
    persentaseTindakLanjut: 100,
    statusTindakLanjut: 'Selesai Ditindaklanjuti',
    statusAddendum: 'Addendum Selesai Diterbitkan',
    catatanStrategis: 'Pemasangan Autogate Imigrasi Terintegrasi dan sistem e-Ticketing sentral selesai 100% dengan kepuasan pengguna 94%.',
  },
  {
    id: 'PKS-BU-008',
    nomorPks: 'PKS.26/KA-BP/KOMERSIAL/2024',
    judulPerjanjian: 'Pengembangan Kawasan Pariwisata Terpadu & Marina Resort Barelang Bridge 1',
    namaMitra: 'PT Bahtera Wisata Nusantara',
    badanUsahaTerkait: 'Aset Properti & Komersial',
    skemaKerjasama: 'BTO / BOT',
    tahunMulai: '2024',
    tahunBerakhir: '2044',
    nilaiInvestasiMitra: 380,
    targetSharingRevenueTahunan: 11.5,
    realisasiSharingRevenueTahunan: 11.2,
    statusPengendalian: 'Terlaksana Penuh',
    skorKepatuhanOperasional: 86,
    statusKepatuhan: 'Patuh Bersyarat',
    jadwalInspeksiTerakhir: '02 Maret 2026',
    jumlahAuditEvaluasi: 2,
    jumlahRekomendasiPerbaikan: 6,
    jumlahRekomendasiSelesai: 5,
    persentaseTindakLanjut: 83.3,
    statusTindakLanjut: 'Menunggu Verifikasi Mitra',
    statusAddendum: 'Legal Drafting',
    catatanStrategis: 'Proses amandemen master layout pelindung pantai sempadan jembatan; dokumen AMDAL telah direvisi.',
  },
];

// DATA TREN TRIWULAN (PELAKSANAAN PENGAWASAN VS TINDAK LANJUT PERBAIKAN)
export const TREN_PENGENDALIAN_TRIWULAN = [
  { triwulan: 'Q1 2025', targetPengawasan: 90, realisasiPengawasan: 92.1, targetTindakLanjut: 85, realisasiTindakLanjut: 87.4, setoranMiliar: 94.2 },
  { triwulan: 'Q2 2025', targetPengawasan: 90, realisasiPengawasan: 93.4, targetTindakLanjut: 85, realisasiTindakLanjut: 88.8, setoranMiliar: 102.8 },
  { triwulan: 'Q3 2025', targetPengawasan: 90, realisasiPengawasan: 94.0, targetTindakLanjut: 88, realisasiTindakLanjut: 90.5, setoranMiliar: 108.5 },
  { triwulan: 'Q4 2025', targetPengawasan: 90, realisasiPengawasan: 95.8, targetTindakLanjut: 88, realisasiTindakLanjut: 93.2, setoranMiliar: 113.2 },
  { triwulan: 'Q1 2026 (YTD)', targetPengawasan: 90, realisasiPengawasan: 94.6, targetTindakLanjut: 88, realisasiTindakLanjut: 91.8, setoranMiliar: 116.4 },
];

// DATA DISTRIBUSI SKEMA KEMITRAAN & STATUS KEPATUHAN
export const DISTRIBUSI_SKEMA_KERJASAMA = [
  { skema: 'KSO (Kerjasama Operasi)', jumlahMitra: 14, nilaiInvestasi: 4850, pnbpTahunan: 182.4, color: '#1F3864' },
  { skema: 'BTO / BOT (Bangun Guna Serah)', jumlahMitra: 8, nilaiInvestasi: 8640, pnbpTahunan: 168.5, color: '#2E75B6' },
  { skema: 'Sewa Aset Komersial', jumlahMitra: 12, nilaiInvestasi: 820, pnbpTahunan: 48.6, color: '#0284C7' },
  { skema: 'Konsesi Pengoperasian', jumlahMitra: 5, nilaiInvestasi: 1150, pnbpTahunan: 52.0, color: '#0D9488' },
  { skema: 'Kontrak Manajemen', jumlahMitra: 4, nilaiInvestasi: 340, pnbpTahunan: 22.1, color: '#F59E0B' },
];

// DATA PIPELINE TAHAPAN PERBAIKAN & RESTUKTURISASI KERJASAMA
export const PIPELINE_TAHAPAN_TINDAK_LANJUT = [
  { tahap: '1. Temuan & Evaluasi PKS', count: 48, persentase: 100, color: 'text-slate-700 bg-slate-100', desc: 'Rekomendasi teknis, audit & finansial' },
  { tahap: '2. Pembahasan & Mediasi Mitra', count: 47, persentase: 97.9, color: 'text-sky-700 bg-sky-50', desc: 'Konsolidasi butir perubahan dengan mitra' },
  { tahap: '3. Legal Drafting & Uji Kepatuhan', count: 45, persentase: 93.7, color: 'text-indigo-700 bg-indigo-50', desc: 'Penyusunan naskah addendum & kajian hukum' },
  { tahap: '4. Selesai Ditindaklanjuti / Addendum', count: 44, persentase: 91.8, color: 'text-emerald-700 bg-emerald-50', desc: 'Amandemen disahkan & operasional diperbaiki' },
];
