import {
  IkpMetricItem,
  SektorPerizinanItem,
  DomainSpbeItem,
  DimensiIkkItem,
  MasterplanProgressItem,
  SatuDatasetItem,
} from './types';

// ============================================================================
// 1. DATA RESMI PERJANJIAN KINERJA (PERKIN A2 / DEP A2) TAHUN 2025
// Nomor: 3/KA/8/2025 | Tanggal: 12 Agustus 2025
// Pihak Pertama: Sudirman Saad (Anggota/Deputi Bidang Kebijakan Strategis dan Perizinan - DEP A2)
// Pihak Kedua: Amsakar Achmad (Kepala BP Batam)
// ============================================================================

export const PERKIN_METADATA = {
  nomor: '3/KA/8/2025',
  tahun: 2025,
  tanggal: '12 Agustus 2025',
  pejabatPertama: 'Sudirman Saad',
  jabatanPertama: 'Anggota/Deputi Bidang Kebijakan Strategis dan Perizinan (DEP A2)',
  pejabatKedua: 'Amsakar Achmad',
  jabatanKedua: 'Kepala Badan Pengusahaan Batam',
  sasaranProgram: 'Meningkatnya kualitas kebijakan dan perizinan BP Batam',
  totalAnggaran: 75874783000, // Rp 75.874.783.000,-
  realisasiAnggaran: 28450120000, // Rp 28.450.120.000,- (37.5%)
  unitKerjaCount: 4,
  datasetCount: 64,
};

// 4 INDIKATOR KINERJA PROGRAM UTAMA (PERKIN A2 / DEP A2)
export const IKP_METRICS_LIST: IkpMetricItem[] = [
  {
    id: 'ikp-1-perencanaan',
    number: 1,
    code: 'IKP-1',
    title: 'Indeks Perencanaan Pembangunan',
    target: 92.0,
    realisasi: 94.2,
    satuan: 'Indeks',
    polarisasi: 'Maximize',
    periodePelaporan: 'Tahunan (Akumulasi Jan - Des)',
    sumberData: 'Pusat Perencanaan Program Strategis BP Batam',
    unitKerja: 'Pusat Perencanaan Program Strategis',
    unitId: 'pusat-perencanaan-program',
    paguKegiatan: 13663667000, // Rp 13.663.667.000,-
    kegiatanNama: 'Penyusunan Perencanaan Program Strategis',
    predikat: 'Sangat Baik',
    predikatColor: 'emerald',
    capaianPersen: 102.39,
    statusKinerja: 'Exceeded',
    keterangan: 'Mengukur kualitas perencanaan melalui Indeks Perencanaan Pembangunan Nasional (IPPN) Bappenas yang mengevaluasi keselarasan dokumen perencanaan Renstra, RKA, dan KRO dengan prioritas nasional.',
    formulaRingkas: 'Rentang 91-100: Sangat Baik | 81-90: Baik | 71-80: Cukup Baik | 61-70: Kurang | <60: Sangat Kurang',
  },
  {
    id: 'ikp-2-kebijakan',
    number: 2,
    code: 'IKP-2',
    title: 'Indeks Kualitas Kebijakan (IKK)',
    target: 65.0,
    realisasi: 71.8,
    satuan: 'Indeks',
    polarisasi: 'Maximize',
    periodePelaporan: 'Tahunan (Akumulasi Jan - Des)',
    sumberData: 'Pusat Harmonisasi Kebijakan Strategis',
    unitKerja: 'Pusat Harmonisasi Kebijakan Strategis',
    unitId: 'pusat-harmonisasi',
    paguKegiatan: 4547062000, // Rp 4.547.062.000,-
    kegiatanNama: 'Penyusunan Harmonisasi Kebijakan dan Pelayanan Dukungan Strategis',
    predikat: 'Cukup Baik',
    predikatColor: 'blue',
    capaianPersen: 110.46,
    statusKinerja: 'Exceeded',
    keterangan: 'Instrumen penilaian kualitas kebijakan pemerintah mencakup 4 tahapan: Perencanaan Kebijakan (Agenda Setting & Formulasi) serta Evaluasi Kemanfaatan (Implementasi & Evaluasi Kebijakan).',
    formulaRingkas: 'Rentang 91-100: Sangat Baik | 81-90: Baik | 71-80: Cukup Baik | 61-70: Kurang | <60: Sangat Kurang',
  },
  {
    id: 'ikp-3-spbe',
    number: 3,
    code: 'IKP-3',
    title: 'Tingkat Kematangan SPBE',
    target: 3.9,
    realisasi: 4.12,
    satuan: 'Indeks (0-5)',
    polarisasi: 'Maximize',
    periodePelaporan: 'Tahunan (Akumulasi Jan - Des)',
    sumberData: 'Pusat Data dan Sistem Informasi',
    unitKerja: 'Pusat Data dan Sistem Informasi',
    unitId: 'pdsi',
    paguKegiatan: 53782639000, // Rp 53.782.639.000,-
    kegiatanNama: 'Pengelolaan Data Center dan Teknologi Informasi',
    predikat: 'Level 4 (Implementatif & Terpadu)',
    predikatColor: 'indigo',
    capaianPersen: 105.64,
    statusKinerja: 'Exceeded',
    keterangan: 'Tingkat kematangan penerapan arsitektur SPBE pada 6 domain: proses bisnis, layanan, data & informasi, aplikasi, infrastruktur, dan keamanan siber yang terintegrasi dengan evaluasi belanja TIK.',
    formulaRingkas: 'Skala 0-5 | (0) Belum ada, (1) As-is, (2) To-be, (3) Gap Analysis, (4) Implementasi & Belanja TIK, (5) Reviu Berkala',
  },
  {
    id: 'ikp-4-ikm-ptsp',
    number: 4,
    code: 'IKP-4',
    title: 'IKM Pengguna Layanan PTSP',
    target: 86.5,
    realisasi: 88.42,
    satuan: 'Indeks',
    polarisasi: 'Maximize',
    periodePelaporan: 'Tahunan (Akumulasi Jan - Des)',
    sumberData: 'Pusat Pelayanan Terpadu Satu Pintu',
    unitKerja: 'Pusat Pelayanan Terpadu Satu Pintu',
    unitId: 'ptsp',
    paguKegiatan: 3881415000, // Rp 3.881.415.000,-
    kegiatanNama: 'Penyelenggaraan Pelayanan Terpadu Satu Pintu',
    predikat: 'Mutu A (Sangat Baik)',
    predikatColor: 'emerald',
    capaianPersen: 102.22,
    statusKinerja: 'Exceeded',
    keterangan: 'Pengukuran komprehensif tingkat kepuasan masyarakat terhadap kualitas perizinan investasi dan non-perizinan pada MPP Batam berpedoman pada 9 unsur PermenPAN-RB No. 14/2017.',
    formulaRingkas: 'Skala Konversi: 3.5324-4.00 (A, Sangat Baik = 88.31-100) | 3.0644-3.532 (B, Baik = 76.61-88.30)',
  },
];

// ============================================================================
// 2. 4 KEGIATAN PROGRAM & ALOKASI ANGGARAN (PAGU VS REALISASI)
// ============================================================================

export const PROGRAM_ACTIVITIES_BUDGET = [
  {
    id: 'kegiatan-1',
    nama: 'Penyusunan Perencanaan Program Strategis',
    unit: 'Pusren (P3S)',
    unitId: 'pusat-perencanaan-program',
    pagu: 13663667000,
    realisasi: 5210450000,
    serapanPersen: 38.13,
    outputUtama: 'Dokumen Renstra 2025-2029, RKA DIPA, 5 Masterplan Wilayah & Evaluasi SE PPN Bappenas',
    kodeDipa: '093.01.WA.6251.BMA',
  },
  {
    id: 'kegiatan-2',
    nama: 'Penyusunan Harmonisasi Kebijakan & Pelayanan Dukungan Strategis',
    unit: 'Pusat Harmonisasi (PHKS)',
    unitId: 'pusat-harmonisasi',
    pagu: 4547062000,
    realisasi: 1845200000,
    serapanPersen: 40.58,
    outputUtama: 'Kajian 4 Dimensi IKK, Uji Kewajaran 7 Level Tarif, Sinkronisasi Regulasi Internal-Eksternal',
    kodeDipa: '093.01.WA.6252.BMB',
  },
  {
    id: 'kegiatan-3',
    nama: 'Pengelolaan Data Center dan Teknologi Informasi',
    unit: 'PDSI',
    unitId: 'pdsi',
    pagu: 53782639000,
    realisasi: 19842100000,
    serapanPersen: 36.89,
    outputUtama: 'Tier-3 Data Center (96 Rak), Fiber Optik 210 Km, SOC Cyber Defense, SPBE Level 4 & 48 Aplikasi TTE',
    kodeDipa: '093.01.WA.6253.BMC',
  },
  {
    id: 'kegiatan-4',
    nama: 'Penyelenggaraan Pelayanan Terpadu Satu Pintu',
    unit: 'PTSP',
    unitId: 'ptsp',
    pagu: 3881415000,
    realisasi: 1552370000,
    serapanPersen: 39.99,
    outputUtama: 'Operasional Layanan MPP Batam, OSS-RBA, SKKBM/SKKAB, SLA Perizinan 91.2%, Survey IKM Mutu A',
    kodeDipa: '093.01.WA.6254.BMD',
  },
];

// ============================================================================
// 3. PROFIL 4 UNIT KERJA PELAKSANA KEBIJAKAN STRATEGIS & PERIZINAN
// ============================================================================

export interface KebijakanStrategisUnitProfile {
  id: string;
  code: string;
  name: string;
  shortName: string;
  pimpinan: string;
  paguAnggaran: number;
  realisasiAnggaran: number;
  serapanPersen: number;
  ikpTerhubung: string;
  targetIkp: string;
  realisasiIkp: string;
  datasetCount: number;
  pdfPages: string;
  ringkasanPeran: string;
  keyHighlights: { label: string; value: string; trend: string }[];
  isuStrategis: string;
}

export const KEBIJAKAN_STRATEGIS_UNITS: KebijakanStrategisUnitProfile[] = [
  {
    id: 'ptsp',
    code: 'PTSP',
    name: 'Pusat Pelayanan Terpadu Satu Pintu',
    shortName: 'PTSP',
    pimpinan: 'Kepala Pusat Pelayanan Terpadu Satu Pintu',
    paguAnggaran: 3881415000,
    realisasiAnggaran: 1552370000,
    serapanPersen: 39.99,
    ikpTerhubung: 'IKP-4: IKM Pengguna Layanan PTSP',
    targetIkp: '86.50',
    realisasiIkp: '88.42 (Mutu A)',
    datasetCount: 17,
    pdfPages: 'Halaman 21 - 28 (17 Dataset)',
    ringkasanPeran: 'Penyelenggaraan gerbang utama pelayanan perizinan berusaha OSS dan non-perizinan investasi, SKKBM bongkar muat, jadwal kapal, transformasi digital MPP Batam, dan penanganan pengaduan.',
    keyHighlights: [
      { label: 'Total Permohonan YTD', value: '1.842 Berkas', trend: '+14.2% vs 2024' },
      { label: 'Izin Terbit Resmi', value: '1.486 Izin', trend: '80.7% Success Rate' },
      { label: 'Kepatuhan SLA Rata-rata', value: '88.6%', trend: 'Target ≥85%' },
      { label: 'IKM Indeks Kepuasan', value: '88.42', trend: 'Predikat A (Sangat Baik)' },
    ],
    isuStrategis: 'Percepatan rekomendasi verifikasi teknis sektor kelautan & integrasi API verifikator eksternal guna memangkas backlog.',
  },
  {
    id: 'pusat-perencanaan-program',
    code: 'P3S',
    name: 'Pusat Perencanaan Program Strategis',
    shortName: 'Pusren',
    pimpinan: 'Kepala Pusat Perencanaan Program Strategis',
    paguAnggaran: 13663667000,
    realisasiAnggaran: 5210450000,
    serapanPersen: 38.13,
    ikpTerhubung: 'IKP-1: Indeks Perencanaan Pembangunan',
    targetIkp: '92.00',
    realisasiIkp: '94.20 (Sangat Baik)',
    datasetCount: 19,
    pdfPages: 'Halaman 51 - 53 (19 Dataset)',
    ringkasanPeran: 'Penyusunan Rencana Strategis (Renstra) 5 tahun, RKA DIPA tahunan, KRO/RO Bappenas, masterplan infrastruktur (drainase, jalan, utilitas box), serta rencana induk bandara dan pelabuhan.',
    keyHighlights: [
      { label: 'Indeks Keselarasan IPPN', value: '94.20', trend: 'Evaluasi Bappenas' },
      { label: 'Masterplan Strategis Aktif', value: '5 Dokumen', trend: '100% On Schedule' },
      { label: 'Capaian Sasaran Renstra', value: '96.8%', trend: 'Tercapai 28 dari 29 RO' },
      { label: 'Stakeholder Feedback Positif', value: '91.4%', trend: 'Survei 142 Asosiasi' },
    ],
    isuStrategis: 'Sinkronisasi revisi tata ruang KSPN Batam-Bintan-Karimun dengan pemutakhiran masterplan drainase & koridor utilitas.',
  },
  {
    id: 'pusat-harmonisasi',
    code: 'PHKS',
    name: 'Pusat Harmonisasi Kebijakan Strategis',
    shortName: 'Harmonisasi',
    pimpinan: 'Kepala Pusat Harmonisasi Kebijakan Strategis',
    paguAnggaran: 4547062000,
    realisasiAnggaran: 1845200000,
    serapanPersen: 40.58,
    ikpTerhubung: 'IKP-2: Indeks Kualitas Kebijakan (IKK)',
    targetIkp: '65.00',
    realisasiIkp: '71.80 (Cukup Baik)',
    datasetCount: 7,
    pdfPages: 'Halaman 12 - 13 (7 Dataset)',
    ringkasanPeran: 'Pengukuran dan evaluasi mutu regulasi BP Batam berbasis 4 dimensi IKK LAN-RI, harmonisasi Perka/Kepka dengan regulasi nasional, survei kewajaran 7 level tarif layanan, dan monitoring tindak lanjut rapim.',
    keyHighlights: [
      { label: 'Indeks Kualitas Kebijakan', value: '71.80', trend: '+6.80 poin di atas target' },
      { label: 'Regulasi Disinkronisasi', value: '42 Perka/Kepka', trend: '100% Selaras Pusat' },
      { label: 'Evaluasi Tarif Layanan', value: '7 Tingkat', trend: 'Survei Kewajaran 89.2%' },
      { label: 'Tindak Lanjut Rapim', value: '94.5%', trend: '76 dari 80 Nota Dinas' },
    ],
    isuStrategis: 'Harmonisasi regulasi turunan Perka pengalokasian lahan dan penyesuaian tarif terminal khusus sesuai PP 20/2024.',
  },
  {
    id: 'pdsi',
    code: 'PDSI',
    name: 'Pusat Data dan Sistem Informasi',
    shortName: 'PDSI',
    pimpinan: 'Kepala Pusat Data dan Sistem Informasi',
    paguAnggaran: 53782639000,
    realisasiAnggaran: 19842100000,
    serapanPersen: 36.89,
    ikpTerhubung: 'IKP-3: Tingkat Kematangan SPBE',
    targetIkp: '3.90',
    realisasiIkp: '4.12 (Level 4)',
    datasetCount: 21,
    pdfPages: 'Halaman 40 - 43 (21 Dataset)',
    ringkasanPeran: 'Tata kelola arsitektur SPBE terpadu, pengelolaan Tier-3 Data Center, penggelaran jaringan Fiber Optik pulau Batam, operasional Security Operation Center (SOC), integrasi Satu Data, dan 48 aplikasi ber-TTE.',
    keyHighlights: [
      { label: 'Indeks Kematangan SPBE', value: '4.12 / 5.0', trend: 'Kategori Sangat Baik' },
      { label: 'Uptime Data Center BP Batam', value: '99.98%', trend: 'SLA 99.9% Tercapai' },
      { label: 'Okupansi Rak Data Center', value: '78 / 96 Rak', trend: '81.25% Terisi' },
      { label: 'Serangan IT Terblokir SOC', value: '99.85%', trend: '12.450 Serangan Dihalau' },
    ],
    isuStrategis: 'Penyelesaian migrasi penuh modul microservices Satu Data BP Batam dan sertifikasi ISO 27001 data center.',
  },
];

// ============================================================================
// 4. DATA OPERASIONAL PTSP: VOLUME, SLA PER SEKTOR & BOTTLENECK ANALYSIS
// Mengacu pada Atribut Data Halaman 21-28 dan Referensi Gambar
// ============================================================================

export const PTSP_SEKTOR_PERFORMANCES: SektorPerizinanItem[] = [
  {
    sektor: 'Logistik & Transportasi Laut',
    kode: 'LOG',
    volume: 542,
    terbit: 494,
    proses: 32,
    revisi: 12,
    tolak: 4,
    slaPercent: 91.1,
    targetSla: 85.0,
    avgLeadTimeHari: 1.4,
    backlog: 18,
    status: 'optimal',
  },
  {
    sektor: 'Perdagangan & Jasa',
    kode: 'DAG',
    volume: 486,
    terbit: 413,
    proses: 48,
    revisi: 19,
    tolak: 6,
    slaPercent: 85.0,
    targetSla: 85.0,
    avgLeadTimeHari: 2.1,
    backlog: 34,
    status: 'optimal',
  },
  {
    sektor: 'Konstruksi & Properti',
    kode: 'KON',
    volume: 378,
    terbit: 281,
    proses: 56,
    revisi: 31,
    tolak: 10,
    slaPercent: 74.2,
    targetSla: 85.0,
    avgLeadTimeHari: 3.8,
    backlog: 49,
    status: 'warning',
  },
  {
    sektor: 'Kelautan & Perikanan',
    kode: 'LAU',
    volume: 246,
    terbit: 167,
    proses: 45,
    revisi: 26,
    tolak: 8,
    slaPercent: 68.0,
    targetSla: 85.0,
    avgLeadTimeHari: 5.4,
    backlog: 62,
    status: 'critical',
  },
  {
    sektor: 'Industri Manufaktur',
    kode: 'IND',
    volume: 190,
    terbit: 131,
    proses: 38,
    revisi: 16,
    tolak: 5,
    slaPercent: 79.5,
    targetSla: 85.0,
    avgLeadTimeHari: 2.9,
    backlog: 31,
    status: 'warning',
  },
];

// Tren Bulanan Permohonan PTSP (Jan - Apr 2026)
export const PTSP_MONTHLY_TREND = [
  { bulan: 'Januari', permohonan: 1420, terbit: 1190, SLA: 84.1, backlog: 180 },
  { bulan: 'Februari', permohonan: 1560, terbit: 1285, SLA: 83.5, backlog: 195 },
  { bulan: 'Maret', permohonan: 1710, terbit: 1390, SLA: 82.8, backlog: 204 },
  { bulan: 'April', permohonan: 1842, terbit: 1486, SLA: 82.4, backlog: 214 },
];

// Titik Hambatan Utama (Bottleneck Atensi Manajemen)
export const PTSP_BOTTLENECK_ITEMS = [
  {
    id: 1,
    judul: 'Keterlambatan verifikasi teknis sektor kelautan & TUKS',
    jumlahKasus: 31,
    level: 'critical',
    dampak: 'Aging dokumen > 14 hari kerja, memicu komplain pelaku usaha maritim',
    rekomendasi: 'Deploy tim verifikasi asistensi bersama Dit. Kepelabuhanan & KSOP',
  },
  {
    id: 2,
    judul: 'Kelengkapan dokumen lingkungan (Amdal/UKL-UPL) belum valid',
    jumlahKasus: 27,
    level: 'warning',
    dampak: 'Pengembalian berkas revisi berulang, menambah lead time perizinan',
    rekomendasi: 'Optimalkan sistem self-validation checklist pada portal MPP Digital',
  },
  {
    id: 3,
    judul: 'Latensi sinkronisasi API perizinan OSS-RBA BKPM ke SIMPADU',
    jumlahKasus: 19,
    level: 'warning',
    dampak: 'Status perizinan terbit tertahan sinkronisasi otomatis',
    rekomendasi: 'Koordinasi pembaruan webhook data bridge dengan PDSI & BKPM',
  },
];

// 9 Unsur IKM PTSP (PermenPAN-RB No. 14/2017)
export const PTSP_IKM_9_UNSUR = [
  { no: 1, unsur: 'Persyaratan Pelayanan', skor: 89.2, mutu: 'A (Sangat Baik)' },
  { no: 2, unsur: 'Sistem, Mekanisme, dan Prosedur', skor: 88.5, mutu: 'A (Sangat Baik)' },
  { no: 3, unsur: 'Waktu Penyelesaian Layanan', skor: 83.4, mutu: 'B (Baik)' },
  { no: 4, unsur: 'Biaya / Tarif Layanan', skor: 92.1, mutu: 'A (Sangat Baik)' },
  { no: 5, unsur: 'Produk Spesifikasi Layanan', skor: 88.9, mutu: 'A (Sangat Baik)' },
  { no: 6, unsur: 'Kompetensi Pelaksana Layanan', skor: 89.6, mutu: 'A (Sangat Baik)' },
  { no: 7, unsur: 'Perilaku Pelaksana Layanan', skor: 91.2, mutu: 'A (Sangat Baik)' },
  { no: 8, unsur: 'Penanganan Pengaduan & Saran', skor: 84.8, mutu: 'B (Baik)' },
  { no: 9, unsur: 'Sarana & Prasarana MPP', skor: 90.7, mutu: 'A (Sangat Baik)' },
];

// ============================================================================
// 5. DATA SPBE 6 DOMAIN & DATA CENTER (PDSI)
// Mengacu pada Atribut Data Halaman 40-43
// ============================================================================

export const SPBE_DOMAINS_DATA: DomainSpbeItem[] = [
  {
    domain: 'Kebijakan Internal SPBE',
    skor: 4.45,
    target: 4.0,
    bobot: 15,
    kategori: 'Sangat Baik',
    indikatorKunci: ['Perka Tata Kelola TIK', 'Standar Keamanan Informasi ISO 27001', 'Pedoman Satu Data BP Batam'],
  },
  {
    domain: 'Tata Kelola SPBE & Kelembagaan',
    skor: 4.25,
    target: 3.9,
    bobot: 20,
    kategori: 'Sangat Baik',
    indikatorKunci: ['Tim Koordinasi SPBE Lintas Unit', 'Arsitektur SPBE 2025-2029', 'Manajemen Risiko TIK'],
  },
  {
    domain: 'Manajemen SPBE & SDM TIK',
    skor: 3.95,
    target: 3.8,
    bobot: 15,
    kategori: 'Baik',
    indikatorKunci: ['Manajemen Keamanan Siber SOC', 'Audit Teknologi Informasi Berkala', 'Sertifikasi Keahlian TI'],
  },
  {
    domain: 'Layanan SPBE Administrasi Pemerintahan',
    skor: 4.30,
    target: 4.0,
    bobot: 20,
    kategori: 'Sangat Baik',
    indikatorKunci: ['SIMPADU Terpadu', 'Sistem Naskah Dinas Elektronik (TTE BSrE)', 'Dashboard BI Eksekutif'],
  },
  {
    domain: 'Layanan SPBE Pelayanan Publik',
    skor: 4.15,
    target: 3.9,
    bobot: 20,
    kategori: 'Sangat Baik',
    indikatorKunci: ['Portal MPP Digital Terintegrasi', 'Layanan Perizinan Online OSS', 'Helpdesk TI Terpusat'],
  },
  {
    domain: 'Infrastruktur & Keamanan Informasi',
    skor: 3.85,
    target: 3.8,
    bobot: 10,
    kategori: 'Baik',
    indikatorKunci: ['Tier-3 Data Center (99.98% Uptime)', 'Jalur Redundant Fiber Optik 210 Km', 'Pemberitahuan Insiden CSIRT'],
  },
];

export const PDSI_INFRASTRUCTURE_DATA = {
  dataCenter: {
    totalRak: 96,
    rakTerisi: 78,
    rakKosong: 18,
    okupansiPersen: 81.25,
    uptimeSla: 99.98,
    pueRatio: 1.38,
    generatorBackupKva: 1250,
  },
  fiberOptic: {
    totalPanjangKm: 210,
    jalurUtama: 'Ring Utama Batam Center - Batu Ampar - Mukakuning - Sekupang',
    coreAktif: 48,
    utilisasiPersen: 86.4,
  },
  cyberSecurity: {
    totalThreatYtd: 12450,
    threatMitigatedPersen: 99.85,
    avgResponseMinutes: 4.2,
    socAlertLevel: 'Normal / Hijau',
  },
  aplikasi: {
    totalAplikasiAktif: 48,
    terintegrasiTte: 42,
    terhubungSatuData: 48,
  },
};

// ============================================================================
// 6. DATA INDEKS KUALITAS KEBIJAKAN (IKK) & TARIF LAYANAN (PHKS)
// Mengacu pada Atribut Data Halaman 12-13
// ============================================================================

export const IKK_DIMENSI_DATA: DimensiIkkItem[] = [
  {
    dimensi: 'Agenda Setting Kebijakan',
    bobot: 20,
    skor: 74.5,
    target: 65.0,
    capaian: 114.6,
    tahapan: ['Identifikasi Masalah Strategis Kawasan', 'Uji Kebutuhan Regulasi Investasi', 'Riset Data Empiris & Kajian Akademis'],
  },
  {
    dimensi: 'Formulasi Kebijakan',
    bobot: 30,
    skor: 73.2,
    target: 65.0,
    capaian: 112.6,
    tahapan: ['Penyusunan Naskah Urgensi Regulasi', 'Harmonisasi Antar Instansi K/L/D', 'Konsultasi Publik dengan Pelaku Usaha'],
  },
  {
    dimensi: 'Implementasi Kebijakan',
    bobot: 25,
    skor: 70.8,
    target: 65.0,
    capaian: 108.9,
    tahapan: ['Sosialisasi Perka/Kepka Terbit', 'Kesiapan Petunjuk Teknis & SOP Unit', 'Alokasi Sumber Daya Pelaksana'],
  },
  {
    dimensi: 'Evaluasi Kemanfaatan Kebijakan',
    bobot: 25,
    skor: 68.6,
    target: 65.0,
    capaian: 105.5,
    tahapan: ['Survei Dampak Kebijakan Ekonomi', 'Uji Kewajaran Tarif Layanan Badan Usaha', 'Penyusunan Rekomendasi Revisi Kebijakan'],
  },
];

export const PHKS_TARIF_EVALUASI_DATA = [
  { level: 'Level 1: Kepelabuhanan', totalLayanan: 34, tarifBerlakuRata: 'Rp 450.000', kewajaranSurvei: 91.2, status: 'Valid' },
  { level: 'Level 2: Bandara Hang Nadim', totalLayanan: 26, tarifBerlakuRata: 'Rp 380.000', kewajaranSurvei: 88.7, status: 'Valid' },
  { level: 'Level 3: Pengelolaan Air SPAM', totalLayanan: 18, tarifBerlakuRata: 'Rp 6.800/m³', kewajaranSurvei: 87.4, status: 'Valid' },
  { level: 'Level 4: Limbah B3 KPLI', totalLayanan: 22, tarifBerlakuRata: 'Rp 1.250.000/ton', kewajaranSurvei: 89.6, status: 'Valid' },
  { level: 'Level 5: Rumah Sakit RSBP', totalLayanan: 84, tarifBerlakuRata: 'Tarif INA-CBGs & PMK', kewajaranSurvei: 92.5, status: 'Valid' },
  { level: 'Level 6: Pemanfaatan Lahan', totalLayanan: 15, tarifBerlakuRata: 'Sesuai Zona Nilai Tanah', kewajaranSurvei: 84.2, status: 'Penyesuaian' },
  { level: 'Level 7: Wisata & Fasilitas', totalLayanan: 19, tarifBerlakuRata: 'Rp 15.000 - Rp 250.000', kewajaranSurvei: 93.1, status: 'Valid' },
];

// ============================================================================
// 7. DATA PERENCANAAN STRATEGIS & MASTERPLAN (PUSREN / P3S)
// Mengacu pada Atribut Data Halaman 51-53
// ============================================================================

export const PUSREN_MASTERPLAN_PROGRESS: MasterplanProgressItem[] = [
  {
    nama: 'Masterplan Drainase Utama Kota Batam',
    kode: 'MP-DRAIN',
    kategori: 'Infrastruktur Pengendalian Banjir',
    progresPersen: 88.5,
    targetTahun: 2025,
    anggaran: 3850000000,
    status: 'On Track',
  },
  {
    nama: 'Masterplan Koridor Utilitas Box Batam',
    kode: 'MP-UTIL',
    kategori: 'Infrastruktur Jaringan Terpadu Bawah Tanah',
    progresPersen: 92.0,
    targetTahun: 2025,
    anggaran: 2650000000,
    status: 'On Track',
  },
  {
    nama: 'Masterplan Jalan Strategis & Arterial KPBPB',
    kode: 'MP-ROAD',
    kategori: 'Konektivitas Logistik Industri',
    progresPersen: 95.0,
    targetTahun: 2025,
    anggaran: 3400000000,
    status: 'Selesai',
  },
  {
    nama: 'Rencana Induk Bandara Internasional Hang Nadim',
    kode: 'RI-AIRPORT',
    kategori: 'Aerotropolis & Hub Logistik Udara',
    progresPersen: 100.0,
    targetTahun: 2024,
    anggaran: 1950000000,
    status: 'Selesai',
  },
  {
    nama: 'Rencana Induk Pelabuhan Modern Batu Ampar',
    kode: 'RI-PORT',
    kategori: 'Hub Transshipment & Container Terminal',
    progresPersen: 84.0,
    targetTahun: 2025,
    anggaran: 2800000000,
    status: 'On Track',
  },
];

// ============================================================================
// 8. REKAPITULASI 64 DATASET SATU DATA DARI PDF
// (PTSP 17, Pusren 19, PHKS 7, PDSI 21)
// ============================================================================

export const SATU_DATA_KEBIJAKAN_STRATEGIS_CATALOG: SatuDatasetItem[] = [
  // --- PTSP (17 Dataset - Hal 21-28) ---
  {
    no: 1,
    unit: 'Pusat Pelayanan Terpadu Satu Pintu',
    unitId: 'ptsp',
    namaData: 'Data Permohonan Perizinan SKKBM (Kerja Bongkar Muat)',
    jenisData: 'Data Statistik',
    periodeData: 'Perbulan',
    sifatData: 'TERTUTUP',
    atributUtama: ['Nama Perusahaan', 'Nama Kapal', 'Bendera Kapal', 'ETA', 'Lama Hari Kerja', 'Jumlah Bongkar Muat'],
    halamanPdf: 'Hal 21-22',
  },
  {
    no: 2,
    unit: 'Pusat Pelayanan Terpadu Satu Pintu',
    unitId: 'ptsp',
    namaData: 'Data Permohonan Perizinan SKKAB (Kerja Angkut Barang)',
    jenisData: 'Data Statistik',
    periodeData: 'Perbulan',
    sifatData: 'TERTUTUP',
    atributUtama: ['Nama Perusahaan', 'Peralatan Bongkar Muat', 'Jumlah TKBM', 'Status Muatan', 'Pelabuhan Asal'],
    halamanPdf: 'Hal 22',
  },
  {
    no: 3,
    unit: 'Pusat Pelayanan Terpadu Satu Pintu',
    unitId: 'ptsp',
    namaData: 'Data Permohonan Perizinan SKKAA (Kepemilikan dan Asal Alat)',
    jenisData: 'Data Statistik',
    periodeData: 'Perbulan',
    sifatData: 'TERTUTUP',
    atributUtama: ['No Izin', 'Jenis Peralatan', 'Status Kepemilikan', 'Estimate Waktu Kerja'],
    halamanPdf: 'Hal 22-23',
  },
  {
    no: 4,
    unit: 'Pusat Pelayanan Terpadu Satu Pintu',
    unitId: 'ptsp',
    namaData: 'Data Ijin Pembangunan/Pengoperasian Terminal Khusus (TUKS)',
    jenisData: 'Data Statistik',
    periodeData: 'Jika Update',
    sifatData: 'TERBUKA',
    atributUtama: ['Nama Perusahaan', 'Lokasi Usaha', 'Status Penanaman Modal', 'KBLI', 'NPWP'],
    halamanPdf: 'Hal 23',
  },
  {
    no: 5,
    unit: 'Pusat Pelayanan Terpadu Satu Pintu',
    unitId: 'ptsp',
    namaData: 'Data Implementasi Kebijakan Transformasi Digital MPP',
    jenisData: 'Data Statistik',
    periodeData: 'Persemester',
    sifatData: 'TERBUKA',
    atributUtama: ['Nama Perusahaan', 'NIB', 'KBLI', 'Nomor Akta', 'Nomor Izin Operasi'],
    halamanPdf: 'Hal 24',
  },
  {
    no: 6,
    unit: 'Pusat Pelayanan Terpadu Satu Pintu',
    unitId: 'ptsp',
    namaData: 'Data Monev Pengelolaan Pengaduan Layanan PTSP',
    jenisData: 'Data Statistik',
    periodeData: 'Persemester',
    sifatData: 'TERBUKA',
    atributUtama: ['Saluran Pengaduan', 'Jenis Pengaduan', 'Jumlah Masuk', 'Penyelesaian', 'Status Selesai'],
    halamanPdf: 'Hal 24',
  },
  {
    no: 7,
    unit: 'Pusat Pelayanan Terpadu Satu Pintu',
    unitId: 'ptsp',
    namaData: 'Daftar Informasi Perizinan BP Batam',
    jenisData: 'Data Statistik',
    periodeData: 'Perbulan',
    sifatData: 'TERTUTUP',
    atributUtama: ['Nama Perusahaan', 'Alamat', 'Penanggung Jawab Proyek', 'Status Selesai'],
    halamanPdf: 'Hal 24',
  },
  {
    no: 8,
    unit: 'Pusat Pelayanan Terpadu Satu Pintu',
    unitId: 'ptsp',
    namaData: 'Data Pemantauan dan Evaluasi Perizinan',
    jenisData: 'Data Statistik',
    periodeData: 'Perbulan',
    sifatData: 'TERTUTUP',
    atributUtama: ['NIB', 'KBLI', 'Sektor', 'Rencana Investasi', 'Realisasi Investasi', 'Tenaga Kerja TKI/TKA'],
    halamanPdf: 'Hal 25',
  },
  {
    no: 9,
    unit: 'Pusat Pelayanan Terpadu Satu Pintu',
    unitId: 'ptsp',
    namaData: 'Data Permohonan Perizinan Berusaha OSS',
    jenisData: 'Data Statistik',
    periodeData: 'Perbulan',
    sifatData: 'TERTUTUP',
    atributUtama: ['Skala Usaha', 'Tingkat Resiko', 'Status Modal', 'Asal Negara', 'Modal Usaha', 'Status Izin'],
    halamanPdf: 'Hal 25',
  },
  {
    no: 10,
    unit: 'Pusat Pelayanan Terpadu Satu Pintu',
    unitId: 'ptsp',
    namaData: 'Data Surat Keterangan Izin Operasi Perusahaan',
    jenisData: 'Data Statistik',
    periodeData: 'Perbulan',
    sifatData: 'TERBUKA',
    atributUtama: ['No Pendaftaran', 'No Izin', 'Nama Agen', 'Nama Kapal', 'Jumlah Muatan'],
    halamanPdf: 'Hal 26',
  },
  {
    no: 11,
    unit: 'Pusat Pelayanan Terpadu Satu Pintu',
    unitId: 'ptsp',
    namaData: 'Data Rekomendasi Tersus untuk Kegiatan Bongkar Muat',
    jenisData: 'Data Statistik',
    periodeData: 'Perbulan',
    sifatData: 'TERTUTUP',
    atributUtama: ['Nama Kapal', 'Jenis Barang', 'Volume Barang', 'Pelabuhan Asal & Tujuan'],
    halamanPdf: 'Hal 26',
  },
  {
    no: 12,
    unit: 'Pusat Pelayanan Terpadu Satu Pintu',
    unitId: 'ptsp',
    namaData: 'Data Permohonan Persetujuan Jadwal Kapal',
    jenisData: 'Data Statistik',
    periodeData: 'Perbulan',
    sifatData: 'TERTUTUP',
    atributUtama: ['Pemilik Kapal', 'Nama Kapal', 'Jadwal Keberangkatan', 'Rute Asal-Tujuan'],
    halamanPdf: 'Hal 27',
  },
  {
    no: 13,
    unit: 'Pusat Pelayanan Terpadu Satu Pintu',
    unitId: 'ptsp',
    namaData: 'Data Ijin Keruk dan Reklamasi',
    jenisData: 'Data Statistik',
    periodeData: 'Pertahun',
    sifatData: 'TERBUKA',
    atributUtama: ['Nama Perusahaan', 'NIB', 'KBLI', 'Lokasi Usaha', 'Status Modal'],
    halamanPdf: 'Hal 27',
  },
  {
    no: 14,
    unit: 'Pusat Pelayanan Terpadu Satu Pintu',
    unitId: 'ptsp',
    namaData: 'Jenis Layanan BP Batam (Layanan Masuk vs Selesai)',
    jenisData: 'Data Statistik',
    periodeData: 'Jika Update',
    sifatData: 'TERBUKA',
    atributUtama: ['Jenis Layanan', 'Jumlah Masuk', 'Jumlah Terselesaikan'],
    halamanPdf: 'Hal 27',
  },
  {
    no: 15,
    unit: 'Pusat Pelayanan Terpadu Satu Pintu',
    unitId: 'ptsp',
    namaData: 'Jumlah Pemantauan dan Evaluasi Perizinan',
    jenisData: 'Data Statistik',
    periodeData: 'Pertahun',
    sifatData: 'TERTUTUP',
    atributUtama: ['NIB', 'Sektor', 'Sertifikat Standar', 'Realisasi Investasi', 'Tenaga Kerja'],
    halamanPdf: 'Hal 27',
  },
  {
    no: 16,
    unit: 'Pusat Pelayanan Terpadu Satu Pintu',
    unitId: 'ptsp',
    namaData: 'Jumlah Layanan Non Perizinan',
    jenisData: 'Data Statistik',
    periodeData: 'Perbulan',
    sifatData: 'TERTUTUP',
    atributUtama: ['Jenis Non Perizinan', 'Status Masuk', 'Status Tolak', 'Status Proses', 'Status Selesai'],
    halamanPdf: 'Hal 27-28',
  },
  {
    no: 17,
    unit: 'Pusat Pelayanan Terpadu Satu Pintu',
    unitId: 'ptsp',
    namaData: 'Data Penyelesaian Perizinan yang Tepat Waktu (SLA)',
    jenisData: 'Data Statistik',
    periodeData: 'Perbulan',
    sifatData: 'TERBUKA',
    atributUtama: ['Jenis Perizinan', 'Status Masuk', 'Status Proses', 'Status Selesai', 'SLA Target & Realisasi'],
    halamanPdf: 'Hal 28',
  },

  // --- PUSREN / P3S (19 Dataset - Hal 51-53) ---
  {
    no: 18,
    unit: 'Pusat Perencanaan Program Strategis',
    unitId: 'pusat-perencanaan-program',
    namaData: 'Data Pemanfaatan Dokumen Perencanaan & Kajian Kelayakan',
    jenisData: 'Data Statistik',
    periodeData: 'Pertahun',
    sifatData: 'TERBUKA',
    atributUtama: ['Nama Kegiatan', 'Lokasi', 'Tahun Kegiatan', 'Sumber Dana', 'Status Progres'],
    halamanPdf: 'Hal 51',
  },
  {
    no: 19,
    unit: 'Pusat Perencanaan Program Strategis',
    unitId: 'pusat-perencanaan-program',
    namaData: 'Rekapitulasi Monev Program Kerja BP Batam',
    jenisData: 'Data Statistik',
    periodeData: 'Pertriwulan',
    sifatData: 'TERTUTUP',
    atributUtama: ['Kode MA', 'Kegiatan/Output/Sub-Komponen', 'Pagu DIPA', 'Progres Paket', 'Sisa Pagu'],
    halamanPdf: 'Hal 51',
  },
  {
    no: 20,
    unit: 'Pusat Perencanaan Program Strategis',
    unitId: 'pusat-perencanaan-program',
    namaData: 'Rekapitulasi Rencana Strategis (Renstra) 5 Tahun',
    jenisData: 'Data Statistik',
    periodeData: 'Per 5 Tahun',
    sifatData: 'TERBUKA',
    atributUtama: ['Program', 'Sasaran Program Indikator', 'Satuan', 'Target 5 Tahunan'],
    halamanPdf: 'Hal 51',
  },
  {
    no: 21,
    unit: 'Pusat Perencanaan Program Strategis',
    unitId: 'pusat-perencanaan-program',
    namaData: 'Rekapitulasi Rencana Kerja Tahunan BP Batam',
    jenisData: 'Data Statistik',
    periodeData: 'Pertahun',
    sifatData: 'TERTUTUP',
    atributUtama: ['KRO & RO Nomenklatur', 'Indikator Kinerja Alokasi', 'Unit Pelaksana'],
    halamanPdf: 'Hal 51',
  },
  {
    no: 22,
    unit: 'Pusat Perencanaan Program Strategis',
    unitId: 'pusat-perencanaan-program',
    namaData: 'RKA (Rencana Kerja dan Anggaran) Tahunan',
    jenisData: 'Data Statistik',
    periodeData: 'Pertahun',
    sifatData: 'TERTUTUP',
    atributUtama: ['Kode Anggaran', 'Uraian', 'Volume', 'Alokasi Dana', 'Sumber Dana'],
    halamanPdf: 'Hal 51',
  },
  {
    no: 23,
    unit: 'Pusat Perencanaan Program Strategis',
    unitId: 'pusat-perencanaan-program',
    namaData: 'Masterplan Drainase Kota Batam',
    jenisData: 'Data Statistik',
    periodeData: 'Jika Update',
    sifatData: 'TERBUKA',
    atributUtama: ['Judul Bab', 'Kategori', 'Poin', 'Detail', 'Rincian Sistem Drainase'],
    halamanPdf: 'Hal 51',
  },
  {
    no: 24,
    unit: 'Pusat Perencanaan Program Strategis',
    unitId: 'pusat-perencanaan-program',
    namaData: 'Masterplan Utilitas Box Terpadu',
    jenisData: 'Data Statistik',
    periodeData: 'Jika Update',
    sifatData: 'TERBUKA',
    atributUtama: ['Tahun Anggaran', 'Judul', 'Koridor Utilitas', 'Rincian Teknis'],
    halamanPdf: 'Hal 51-52',
  },
  {
    no: 25,
    unit: 'Pusat Perencanaan Program Strategis',
    unitId: 'pusat-perencanaan-program',
    namaData: 'Rekapitulasi Rekomendasi Perubahan Peruntukan Lahan',
    jenisData: 'Data Statistik',
    periodeData: 'Jika Update',
    sifatData: 'TERTUTUP',
    atributUtama: ['Jumlah Permohonan', 'Status Selesai', 'Rekomendasi Tata Ruang'],
    halamanPdf: 'Hal 52',
  },
  {
    no: 26,
    unit: 'Pusat Perencanaan Program Strategis',
    unitId: 'pusat-perencanaan-program',
    namaData: 'Rekapitulasi Perizinan Pengelolaan Lingkungan',
    jenisData: 'Data Statistik',
    periodeData: 'Jika Update',
    sifatData: 'TERTUTUP',
    atributUtama: ['Nomor SK', 'Poin Lingkungan', 'Rencana Induk'],
    halamanPdf: 'Hal 52',
  },
  {
    no: 27,
    unit: 'Pusat Perencanaan Program Strategis',
    unitId: 'pusat-perencanaan-program',
    namaData: 'Rencana Induk Bandara Internasional Hang Nadim',
    jenisData: 'Data Statistik',
    periodeData: 'Jika Update',
    sifatData: 'TERBUKA',
    atributUtama: ['Nomor SK', 'Rencana Induk Aerotropolis', 'Rincian Tahapan'],
    halamanPdf: 'Hal 52',
  },
  {
    no: 28,
    unit: 'Pusat Perencanaan Program Strategis',
    unitId: 'pusat-perencanaan-program',
    namaData: 'Rencana Induk Pelabuhan Modern Batu Ampar',
    jenisData: 'Data Statistik',
    periodeData: 'Jika Update',
    sifatData: 'TERBUKA',
    atributUtama: ['Nomor SK', 'Masterplan Pelabuhan', 'Kapasitas Dermaga'],
    halamanPdf: 'Hal 52',
  },
  {
    no: 29,
    unit: 'Pusat Perencanaan Program Strategis',
    unitId: 'pusat-perencanaan-program',
    namaData: 'Masterplan Jalan Strategis Kota Batam',
    jenisData: 'Data Statistik',
    periodeData: 'Jika Update',
    sifatData: 'TERBUKA',
    atributUtama: ['Klasifikasi Jalan', 'Wilayah', 'Sub Wilayah', 'Panjang (Km)', 'Lebar (M)'],
    halamanPdf: 'Hal 52',
  },
  {
    no: 30,
    unit: 'Pusat Perencanaan Program Strategis',
    unitId: 'pusat-perencanaan-program',
    namaData: 'Kontur Spasial Kota Batam (Interval 1 Meter)',
    jenisData: 'Data Spasial',
    periodeData: 'Jika Update',
    sifatData: 'TERBUKA',
    atributUtama: ['Nomor Elevasi', 'Ukuran Ketinggian', 'Koordinat Spasial', 'Lokasi'],
    halamanPdf: 'Hal 52',
  },
  {
    no: 31,
    unit: 'Pusat Perencanaan Program Strategis',
    unitId: 'pusat-perencanaan-program',
    namaData: 'Laporan Analisis Stakeholder Feedback',
    jenisData: 'Dokumen Digital',
    periodeData: 'Pertahun',
    sifatData: 'TERBUKA',
    atributUtama: ['Sasaran Strategis', 'Indikator Kinerja Program', 'Satuan', 'Feedback Target'],
    halamanPdf: 'Hal 52',
  },
  {
    no: 32,
    unit: 'Pusat Perencanaan Program Strategis',
    unitId: 'pusat-perencanaan-program',
    namaData: 'Laporan Analisis Capaian Renstra Ditetapkan',
    jenisData: 'Dokumen Digital',
    periodeData: 'Per 5 Tahun',
    sifatData: 'TERBUKA',
    atributUtama: ['Sasaran Strategis', 'Realisasi Target Renstra', 'Evaluasi Kinerja'],
    halamanPdf: 'Hal 52',
  },
  {
    no: 33,
    unit: 'Pusat Perencanaan Program Strategis',
    unitId: 'pusat-perencanaan-program',
    namaData: 'Laporan Tindak Lanjut Hasil Analisis Renstra',
    jenisData: 'Dokumen Digital',
    periodeData: 'Per 5 Tahun',
    sifatData: 'TERBUKA',
    atributUtama: ['Tindak Lanjut Sasaran', 'Rekomendasi Alokasi Program'],
    halamanPdf: 'Hal 52',
  },
  {
    no: 34,
    unit: 'Pusat Perencanaan Program Strategis',
    unitId: 'pusat-perencanaan-program',
    namaData: 'Data Pemantauan Capaian Rencana Strategis',
    jenisData: 'Data Statistik',
    periodeData: 'Pertahun',
    sifatData: 'TERBUKA',
    atributUtama: ['Sasaran Strategis', 'Indikator Kinerja', 'Realisasi Tahunan'],
    halamanPdf: 'Hal 52-53',
  },
  {
    no: 35,
    unit: 'Pusat Perencanaan Program Strategis',
    unitId: 'pusat-perencanaan-program',
    namaData: 'Data Evaluasi Perencanaan Pembangunan Bappenas (SE PPN No. 3/2023)',
    jenisData: 'Data Statistik',
    periodeData: 'Pertahun',
    sifatData: 'TERBUKA',
    atributUtama: ['Kode & Nomenklatur', 'Progress Pelaksanaan', 'Jumlah KRO', 'Partisipasi Pelaporan'],
    halamanPdf: 'Hal 53',
  },
  {
    no: 36,
    unit: 'Pusat Perencanaan Program Strategis',
    unitId: 'pusat-perencanaan-program',
    namaData: 'Wilayah Kerja Spasial KPBPB Batam',
    jenisData: 'Data Spasial',
    periodeData: 'Jika Update',
    sifatData: 'TERBUKA',
    atributUtama: ['Batasan Delineasi', 'Luas Wilayah', 'Kewenangan Kawasan'],
    halamanPdf: 'Hal 53',
  },

  // --- PHKS (7 Dataset - Hal 12-13) ---
  {
    no: 37,
    unit: 'Pusat Harmonisasi Kebijakan Strategis',
    unitId: 'pusat-harmonisasi',
    namaData: 'Data Pemantauan & Evaluasi Kualitas Kebijakan BP Batam',
    jenisData: 'Data Statistik',
    periodeData: 'Pertahun',
    sifatData: 'TERBUKA',
    atributUtama: ['Nama Kebijakan', 'Nomor Perka/Kepka', 'Analisis Instansi', 'Tahun Penetapan', 'Skor IKK'],
    halamanPdf: 'Hal 12',
  },
  {
    no: 38,
    unit: 'Pusat Harmonisasi Kebijakan Strategis',
    unitId: 'pusat-harmonisasi',
    namaData: 'Rekapitulasi Hasil Sinkronisasi Kebijakan Eksternal',
    jenisData: 'Data Statistik',
    periodeData: 'Pertahun',
    sifatData: 'TERTUTUP',
    atributUtama: ['Tentang', 'Kategori', 'Status Keselarasan', 'Nomor Regulasi Pusat'],
    halamanPdf: 'Hal 13',
  },
  {
    no: 39,
    unit: 'Pusat Harmonisasi Kebijakan Strategis',
    unitId: 'pusat-harmonisasi',
    namaData: 'Daftar Tarif Layanan BP Batam (Level 1 s.d Level 7)',
    jenisData: 'Data Statistik',
    periodeData: 'Pertahun',
    sifatData: 'TERBUKA',
    atributUtama: ['Unit Kerja', 'Level 1-7', 'Satuan Layanan', 'Unit Cost', 'Tarif Berlaku', 'Dasar Hukum PMK'],
    halamanPdf: 'Hal 13',
  },
  {
    no: 40,
    unit: 'Pusat Harmonisasi Kebijakan Strategis',
    unitId: 'pusat-harmonisasi',
    namaData: 'Rekapitulasi Hasil Sinkronisasi Kebijakan Internal',
    jenisData: 'Data Statistik',
    periodeData: 'Pertahun',
    sifatData: 'TERTUTUP',
    atributUtama: ['Tentang', 'Kategori Regulasi', 'Status Berlaku', 'Nomor SK'],
    halamanPdf: 'Hal 13',
  },
  {
    no: 41,
    unit: 'Pusat Harmonisasi Kebijakan Strategis',
    unitId: 'pusat-harmonisasi',
    namaData: 'Survei Kewajaran dan Evaluasi Tarif Layanan',
    jenisData: 'Data Statistik',
    periodeData: 'Pertahun',
    sifatData: 'TERTUTUP',
    atributUtama: ['Lokasi', 'Instrumen Penelitian', 'Kriteria Responden', 'Skor Kewajaran', 'Persentase'],
    halamanPdf: 'Hal 13',
  },
  {
    no: 42,
    unit: 'Pusat Harmonisasi Kebijakan Strategis',
    unitId: 'pusat-harmonisasi',
    namaData: 'Daftar Risalah Rapat Dengar Pendapat (RDP) Pimpinan',
    jenisData: 'Data Statistik',
    periodeData: 'Perbulan',
    sifatData: 'TERTUTUP',
    atributUtama: ['Tanggal Rapat', 'Judul Rapat', 'Tempat', 'Waktu', 'Keputusan Strategis'],
    halamanPdf: 'Hal 13',
  },
  {
    no: 43,
    unit: 'Pusat Harmonisasi Kebijakan Strategis',
    unitId: 'pusat-harmonisasi',
    namaData: 'Data Monitoring Tindak Lanjut Rapat Pimpinan',
    jenisData: 'Data Statistik',
    periodeData: 'Pertahun',
    sifatData: 'TERTUTUP',
    atributUtama: ['Nota Dinas Pengantar', 'Matrik Tindak Lanjut', 'Status Realisasi Rekomendasi'],
    halamanPdf: 'Hal 13',
  },

  // --- PDSI (21 Dataset - Hal 40-43) ---
  {
    no: 44,
    unit: 'Pusat Data dan Sistem Informasi',
    unitId: 'pdsi',
    namaData: 'Informasi Business Intelligence (BI) BP Batam',
    jenisData: 'Data Statistik',
    periodeData: 'Jika Update',
    sifatData: 'TERBUKA',
    atributUtama: ['Unit Kerja', 'Nama Dashboard', 'Jumlah Worksheet', 'Pembaharuan Terakhir'],
    halamanPdf: 'Hal 40',
  },
  {
    no: 45,
    unit: 'Pusat Data dan Sistem Informasi',
    unitId: 'pdsi',
    namaData: 'Jaringan Spasial Fiber Optik BP Batam',
    jenisData: 'Data Spasial',
    periodeData: 'Jika Update',
    sifatData: 'TERBATAS',
    atributUtama: ['Jalur Jalan', 'Jumlah Core (48/96)', 'Panjang Lintasan', 'Brand FO', 'Start/Endpoint'],
    halamanPdf: 'Hal 40',
  },
  {
    no: 46,
    unit: 'Pusat Data dan Sistem Informasi',
    unitId: 'pdsi',
    namaData: 'Daftar Data Satu Data BP Batam',
    jenisData: 'Data Statistik',
    periodeData: 'Jika Update',
    sifatData: 'TERBATAS',
    atributUtama: ['Nama Data', 'Produsen Data', 'Kategori Data', 'Status Pemutakhiran'],
    halamanPdf: 'Hal 41',
  },
  {
    no: 47,
    unit: 'Pusat Data dan Sistem Informasi',
    unitId: 'pdsi',
    namaData: 'Daftar Sistem Penghubung & Integrasi API Data',
    jenisData: 'Data Statistik',
    periodeData: 'Jika Update',
    sifatData: 'TERTUTUP',
    atributUtama: ['Organisasi Penyedia', 'Sistem Terhubung', 'Tipe Komunikasi (REST API)', 'Aplikasi', 'Status Sinkronisasi'],
    halamanPdf: 'Hal 41',
  },
  {
    no: 48,
    unit: 'Pusat Data dan Sistem Informasi',
    unitId: 'pdsi',
    namaData: 'Data Jalur Fiber Optic (FO) Wilayah',
    jenisData: 'Data Statistik',
    periodeData: 'Jika Update',
    sifatData: 'TERTUTUP',
    atributUtama: ['Bagian Wilayah', 'Lokasi', 'Titik Sambung (Closure)', 'Redundansi'],
    halamanPdf: 'Hal 41',
  },
  {
    no: 49,
    unit: 'Pusat Data dan Sistem Informasi',
    unitId: 'pdsi',
    namaData: 'Sarana dan Aset Fiber Optic Spasial',
    jenisData: 'Data Spasial',
    periodeData: 'Jika Update',
    sifatData: 'TERBATAS',
    atributUtama: ['Manhole', 'Handhole', 'Pole Tiang', 'Kategori Kabel'],
    halamanPdf: 'Hal 41',
  },
  {
    no: 50,
    unit: 'Pusat Data dan Sistem Informasi',
    unitId: 'pdsi',
    namaData: 'Rekap Kerusakan dan Perbaikan Perangkat TI',
    jenisData: 'Data Statistik',
    periodeData: 'Pertahun',
    sifatData: 'TERTUTUP',
    atributUtama: ['Jenis Kerusakan', 'Lokasi Unit', 'Jumlah Perbaikan', 'Waktu Pemulihan (MTTR)'],
    halamanPdf: 'Hal 41',
  },
  {
    no: 51,
    unit: 'Pusat Data dan Sistem Informasi',
    unitId: 'pdsi',
    namaData: 'Data Rak Tier-3 Data Center BP Batam',
    jenisData: 'Data Statistik',
    periodeData: 'Pertahun',
    sifatData: 'TERBUKA',
    atributUtama: ['Ruangan Data Center', 'Total Rak (96)', 'Rak Terisi (78)', 'Rak Kosong (18)', 'Daya Listrik'],
    halamanPdf: 'Hal 41',
  },
  {
    no: 52,
    unit: 'Pusat Data dan Sistem Informasi',
    unitId: 'pdsi',
    namaData: 'Daftar Lisensi Software Resmi BP Batam',
    jenisData: 'Data Statistik',
    periodeData: 'Jika Update',
    sifatData: 'TERTUTUP',
    atributUtama: ['Nama Software', 'Tipe Perangkat Lunak', 'Jenis OS/Utilitas', 'Validasi Lisensi'],
    halamanPdf: 'Hal 41-42',
  },
  {
    no: 53,
    unit: 'Pusat Data dan Sistem Informasi',
    unitId: 'pdsi',
    namaData: 'Data Layanan Data Centre & Co-Location',
    jenisData: 'Data Statistik',
    periodeData: 'Jika Update',
    sifatData: 'TERBUKA',
    atributUtama: ['Kelompok Layanan', 'Kategori', 'Detail Layanan Co-location/VPS', 'Tarif Layanan'],
    halamanPdf: 'Hal 42',
  },
  {
    no: 54,
    unit: 'Pusat Data dan Sistem Informasi',
    unitId: 'pdsi',
    namaData: 'Data Kepuasan Pelanggan Data Centre',
    jenisData: 'Data Statistik',
    periodeData: 'Pertahun',
    sifatData: 'TERBUKA',
    atributUtama: ['Kategori Tenant', 'Tingkat Kepuasan (94.6%)', 'SLA Uptime Tersedia'],
    halamanPdf: 'Hal 42',
  },
  {
    no: 55,
    unit: 'Pusat Data dan Sistem Informasi',
    unitId: 'pdsi',
    namaData: 'Data Serangan Keamanan Siber IT / SOC BP Batam',
    jenisData: 'Data Statistik',
    periodeData: 'Perbulan',
    sifatData: 'TERTUTUP',
    atributUtama: ['Threat Activity (DDoS, Malware, Brute Force)', 'Status Keamanan', 'Jumlah Serangan Terblokir'],
    halamanPdf: 'Hal 42',
  },
  {
    no: 56,
    unit: 'Pusat Data dan Sistem Informasi',
    unitId: 'pdsi',
    namaData: 'Rekap Infrastruktur Server dan Storage',
    jenisData: 'Data Statistik',
    periodeData: 'Jika Update',
    sifatData: 'TERTUTUP',
    atributUtama: ['Nama Server', 'Tipe', 'Brand Hardware', 'Status Garansi', 'End of Support (EOS)'],
    halamanPdf: 'Hal 42',
  },
  {
    no: 57,
    unit: 'Pusat Data dan Sistem Informasi',
    unitId: 'pdsi',
    namaData: 'Katalog 48 Aplikasi Resmi BP Batam',
    jenisData: 'Data Statistik',
    periodeData: 'Jika Update',
    sifatData: 'TERTUTUP',
    atributUtama: ['Nama Aplikasi', 'Basis Web/Mobile', 'Bahasa Pemrograman', 'Integrasi TTE BSrE', 'Dev Year'],
    halamanPdf: 'Hal 42',
  },
  {
    no: 58,
    unit: 'Pusat Data dan Sistem Informasi',
    unitId: 'pdsi',
    namaData: 'Rencana Bisnis dan Anggaran (RBA) PDSI',
    jenisData: 'Data Statistik',
    periodeData: 'Pertahun',
    sifatData: 'TERBUKA',
    atributUtama: ['Alokasi Pagu Belanja TIK', 'Realisasi Investasi Server', 'Target PNBP Co-Location'],
    halamanPdf: 'Hal 42',
  },
  {
    no: 59,
    unit: 'Pusat Data dan Sistem Informasi',
    unitId: 'pdsi',
    namaData: 'Peta Rencana SPBE BP Batam 2025-2029',
    jenisData: 'Data Statistik',
    periodeData: 'Jika Update',
    sifatData: 'TERBUKA',
    atributUtama: ['Arsitektur Proses Bisnis', 'Arsitektur Layanan', 'Peta Jalan TIK Multi-Tahun'],
    halamanPdf: 'Hal 43',
  },
  {
    no: 60,
    unit: 'Pusat Data dan Sistem Informasi',
    unitId: 'pdsi',
    namaData: 'Daftar Layanan TI & Service Level Agreement',
    jenisData: 'Data Statistik',
    periodeData: 'Jika Update',
    sifatData: 'TERBUKA',
    atributUtama: ['Nama Sub-Layanan', 'Prioritas Penanganan', 'Norma Waktu Respon', 'Norma Waktu Penyelesaian'],
    halamanPdf: 'Hal 43',
  },
  {
    no: 61,
    unit: 'Pusat Data dan Sistem Informasi',
    unitId: 'pdsi',
    namaData: 'Laporan Pemantauan dan Evaluasi SPBE',
    jenisData: 'Data Statistik',
    periodeData: 'Pertahun',
    sifatData: 'TERTUTUP',
    atributUtama: ['6 Domain Arsitektur', 'Aspek Penilaian MenPAN-RB', 'Indeks Kematangan 4.12'],
    halamanPdf: 'Hal 43',
  },
  {
    no: 62,
    unit: 'Pusat Data dan Sistem Informasi',
    unitId: 'pdsi',
    namaData: 'Data Monitoring Sistem Informasi Arsitektur (SIA)',
    jenisData: 'Data Statistik',
    periodeData: 'Jika Update',
    sifatData: 'TERTUTUP',
    atributUtama: ['Model Arsitektur', 'Matriks Hubungan Aplikasi-Data-Proses', 'Audit Arsitektur'],
    halamanPdf: 'Hal 43',
  },
  {
    no: 63,
    unit: 'Pusat Data dan Sistem Informasi',
    unitId: 'pdsi',
    namaData: 'Laporan Evaluasi Penyelenggaraan Statistik Sektoral (EPSS)',
    jenisData: 'Data Statistik',
    periodeData: 'Pertahun',
    sifatData: 'TERTUTUP',
    atributUtama: ['Domain Statistik BPS', 'Indeks Pembangunan Statistik (IPS)', 'Bobot dan Nilai Capaian'],
    halamanPdf: 'Hal 43',
  },
  {
    no: 64,
    unit: 'Pusat Data dan Sistem Informasi',
    unitId: 'pdsi',
    namaData: 'Data Permintaan Layanan IT (Helpdesk Ticketing)',
    jenisData: 'Data Statistik',
    periodeData: 'Perbulan',
    sifatData: 'TERBUKA',
    atributUtama: ['Bulan', 'Nama Layanan Permintaan', 'Jumlah Tiket Masuk', 'Tiket Selesai Tepat Waktu (SLA)'],
    halamanPdf: 'Hal 43',
  },
];
