import { SdmYearData, SdmFilterState, StandarKasnKonversi } from './types';

export const DEFAULT_SDM_FILTERS: SdmFilterState = {
  tahun: 2026,
  genderFilter: 'all',
  statusFilter: 'all',
  searchQuery: '',
};

export const SDM_DATA_BY_YEAR: Record<number, SdmYearData> = {
  2026: {
    tahun: 2026,
    totalPegawai: 2978,
    gender: {
      lakiLaki: {
        jenisKelamin: 'Laki-laki',
        jumlah: 1796,
        persentase: 60.31,
        rataRataUsia: 39.4,
      },
      perempuan: {
        jenisKelamin: 'Perempuan',
        jumlah: 1182,
        persentase: 39.69,
        rataRataUsia: 36.8,
      },
    },
    statusKepegawaian: [
      {
        id: 'pns',
        statusPegawai: 'Pegawai Negeri Sipil (PNS)',
        jumlahPegawai: 1042,
        persentase: 34.99,
        warna: '#2563EB',
        deskripsi: 'Aparatur Sipil Negara tetap dengan penetapan NIP BKN.',
      },
      {
        id: 'p2k',
        statusPegawai: 'Pegawai Tetap BP Batam (P2K)',
        jumlahPegawai: 872,
        persentase: 29.28,
        warna: '#0D9488',
        deskripsi: 'Pegawai berstatus tetap non-PNS berdasarkan SK Kepala BP Batam.',
      },
      {
        id: 'p3k',
        statusPegawai: 'PPPK (P3K)',
        jumlahPegawai: 485,
        persentase: 16.29,
        warna: '#7C3AED',
        deskripsi: 'Pegawai Pemerintah dengan Perjanjian Kerja fungsional dan teknis.',
      },
      {
        id: 'ptt',
        statusPegawai: 'Pegawai Tidak Tetap (PTT)',
        jumlahPegawai: 396,
        persentase: 13.30,
        warna: '#EA580C',
        deskripsi: 'Pegawai kontrak pendukung operasional dan pelayanan perkantoran.',
      },
      {
        id: 'profesional',
        statusPegawai: 'Tenaga Profesional / Kontrak Khusus',
        jumlahPegawai: 183,
        persentase: 6.14,
        warna: '#D97706',
        deskripsi: 'Spesialis medis, analis pelabuhan, IT engineer, dan ahli hukum.',
      },
    ],
    pendidikan: [
      {
        id: 's3',
        tingkatPendidikan: 'S3 (Doktor)',
        jumlahPegawai: 24,
        persentase: 0.81,
        warna: '#4338CA',
        golonganDominan: 'Golongan IV/c - IV/e',
      },
      {
        id: 's2',
        tingkatPendidikan: 'S2 (Magister)',
        jumlahPegawai: 312,
        persentase: 10.48,
        warna: '#2563EB',
        golonganDominan: 'Golongan III/c - IV/b',
      },
      {
        id: 's1',
        tingkatPendidikan: 'S1 / D4 (Sarjana)',
        jumlahPegawai: 1584,
        persentase: 53.19,
        warna: '#0284C7',
        golonganDominan: 'Golongan III/a - III/d',
      },
      {
        id: 'd3',
        tingkatPendidikan: 'D3 (Diploma)',
        jumlahPegawai: 428,
        persentase: 14.37,
        warna: '#0D9488',
        golonganDominan: 'Golongan II/c - III/b',
      },
      {
        id: 'sma',
        tingkatPendidikan: 'SMA / SMK',
        jumlahPegawai: 562,
        persentase: 18.87,
        warna: '#F59E0B',
        golonganDominan: 'Golongan II/a - II/d',
      },
      {
        id: 'smp_sd',
        tingkatPendidikan: 'SMP / SD',
        jumlahPegawai: 68,
        persentase: 2.28,
        warna: '#94A3B8',
        golonganDominan: 'Golongan I/c - I/d',
      },
    ],
    sistemMerit: {
      aspekList: [
        {
          id: 'aspek-1',
          kodeAspek: 'ASPEK_1',
          nama: 'Perencanaan Kebutuhan',
          bobotPersen: 10,
          nilaiMaks: 40,
          nilaiAspek: 36.0,
          indeksAspek: 0.90,
          statusPemenuhan: 'Sangat Baik',
          deskripsiRingkas: 'Perhitungan peta jabatan dan Analisis Beban Kerja (ABK) 5 tahunan terintegrasi SIASN.',
          poinKunci: ['Peta jabatan berbasis e-Formasi', 'Kesesuaian kualifikasi formasi 94.2%', 'Proyeksi pensiun & suksesi akurat'],
        },
        {
          id: 'aspek-2',
          kodeAspek: 'ASPEK_2',
          nama: 'Pengadaan',
          bobotPersen: 10,
          nilaiMaks: 40,
          nilaiAspek: 35.0,
          indeksAspek: 0.875,
          statusPemenuhan: 'Sangat Baik',
          deskripsiRingkas: 'Seleksi ASN dan tenaga profesional transparan berbasis CAT dan portofolio kompetensi.',
          poinKunci: ['100% seleksi CPNS/PPPK memakai CAT BKN', 'Kanal aduan rekrutmen transparan', 'Nol temuan sanggah maladministrasi'],
        },
        {
          id: 'aspek-3',
          kodeAspek: 'ASPEK_3',
          nama: 'Pengembangan Karir',
          bobotPersen: 30,
          nilaiMaks: 120,
          nilaiAspek: 102.0,
          indeksAspek: 0.85,
          statusPemenuhan: 'Sangat Baik',
          deskripsiRingkas: 'Pemetaan Talent Pool berbasis 9-Box Matrix dan pemenuhan 20 JP diklat per pegawai/tahun.',
          poinKunci: ['9-Box Talent Mapping terverifikasi', 'Rata-rata 24.6 JP diklat per pegawai', 'Pemberian tugas belajar bersyarat kompetitif'],
        },
        {
          id: 'aspek-4',
          kodeAspek: 'ASPEK_4',
          nama: 'Promosi dan Mutasi',
          bobotPersen: 10,
          nilaiMaks: 40,
          nilaiAspek: 34.0,
          indeksAspek: 0.85,
          statusPemenuhan: 'Sangat Baik',
          deskripsiRingkas: 'Pengisian Jabatan Pimpinan Tinggi (JPT) dan administrator berdasarkan kualifikasi objektif.',
          poinKunci: ['Uji kompetensi manajerial & sosio-kultural', 'Penerapan rotasi/mutasi berkala berkala 2-5 tahun', 'Bebas dari konflik kepentingan'],
        },
        {
          id: 'aspek-5',
          kodeAspek: 'ASPEK_5',
          nama: 'Manajemen Kinerja',
          bobotPersen: 20,
          nilaiMaks: 80,
          nilaiAspek: 68.5,
          indeksAspek: 0.856,
          statusPemenuhan: 'Sangat Baik',
          deskripsiRingkas: 'Penyelarasan Sasaran Kinerja Pegawai (SKP) dengan Indikator Kinerja Utama (IKU) pimpinan.',
          poinKunci: ['Cascading IKU instansi ke SKP staf 100%', 'Evaluasi periodik triwulanan aktif', 'Koreksi dan dialog kinerja teratur'],
        },
        {
          id: 'aspek-6',
          kodeAspek: 'ASPEK_6',
          nama: 'Penggajian, Penghargaan, dan Disiplin',
          bobotPersen: 10,
          nilaiMaks: 40,
          nilaiAspek: 33.5,
          indeksAspek: 0.838,
          statusPemenuhan: 'Baik',
          deskripsiRingkas: 'Pemberian tunjangan kinerja berdasarkan capaian riil serta penegakan kode etik kepegawaian.',
          poinKunci: ['Sistem reward Satyalancana Karya Satya', 'Tukin terhubung logbook harian', 'Sidang kode etik adil & berkepastian'],
        },
        {
          id: 'aspek-7',
          kodeAspek: 'ASPEK_7',
          nama: 'Perlindungan dan Pelayanan',
          bobotPersen: 4,
          nilaiMaks: 16,
          nilaiAspek: 14.5,
          indeksAspek: 0.906,
          statusPemenuhan: 'Sangat Baik',
          deskripsiRingkas: 'Jaminan kesehatan BPJS, asuransi kecelakaan kerja, bantuan hukum dinas, dan layanan konseling.',
          poinKunci: ['Cakupan asuransi kesehatan 100%', 'Bantuan advokasi hukum tugas kedinasan', 'Program Medical Check Up berkala'],
        },
        {
          id: 'aspek-8',
          kodeAspek: 'ASPEK_8',
          nama: 'Sistem Informasi',
          bobotPersen: 6,
          nilaiMaks: 24,
          nilaiAspek: 19.0,
          indeksAspek: 0.792,
          statusPemenuhan: 'Baik',
          deskripsiRingkas: 'Digitalisasi SIMPEG BP Batam, integrasi data presensi biometrik, dan bridging SIASN BKN.',
          poinKunci: ['SIMPEG terhubung SIASN & MyASN', 'Presensi geolokasi akurat', 'Arsip digital SK kepegawaian 96%'],
        },
      ],
      datasetRow: {
        TAHUN: 2026,
        NILAI_PERENCANAAN_KEBUTUHAN: 36.0,
        NILAI_PENGADAAN: 35.0,
        NILAI_PENGEMBANGAN_KARIR: 102.0,
        NILAI_PROMOSI_DAN_MUTASI: 34.0,
        NILAI_MANAJEMEN_KINERJA: 68.5,
        NILAI_PENGGAJIAN_PENGHARGAAN_DISIPLIN: 33.5,
        NILAI_PERLINDUNGAN_DAN_PELAYANAN: 14.5,
        NILAI_SISTEM_INFORMASI: 19.0,
        INDEKS_PERENCANAAN_KEBUTUHAN: 0.900,
        INDEKS_PENGADAAN: 0.875,
        INDEKS_PENGEMBANGAN_KARIR: 0.850,
        INDEKS_PROMOSI_DAN_MUTASI: 0.850,
        INDEKS_MANAJEMEN_KINERJA: 0.856,
        INDEKS_PENGGAJIAN_PENGHARGAAN_DISIPLIN: 0.838,
        INDEKS_PERLINDUNGAN_DAN_PELAYANAN: 0.906,
        INDEKS_SISTEM_INFORMASI: 0.792,
        TOTAL_NILAI_MERIT: 342.5,
        INDEKS_SISTEM_MERIT: 0.8563, // 342.5 / 400 = 0.8563
        STATUS_PEMENUHAN: 'Kategori IV (Sangat Baik)',
        KATEGORI_PREDIKAT: 'Kategori IV (Sangat Baik)',
      },
    },
  },
  2025: {
    tahun: 2025,
    totalPegawai: 2914,
    gender: {
      lakiLaki: {
        jenisKelamin: 'Laki-laki',
        jumlah: 1768,
        persentase: 60.67,
        rataRataUsia: 39.8,
      },
      perempuan: {
        jenisKelamin: 'Perempuan',
        jumlah: 1146,
        persentase: 39.33,
        rataRataUsia: 37.1,
      },
    },
    statusKepegawaian: [
      {
        id: 'pns',
        statusPegawai: 'Pegawai Negeri Sipil (PNS)',
        jumlahPegawai: 1060,
        persentase: 36.38,
        warna: '#2563EB',
        deskripsi: 'Aparatur Sipil Negara tetap dengan penetapan NIP BKN.',
      },
      {
        id: 'p2k',
        statusPegawai: 'Pegawai Tetap BP Batam (P2K)',
        jumlahPegawai: 885,
        persentase: 30.37,
        warna: '#0D9488',
        deskripsi: 'Pegawai berstatus tetap non-PNS berdasarkan SK Kepala BP Batam.',
      },
      {
        id: 'p3k',
        statusPegawai: 'PPPK (P3K)',
        jumlahPegawai: 390,
        persentase: 13.38,
        warna: '#7C3AED',
        deskripsi: 'Pegawai Pemerintah dengan Perjanjian Kerja fungsional dan teknis.',
      },
      {
        id: 'ptt',
        statusPegawai: 'Pegawai Tidak Tetap (PTT)',
        jumlahPegawai: 412,
        persentase: 14.14,
        warna: '#EA580C',
        deskripsi: 'Pegawai kontrak pendukung operasional dan pelayanan perkantoran.',
      },
      {
        id: 'profesional',
        statusPegawai: 'Tenaga Profesional / Kontrak Khusus',
        jumlahPegawai: 167,
        persentase: 5.73,
        warna: '#D97706',
        deskripsi: 'Spesialis medis, analis pelabuhan, IT engineer, dan ahli hukum.',
      },
    ],
    pendidikan: [
      {
        id: 's3',
        tingkatPendidikan: 'S3 (Doktor)',
        jumlahPegawai: 21,
        persentase: 0.72,
        warna: '#4338CA',
        golonganDominan: 'Golongan IV/c - IV/e',
      },
      {
        id: 's2',
        tingkatPendidikan: 'S2 (Magister)',
        jumlahPegawai: 298,
        persentase: 10.23,
        warna: '#2563EB',
        golonganDominan: 'Golongan III/c - IV/b',
      },
      {
        id: 's1',
        tingkatPendidikan: 'S1 / D4 (Sarjana)',
        jumlahPegawai: 1512,
        persentase: 51.89,
        warna: '#0284C7',
        golonganDominan: 'Golongan III/a - III/d',
      },
      {
        id: 'd3',
        tingkatPendidikan: 'D3 (Diploma)',
        jumlahPegawai: 436,
        persentase: 14.96,
        warna: '#0D9488',
        golonganDominan: 'Golongan II/c - III/b',
      },
      {
        id: 'sma',
        tingkatPendidikan: 'SMA / SMK',
        jumlahPegawai: 572,
        persentase: 19.63,
        warna: '#F59E0B',
        golonganDominan: 'Golongan II/a - II/d',
      },
      {
        id: 'smp_sd',
        tingkatPendidikan: 'SMP / SD',
        jumlahPegawai: 75,
        persentase: 2.57,
        warna: '#94A3B8',
        golonganDominan: 'Golongan I/c - I/d',
      },
    ],
    sistemMerit: {
      aspekList: [
        {
          id: 'aspek-1',
          kodeAspek: 'ASPEK_1',
          nama: 'Perencanaan Kebutuhan',
          bobotPersen: 10,
          nilaiMaks: 40,
          nilaiAspek: 34.5,
          indeksAspek: 0.863,
          statusPemenuhan: 'Sangat Baik',
          deskripsiRingkas: 'Peta jabatan dan Analisis Beban Kerja disusun berbasis rencana strategis.',
          poinKunci: ['e-Formasi BKN terisi', 'Peta jabatan disahkan pimpinan'],
        },
        {
          id: 'aspek-2',
          kodeAspek: 'ASPEK_2',
          nama: 'Pengadaan',
          bobotPersen: 10,
          nilaiMaks: 40,
          nilaiAspek: 33.5,
          indeksAspek: 0.838,
          statusPemenuhan: 'Baik',
          deskripsiRingkas: 'Rekrutmen CASN berbasis CAT BKN dengan pengawasan ketat.',
          poinKunci: ['Tes CAT BKN akuntabel', 'Hasil seleksi terbuka'],
        },
        {
          id: 'aspek-3',
          kodeAspek: 'ASPEK_3',
          nama: 'Pengembangan Karir',
          bobotPersen: 30,
          nilaiMaks: 120,
          nilaiAspek: 96.0,
          indeksAspek: 0.800,
          statusPemenuhan: 'Baik',
          deskripsiRingkas: 'Pengembangan kompetensi pegawai dan rintisan talent pool.',
          poinKunci: ['Uji kompetensi asesmen berkala', 'Rata-rata 21.2 JP per pegawai'],
        },
        {
          id: 'aspek-4',
          kodeAspek: 'ASPEK_4',
          nama: 'Promosi dan Mutasi',
          bobotPersen: 10,
          nilaiMaks: 40,
          nilaiAspek: 32.0,
          indeksAspek: 0.800,
          statusPemenuhan: 'Baik',
          deskripsiRingkas: 'Seleksi terbuka JPT dan uji kelayakan promosi internal.',
          poinKunci: ['Pansel seleksi terbuka JPT', 'Mutasi lintas kedeputian teratur'],
        },
        {
          id: 'aspek-5',
          kodeAspek: 'ASPEK_5',
          nama: 'Manajemen Kinerja',
          bobotPersen: 20,
          nilaiMaks: 80,
          nilaiAspek: 64.0,
          indeksAspek: 0.800,
          statusPemenuhan: 'Baik',
          deskripsiRingkas: 'Penetapan target kinerja SKP dan evaluasi tahunan.',
          poinKunci: ['SKP berbasis PermenPAN-RB No 6/2022', 'Evaluasi akhir tahun serentak'],
        },
        {
          id: 'aspek-6',
          kodeAspek: 'ASPEK_6',
          nama: 'Penggajian, Penghargaan, dan Disiplin',
          bobotPersen: 10,
          nilaiMaks: 40,
          nilaiAspek: 32.0,
          indeksAspek: 0.800,
          statusPemenuhan: 'Baik',
          deskripsiRingkas: 'Kepatuhan pembayaran gaji, tukin terstruktur, dan disiplin jam kerja.',
          poinKunci: ['Tepat waktu pembayaran tunjangan', 'Teguran disiplin terdokumentasi'],
        },
        {
          id: 'aspek-7',
          kodeAspek: 'ASPEK_7',
          nama: 'Perlindungan dan Pelayanan',
          bobotPersen: 4,
          nilaiMaks: 16,
          nilaiAspek: 13.8,
          indeksAspek: 0.863,
          statusPemenuhan: 'Sangat Baik',
          deskripsiRingkas: 'Proteksi kesehatan BPJS dan bantuan hukum tugas dinas.',
          poinKunci: ['BPJS Kesehatan & Ketenagakerjaan aktif', 'Klinik pratama internal'],
        },
        {
          id: 'aspek-8',
          kodeAspek: 'ASPEK_8',
          nama: 'Sistem Informasi',
          bobotPersen: 6,
          nilaiMaks: 24,
          nilaiAspek: 17.5,
          indeksAspek: 0.729,
          statusPemenuhan: 'Baik',
          deskripsiRingkas: 'Pengembangan SIMPEG online dan integrasi presensi.',
          poinKunci: ['SIMPEG BP Batam online', 'Migrasi data berkala'],
        },
      ],
      datasetRow: {
        TAHUN: 2025,
        NILAI_PERENCANAAN_KEBUTUHAN: 34.5,
        NILAI_PENGADAAN: 33.5,
        NILAI_PENGEMBANGAN_KARIR: 96.0,
        NILAI_PROMOSI_DAN_MUTASI: 32.0,
        NILAI_MANAJEMEN_KINERJA: 64.0,
        NILAI_PENGGAJIAN_PENGHARGAAN_DISIPLIN: 32.0,
        NILAI_PERLINDUNGAN_DAN_PELAYANAN: 13.8,
        NILAI_SISTEM_INFORMASI: 17.5,
        INDEKS_PERENCANAAN_KEBUTUHAN: 0.863,
        INDEKS_PENGADAAN: 0.838,
        INDEKS_PENGEMBANGAN_KARIR: 0.800,
        INDEKS_PROMOSI_DAN_MUTASI: 0.800,
        INDEKS_MANAJEMEN_KINERJA: 0.800,
        INDEKS_PENGGAJIAN_PENGHARGAAN_DISIPLIN: 0.800,
        INDEKS_PERLINDUNGAN_DAN_PELAYANAN: 0.863,
        INDEKS_SISTEM_INFORMASI: 0.729,
        TOTAL_NILAI_MERIT: 323.3,
        INDEKS_SISTEM_MERIT: 0.8083,
        STATUS_PEMENUHAN: 'Kategori III (Baik)',
        KATEGORI_PREDIKAT: 'Kategori III (Baik)',
      },
    },
  },
  2024: {
    tahun: 2024,
    totalPegawai: 2845,
    gender: {
      lakiLaki: {
        jenisKelamin: 'Laki-laki',
        jumlah: 1735,
        persentase: 60.98,
        rataRataUsia: 40.2,
      },
      perempuan: {
        jenisKelamin: 'Perempuan',
        jumlah: 1110,
        persentase: 39.02,
        rataRataUsia: 37.5,
      },
    },
    statusKepegawaian: [
      {
        id: 'pns',
        statusPegawai: 'Pegawai Negeri Sipil (PNS)',
        jumlahPegawai: 1085,
        persentase: 38.14,
        warna: '#2563EB',
        deskripsi: 'Aparatur Sipil Negara tetap dengan penetapan NIP BKN.',
      },
      {
        id: 'p2k',
        statusPegawai: 'Pegawai Tetap BP Batam (P2K)',
        jumlahPegawai: 902,
        persentase: 31.70,
        warna: '#0D9488',
        deskripsi: 'Pegawai berstatus tetap non-PNS berdasarkan SK Kepala BP Batam.',
      },
      {
        id: 'p3k',
        statusPegawai: 'PPPK (P3K)',
        jumlahPegawai: 280,
        persentase: 9.84,
        warna: '#7C3AED',
        deskripsi: 'Pegawai Pemerintah dengan Perjanjian Kerja formasi awal.',
      },
      {
        id: 'ptt',
        statusPegawai: 'Pegawai Tidak Tetap (PTT)',
        jumlahPegawai: 432,
        persentase: 15.18,
        warna: '#EA580C',
        deskripsi: 'Pegawai kontrak pendukung operasional dan pelayanan perkantoran.',
      },
      {
        id: 'profesional',
        statusPegawai: 'Tenaga Profesional / Kontrak Khusus',
        jumlahPegawai: 146,
        persentase: 5.13,
        warna: '#D97706',
        deskripsi: 'Tenaga keahlian khusus dan konsultan teknis operasional.',
      },
    ],
    pendidikan: [
      {
        id: 's3',
        tingkatPendidikan: 'S3 (Doktor)',
        jumlahPegawai: 18,
        persentase: 0.63,
        warna: '#4338CA',
        golonganDominan: 'Golongan IV/c - IV/e',
      },
      {
        id: 's2',
        tingkatPendidikan: 'S2 (Magister)',
        jumlahPegawai: 275,
        persentase: 9.67,
        warna: '#2563EB',
        golonganDominan: 'Golongan III/c - IV/b',
      },
      {
        id: 's1',
        tingkatPendidikan: 'S1 / D4 (Sarjana)',
        jumlahPegawai: 1445,
        persentase: 50.79,
        warna: '#0284C7',
        golonganDominan: 'Golongan III/a - III/d',
      },
      {
        id: 'd3',
        tingkatPendidikan: 'D3 (Diploma)',
        jumlahPegawai: 450,
        persentase: 15.82,
        warna: '#0D9488',
        golonganDominan: 'Golongan II/c - III/b',
      },
      {
        id: 'sma',
        tingkatPendidikan: 'SMA / SMK',
        jumlahPegawai: 575,
        persentase: 20.21,
        warna: '#F59E0B',
        golonganDominan: 'Golongan II/a - II/d',
      },
      {
        id: 'smp_sd',
        tingkatPendidikan: 'SMP / SD',
        jumlahPegawai: 82,
        persentase: 2.88,
        warna: '#94A3B8',
        golonganDominan: 'Golongan I/c - I/d',
      },
    ],
    sistemMerit: {
      aspekList: [
        {
          id: 'aspek-1',
          kodeAspek: 'ASPEK_1',
          nama: 'Perencanaan Kebutuhan',
          bobotPersen: 10,
          nilaiMaks: 40,
          nilaiAspek: 32.0,
          indeksAspek: 0.800,
          statusPemenuhan: 'Baik',
          deskripsiRingkas: 'Peta jabatan awal dan ABK manual.',
          poinKunci: ['Analisis jabatan berjalan'],
        },
        {
          id: 'aspek-2',
          kodeAspek: 'ASPEK_2',
          nama: 'Pengadaan',
          bobotPersen: 10,
          nilaiMaks: 40,
          nilaiAspek: 31.0,
          indeksAspek: 0.775,
          statusPemenuhan: 'Baik',
          deskripsiRingkas: 'Rekrutmen CASN melalui seleksi nasional.',
          poinKunci: ['CAT BKN terintegrasi'],
        },
        {
          id: 'aspek-3',
          kodeAspek: 'ASPEK_3',
          nama: 'Pengembangan Karir',
          bobotPersen: 30,
          nilaiMaks: 120,
          nilaiAspek: 88.0,
          indeksAspek: 0.733,
          statusPemenuhan: 'Baik',
          deskripsiRingkas: 'Program pelatihan internal dan sertifikasi profesi.',
          poinKunci: ['Rata-rata 18.5 JP per pegawai'],
        },
        {
          id: 'aspek-4',
          kodeAspek: 'ASPEK_4',
          nama: 'Promosi dan Mutasi',
          bobotPersen: 10,
          nilaiMaks: 40,
          nilaiAspek: 29.5,
          indeksAspek: 0.738,
          statusPemenuhan: 'Baik',
          deskripsiRingkas: 'Seleksi berkala jabatan pengawas dan administrator.',
          poinKunci: ['Uji portofolio jabatan'],
        },
        {
          id: 'aspek-5',
          kodeAspek: 'ASPEK_5',
          nama: 'Manajemen Kinerja',
          bobotPersen: 20,
          nilaiMaks: 80,
          nilaiAspek: 58.0,
          indeksAspek: 0.725,
          statusPemenuhan: 'Baik',
          deskripsiRingkas: 'Penyusunan SKP tahunan berbasis form manual-online.',
          poinKunci: ['Capaian kinerja unit kerja'],
        },
        {
          id: 'aspek-6',
          kodeAspek: 'ASPEK_6',
          nama: 'Penggajian, Penghargaan, dan Disiplin',
          bobotPersen: 10,
          nilaiMaks: 40,
          nilaiAspek: 30.5,
          indeksAspek: 0.763,
          statusPemenuhan: 'Baik',
          deskripsiRingkas: 'Sistem kompensasi dan absensi pegawai.',
          poinKunci: ['Ketepatan penggajian bulanan'],
        },
        {
          id: 'aspek-7',
          kodeAspek: 'ASPEK_7',
          nama: 'Perlindungan dan Pelayanan',
          bobotPersen: 4,
          nilaiMaks: 16,
          nilaiAspek: 13.0,
          indeksAspek: 0.813,
          statusPemenuhan: 'Baik',
          deskripsiRingkas: 'Jaminan perlindungan tenaga kerja dan layanan kesehatan.',
          poinKunci: ['BPJS aktif seluruh pegawai'],
        },
        {
          id: 'aspek-8',
          kodeAspek: 'ASPEK_8',
          nama: 'Sistem Informasi',
          bobotPersen: 6,
          nilaiMaks: 24,
          nilaiAspek: 15.5,
          indeksAspek: 0.646,
          statusPemenuhan: 'Cukup',
          deskripsiRingkas: 'SIMPEG v1.0 dalam tahap peremajaan.',
          poinKunci: ['Digitalisasi dokumen kepegawaian'],
        },
      ],
      datasetRow: {
        TAHUN: 2024,
        NILAI_PERENCANAAN_KEBUTUHAN: 32.0,
        NILAI_PENGADAAN: 31.0,
        NILAI_PENGEMBANGAN_KARIR: 88.0,
        NILAI_PROMOSI_DAN_MUTASI: 29.5,
        NILAI_MANAJEMEN_KINERJA: 58.0,
        NILAI_PENGGAJIAN_PENGHARGAAN_DISIPLIN: 30.5,
        NILAI_PERLINDUNGAN_DAN_PELAYANAN: 13.0,
        NILAI_SISTEM_INFORMASI: 15.5,
        INDEKS_PERENCANAAN_KEBUTUHAN: 0.800,
        INDEKS_PENGADAAN: 0.775,
        INDEKS_PENGEMBANGAN_KARIR: 0.733,
        INDEKS_PROMOSI_DAN_MUTASI: 0.738,
        INDEKS_MANAJEMEN_KINERJA: 0.725,
        INDEKS_PENGGAJIAN_PENGHARGAAN_DISIPLIN: 0.763,
        INDEKS_PERLINDUNGAN_DAN_PELAYANAN: 0.813,
        INDEKS_SISTEM_INFORMASI: 0.646,
        TOTAL_NILAI_MERIT: 297.5,
        INDEKS_SISTEM_MERIT: 0.7438,
        STATUS_PEMENUHAN: 'Kategori III (Baik)',
        KATEGORI_PREDIKAT: 'Kategori III (Baik)',
      },
    },
  },
};

export const STANDAR_KASN_KONVERSI: StandarKasnKonversi[] = [
  {
    kategori: 'IV',
    namaKategori: 'Kategori IV',
    nilai: '325 – 400',
    rentangSkor: '325 – 400',
    mutuPelayanan: '0.81 – 1',
    rentangIndeks: '0.81 – 1',
    predikat: 'Sangat Baik',
    minNilai: 325,
    maxNilai: 400,
    minMutu: 0.81,
    maxMutu: 1.0,
    warna: '#059669', // Emerald
    bgWarna: 'bg-emerald-50 text-emerald-800 border-emerald-200',
    badgeWarna: 'bg-emerald-100 text-emerald-800 border border-emerald-300',
    konsekuensi: 'Dapat dikecualikan dari seleksi terbuka pengisian Jabatan Pimpinan Tinggi (JPT) melalui sistem rotasi talent pool internal.',
  },
  {
    kategori: 'III',
    namaKategori: 'Kategori III',
    nilai: '250 – 324',
    rentangSkor: '250 – 324',
    mutuPelayanan: '0.61 – 0.8',
    rentangIndeks: '0.61 – 0.8',
    predikat: 'Baik',
    minNilai: 250,
    maxNilai: 324,
    minMutu: 0.61,
    maxMutu: 0.8,
    warna: '#2563EB', // Blue
    bgWarna: 'bg-blue-50 text-blue-800 border-blue-200',
    badgeWarna: 'bg-blue-100 text-blue-800 border border-blue-300',
    konsekuensi: 'Penerapan sistem merit sudah berjalan efektif, dapat mengisi sebagian JPT melalui seleksi terbuka terawasi.',
  },
  {
    kategori: 'II',
    namaKategori: 'Kategori II',
    nilai: '175 – 249',
    rentangSkor: '175 – 249',
    mutuPelayanan: '0.41 – 0.6',
    rentangIndeks: '0.41 – 0.6',
    predikat: 'Kurang',
    minNilai: 175,
    maxNilai: 249,
    minMutu: 0.41,
    maxMutu: 0.6,
    warna: '#D97706', // Amber
    bgWarna: 'bg-amber-50 text-amber-800 border-amber-200',
    badgeWarna: 'bg-amber-100 text-amber-800 border border-amber-300',
    konsekuensi: 'Perlu percepatan pembenahan manajemen talenta, manajemen kinerja, dan sistem informasi kepegawaian.',
  },
  {
    kategori: 'I',
    namaKategori: 'Kategori I',
    nilai: '100 – 174',
    rentangSkor: '100 – 174',
    mutuPelayanan: '0.2 – 0.4',
    rentangIndeks: '0.2 – 0.4',
    predikat: 'Buruk',
    minNilai: 100,
    maxNilai: 174,
    minMutu: 0.2,
    maxMutu: 0.4,
    warna: '#DC2626', // Red
    bgWarna: 'bg-rose-50 text-rose-800 border-rose-200',
    badgeWarna: 'bg-rose-100 text-rose-800 border border-rose-300',
    konsekuensi: 'Seluruh pengisian jabatan wajib melalui seleksi terbuka penuh dan pengawasan ketat Komisi Aparatur Sipil Negara (KASN).',
  },
];
