import {
  PnbpBandaraItem,
  OperatorFlightData,
  BulananPenumpangData,
  FlightMovementRecord,
  AirportRouteData,
  AirportAssetSpec,
} from './types';

// DATASET NO 1: DATA REALISASI PENERIMAAN NEGARA BUKAN PAJAK (PNBP) BANDARA
// Sumber: Satu Data Hal 11 No 1 (Atribut: JENIS PENERIMAAN, ANGGARAN PNBP, TOTAL IDR)
export const PNBP_BANDARA_ITEMS: PnbpBandaraItem[] = [
  {
    id: 'pnbp-pjp2u',
    jenisPenerimaan: 'Pelayanan Jasa Penumpang Pesawat Udara (PJP2U / PSC)',
    kodeAkun: '424111 - PJP2U Domestik & Internasional',
    anggaranPnbp: 135000000000, // Rp 135 Miliar
    realisasiTotalIdr: 148200000000, // Rp 148,20 Miliar
    persentaseCapaian: 109.78,
    keterangan: 'Penerimaan kontribusi retribusi pass penumpang terminal keberangkatan domestik & intl.',
    iconName: 'Users',
  },
  {
    id: 'pnbp-pjp4u',
    jenisPenerimaan: 'Pelayanan Jasa Pendaratan, Penempatan & Penyimpanan Pesawat (PJP4U)',
    kodeAkun: '424112 - PJP4U Landing & Parking Fee',
    anggaranPnbp: 72000000000, // Rp 72 Miliar
    realisasiTotalIdr: 79850000000, // Rp 79,85 Miliar
    persentaseCapaian: 110.9,
    keterangan: 'Jasa landing fee, parking stand apron, dan navigasi approach Bandara Hang Nadim.',
    iconName: 'PlaneLanding',
  },
  {
    id: 'pnbp-kargo',
    jenisPenerimaan: 'Jasa Pelayanan Kargo & Pos Udara (EMPU)',
    kodeAkun: '424113 - Terminal Kargo & Gudang Logistik',
    anggaranPnbp: 38000000000, // Rp 38 Miliar
    realisasiTotalIdr: 41620000000, // Rp 41,62 Miliar
    persentaseCapaian: 109.53,
    keterangan: 'Tarif jasa kargo inbound/outbound, regulated agent, serta sewa gudang kargo Batam.',
    iconName: 'Package',
  },
  {
    id: 'pnbp-garbarata',
    jenisPenerimaan: 'Jasa Pemakaian Garbarata (Aviobridge) & Fasilitas Apron',
    kodeAkun: '424114 - Aviobridge & GSE Apron Handling',
    anggaranPnbp: 18000000000, // Rp 18 Miliar
    realisasiTotalIdr: 19480000000, // Rp 19,48 Miliar
    persentaseCapaian: 108.22,
    keterangan: 'Utilisasi 6 unit garbarata terhubung terminal untuk kemudahan embarkasi/debarkasi.',
    iconName: 'Milestone',
  },
  {
    id: 'pnbp-konsesi-lahan',
    jenisPenerimaan: 'Pemanfaatan Lahan, Ruang & Konsesi Fasilitas Komersial Bandara',
    kodeAkun: '424115 - Konsesi F&B, Retail, Lounge & Advertising',
    anggaranPnbp: 22000000000, // Rp 22 Miliar
    realisasiTotalIdr: 23300000000, // Rp 23,30 Miliar
    persentaseCapaian: 105.91,
    keterangan: 'Sewa ruang komersial terminal penumpang, duty free, periklanan, dan lounge eksekutif.',
    iconName: 'Store',
  },
];

// Ringkasan Agregat PNBP
export const TOTAL_ANGGARAN_PNBP = PNBP_BANDARA_ITEMS.reduce((sum, item) => sum + item.anggaranPnbp, 0); // Rp 285 Miliar
export const TOTAL_REALISASI_PNBP = PNBP_BANDARA_ITEMS.reduce((sum, item) => sum + item.realisasiTotalIdr, 0); // Rp 312,45 Miliar
export const CAPAIAN_TOTAL_PNBP_PERSEN = Number(((TOTAL_REALISASI_PNBP / TOTAL_ANGGARAN_PNBP) * 100).toFixed(2)); // 109.63%

// DATASET NO 2: DAFTAR ARUS LALU LINTAS UDARA (DATA PENERBANGAN & PENUMPANG)
// Ringkasan Total Tahunan Penerbangan & Penumpang Hang Nadim (BTH / WIDD)
export const TOTAL_PENERBANGAN_TAHUNAN = 38450; // Total pergerakan pesawat (A/D)
export const TOTAL_PENERBANGAN_ARRIVAL = 19180;
export const TOTAL_PENERBANGAN_DEPARTURE = 19270;
export const TOTAL_PENERBANGAN_DOMESTIK = 36850;
export const TOTAL_PENERBANGAN_INTERNASIONAL = 1600;

export const TOTAL_PENUMPANG_TAHUNAN = 4862300; // 4,86 Juta pax
export const TOTAL_PENUMPANG_ARRIVAL = 2385790;
export const TOTAL_PENUMPANG_DEPARTURE = 2409890;
export const TOTAL_PENUMPANG_TRANSIT = 66620;

export const TOTAL_KARGO_TON = 46280; // 46,28 ribu ton kargo udara
export const TOTAL_BAGASI_KG = 38940000; // 38,94 juta kg bagasi tercatat
export const AVERAGE_SEAT_LOAD_FACTOR = 84.6; // Rata-rata okupansi kursi

// JUMLAH PENERBANGAN BERDASARKAN OPERATOR (DATASET SATU DATA NO 10 & PDF OP-PENERBANGAN)
export const OPERATOR_FLIGHT_DATA: OperatorFlightData[] = [
  {
    id: 'op-lion',
    namaMaskapai: 'Lion Air',
    kodeIata: 'JT',
    kodeIcao: 'LNI',
    kategori: 'Lion Group',
    tipe: 'PENUMPANG',
    jenisPenerbangan: 'DOMESTIK',
    status: 'BEROPERASI',
    siup: 'BERJADWAL & TIDAK BERJADWAL',
    jumlahPenerbangan: 12450,
    sharePersen: 32.38,
    totalPenumpang: 1720000,
    loadFactorPersen: 86.2,
    armadaDominan: 'Boeing 737-800 / 900ER',
    ruteUtama: ['CGK (Jakarta)', 'SUB (Surabaya)', 'KNO (Medan)', 'PDG (Padang)', 'PKU (Pekanbaru)'],
  },
  {
    id: 'op-citilink',
    namaMaskapai: 'Citilink Indonesia',
    kodeIata: 'QG',
    kodeIcao: 'CTV',
    kategori: 'Garuda Group',
    tipe: 'PENUMPANG',
    jenisPenerbangan: 'DOMESTIK',
    status: 'BEROPERASI',
    siup: 'BERJADWAL & TIDAK BERJADWAL',
    jumlahPenerbangan: 7120,
    sharePersen: 18.52,
    totalPenumpang: 985000,
    loadFactorPersen: 85.4,
    armadaDominan: 'Airbus A320-200',
    ruteUtama: ['CGK (Jakarta)', 'SUB (Surabaya)', 'KNO (Medan)', 'PLM (Palembang)'],
  },
  {
    id: 'op-super-air-jet',
    namaMaskapai: 'Super Air Jet',
    kodeIata: 'IU',
    kodeIcao: 'SJV',
    kategori: 'Lion Group',
    tipe: 'PENUMPANG',
    jenisPenerbangan: 'DOMESTIK',
    status: 'BEROPERASI',
    siup: 'BERJADWAL & TIDAK BERJADWAL',
    jumlahPenerbangan: 5480,
    sharePersen: 14.25,
    totalPenumpang: 760000,
    loadFactorPersen: 87.1,
    armadaDominan: 'Airbus A320-200',
    ruteUtama: ['CGK (Jakarta)', 'PDG (Padang)', 'PKU (Pekanbaru)', 'PLM (Palembang)', 'PNK (Pontianak)'],
  },
  {
    id: 'op-batik-air',
    namaMaskapai: 'Batik Air',
    kodeIata: 'ID',
    kodeIcao: 'BTK',
    kategori: 'Lion Group',
    tipe: 'PENUMPANG',
    jenisPenerbangan: 'DOMESTIK',
    status: 'BEROPERASI',
    siup: 'BERJADWAL & TIDAK BERJADWAL',
    jumlahPenerbangan: 4230,
    sharePersen: 11.0,
    totalPenumpang: 590000,
    loadFactorPersen: 84.8,
    armadaDominan: 'Boeing 737-800 / Airbus A320',
    ruteUtama: ['CGK (Jakarta - Soekarno Hatta)', 'HLP (Jakarta - Halim PK)'],
  },
  {
    id: 'op-garuda',
    namaMaskapai: 'Garuda Indonesia',
    kodeIata: 'GA',
    kodeIcao: 'GIA',
    kategori: 'Garuda Group',
    tipe: 'PENUMPANG',
    jenisPenerbangan: 'DOMESTIK & INTERNASIONAL',
    status: 'BEROPERASI',
    siup: 'BERJADWAL & TIDAK BERJADWAL',
    jumlahPenerbangan: 2840,
    sharePersen: 7.39,
    totalPenumpang: 382000,
    loadFactorPersen: 83.5,
    armadaDominan: 'Boeing 737-800 NG / Boeing 777-300ER (Haji)',
    ruteUtama: ['CGK (Jakarta)', 'JED (Jeddah - Embarkasi Haji Batam)'],
  },
  {
    id: 'op-wings-air',
    namaMaskapai: 'Wings Air',
    kodeIata: 'IW',
    kodeIcao: 'WON',
    kategori: 'Lion Group',
    tipe: 'PENUMPANG',
    jenisPenerbangan: 'DOMESTIK',
    status: 'BEROPERASI',
    siup: 'BERJADWAL & TIDAK BERJADWAL',
    jumlahPenerbangan: 2360,
    sharePersen: 6.14,
    totalPenumpang: 148000,
    loadFactorPersen: 81.3,
    armadaDominan: 'ATR 72-500 / 600',
    ruteUtama: ['NTX (Natuna Ranai)', 'MWK (Matak Anambas)', 'DJB (Jambi)', 'TNJ (Tanjungpinang)'],
  },
  {
    id: 'op-airasia',
    namaMaskapai: 'AirAsia Berhad / Indonesia AirAsia',
    kodeIata: 'AK / QZ',
    kodeIcao: 'AXM / AWQ',
    kategori: 'AirAsia',
    tipe: 'PENUMPANG',
    jenisPenerbangan: 'DOMESTIK & INTERNASIONAL',
    status: 'BEROPERASI',
    siup: 'BERJADWAL & TIDAK BERJADWAL',
    jumlahPenerbangan: 1420,
    sharePersen: 3.69,
    totalPenumpang: 172000,
    loadFactorPersen: 85.9,
    armadaDominan: 'Airbus A320',
    ruteUtama: ['KUL (Kuala Lumpur)', 'SZB (Subang Jaya)', 'CGK (Jakarta)'],
  },
  {
    id: 'op-pelita-air',
    namaMaskapai: 'Pelita Air Service',
    kodeIata: 'IP',
    kodeIcao: 'PAS',
    kategori: 'Perintis/Lainnya',
    tipe: 'PENUMPANG',
    jenisPenerbangan: 'DOMESTIK',
    status: 'BEROPERASI',
    siup: 'BERJADWAL & TIDAK BERJADWAL',
    jumlahPenerbangan: 1180,
    sharePersen: 3.07,
    totalPenumpang: 161000,
    loadFactorPersen: 84.1,
    armadaDominan: 'Airbus A320-200',
    ruteUtama: ['CGK (Jakarta)'],
  },
  {
    id: 'op-susi-air',
    namaMaskapai: 'Susi Air (PT ASI Pudjiastuti Aviation)',
    kodeIata: 'SI',
    kodeIcao: 'VRS',
    kategori: 'Perintis/Lainnya',
    tipe: 'PENUMPANG',
    jenisPenerbangan: 'DOMESTIK',
    status: 'BEROPERASI',
    siup: 'BERJADWAL (PERINTIS)',
    jumlahPenerbangan: 680,
    sharePersen: 1.77,
    totalPenumpang: 7300,
    loadFactorPersen: 78.4,
    armadaDominan: 'Cessna 208B Grand Caravan',
    ruteUtama: ['Dabo Singkep', 'Karimun', 'Pasir Pengaraian', 'Tambelan'],
  },
  {
    id: 'op-kargo-gabungan',
    namaMaskapai: 'Kargo Udara Khusus (Tri-M.G, Cardig, My Indo, Asialink)',
    kodeIata: 'CARGO',
    kodeIcao: 'TMG/CRG/MYU',
    kategori: 'Kargo',
    tipe: 'KARGO',
    jenisPenerbangan: 'DOMESTIK & INTERNASIONAL',
    status: 'BEROPERASI',
    siup: 'BERJADWAL & TIDAK BERJADWAL',
    jumlahPenerbangan: 690,
    sharePersen: 1.79,
    totalPenumpang: 0,
    loadFactorPersen: 91.2,
    armadaDominan: 'Boeing 737-300F / 400F / 800BCF Freighter',
    ruteUtama: ['CGK (Jakarta)', 'SIN (Singapura Changi Cargo)', 'KNO (Medan)'],
  },
];

// TREN JUMLAH PENUMPANG & PENERBANGAN BERDASARKAN BULAN (12 BULAN)
export const TREN_BULANAN_PENUMPANG: BulananPenumpangData[] = [
  {
    bulan: 'Januari',
    kodeBulan: 'Jan',
    penumpangDomestikArrival: 188400,
    penumpangDomestikDeparture: 196500,
    penumpangDomestikTransit: 5200,
    penumpangInternasionalArrival: 10400,
    penumpangInternasionalDeparture: 11100,
    totalPenumpang: 411600,
    totalPenerbangan: 3180,
    kargoTon: 3620,
    bagasiKg: 3140000,
    posKg: 84000,
    seatLoadFactor: 83.2,
  },
  {
    bulan: 'Februari',
    kodeBulan: 'Feb',
    penumpangDomestikArrival: 174200,
    penumpangDomestikDeparture: 172900,
    penumpangDomestikTransit: 4800,
    penumpangInternasionalArrival: 11800,
    penumpangInternasionalDeparture: 11500,
    totalPenumpang: 375200,
    totalPenerbangan: 2940,
    kargoTon: 3410,
    bagasiKg: 2890000,
    posKg: 79000,
    seatLoadFactor: 82.5,
  },
  {
    bulan: 'Maret',
    kodeBulan: 'Mar',
    penumpangDomestikArrival: 182100,
    penumpangDomestikDeparture: 184500,
    penumpangDomestikTransit: 5100,
    penumpangInternasionalArrival: 12100,
    penumpangInternasionalDeparture: 12400,
    totalPenumpang: 396200,
    totalPenerbangan: 3120,
    kargoTon: 3790,
    bagasiKg: 3080000,
    posKg: 85000,
    seatLoadFactor: 83.8,
  },
  {
    bulan: 'April (Peak Mudik)',
    kodeBulan: 'Apr',
    penumpangDomestikArrival: 242800,
    penumpangDomestikDeparture: 238600,
    penumpangDomestikTransit: 6800,
    penumpangInternasionalArrival: 14200,
    penumpangInternasionalDeparture: 13900,
    totalPenumpang: 516300,
    totalPenerbangan: 3680,
    kargoTon: 4180,
    bagasiKg: 4210000,
    posKg: 98000,
    seatLoadFactor: 91.4,
  },
  {
    bulan: 'Mei',
    kodeBulan: 'Mei',
    penumpangDomestikArrival: 192500,
    penumpangDomestikDeparture: 194800,
    penumpangDomestikTransit: 5300,
    penumpangInternasionalArrival: 12600,
    penumpangInternasionalDeparture: 12900,
    totalPenumpang: 418100,
    totalPenerbangan: 3240,
    kargoTon: 3820,
    bagasiKg: 3260000,
    posKg: 86000,
    seatLoadFactor: 84.1,
  },
  {
    bulan: 'Juni (Libur Sekolah)',
    kodeBulan: 'Jun',
    penumpangDomestikArrival: 218600,
    penumpangDomestikDeparture: 224100,
    penumpangDomestikTransit: 6100,
    penumpangInternasionalArrival: 15400,
    penumpangInternasionalDeparture: 15800,
    totalPenumpang: 480000,
    totalPenerbangan: 3510,
    kargoTon: 3980,
    bagasiKg: 3840000,
    posKg: 91000,
    seatLoadFactor: 88.5,
  },
  {
    bulan: 'Juli (Peak Holiday)',
    kodeBulan: 'Jul',
    penumpangDomestikArrival: 226400,
    penumpangDomestikDeparture: 229700,
    penumpangDomestikTransit: 6400,
    penumpangInternasionalArrival: 16200,
    penumpangInternasionalDeparture: 16800,
    totalPenumpang: 495500,
    totalPenerbangan: 3590,
    kargoTon: 4050,
    bagasiKg: 3990000,
    posKg: 93000,
    seatLoadFactor: 89.2,
  },
  {
    bulan: 'Agustus (HUT RI)',
    kodeBulan: 'Agu',
    penumpangDomestikArrival: 201200,
    penumpangDomestikDeparture: 203500,
    penumpangDomestikTransit: 5500,
    penumpangInternasionalArrival: 13800,
    penumpangInternasionalDeparture: 13900,
    totalPenumpang: 437900,
    totalPenerbangan: 3320,
    kargoTon: 3910,
    bagasiKg: 3410000,
    posKg: 88000,
    seatLoadFactor: 85.6,
  },
  {
    bulan: 'September',
    kodeBulan: 'Sep',
    penumpangDomestikArrival: 186400,
    penumpangDomestikDeparture: 188200,
    penumpangDomestikTransit: 5000,
    penumpangInternasionalArrival: 12200,
    penumpangInternasionalDeparture: 12500,
    totalPenumpang: 404300,
    totalPenerbangan: 3140,
    kargoTon: 3750,
    bagasiKg: 3120000,
    posKg: 85000,
    seatLoadFactor: 83.4,
  },
  {
    bulan: 'Oktober',
    kodeBulan: 'Okt',
    penumpangDomestikArrival: 191800,
    penumpangDomestikDeparture: 193400,
    penumpangDomestikTransit: 5200,
    penumpangInternasionalArrival: 12800,
    penumpangInternasionalDeparture: 13100,
    totalPenumpang: 416300,
    totalPenerbangan: 3210,
    kargoTon: 3890,
    bagasiKg: 3250000,
    posKg: 87000,
    seatLoadFactor: 84.3,
  },
  {
    bulan: 'November',
    kodeBulan: 'Nov',
    penumpangDomestikArrival: 189500,
    penumpangDomestikDeparture: 190800,
    penumpangDomestikTransit: 5100,
    penumpangInternasionalArrival: 12500,
    penumpangInternasionalDeparture: 12800,
    totalPenumpang: 410700,
    totalPenerbangan: 3190,
    kargoTon: 3920,
    bagasiKg: 3200000,
    posKg: 88000,
    seatLoadFactor: 83.9,
  },
  {
    bulan: 'Desember (Peak Nataru)',
    kodeBulan: 'Des',
    penumpangDomestikArrival: 242290,
    penumpangDomestikDeparture: 244790,
    penumpangDomestikTransit: 6920,
    penumpangInternasionalArrival: 18500,
    penumpangInternasionalDeparture: 18900,
    totalPenumpang: 531400,
    totalPenerbangan: 3770,
    kargoTon: 4450,
    bagasiKg: 4540000,
    posKg: 104000,
    seatLoadFactor: 92.8,
  },
];

// DATA STRATEGIS 1: RUTE PENERBANGAN LANGSUNG DARI BATAM (DATASET NO 9)
export const AIRPORT_TOP_ROUTES: AirportRouteData[] = [
  {
    kodeRute: 'BTH-CGK',
    kotaAsal: 'Batam (BTH)',
    kotaTujuan: 'Jakarta Soekarno-Hatta (CGK)',
    namaBandara: 'Bandara Internasional Soekarno-Hatta',
    frekuensiMingguan: 148,
    totalPenumpangTahunan: 1680000,
    seatLoadFactor: 88.4,
    maskapaiMelayani: ['Lion Air', 'Citilink', 'Garuda Indonesia', 'Batik Air', 'Super Air Jet', 'Pelita Air'],
    kategori: 'Domestik',
  },
  {
    kodeRute: 'BTH-KNO',
    kotaAsal: 'Batam (BTH)',
    kotaTujuan: 'Medan Kualanamu (KNO)',
    namaBandara: 'Bandara Internasional Kualanamu',
    frekuensiMingguan: 56,
    totalPenumpangTahunan: 595000,
    seatLoadFactor: 86.1,
    maskapaiMelayani: ['Lion Air', 'Citilink', 'Super Air Jet'],
    kategori: 'Domestik',
  },
  {
    kodeRute: 'BTH-SUB',
    kotaAsal: 'Batam (BTH)',
    kotaTujuan: 'Surabaya (SUB)',
    namaBandara: 'Bandara Internasional Juanda',
    frekuensiMingguan: 42,
    totalPenumpangTahunan: 480000,
    seatLoadFactor: 85.2,
    maskapaiMelayani: ['Lion Air', 'Citilink'],
    kategori: 'Domestik',
  },
  {
    kodeRute: 'BTH-PKU',
    kotaAsal: 'Batam (BTH)',
    kotaTujuan: 'Pekanbaru (PKU)',
    namaBandara: 'Bandara Sultan Syarif Kasim II',
    frekuensiMingguan: 35,
    totalPenumpangTahunan: 390000,
    seatLoadFactor: 84.7,
    maskapaiMelayani: ['Lion Air', 'Super Air Jet'],
    kategori: 'Domestik',
  },
  {
    kodeRute: 'BTH-PDG',
    kotaAsal: 'Batam (BTH)',
    kotaTujuan: 'Padang (PDG)',
    namaBandara: 'Bandara Internasional Minangkabau',
    frekuensiMingguan: 28,
    totalPenumpangTahunan: 320000,
    seatLoadFactor: 83.9,
    maskapaiMelayani: ['Lion Air', 'Super Air Jet'],
    kategori: 'Domestik',
  },
  {
    kodeRute: 'BTH-PLM',
    kotaAsal: 'Batam (BTH)',
    kotaTujuan: 'Palembang (PLM)',
    namaBandara: 'Bandara Sultan Mahmud Badaruddin II',
    frekuensiMingguan: 21,
    totalPenumpangTahunan: 235000,
    seatLoadFactor: 82.5,
    maskapaiMelayani: ['Citilink', 'Super Air Jet'],
    kategori: 'Domestik',
  },
  {
    kodeRute: 'BTH-NTX',
    kotaAsal: 'Batam (BTH)',
    kotaTujuan: 'Natuna Ranai (NTX)',
    namaBandara: 'Bandara Raden Sadjad',
    frekuensiMingguan: 14,
    totalPenumpangTahunan: 78000,
    seatLoadFactor: 81.2,
    maskapaiMelayani: ['Wings Air', 'Super Air Jet'],
    kategori: 'Domestik',
  },
  {
    kodeRute: 'BTH-YIA',
    kotaAsal: 'Batam (BTH)',
    kotaTujuan: 'Yogyakarta Kulon Progo (YIA)',
    namaBandara: 'Bandara Internasional Yogyakarta',
    frekuensiMingguan: 21,
    totalPenumpangTahunan: 210000,
    seatLoadFactor: 86.5,
    maskapaiMelayani: ['Lion Air', 'Super Air Jet'],
    kategori: 'Domestik',
  },
  {
    kodeRute: 'BTH-PNK',
    kotaAsal: 'Batam (BTH)',
    kotaTujuan: 'Pontianak Supadio (PNK)',
    namaBandara: 'Bandara Supadio',
    frekuensiMingguan: 14,
    totalPenumpangTahunan: 125000,
    seatLoadFactor: 83.4,
    maskapaiMelayani: ['Lion Air'],
    kategori: 'Domestik',
  },
  {
    kodeRute: 'BTH-DPS',
    kotaAsal: 'Batam (BTH)',
    kotaTujuan: 'Denpasar Bali (DPS)',
    namaBandara: 'Bandara Internasional I Gusti Ngurah Rai',
    frekuensiMingguan: 14,
    totalPenumpangTahunan: 142000,
    seatLoadFactor: 89.1,
    maskapaiMelayani: ['Batik Air', 'Super Air Jet'],
    kategori: 'Domestik',
  },
  {
    kodeRute: 'BTH-LHI',
    kotaAsal: 'Batam (BTH)',
    kotaTujuan: 'Letung Anambas (LHI)',
    namaBandara: 'Bandara Letung Jemaja',
    frekuensiMingguan: 7,
    totalPenumpangTahunan: 28000,
    seatLoadFactor: 79.5,
    maskapaiMelayani: ['Wings Air'],
    kategori: 'Domestik',
  },
  {
    kodeRute: 'BTH-SIQ',
    kotaAsal: 'Batam (BTH)',
    kotaTujuan: 'Dabo Singkep (SIQ)',
    namaBandara: 'Bandara Dabo',
    frekuensiMingguan: 7,
    totalPenumpangTahunan: 18500,
    seatLoadFactor: 76.8,
    maskapaiMelayani: ['Susi Air'],
    kategori: 'Domestik',
  },
  {
    kodeRute: 'BTH-KUL',
    kotaAsal: 'Batam (BTH)',
    kotaTujuan: 'Kuala Lumpur (KUL)',
    namaBandara: 'Kuala Lumpur International Airport',
    frekuensiMingguan: 14,
    totalPenumpangTahunan: 112000,
    seatLoadFactor: 87.3,
    maskapaiMelayani: ['AirAsia Berhad', 'Batik Air Malaysia'],
    kategori: 'Internasional',
  },
  {
    kodeRute: 'BTH-SZB',
    kotaAsal: 'Batam (BTH)',
    kotaTujuan: 'Kuala Lumpur Subang (SZB)',
    namaBandara: 'Sultan Abdul Aziz Shah Airport',
    frekuensiMingguan: 7,
    totalPenumpangTahunan: 46000,
    seatLoadFactor: 82.0,
    maskapaiMelayani: ['Firefly'],
    kategori: 'Internasional',
  },
  {
    kodeRute: 'BTH-ICN',
    kotaAsal: 'Batam (BTH)',
    kotaTujuan: 'Seoul Incheon (ICN)',
    namaBandara: 'Incheon International Airport',
    frekuensiMingguan: 4,
    totalPenumpangTahunan: 32000,
    seatLoadFactor: 91.5,
    maskapaiMelayani: ['Jeju Air Charter', 'Korean Air (Seasonal)'],
    kategori: 'Internasional',
  },
];

// DATA STRATEGIS 2: SPESIFIKASI & PEMANFAATAN FASILITAS ASET BANDARA HANG NADIM (DATASET NO 6, 7, 8)
export const AIRPORT_ASSET_SPECS: AirportAssetSpec[] = [
  {
    fasilitas: 'Runway 04/22 (Landas Pacu Tunggal)',
    spesifikasi: 'Panjang 4.025 m x Lebar 45 m (PCN 85 F/C/X/T, Asphalt Concrete)',
    kapasitasEksisting: 'Mampu didarati Boeing 747-400, B777-300ER, dan Airbus A380',
    utilisasiPersen: 64.5,
    keterangan: 'Runway terpanjang di Indonesia dan kedua terpanjang di Asia Tenggara.',
  },
  {
    fasilitas: 'Terminal Penumpang Eksisting (T1)',
    spesifikasi: 'Luas Bangunan 30.000 m² (2 Lantai, 6 Garbarata)',
    kapasitasEksisting: '5.000.000 penumpang / tahun',
    utilisasiPersen: 97.2,
    keterangan: 'Mendekati kapasitas optimal; saat ini proyek Terminal 2 KSO sedang berjalan.',
  },
  {
    fasilitas: 'Apron & Aircraft Parking Stand',
    spesifikasi: 'Luas Apron 165.000 m² dengan Rigid Pavement',
    kapasitasEksisting: '28 Parking Stands (22 Narrow-body + 6 Wide-body)',
    utilisasiPersen: 78.4,
    keterangan: 'Dilengkapi fasilitas hydran refuelling Avtur Pertamina langsung ke pesawat.',
  },
  {
    fasilitas: 'Terminal Kargo & Gudang EMPU',
    spesifikasi: 'Gudang Domestik 12.000 m² + Gudang Internasional 4.500 m²',
    kapasitasEksisting: '60.000 ton kargo / tahun',
    utilisasiPersen: 77.1,
    keterangan: 'Dukungan X-ray dual view Regulated Agent dan sistem cold storage kargo segar.',
  },
  {
    fasilitas: 'Garbarata (Aviobridge)',
    spesifikasi: '6 Unit Garbarata Dual-Tunnel dengan AC Otomatis',
    kapasitasEksisting: '6 Pintu Keberangkatan / Boarding Gate (Gate 1 - 6)',
    utilisasiPersen: 86.8,
    keterangan: 'Tingkat utilisasi tinggi untuk maskapai Full Service dan LCC penerbangan padat.',
  },
];

// SAMPLE REKAP ARUS PENERBANGAN REAL-TIME / DOSSIER KARTU
export const SAMPLE_FLIGHT_MOVEMENTS: FlightMovementRecord[] = [
  {
    id: 'fl-01',
    nomorPenerbangan: 'JT-378',
    operator: 'Lion Air',
    asal: 'Batam (BTH)',
    tujuan: 'Jakarta (CGK)',
    ruteLabel: 'BTH → CGK',
    arah: 'Departure',
    jenisPenerbangan: 'Domestik',
    waktuPenerbangan: '08:15 WIB',
    typePesawat: 'Boeing 737-900ER',
    registrasiPesawat: 'PK-LKP',
    kapasitasKursi: 215,
    penumpangDewasa: 182,
    penumpangAnak: 18,
    penumpangBayi: 4,
    transit: 0,
    totalPenumpang: 204,
    seatLoadFactor: 94.88,
    bagasiKg: 2840,
    kargoKg: 1450,
    posKg: 45,
    statusPenerbangan: 'Departed',
  },
  {
    id: 'fl-02',
    nomorPenerbangan: 'GA-152',
    operator: 'Garuda Indonesia',
    asal: 'Jakarta (CGK)',
    tujuan: 'Batam (BTH)',
    ruteLabel: 'CGK → BTH',
    arah: 'Arrival',
    jenisPenerbangan: 'Domestik',
    waktuPenerbangan: '09:30 WIB',
    typePesawat: 'Boeing 737-800 NG',
    registrasiPesawat: 'PK-GFD',
    kapasitasKursi: 162,
    penumpangDewasa: 135,
    penumpangAnak: 12,
    penumpangBayi: 2,
    transit: 0,
    totalPenumpang: 149,
    seatLoadFactor: 91.97,
    bagasiKg: 2210,
    kargoKg: 1890,
    posKg: 110,
    statusPenerbangan: 'Landed',
  },
  {
    id: 'fl-03',
    nomorPenerbangan: 'QG-940',
    operator: 'Citilink Indonesia',
    asal: 'Batam (BTH)',
    tujuan: 'Surabaya (SUB)',
    ruteLabel: 'BTH → SUB',
    arah: 'Departure',
    jenisPenerbangan: 'Domestik',
    waktuPenerbangan: '10:45 WIB',
    typePesawat: 'Airbus A320-200',
    registrasiPesawat: 'PK-GLB',
    kapasitasKursi: 180,
    penumpangDewasa: 148,
    penumpangAnak: 14,
    penumpangBayi: 3,
    transit: 0,
    totalPenumpang: 165,
    seatLoadFactor: 91.67,
    bagasiKg: 2450,
    kargoKg: 1200,
    posKg: 30,
    statusPenerbangan: 'Departed',
  },
  {
    id: 'fl-04',
    nomorPenerbangan: 'AK-412',
    operator: 'AirAsia Berhad',
    asal: 'Kuala Lumpur (KUL)',
    tujuan: 'Batam (BTH)',
    ruteLabel: 'KUL → BTH',
    arah: 'Arrival',
    jenisPenerbangan: 'Internasional',
    waktuPenerbangan: '11:20 WIB',
    typePesawat: 'Airbus A320-200',
    registrasiPesawat: '9M-AGH',
    kapasitasKursi: 180,
    penumpangDewasa: 151,
    penumpangAnak: 10,
    penumpangBayi: 2,
    transit: 0,
    totalPenumpang: 163,
    seatLoadFactor: 90.55,
    bagasiKg: 2310,
    kargoKg: 640,
    posKg: 0,
    statusPenerbangan: 'Landed',
  },
  {
    id: 'fl-05',
    nomorPenerbangan: 'IU-856',
    operator: 'Super Air Jet',
    asal: 'Batam (BTH)',
    tujuan: 'Medan Kualanamu (KNO)',
    ruteLabel: 'BTH → KNO',
    arah: 'Departure',
    jenisPenerbangan: 'Domestik',
    waktuPenerbangan: '13:00 WIB',
    typePesawat: 'Airbus A320-200',
    registrasiPesawat: 'PK-SAP',
    kapasitasKursi: 180,
    penumpangDewasa: 154,
    penumpangAnak: 12,
    penumpangBayi: 1,
    transit: 0,
    totalPenumpang: 167,
    seatLoadFactor: 92.78,
    bagasiKg: 2190,
    kargoKg: 950,
    posKg: 20,
    statusPenerbangan: 'Scheduled',
  },
  {
    id: 'fl-06',
    nomorPenerbangan: 'IW-1272',
    operator: 'Wings Air',
    asal: 'Natuna Ranai (NTX)',
    tujuan: 'Batam (BTH)',
    ruteLabel: 'NTX → BTH',
    arah: 'Arrival',
    jenisPenerbangan: 'Domestik',
    waktuPenerbangan: '14:10 WIB',
    typePesawat: 'ATR 72-600',
    registrasiPesawat: 'PK-WJH',
    kapasitasKursi: 72,
    penumpangDewasa: 58,
    penumpangAnak: 4,
    penumpangBayi: 1,
    transit: 5,
    totalPenumpang: 63,
    seatLoadFactor: 87.5,
    bagasiKg: 780,
    kargoKg: 320,
    posKg: 15,
    statusPenerbangan: 'Scheduled',
  },
  {
    id: 'fl-07',
    nomorPenerbangan: 'CRG-810',
    operator: 'Kargo Udara Khusus (Tri-M.G, Cardig, My Indo, Asialink)',
    asal: 'Jakarta Halim (HLP)',
    tujuan: 'Batam (BTH)',
    ruteLabel: 'HLP → BTH (Kargo Murni)',
    arah: 'Arrival',
    jenisPenerbangan: 'Domestik',
    waktuPenerbangan: '15:30 WIB',
    typePesawat: 'Boeing 737-400F Freighter',
    registrasiPesawat: 'PK-CLG',
    kapasitasKursi: 0,
    penumpangDewasa: 0,
    penumpangAnak: 0,
    penumpangBayi: 0,
    transit: 0,
    totalPenumpang: 0,
    seatLoadFactor: 100,
    bagasiKg: 0,
    kargoKg: 14800,
    posKg: 1200,
    statusPenerbangan: 'Scheduled',
  },
];
