import {
  KpiPesisirReklamasiSummary,
  PermasalahanPesisirItem,
  RencanaPemanfaatanPesisirItem,
  PerizinanPesisirWaktuItem,
  RekapTahunanPerizinanItem,
  PemanfaatanInvestasiItem,
} from './types';

// EXECUTIVE KPIS (Sesuai Satu Data PDF Hal. 13 - 14)
// MURNI LUAS (HA/M²) DAN KINERJA PELAYANAN, TANPA NILAI INVESTASI
export const KPI_PESISIR_REKLAMASI_DATA: KpiPesisirReklamasiSummary = {
  // 1. KPI Luas Izin Pemanfaatan Kawasan Pesisir dan Izin Reklamasi untuk Investasi (Dataset No. 4)
  kpi1_luasIzinInvestasiHa: 1485.4, // Total Luas Izin (Ha)
  kpi1_targetLuasHa: 1600.0,
  kpi1_totalIzinTerbit: 48,
  kpi1_rataRataLuasHa: 30.9,

  // 2. Persentase Perizinan Pesisir dan Reklamasi yang Selesai Tepat Waktu (Dataset No. 3)
  kpi2_persenTepatWaktu: 92.4, // 92,4%
  kpi2_totalPerizinanSelesai: 158,
  kpi2_totalTepatWaktu: 146,
  kpi2_totalTerlambat: 12,
  kpi2_totalLuasanHa: 1820.5,
  kpi2_rataRataSlaHari: 11.2, // Dari standar SLA 14 hari kerja

  // 3. Persentase Penyelesaian Permasalahan Pesisir dan Reklamasi (Dataset No. 1)
  kpi3_persenPenyelesaianMasalah: 88.6, // 88,6%
  kpi3_totalKasus: 79,
  kpi3_kasusSelesai: 70,
  kpi3_kasusProses: 9,
  kpi3_totalLuasTerdampakHa: 128.5,
  kpi3_rataRataWaktuSelesaiHari: 18.5,

  // 4. Rencana Pemanfaatan Wilayah Pesisir dan Reklamasi (Dataset No. 2 - Data Spasial)
  kpi4_totalRencanaLuasHa: 2150.0,
  kpi4_totalRencanaTitik: 26,

  // Proporsi Luas Reklamasi vs Pesisir (Ha)
  reklamasiVsPesisirHa: {
    reklamasiHa: 912.6,
    pesisirHa: 572.8,
    reklamasiPersen: 61.4,
    pesisirPersen: 38.6,
  },
};

// DATASET NO. 1: Persentase Penyelesaian Permasalahan Pesisir dan Reklamasi
// Atribut PDF (Hal 13-14 & Form Satu Data):
// NAMA PERUSAHAAN, DOKUMEN PERIZINAN, DOKUMEN PENDUKUNG, WILAYAH, LUAS YANG DITERBITKAN, TRIWULAN, TAHUN
export const DATASET_1_PERMASALAHAN: PermasalahanPesisirItem[] = [
  {
    id: 'PMS-001',
    namaPerusahaan: 'PT Marina Nusantara Indah',
    dokumenPerizinan: 'PKKPRL/2024/014/DPKPR (Pemanfaatan Ruang Pesisir)',
    dokumenPendukung: 'Berita Acara Patroli & SK Penghentian Kegiatan No. 04/DPKPR/2026',
    wilayah: 'Batu Ampar & Bengkong',
    luasYangDiterbitkan: 4.8,
    luasDiterbitkanHa: 4.8,
    triwulan: 'Triwulan I',
    tahun: 2026,
    noPengaduan: 'PENG-PSR/2026/014',
    judulKasus: 'Penimbunan Pesisir Tanpa Izin Reklamasi di Area Bakau',
    lokasi: 'Tanjung Sengkuang, Batu Ampar',
    swp: 'Batu Ampar & Bengkong',
    kategori: 'Pemanfaatan Tanpa Izin',
    namaPihakTerkait: 'PT Marina Nusantara Indah',
    tanggalLapor: '12 Jan 2026',
    status: 'Selesai',
    solusiTindakan: 'Penerbitan Surat Peringatan, Penghentian Kegiatan & Restorasi Garis Pantai',
    lamaPenyelesaianHari: 14,
  },
  {
    id: 'PMS-002',
    namaPerusahaan: 'CV Bahari Indah Sentosa',
    dokumenPerizinan: 'SIPR-021/BTM/2024 (Izin Pembangunan Dermaga)',
    dokumenPendukung: 'Laporan Verifikasi Spasial & Nota Dinas Pengawasan No. 12/WAS/2026',
    wilayah: 'Nongsa & Kabil',
    luasYangDiterbitkan: 1.2,
    luasDiterbitkanHa: 1.2,
    triwulan: 'Triwulan I',
    tahun: 2026,
    noPengaduan: 'PENG-PSR/2026/021',
    judulKasus: 'Pelanggaran Garis Sempadan Pesisir Pembangunan Dermaga Pribadi',
    lokasi: 'Teluk Mata Ikan, Sambau',
    swp: 'Nongsa & Kabil',
    kategori: 'Pelanggaran Sempadan Pantai',
    namaPihakTerkait: 'CV Bahari Indah Sentosa',
    tanggalLapor: '03 Feb 2026',
    status: 'Selesai',
    solusiTindakan: 'Penyesuaian Gambar Teknis Layout Dermaga Sesuai Batas Garis Pantai BP Batam',
    lamaPenyelesaianHari: 12,
  },
  {
    id: 'PMS-003',
    namaPerusahaan: 'PT Samudera Karya Shipyard',
    dokumenPerizinan: 'PKKPRL/2023/089/DPKPR (Pematangan Galangan Kapal)',
    dokumenPendukung: 'Rekomendasi Lingkungan DLH & BAP Tim Terpadu No. 89/BAP/2025',
    wilayah: 'Sekupang & Tg. Uncang',
    luasYangDiterbitkan: 8.5,
    luasDiterbitkanHa: 8.5,
    triwulan: 'Triwulan IV',
    tahun: 2025,
    noPengaduan: 'PENG-PSR/2025/089',
    judulKasus: 'Sedimentasi Alur Pelayaran Akibat Erosi Pematangan Lahan Pesisir',
    lokasi: 'Kawasan Industri Galangan Tanjung Uncang',
    swp: 'Sekupang & Tg. Uncang',
    kategori: 'Pencemaran / Sedimentasi',
    namaPihakTerkait: 'PT Samudera Karya Shipyard',
    tanggalLapor: '18 Nov 2025',
    status: 'Selesai',
    solusiTindakan: 'Kewajiban Pengerukan Sendiri (Dredging Mandiri) dan Pemasangan Silt Barrier',
    lamaPenyelesaianHari: 25,
  },
  {
    id: 'PMS-004',
    namaPerusahaan: 'PT Galang Logistik Maritim',
    dokumenPerizinan: 'SIPR-095/BTM/2023 (Konsesi Fasilitas Dermaga Jetty)',
    dokumenPendukung: 'Berita Acara Mediasi Kesepakatan Ruang Laut No. 95/MED/2025',
    wilayah: 'Rempang & Galang',
    luasYangDiterbitkan: 15.0,
    luasDiterbitkanHa: 15.0,
    triwulan: 'Triwulan IV',
    tahun: 2025,
    noPengaduan: 'PENG-PSR/2025/095',
    judulKasus: 'Tumpang Tindih Batas Ruang Laut Konsesi Jetty & Alur Labuh Nelayan',
    lokasi: 'Perairan Selat Galang Baru',
    swp: 'Rempang & Galang',
    kategori: 'Sengketa Batas Laut',
    namaPihakTerkait: 'Kelompok Nelayan Galang & PT Galang Logistik Maritim',
    tanggalLapor: '05 Des 2025',
    status: 'Selesai',
    solusiTindakan: 'Revisi Koridor Alur Pelayaran Nelayan dan Penataan Batas Koordinat Jetty',
    lamaPenyelesaianHari: 21,
  },
  {
    id: 'PMS-005',
    namaPerusahaan: 'PT Citra Bahari Rempang',
    dokumenPerizinan: 'PKKPRL/2025/032/DPKPR (Reklamasi Kawasan Wisata Pesisir)',
    dokumenPendukung: 'Laporan Pengukuran GPS Geodetik & Surat Teguran No. 32/ST/2026',
    wilayah: 'Rempang & Galang',
    luasYangDiterbitkan: 6.4,
    luasDiterbitkanHa: 6.4,
    triwulan: 'Triwulan I',
    tahun: 2026,
    noPengaduan: 'PENG-PSR/2026/032',
    judulKasus: 'Deviasi Desain Batas Timbunan Reklamasi Melebihi Izin PKKPRL',
    lokasi: 'Pesisir Rempang Eco-City Sektor Barat',
    swp: 'Rempang & Galang',
    kategori: 'Deviasi Amdal Reklamasi',
    namaPihakTerkait: 'PT Citra Bahari Rempang',
    tanggalLapor: '20 Feb 2026',
    status: 'Dalam Proses',
    solusiTindakan: 'Audit Ukur Ulang Geodesi, Penghentian Sebagian Zona Deviasi & Penyesuaian Izin',
    lamaPenyelesaianHari: 18,
  },
  {
    id: 'PMS-006',
    namaPerusahaan: 'PT Wisata Pantai Sejahtera',
    dokumenPerizinan: 'SIPR-041/BTM/2025 (Pembangunan Sarana Rekreasi Pesisir)',
    dokumenPendukung: 'BAP Tim Reaksi Cepat Pengendalian Pesisir No. 41/TRC/2026',
    wilayah: 'Sekupang & Tg. Uncang',
    luasYangDiterbitkan: 3.2,
    luasDiterbitkanHa: 3.2,
    triwulan: 'Triwulan I',
    tahun: 2026,
    noPengaduan: 'PENG-PSR/2026/041',
    judulKasus: 'Erosi Tebing Pesisir Akibat Pembukaan Lahan Tanpa Turap Pengaman',
    lokasi: 'Pantai Dangas, Sekupang',
    swp: 'Sekupang & Tg. Uncang',
    kategori: 'Pencemaran / Sedimentasi',
    namaPihakTerkait: 'PT Wisata Pantai Sejahtera',
    tanggalLapor: '08 Mar 2026',
    status: 'Dalam Proses',
    solusiTindakan: 'Instruksi Pembangunan Revetment / Dinding Penahan Ombak Darurat',
    lamaPenyelesaianHari: 9,
  },
  {
    id: 'PMS-007',
    namaPerusahaan: 'PT Kabil Citra Dermaga',
    dokumenPerizinan: 'PKKPRL/2025/077/DPKPR (Pemanfaatan Alur Labuh Pesisir)',
    dokumenPendukung: 'Surat Keputusan Tindak Lanjut Pemantauan No. 77/SKTL/2025',
    wilayah: 'Nongsa & Kabil',
    luasYangDiterbitkan: 5.6,
    luasDiterbitkanHa: 5.6,
    triwulan: 'Triwulan III',
    tahun: 2025,
    noPengaduan: 'PENG-PSR/2025/077',
    judulKasus: 'Pemasangan Pelampung Navigasi Tanpa Koordinasi Kesyahbandaran',
    lokasi: 'Perairan Teluk Kabil Timur',
    swp: 'Nongsa & Kabil',
    kategori: 'Pemanfaatan Tanpa Izin',
    namaPihakTerkait: 'PT Kabil Citra Dermaga',
    tanggalLapor: '14 Agu 2025',
    status: 'Selesai',
    solusiTindakan: 'Penyesuaian Tata Letak Buoy Navigasi Sesuai Peta Batimetri BP Batam',
    lamaPenyelesaianHari: 15,
  },
  {
    id: 'PMS-008',
    namaPerusahaan: 'PT Batam Centre Waterfront City',
    dokumenPerizinan: 'PKKPRL/2025/062/DPKPR (Reklamasi Pematangan Lahan Pesisir)',
    dokumenPendukung: 'Berita Acara Pengawasan Berkala Semesteran No. 62/BAP-SM/2025',
    wilayah: 'Batam Kota',
    luasYangDiterbitkan: 9.8,
    luasDiterbitkanHa: 9.8,
    triwulan: 'Triwulan II',
    tahun: 2025,
    noPengaduan: 'PENG-PSR/2025/062',
    judulKasus: 'Gangguan Drainase Muara Sungai Menuju Laut Akibat Timbunan Sementara',
    lokasi: 'Muara Sungai Batam Centre',
    swp: 'Batam Kota',
    kategori: 'Deviasi Amdal Reklamasi',
    namaPihakTerkait: 'PT Batam Centre Waterfront City',
    tanggalLapor: '22 Mei 2025',
    status: 'Selesai',
    solusiTindakan: 'Normalisasi Sodetan Air Muara dan Pembuatan Kolam Retensi Sementara',
    lamaPenyelesaianHari: 11,
  },
  {
    id: 'PMS-009',
    namaPerusahaan: 'PT Sagulung Galangan Samudera',
    dokumenPerizinan: 'SIPR-050/BTM/2025 (Pembangunan Slipway Perbaikan Kapal)',
    dokumenPendukung: 'Laporan Investigasi Lapangan Gabungan No. 50/LIG/2025',
    wilayah: 'Batu Aji & Sagulung',
    luasYangDiterbitkan: 7.2,
    luasDiterbitkanHa: 7.2,
    triwulan: 'Triwulan II',
    tahun: 2025,
    noPengaduan: 'PENG-PSR/2025/050',
    judulKasus: 'Perluasan Area Slipway Melebihi Batas Garis Pantai Yang Ditetapkan',
    lokasi: 'Pesisir Sei Lekop, Sagulung',
    swp: 'Batu Aji & Sagulung',
    kategori: 'Pelanggaran Sempadan Pantai',
    namaPihakTerkait: 'PT Sagulung Galangan Samudera',
    tanggalLapor: '10 Apr 2025',
    status: 'Selesai',
    solusiTindakan: 'Denda Administratif dan Pemunduran Struktur Ujung Slipway ke Batas Izin',
    lamaPenyelesaianHari: 16,
  },
  {
    id: 'PMS-010',
    namaPerusahaan: 'PT Rempang Bahari Investama',
    dokumenPerizinan: 'PKKPRL/2025/018/DPKPR (Pemanfaatan Perairan Budidaya Modern)',
    dokumenPendukung: 'Berita Acara Kesepakatan Zonasi Budidaya No. 18/BAZ/2025',
    wilayah: 'Rempang & Galang',
    luasYangDiterbitkan: 12.0,
    luasDiterbitkanHa: 12.0,
    triwulan: 'Triwulan I',
    tahun: 2025,
    noPengaduan: 'PENG-PSR/2025/018',
    judulKasus: 'Penataan Koridor Keramba Apung Dengan Jalur Transportasi Laut Lokal',
    lokasi: 'Selat Tiangwangkang, Galang',
    swp: 'Rempang & Galang',
    kategori: 'Sengketa Batas Laut',
    namaPihakTerkait: 'PT Rempang Bahari Investama',
    tanggalLapor: '19 Jan 2025',
    status: 'Selesai',
    solusiTindakan: 'Penataan Ulang Koordinat Keramba Apung Memberikan Ruang Bebas 50m Alur Kapal',
    lamaPenyelesaianHari: 13,
  },
];

// DATASET NO. 2: Rencana Pemanfaatan Wilayah Pesisir dan Reklamasi (Data Spasial)
// Atribut PDF (Hal 14): NAMA PERUSAHAAN, NOMOR IZIN PKKPRL, KOORDINAT, WILAYAH, STATUS KEGIATAN, LUAS, TAHUN PENERBITAN
export const DATASET_2_RENCANA_PEMANFAATAN: RencanaPemanfaatanPesisirItem[] = [
  {
    id: 'RCN-001',
    namaPerusahaan: 'PT Batam Maritime Shipyard & Engineering',
    nomorIzinPkkprl: 'PKKPRL/2026/001/DPKPR',
    koordinat: '1°04\'18.2"N 103°54\'22.6"E',
    wilayah: 'Sekupang & Tg. Uncang',
    swp: 'Sekupang & Tg. Uncang',
    statusKegiatan: 'Kawasan Industri Maritim Lepas Pantai',
    luasHa: 48.5,
    luasM2: 485000,
    tahunPenerbitan: 2026,
    lokasiSpesifik: 'Tanjung Uncang Sektor Barat',
    statusRencana: 'Terbit Rekomendasi Teknis',
  },
  {
    id: 'RCN-002',
    namaPerusahaan: 'PT Kabil Terminal Logistik Internasional',
    nomorIzinPkkprl: 'PKKPRL/2026/002/DPKPR',
    koordinat: '1°07\'45.0"N 104°08\'33.1"E',
    wilayah: 'Nongsa & Kabil',
    swp: 'Nongsa & Kabil',
    statusKegiatan: 'Terminal Logistik Pelabuhan',
    luasHa: 62.0,
    luasM2: 620000,
    tahunPenerbitan: 2026,
    lokasiSpesifik: 'Perairan Selat Kabil',
    statusRencana: 'Tahap Amdal & PKKPRL',
  },
  {
    id: 'RCN-003',
    namaPerusahaan: 'PT Marina Bay Batam Centre Perkasa',
    nomorIzinPkkprl: 'PKKPRL/2025/019/DPKPR',
    koordinat: '1°08\'12.5"N 104°03\'50.4"E',
    wilayah: 'Batam Kota',
    swp: 'Batam Kota',
    statusKegiatan: 'Pengembangan Wisata Bahari',
    luasHa: 35.8,
    luasM2: 358000,
    tahunPenerbitan: 2025,
    lokasiSpesifik: 'Pesisir Teluk Batam Centre',
    statusRencana: 'Terbit Rekomendasi Teknis',
  },
  {
    id: 'RCN-004',
    namaPerusahaan: 'PT Nongsa Digital Waterfront Eco-Resort',
    nomorIzinPkkprl: 'PKKPRL/2025/024/DPKPR',
    koordinat: '1°11\'30.8"N 104°06\'15.0"E',
    wilayah: 'Nongsa & Kabil',
    swp: 'Nongsa & Kabil',
    statusKegiatan: 'Pengembangan Wisata Bahari',
    luasHa: 28.4,
    luasM2: 284000,
    tahunPenerbitan: 2025,
    lokasiSpesifik: 'Pantai Nongsa Village Timur',
    statusRencana: 'Terbit Rekomendasi Teknis',
  },
  {
    id: 'RCN-005',
    namaPerusahaan: 'PT Rempang Clean Energy Hub',
    nomorIzinPkkprl: 'PKKPRL/2026/005/DPKPR',
    koordinat: '0°54\'12.0"N 104°09\'45.2"E',
    wilayah: 'Rempang & Galang',
    swp: 'Rempang & Galang',
    statusKegiatan: 'Rencana Reklamasi Timbunan',
    luasHa: 120.0,
    luasM2: 1200000,
    tahunPenerbitan: 2026,
    lokasiSpesifik: 'Kawasan Pesisir Rempang Utara',
    statusRencana: 'Tahap Amdal & PKKPRL',
  },
  {
    id: 'RCN-006',
    namaPerusahaan: 'PT Harbour Bay Waterfront Extension',
    nomorIzinPkkprl: 'PKKPRL/2025/011/DPKPR',
    koordinat: '1°09\'22.0"N 103°59\'40.6"E',
    wilayah: 'Batu Ampar & Bengkong',
    swp: 'Batu Ampar & Bengkong',
    statusKegiatan: 'Rencana Reklamasi Timbunan',
    luasHa: 18.5,
    luasM2: 185000,
    tahunPenerbitan: 2025,
    lokasiSpesifik: 'Waterfront Jodoh - Batu Ampar',
    statusRencana: 'Terbit Rekomendasi Teknis',
  },
  {
    id: 'RCN-007',
    namaPerusahaan: 'PT Galang Maritime Marine Logistics',
    nomorIzinPkkprl: 'PKKPRL/2026/008/DPKPR',
    koordinat: '0°45\'50.2"N 104°14\'20.0"E',
    wilayah: 'Rempang & Galang',
    swp: 'Rempang & Galang',
    statusKegiatan: 'Pembangunan Dermaga & Jetty',
    luasHa: 75.0,
    luasM2: 750000,
    tahunPenerbitan: 2026,
    lokasiSpesifik: 'Pesisir Timur Pulau Galang Baru',
    statusRencana: 'Konfirmasi Kesesuaian Ruang Laut',
  },
  {
    id: 'RCN-008',
    namaPerusahaan: 'PT Sagulung Galangan Jaya Mandiri',
    nomorIzinPkkprl: 'PKKPRL/2025/030/DPKPR',
    koordinat: '1°02\'15.6"N 103°57\'10.4"E',
    wilayah: 'Batu Aji & Sagulung',
    swp: 'Batu Aji & Sagulung',
    statusKegiatan: 'Pembangunan Dermaga & Jetty',
    luasHa: 42.0,
    luasM2: 420000,
    tahunPenerbitan: 2025,
    lokasiSpesifik: 'Alur Sei Binti, Sagulung',
    statusRencana: 'Terbit Rekomendasi Teknis',
  },
];

// DATASET NO. 3: Rekap Kinerja Perizinan Selesai Tepat Waktu (Data Statistik)
// Atribut PDF (Hal 14): JUMLAH PERMOHONAN, TOTAL LUASAN, TAHUN
export const DATASET_3_REKAP_TAHUNAN: RekapTahunanPerizinanItem[] = [
  {
    tahun: 2023,
    jumlahPermohonan: 142,
    jumlahTepatWaktu: 128,
    persentaseTepatWaktu: 90.1,
    totalLuasanHa: 1540.0,
    totalLuasanDisetujuiHa: 1420.0,
  },
  {
    tahun: 2024,
    jumlahPermohonan: 155,
    jumlahTepatWaktu: 142,
    persentaseTepatWaktu: 91.6,
    totalLuasanHa: 1680.0,
    totalLuasanDisetujuiHa: 1560.0,
  },
  {
    tahun: 2025,
    jumlahPermohonan: 158,
    jumlahTepatWaktu: 146,
    persentaseTepatWaktu: 92.4,
    totalLuasanHa: 1820.5,
    totalLuasanDisetujuiHa: 1710.0,
  },
  {
    tahun: 2026,
    jumlahPermohonan: 45,
    jumlahTepatWaktu: 42,
    persentaseTepatWaktu: 93.3,
    totalLuasanHa: 490.0,
    totalLuasanDisetujuiHa: 465.0,
  },
];

// Detail Rekam Permohonan Perizinan untuk Pelacakan SLA (Dataset #3)
export const DATASET_3_PERIZINAN_WAKTU: PerizinanPesisirWaktuItem[] = [
  {
    id: 'IZN-001',
    noIzin: 'IZN-PSR/2026/001',
    namaPemohon: 'PT Batam Maritime Shipyard',
    jenisIzin: 'Izin Pelaksanaan Reklamasi',
    tanggalPengajuan: '05 Jan 2026',
    tanggalPenyelesaian: '16 Jan 2026',
    targetSlaHari: 14,
    realisasiHari: 11,
    statusWaktu: 'Tepat Waktu',
    statusIzin: 'Diterbitkan',
    wilayah: 'Sekupang & Tg. Uncang',
    swp: 'Sekupang & Tg. Uncang',
    luasHa: 48.5,
  },
  {
    id: 'IZN-002',
    noIzin: 'IZN-PSR/2026/002',
    namaPemohon: 'PT Marina Bay Batam Centre',
    jenisIzin: 'Izin Pemanfaatan Ruang Pesisir',
    tanggalPengajuan: '12 Jan 2026',
    tanggalPenyelesaian: '22 Jan 2026',
    targetSlaHari: 14,
    realisasiHari: 10,
    statusWaktu: 'Tepat Waktu',
    statusIzin: 'Diterbitkan',
    wilayah: 'Batam Kota',
    swp: 'Batam Kota',
    luasHa: 35.8,
  },
  {
    id: 'IZN-003',
    noIzin: 'IZN-PSR/2026/003',
    namaPemohon: 'PT Kabil Citra Maritim',
    jenisIzin: 'Persetujuan Kesesuaian PKKPRL',
    tanggalPengajuan: '18 Jan 2026',
    tanggalPenyelesaian: '29 Jan 2026',
    targetSlaHari: 14,
    realisasiHari: 11,
    statusWaktu: 'Tepat Waktu',
    statusIzin: 'Diterbitkan',
    wilayah: 'Nongsa & Kabil',
    swp: 'Nongsa & Kabil',
    luasHa: 62.0,
  },
  {
    id: 'IZN-004',
    noIzin: 'IZN-PSR/2026/004',
    namaPemohon: 'PT Selat Makmur Bahari',
    jenisIzin: 'Izin Pembangunan Dermaga / Jetty',
    tanggalPengajuan: '01 Feb 2026',
    tanggalPenyelesaian: '18 Feb 2026',
    targetSlaHari: 14,
    realisasiHari: 17,
    statusWaktu: 'Terlambat',
    statusIzin: 'Diterbitkan',
    wilayah: 'Sekupang & Tg. Uncang',
    swp: 'Sekupang & Tg. Uncang',
    luasHa: 14.2,
  },
  {
    id: 'IZN-005',
    noIzin: 'IZN-PSR/2026/005',
    namaPemohon: 'PT Nongsa Resort Bahari',
    jenisIzin: 'Izin Pemanfaatan Ruang Pesisir',
    tanggalPengajuan: '10 Feb 2026',
    tanggalPenyelesaian: '21 Feb 2026',
    targetSlaHari: 14,
    realisasiHari: 11,
    statusWaktu: 'Tepat Waktu',
    statusIzin: 'Diterbitkan',
    wilayah: 'Nongsa & Kabil',
    swp: 'Nongsa & Kabil',
    luasHa: 28.4,
  },
  {
    id: 'IZN-006',
    noIzin: 'IZN-PSR/2026/006',
    namaPemohon: 'PT Galangan Samudera Pasifik',
    jenisIzin: 'Izin Pelaksanaan Reklamasi',
    tanggalPengajuan: '24 Feb 2026',
    tanggalPenyelesaian: '07 Mar 2026',
    targetSlaHari: 14,
    realisasiHari: 11,
    statusWaktu: 'Tepat Waktu',
    statusIzin: 'Diterbitkan',
    wilayah: 'Batu Aji & Sagulung',
    swp: 'Batu Aji & Sagulung',
    luasHa: 42.0,
  },
  {
    id: 'IZN-007',
    noIzin: 'IZN-PSR/2026/007',
    namaPemohon: 'PT Pelabuhan Batu Ampar Modern',
    jenisIzin: 'Persetujuan Kesesuaian PKKPRL',
    tanggalPengajuan: '05 Mar 2026',
    tanggalPenyelesaian: '16 Mar 2026',
    targetSlaHari: 14,
    realisasiHari: 11,
    statusWaktu: 'Tepat Waktu',
    statusIzin: 'Diterbitkan',
    wilayah: 'Batu Ampar & Bengkong',
    swp: 'Batu Ampar & Bengkong',
    luasHa: 18.5,
  },
  {
    id: 'IZN-008',
    noIzin: 'IZN-PSR/2026/008',
    namaPemohon: 'PT Rempang Offshore Energy',
    jenisIzin: 'Izin Pelaksanaan Reklamasi',
    tanggalPengajuan: '20 Mar 2026',
    tanggalPenyelesaian: '08 Apr 2026',
    targetSlaHari: 14,
    realisasiHari: 19,
    statusWaktu: 'Terlambat',
    statusIzin: 'Diterbitkan',
    wilayah: 'Rempang & Galang',
    swp: 'Rempang & Galang',
    luasHa: 120.0,
  },
];

// DATASET NO. 4: Luas Izin Pemanfaatan Kawasan Pesisir dan Izin Reklamasi untuk Investasi
// Atribut PDF (Hal 14): NAMA PERUSAHAAN, NOMOR IZIN PKKPRL, KOORDINAT, WILAYAH, LUAS, TAHUN PENERBITAN
// CATATAN: MURNI HANYA LUAS (HA / M²), TANPA NILAI INVESTASI APAPUN SESUAI PERMINTAAN USER & SATU DATA
export const DATASET_4_PEMANFAATAN_INVESTASI: PemanfaatanInvestasiItem[] = [
  {
    id: 'INV-001',
    namaPerusahaan: 'PT Batam Shipyard Industri Pratama',
    nomorIzinPkkprl: 'PKKPRL/2024/001/DPKPR',
    koordinat: '1°04\'25.1"N 103°54\'12.3"E',
    wilayah: 'Sekupang & Tg. Uncang',
    swp: 'Sekupang & Tg. Uncang',
    luasHa: 142.5,
    luasM2: 1425000,
    tahunPenerbitan: 2024,
    lokasiSpesifik: 'Kawasan Industri Tanjung Uncang',
    jenisIzin: 'Izin Reklamasi',
    sektorIndustri: 'Galangan Kapal (Shipyard)',
    statusProgresFisik: 'Operasional Penuh',
    progresPersen: 100,
  },
  {
    id: 'INV-002',
    namaPerusahaan: 'PT Citra Tubindo Pesisir Maritim',
    nomorIzinPkkprl: 'PKKPRL/2023/014/DPKPR',
    koordinat: '1°07\'18.5"N 104°08\'45.2"E',
    wilayah: 'Nongsa & Kabil',
    swp: 'Nongsa & Kabil',
    luasHa: 98.4,
    luasM2: 984000,
    tahunPenerbitan: 2023,
    lokasiSpesifik: 'Kabil Integrated Industrial Port',
    jenisIzin: 'Izin Pemanfaatan Kawasan Pesisir',
    sektorIndustri: 'Terminal Logistik / Pelabuhan',
    statusProgresFisik: 'Operasional Penuh',
    progresPersen: 100,
  },
  {
    id: 'INV-003',
    namaPerusahaan: 'PT Harbour Bay Eco-City Reklamasi',
    nomorIzinPkkprl: 'PKKPRL/2025/007/DPKPR',
    koordinat: '1°09\'14.2"N 103°59\'35.0"E',
    wilayah: 'Batu Ampar & Bengkong',
    swp: 'Batu Ampar & Bengkong',
    luasHa: 68.2,
    luasM2: 682000,
    tahunPenerbitan: 2025,
    lokasiSpesifik: 'Waterfront Harbour Bay, Jodoh',
    jenisIzin: 'Izin Terpadu Pesisir & Reklamasi',
    sektorIndustri: 'Pariwisata & Resort Bahari',
    statusProgresFisik: 'Konstruksi / Reklamasi Berjalan',
    progresPersen: 74,
  },
  {
    id: 'INV-004',
    namaPerusahaan: 'PT Nongsa Digital Coastline Hub',
    nomorIzinPkkprl: 'PKKPRL/2025/022/DPKPR',
    koordinat: '1°11\'45.0"N 104°05\'50.8"E',
    wilayah: 'Nongsa & Kabil',
    swp: 'Nongsa & Kabil',
    luasHa: 45.6,
    luasM2: 456000,
    tahunPenerbitan: 2025,
    lokasiSpesifik: 'Kawasan KEK Nongsa Digital Park',
    jenisIzin: 'Izin Pemanfaatan Kawasan Pesisir',
    sektorIndustri: 'Pariwisata & Resort Bahari',
    statusProgresFisik: 'Konstruksi / Reklamasi Berjalan',
    progresPersen: 68,
  },
  {
    id: 'INV-005',
    namaPerusahaan: 'PT Samudera Rempang Offshore Hub',
    nomorIzinPkkprl: 'PKKPRL/2024/035/DPKPR',
    koordinat: '0°53\'40.1"N 104°08\'15.6"E',
    wilayah: 'Rempang & Galang',
    swp: 'Rempang & Galang',
    luasHa: 215.0,
    luasM2: 2150000,
    tahunPenerbitan: 2024,
    lokasiSpesifik: 'Pesisir Barat Rempang Eco-City',
    jenisIzin: 'Izin Reklamasi',
    sektorIndustri: 'Industri Manufaktur Lepas Pantai',
    statusProgresFisik: 'Konstruksi / Reklamasi Berjalan',
    progresPersen: 52,
  },
  {
    id: 'INV-006',
    namaPerusahaan: 'PT Batam Centre Marina Waterfront',
    nomorIzinPkkprl: 'PKKPRL/2023/029/DPKPR',
    koordinat: '1°08\'30.0"N 104°03\'22.0"E',
    wilayah: 'Batam Kota',
    swp: 'Batam Kota',
    luasHa: 54.8,
    luasM2: 548000,
    tahunPenerbitan: 2023,
    lokasiSpesifik: 'Perairan Teluk Tering Batam Centre',
    jenisIzin: 'Izin Terpadu Pesisir & Reklamasi',
    sektorIndustri: 'Pariwisata & Resort Bahari',
    statusProgresFisik: 'Operasional Penuh',
    progresPersen: 100,
  },
  {
    id: 'INV-007',
    namaPerusahaan: 'PT Sagulung Heavy Coastal Engineering',
    nomorIzinPkkprl: 'PKKPRL/2024/018/DPKPR',
    koordinat: '1°02\'40.8"N 103°56\'45.0"E',
    wilayah: 'Batu Aji & Sagulung',
    swp: 'Batu Aji & Sagulung',
    luasHa: 112.3,
    luasM2: 1123000,
    tahunPenerbitan: 2024,
    lokasiSpesifik: 'Kawasan Galangan Kapal Sei Lekop',
    jenisIzin: 'Izin Reklamasi',
    sektorIndustri: 'Galangan Kapal (Shipyard)',
    statusProgresFisik: 'Operasional Penuh',
    progresPersen: 100,
  },
  {
    id: 'INV-008',
    namaPerusahaan: 'PT Galang Green Ocean Energy',
    nomorIzinPkkprl: 'PKKPRL/2025/041/DPKPR',
    koordinat: '0°44\'30.0"N 104°13\'15.0"E',
    wilayah: 'Rempang & Galang',
    swp: 'Rempang & Galang',
    luasHa: 185.0,
    luasM2: 1850000,
    tahunPenerbitan: 2025,
    lokasiSpesifik: 'Selat Galang Baru',
    jenisIzin: 'Izin Pemanfaatan Kawasan Pesisir',
    sektorIndustri: 'Energi & Pembangkit Listrik Pesisir',
    statusProgresFisik: 'Pematangan Lahan Reklamasi',
    progresPersen: 35,
  },
  {
    id: 'INV-009',
    namaPerusahaan: 'PT Batu Ampar Transhipment Wharf',
    nomorIzinPkkprl: 'PKKPRL/2023/005/DPKPR',
    koordinat: '1°10\'05.2"N 104°00\'18.4"E',
    wilayah: 'Batu Ampar & Bengkong',
    swp: 'Batu Ampar & Bengkong',
    luasHa: 63.6,
    luasM2: 636000,
    tahunPenerbitan: 2023,
    lokasiSpesifik: 'Zona Reklamasi Utara Dermaga Utara',
    jenisIzin: 'Izin Reklamasi',
    sektorIndustri: 'Terminal Logistik / Pelabuhan',
    statusProgresFisik: 'Operasional Penuh',
    progresPersen: 100,
  },
  {
    id: 'INV-010',
    namaPerusahaan: 'PT Sekupang Ocean Resort & Marina',
    nomorIzinPkkprl: 'PKKPRL/2024/012/DPKPR',
    koordinat: '1°07\'10.5"N 103°55\'40.0"E',
    wilayah: 'Sekupang & Tg. Uncang',
    swp: 'Sekupang & Tg. Uncang',
    luasHa: 58.2,
    luasM2: 582000,
    tahunPenerbitan: 2024,
    lokasiSpesifik: 'Pesisir Tanjung Pinggir, Sekupang',
    jenisIzin: 'Izin Pemanfaatan Kawasan Pesisir',
    sektorIndustri: 'Pariwisata & Resort Bahari',
    statusProgresFisik: 'Operasional Penuh',
    progresPersen: 100,
  },
  {
    id: 'INV-011',
    namaPerusahaan: 'PT Kabil Citra Offshore Platform',
    nomorIzinPkkprl: 'PKKPRL/2024/027/DPKPR',
    koordinat: '1°06\'30.0"N 104°09\'10.0"E',
    wilayah: 'Nongsa & Kabil',
    swp: 'Nongsa & Kabil',
    luasHa: 85.0,
    luasM2: 850000,
    tahunPenerbitan: 2024,
    lokasiSpesifik: 'Perairan Dalam Teluk Kabil',
    jenisIzin: 'Izin Reklamasi',
    sektorIndustri: 'Industri Manufaktur Lepas Pantai',
    statusProgresFisik: 'Operasional Penuh',
    progresPersen: 100,
  },
  {
    id: 'INV-012',
    namaPerusahaan: 'PT Galang South Gate Terminal',
    nomorIzinPkkprl: 'PKKPRL/2025/038/DPKPR',
    koordinat: '0°42\'15.0"N 104°15\'50.0"E',
    wilayah: 'Rempang & Galang',
    swp: 'Rempang & Galang',
    luasHa: 76.2,
    luasM2: 762000,
    tahunPenerbitan: 2025,
    lokasiSpesifik: 'Ujung Selatan Pulau Galang Baru',
    jenisIzin: 'Izin Terpadu Pesisir & Reklamasi',
    sektorIndustri: 'Terminal Logistik / Pelabuhan',
    statusProgresFisik: 'Konstruksi / Reklamasi Berjalan',
    progresPersen: 45,
  },
];

// DISTRIBUSI LUAS PER WILAYAH / SWP (HANYA LUAS & JUMLAH PROYEK, TANPA INVESTASI)
export const DISTRIBUSI_WILAYAH_PESISIR_DATA = [
  {
    wilayah: 'Sekupang & Tg. Uncang',
    swp: 'Sekupang & Tg. Uncang',
    luasTotalHa: 412.5,
    jumlahIzin: 14,
    jumlahProyek: 14,
    reklamasiHa: 295.0,
    pesisirHa: 117.5,
    kepatuhanPersen: 95.2,
  },
  {
    wilayah: 'Rempang & Galang',
    swp: 'Rempang & Galang',
    luasTotalHa: 476.2,
    jumlahIzin: 8,
    jumlahProyek: 8,
    reklamasiHa: 310.0,
    pesisirHa: 166.2,
    kepatuhanPersen: 87.5,
  },
  {
    wilayah: 'Nongsa & Kabil',
    swp: 'Nongsa & Kabil',
    luasTotalHa: 234.4,
    jumlahIzin: 12,
    jumlahProyek: 12,
    reklamasiHa: 112.4,
    pesisirHa: 122.0,
    kepatuhanPersen: 92.8,
  },
  {
    wilayah: 'Batu Ampar & Bengkong',
    swp: 'Batu Ampar & Bengkong',
    luasTotalHa: 168.0,
    jumlahIzin: 7,
    jumlahProyek: 7,
    reklamasiHa: 105.2,
    pesisirHa: 62.8,
    kepatuhanPersen: 96.0,
  },
  {
    wilayah: 'Batam Kota',
    swp: 'Batam Kota',
    luasTotalHa: 94.3,
    jumlahIzin: 4,
    jumlahProyek: 4,
    reklamasiHa: 50.0,
    pesisirHa: 44.3,
    kepatuhanPersen: 94.0,
  },
  {
    wilayah: 'Batu Aji & Sagulung',
    swp: 'Batu Aji & Sagulung',
    luasTotalHa: 100.0,
    jumlahIzin: 3,
    jumlahProyek: 3,
    reklamasiHa: 40.0,
    pesisirHa: 60.0,
    kepatuhanPersen: 91.0,
  },
];

export const DISTRIBUSI_SWP_PESISIR_DATA = DISTRIBUSI_WILAYAH_PESISIR_DATA;

// TREN PENYELESAIAN MASALAH PER TRIWULAN (DATASET #1)
export const TREN_TRIWULAN_MASALAH = [
  {
    triwulan: 'Triwulan I 2025',
    kasusMasuk: 18,
    kasusSelesai: 16,
    persenSelesai: 88.9,
    luasTerdampakHa: 24.5,
  },
  {
    triwulan: 'Triwulan II 2025',
    kasusMasuk: 22,
    kasusSelesai: 19,
    persenSelesai: 86.4,
    luasTerdampakHa: 38.2,
  },
  {
    triwulan: 'Triwulan III 2025',
    kasusMasuk: 20,
    kasusSelesai: 18,
    persenSelesai: 90.0,
    luasTerdampakHa: 31.0,
  },
  {
    triwulan: 'Triwulan IV 2025',
    kasusMasuk: 19,
    kasusSelesai: 17,
    persenSelesai: 89.5,
    luasTerdampakHa: 34.8,
  },
  {
    triwulan: 'Triwulan I 2026',
    kasusMasuk: 15,
    kasusSelesai: 13,
    persenSelesai: 86.7,
    luasTerdampakHa: 21.6,
  },
];
