import {
  KpiPesisirReklamasiSummary,
  PermasalahanPesisirItem,
  RencanaPemanfaatanPesisirItem,
  PerizinanPesisirWaktuItem,
  PemanfaatanInvestasiItem,
} from './types';

// EXECUTIVE KPIS (Sesuai Poin 1, 2, 3)
export const KPI_PESISIR_REKLAMASI_DATA: KpiPesisirReklamasiSummary = {
  // 1. KPI Luas Izin Pemanfaatan Kawasan Pesisir dan Izin Reklamasi untuk Investasi (Dataset No. 4)
  kpi1_luasIzinInvestasiHa: 1485.4, // Total Luas (Ha)
  kpi1_targetLuasHa: 1600.0,
  kpi1_totalIzinTerbit: 48,
  kpi1_totalNilaiInvestasiT: 28.65, // Rp 28,65 Triliun

  // 2. Persentase Perizinan Pesisir dan Reklamasi yang Selesai Tepat Waktu (Dataset No. 3)
  kpi2_persenTepatWaktu: 92.4, // 92,4%
  kpi2_totalPerizinanSelesai: 158,
  kpi2_totalTepatWaktu: 146,
  kpi2_totalTerlambat: 12,
  kpi2_rataRataSlaHari: 11.2, // Dari standar 14 hari

  // 3. Persentase Penyelesaian Permasalahan Pesisir dan Reklamasi (Dataset No. 1)
  kpi3_persenPenyelesaianMasalah: 88.6, // 88,6%
  kpi3_totalKasus: 79,
  kpi3_kasusSelesai: 70,
  kpi3_kasusProses: 9,
  kpi3_rataRataWaktuSelesaiHari: 18.5,

  // Analitik Monitoring Atasan (Poin 7)
  reklamasiVsPesisirHa: {
    reklamasiHa: 912.6,
    pesisirHa: 572.8,
    reklamasiPersen: 61.4,
    pesisirPersen: 38.6,
  },
};

// DATASET NO. 1: Permasalahan Pesisir dan Reklamasi (Untuk KPI 3)
export const DATASET_1_PERMASALAHAN: PermasalahanPesisirItem[] = [
  {
    id: 'PMS-001',
    noPengaduan: 'PENG-PSR/2026/014',
    judulKasus: 'Penimbunan Pesisir Tanpa Izin Reklamasi di Area Bakau',
    lokasi: 'Tanjung Sengkuang, Batu Ampar',
    swp: 'Batu Ampar & Bengkong',
    kategori: 'Pemanfaatan Tanpa Izin',
    namaPihakTerkait: 'PT Marina Nusantara Indah',
    luasTerdampakHa: 4.8,
    tanggalLapor: '12 Jan 2026',
    status: 'Selesai',
    solusiTindakan: 'Penerbitan Surat Peringatan, Penghentian Kegiatan & Restorasi Garis Pantai',
    lamaPenyelesaianHari: 14,
  },
  {
    id: 'PMS-002',
    noPengaduan: 'PENG-PSR/2026/021',
    judulKasus: 'Pelanggaran Garis Sempadan Pesisir Pembangunan Dermaga Pribadi',
    lokasi: 'Teluk Mata Ikan, Sambau',
    swp: 'Nongsa & Kabil',
    kategori: 'Pelanggaran Sempadan Pantai',
    namaPihakTerkait: 'CV Batam Bahari Abadi',
    luasTerdampakHa: 1.5,
    tanggalLapor: '28 Jan 2026',
    status: 'Selesai',
    solusiTindakan: 'Penyesuaian Gambar Teknis Layout & Pembongkaran Struktur Menjorok Terlarang',
    lamaPenyelesaianHari: 21,
  },
  {
    id: 'PMS-003',
    noPengaduan: 'PENG-PSR/2026/033',
    judulKasus: 'Sedimentasi Alur Pelayaran Akibat Limpasan Material Reklamasi',
    lokasi: 'Tanjung Uncang, Batu Aji',
    swp: 'Batu Aji & Sagulung',
    kategori: 'Pencemaran / Sedimentasi',
    namaPihakTerkait: 'PT Galangan Samudera Pasifik',
    luasTerdampakHa: 12.0,
    tanggalLapor: '15 Feb 2026',
    status: 'Selesai',
    solusiTindakan: 'Pemasangan Silt Curtain Tambahan & Pengerukan Alur Terdampak atas Biaya Pemrakarsa',
    lamaPenyelesaianHari: 26,
  },
  {
    id: 'PMS-004',
    noPengaduan: 'PENG-PSR/2026/047',
    judulKasus: 'Tumpang Tindih Batas Laut Wilayah Kerja Terminal Khusus',
    lokasi: 'Kabil Port Zone, Kabil',
    swp: 'Nongsa & Kabil',
    kategori: 'Sengketa Batas Laut',
    namaPihakTerkait: 'PT Kabil Citra Maritim & PT Petro Indo',
    luasTerdampakHa: 8.3,
    tanggalLapor: '04 Mar 2026',
    status: 'Selesai',
    solusiTindakan: 'Mediasi Teknis & Penerbitan Berita Acara Rekonsiliasi Batas Koordinat BRP',
    lamaPenyelesaianHari: 16,
  },
  {
    id: 'PMS-005',
    noPengaduan: 'PENG-PSR/2026/055',
    judulKasus: 'Deviasi Elevasi Pematangan Reklamasi Melebihi Izin Rencana',
    lokasi: 'Sekupang Waterfront',
    swp: 'Sekupang & Tg. Uncang',
    kategori: 'Deviasi Amdal Reklamasi',
    namaPihakTerkait: 'PT Selat Makmur Bahari',
    luasTerdampakHa: 6.2,
    tanggalLapor: '19 Mar 2026',
    status: 'Selesai',
    solusiTindakan: 'Koreksi Elevasi Timbunan Sesuai Dokumen Rekomendasi Teknis DP2KPR',
    lamaPenyelesaianHari: 19,
  },
  {
    id: 'PMS-006',
    noPengaduan: 'PENG-PSR/2026/063',
    judulKasus: 'Klaim Hak Nelayan atas Area Pemanfaatan Budidaya Tertutup Reklamasi',
    lokasi: 'Pulau Galang Barat',
    swp: 'Rempang & Galang',
    kategori: 'Sengketa Batas Laut',
    namaPihakTerkait: 'PT Galang Agro Marina',
    luasTerdampakHa: 18.5,
    tanggalLapor: '08 Apr 2026',
    status: 'Dalam Proses',
    solusiTindakan: 'Kajian Pemetaan Zonasi Tangkap Tradisional & Relokasi Alur Tambat Perahu',
    lamaPenyelesaianHari: 22,
  },
  {
    id: 'PMS-007',
    noPengaduan: 'PENG-PSR/2026/072',
    judulKasus: 'Indikasi Penyerobotan Sempadan Pantai oleh Usaha Wisata Tanpa Rekomendasi',
    lokasi: 'Batam Centre Coastal Walk',
    swp: 'Batam Kota',
    kategori: 'Pelanggaran Sempadan Pantai',
    namaPihakTerkait: 'PT Pantai Emas Pesona',
    luasTerdampakHa: 2.1,
    tanggalLapor: '14 Mei 2026',
    status: 'Dalam Proses',
    solusiTindakan: 'Audit Lapangan Bersama Tim Terpadu & Permintaan Berkas PKKPRL',
    lamaPenyelesaianHari: 15,
  },
  {
    id: 'PMS-008',
    noPengaduan: 'PENG-PSR/2026/078',
    judulKasus: 'Erosi Tebing Pesisir Akibat Pembukaan Lahan Tanpa Turap Pengaman',
    lokasi: 'Tanjung Riau, Sekupang',
    swp: 'Sekupang & Tg. Uncang',
    kategori: 'Pencemaran / Sedimentasi',
    namaPihakTerkait: 'PT Riau Permai Sejahtera',
    luasTerdampakHa: 3.4,
    tanggalLapor: '02 Jun 2026',
    status: 'Dalam Proses',
    solusiTindakan: 'Instruksi Pembangunan Revetment / Dinding Penahan Ombak Darurat',
    lamaPenyelesaianHari: 9,
  },
];

// DATASET NO. 2: Rencana Pemanfaatan Wilayah Pesisir dan Reklamasi (Untuk Poin 4 & Sheet Swap)
// Kolom Sesuai Permintaan User: Nama Perusahaan, Luas, Tahun Penerbitan, dan Luas
export const DATASET_2_RENCANA_PEMANFAATAN: RencanaPemanfaatanPesisirItem[] = [
  {
    id: 'RCN-001',
    namaPerusahaan: 'PT Batam Maritime Shipyard & Engineering',
    luasHa: 48.5,
    luasM2: 485000,
    tahunPenerbitan: 2026,
    swp: 'Sekupang & Tg. Uncang',
    lokasiSpesifik: 'Tanjung Uncang Sektor Barat',
    zonaRencana: 'Zona Pelabuhan & Industri Maritim',
    statusRencana: 'Terbit Rekomendasi Teknis',
    targetRealisasiInvestasiRp: 1250, // 1,25 Triliun
  },
  {
    id: 'RCN-002',
    namaPerusahaan: 'PT Kabil Terminal Logistik Internasional',
    luasHa: 62.0,
    luasM2: 620000,
    tahunPenerbitan: 2026,
    swp: 'Nongsa & Kabil',
    lokasiSpesifik: 'Perairan Selat Kabil',
    zonaRencana: 'Zona Logistik & Pergudangan Pesisir',
    statusRencana: 'Tahap Amdal & PKKPRL',
    targetRealisasiInvestasiRp: 1800,
  },
  {
    id: 'RCN-003',
    namaPerusahaan: 'PT Marina Bay Batam Centre Perkasa',
    luasHa: 35.8,
    luasM2: 358000,
    tahunPenerbitan: 2025,
    swp: 'Batam Kota',
    lokasiSpesifik: 'Pesisir Teluk Batam Centre',
    zonaRencana: 'Zona Pariwisata Bahari',
    statusRencana: 'Terbit Rekomendasi Teknis',
    targetRealisasiInvestasiRp: 950,
  },
  {
    id: 'RCN-004',
    namaPerusahaan: 'PT Nongsa Digital Waterfront Eco-Resort',
    luasHa: 28.4,
    luasM2: 284000,
    tahunPenerbitan: 2025,
    swp: 'Nongsa & Kabil',
    lokasiSpesifik: 'Teluk Mata Ikan, Nongsa',
    zonaRencana: 'Zona Pariwisata Bahari',
    statusRencana: 'Konfirmasi Kesesuaian Ruang Laut',
    targetRealisasiInvestasiRp: 720,
  },
  {
    id: 'RCN-005',
    namaPerusahaan: 'PT Samudera Rempang Offshore Services',
    luasHa: 76.2,
    luasM2: 762000,
    tahunPenerbitan: 2026,
    swp: 'Rempang & Galang',
    lokasiSpesifik: 'Kawasan Pesisir Rempang Utara',
    zonaRencana: 'Zona KEK & Hub Maritim',
    statusRencana: 'Tahap Amdal & PKKPRL',
    targetRealisasiInvestasiRp: 2400,
  },
  {
    id: 'RCN-006',
    namaPerusahaan: 'PT Pelabuhan Batu Ampar Modern Hub',
    luasHa: 41.0,
    luasM2: 410000,
    tahunPenerbitan: 2024,
    swp: 'Batu Ampar & Bengkong',
    lokasiSpesifik: 'Perluasan Kolam Pelabuhan Batu Ampar',
    zonaRencana: 'Zona Pelabuhan & Industri Maritim',
    statusRencana: 'Terbit Rekomendasi Teknis',
    targetRealisasiInvestasiRp: 1550,
  },
  {
    id: 'RCN-007',
    namaPerusahaan: 'PT Galang Clean Energy Coast Station',
    luasHa: 52.6,
    luasM2: 526000,
    tahunPenerbitan: 2025,
    swp: 'Rempang & Galang',
    lokasiSpesifik: 'Pesisir Timur Pulau Galang Baru',
    zonaRencana: 'Zona Jasa & Komersial Maritim',
    statusRencana: 'Tahap Amdal & PKKPRL',
    targetRealisasiInvestasiRp: 1650,
  },
  {
    id: 'RCN-008',
    namaPerusahaan: 'PT Sagulung Galangan Terpadu',
    luasHa: 30.5,
    luasM2: 305000,
    tahunPenerbitan: 2024,
    swp: 'Batu Aji & Sagulung',
    lokasiSpesifik: 'Alur Sei Binti, Sagulung',
    zonaRencana: 'Zona Pelabuhan & Industri Maritim',
    statusRencana: 'Terbit Rekomendasi Teknis',
    targetRealisasiInvestasiRp: 890,
  },
];

// DATASET NO. 3: Perizinan Pesisir dan Reklamasi Selesai Tepat Waktu (Untuk KPI 2)
export const DATASET_3_PERIZINAN_WAKTU: PerizinanPesisirWaktuItem[] = [
  {
    id: 'IZN-001',
    noIzin: 'IZN-PSR/2026/001',
    namaPemohon: 'PT Batam Maritime Shipyard',
    jenisIzin: 'Izin Pelaksanaan Reklamasi',
    tanggalPengajuan: '05 Jan 2026',
    tanggalPenyelesaian: '16 Jan 2026',
    targetSlaHari: 14,
    realisasiHari: 11,
    statusWaktu: 'Tepat Waktu',
    statusIzin: 'Diterbitkan',
    swp: 'Sekupang & Tg. Uncang',
  },
  {
    id: 'IZN-002',
    noIzin: 'IZN-PSR/2026/002',
    namaPemohon: 'PT Marina Bay Batam Centre',
    jenisIzin: 'Izin Pemanfaatan Ruang Pesisir',
    tanggalPengajuan: '12 Jan 2026',
    tanggalPenyelesaian: '22 Jan 2026',
    targetSlaHari: 14,
    realisasiHari: 10,
    statusWaktu: 'Tepat Waktu',
    statusIzin: 'Diterbitkan',
    swp: 'Batam Kota',
  },
  {
    id: 'IZN-003',
    noIzin: 'IZN-PSR/2026/003',
    namaPemohon: 'PT Kabil Citra Maritim',
    jenisIzin: 'Persetujuan Kesesuaian PKKPRL',
    tanggalPengajuan: '18 Jan 2026',
    tanggalPenyelesaian: '29 Jan 2026',
    targetSlaHari: 14,
    realisasiHari: 11,
    statusWaktu: 'Tepat Waktu',
    statusIzin: 'Diterbitkan',
    swp: 'Nongsa & Kabil',
  },
  {
    id: 'IZN-004',
    noIzin: 'IZN-PSR/2026/004',
    namaPemohon: 'PT Selat Makmur Bahari',
    jenisIzin: 'Izin Pembangunan Dermaga / Jetty',
    tanggalPengajuan: '01 Feb 2026',
    tanggalPenyelesaian: '18 Feb 2026',
    targetSlaHari: 14,
    realisasiHari: 17,
    statusWaktu: 'Terlambat',
    statusIzin: 'Diterbitkan',
    swp: 'Sekupang & Tg. Uncang',
  },
  {
    id: 'IZN-005',
    noIzin: 'IZN-PSR/2026/005',
    namaPemohon: 'PT Nongsa Resort Bahari',
    jenisIzin: 'Izin Pemanfaatan Ruang Pesisir',
    tanggalPengajuan: '10 Feb 2026',
    tanggalPenyelesaian: '21 Feb 2026',
    targetSlaHari: 14,
    realisasiHari: 11,
    statusWaktu: 'Tepat Waktu',
    statusIzin: 'Diterbitkan',
    swp: 'Nongsa & Kabil',
  },
  {
    id: 'IZN-006',
    noIzin: 'IZN-PSR/2026/006',
    namaPemohon: 'PT Galangan Samudera Pasifik',
    jenisIzin: 'Izin Pelaksanaan Reklamasi',
    tanggalPengajuan: '24 Feb 2026',
    tanggalPenyelesaian: '07 Mar 2026',
    targetSlaHari: 14,
    realisasiHari: 11,
    statusWaktu: 'Tepat Waktu',
    statusIzin: 'Diterbitkan',
    swp: 'Batu Aji & Sagulung',
  },
  {
    id: 'IZN-007',
    noIzin: 'IZN-PSR/2026/007',
    namaPemohon: 'PT Pelabuhan Batu Ampar Modern',
    jenisIzin: 'Persetujuan Kesesuaian PKKPRL',
    tanggalPengajuan: '05 Mar 2026',
    tanggalPenyelesaian: '16 Mar 2026',
    targetSlaHari: 14,
    realisasiHari: 11,
    statusWaktu: 'Tepat Waktu',
    statusIzin: 'Diterbitkan',
    swp: 'Batu Ampar & Bengkong',
  },
  {
    id: 'IZN-008',
    noIzin: 'IZN-PSR/2026/008',
    namaPemohon: 'PT Rempang Offshore Energy',
    jenisIzin: 'Izin Pelaksanaan Reklamasi',
    tanggalPengajuan: '20 Mar 2026',
    tanggalPenyelesaian: '08 Apr 2026',
    targetSlaHari: 14,
    realisasiHari: 19,
    statusWaktu: 'Terlambat',
    statusIzin: 'Diterbitkan',
    swp: 'Rempang & Galang',
  },
];

// DATASET NO. 4: Pemanfaatan Kawasan Pesisir dan Izin Reklamasi untuk Investasi (Untuk KPI 1, Poin 5 & Sheet Swap)
// Kolom Sesuai Permintaan User: Nama Perusahaan, Luas, Tahun, dan Tahun Penerbitan
export const DATASET_4_PEMANFAATAN_INVESTASI: PemanfaatanInvestasiItem[] = [
  {
    id: 'INV-001',
    namaPerusahaan: 'PT Batam Shipyard Industri Pratama',
    luasHa: 142.5,
    luasM2: 1425000,
    tahun: 2026,
    tahunPenerbitan: 2024,
    jenisIzin: 'Izin Reklamasi',
    swp: 'Sekupang & Tg. Uncang',
    lokasiSpesifik: 'Kawasan Industri Tanjung Uncang',
    nilaiInvestasiMiliar: 3200,
    sektorIndustri: 'Galangan Kapal (Shipyard)',
    statusProgresFisik: 'Operasional Penuh',
    progresPersen: 100,
  },
  {
    id: 'INV-002',
    namaPerusahaan: 'PT Citra Tubindo Pesisir Maritim',
    luasHa: 98.4,
    luasM2: 984000,
    tahun: 2026,
    tahunPenerbitan: 2023,
    jenisIzin: 'Izin Pemanfaatan Kawasan Pesisir',
    swp: 'Nongsa & Kabil',
    lokasiSpesifik: 'Kabil Integrated Industrial Port',
    nilaiInvestasiMiliar: 2850,
    sektorIndustri: 'Terminal Logistik / Pelabuhan',
    statusProgresFisik: 'Operasional Penuh',
    progresPersen: 100,
  },
  {
    id: 'INV-003',
    namaPerusahaan: 'PT Harbour Bay Eco-City Reklamasi',
    luasHa: 68.2,
    luasM2: 682000,
    tahun: 2026,
    tahunPenerbitan: 2025,
    jenisIzin: 'Izin Terpadu Pesisir & Reklamasi',
    swp: 'Batu Ampar & Bengkong',
    lokasiSpesifik: 'Waterfront Harbour Bay, Jodoh',
    nilaiInvestasiMiliar: 4100,
    sektorIndustri: 'Pariwisata & Resort Bahari',
    statusProgresFisik: 'Konstruksi / Reklamasi Berjalan',
    progresPersen: 74,
  },
  {
    id: 'INV-004',
    namaPerusahaan: 'PT Nongsa Digital Coastline Hub',
    luasHa: 45.6,
    luasM2: 456000,
    tahun: 2026,
    tahunPenerbitan: 2025,
    jenisIzin: 'Izin Pemanfaatan Kawasan Pesisir',
    swp: 'Nongsa & Kabil',
    lokasiSpesifik: 'Kawasan KEK Nongsa Digital Park',
    nilaiInvestasiMiliar: 1950,
    sektorIndustri: 'Pariwisata & Resort Bahari',
    statusProgresFisik: 'Konstruksi / Reklamasi Berjalan',
    progresPersen: 68,
  },
  {
    id: 'INV-005',
    namaPerusahaan: 'PT Samudera Rempang Offshore Hub',
    luasHa: 215.0,
    luasM2: 2150000,
    tahun: 2026,
    tahunPenerbitan: 2024,
    jenisIzin: 'Izin Reklamasi',
    swp: 'Rempang & Galang',
    lokasiSpesifik: 'Pesisir Barat Rempang Eco-City',
    nilaiInvestasiMiliar: 5600,
    sektorIndustri: 'Industri Manufaktur Lepas Pantai',
    statusProgresFisik: 'Konstruksi / Reklamasi Berjalan',
    progresPersen: 52,
  },
  {
    id: 'INV-006',
    namaPerusahaan: 'PT Batam Centre Marina Waterfront',
    luasHa: 54.8,
    luasM2: 548000,
    tahun: 2026,
    tahunPenerbitan: 2023,
    jenisIzin: 'Izin Terpadu Pesisir & Reklamasi',
    swp: 'Batam Kota',
    lokasiSpesifik: 'Perairan Teluk Tering Batam Centre',
    nilaiInvestasiMiliar: 2450,
    sektorIndustri: 'Pariwisata & Resort Bahari',
    statusProgresFisik: 'Operasional Penuh',
    progresPersen: 100,
  },
  {
    id: 'INV-007',
    namaPerusahaan: 'PT Sagulung Heavy Coastal Engineering',
    luasHa: 112.3,
    luasM2: 1123000,
    tahun: 2026,
    tahunPenerbitan: 2024,
    jenisIzin: 'Izin Reklamasi',
    swp: 'Batu Aji & Sagulung',
    lokasiSpesifik: 'Kawasan Galangan Kapal Sei Lekop',
    nilaiInvestasiMiliar: 3100,
    sektorIndustri: 'Galangan Kapal (Shipyard)',
    statusProgresFisik: 'Operasional Penuh',
    progresPersen: 100,
  },
  {
    id: 'INV-008',
    namaPerusahaan: 'PT Galang Green Ocean Energy',
    luasHa: 185.0,
    luasM2: 1850000,
    tahun: 2026,
    tahunPenerbitan: 2025,
    jenisIzin: 'Izin Pemanfaatan Kawasan Pesisir',
    swp: 'Rempang & Galang',
    lokasiSpesifik: 'Selat Galang Baru',
    nilaiInvestasiMiliar: 3800,
    sektorIndustri: 'Energi & Pembangkit Listrik Pesisir',
    statusProgresFisik: 'Pematangan Lahan Reklamasi',
    progresPersen: 35,
  },
  {
    id: 'INV-009',
    namaPerusahaan: 'PT Batu Ampar Transhipment Wharf',
    luasHa: 63.6,
    luasM2: 636000,
    tahun: 2026,
    tahunPenerbitan: 2023,
    jenisIzin: 'Izin Reklamasi',
    swp: 'Batu Ampar & Bengkong',
    lokasiSpesifik: 'Zona Reklamasi Utara Dermaga Utara',
    nilaiInvestasiMiliar: 1600,
    sektorIndustri: 'Terminal Logistik / Pelabuhan',
    statusProgresFisik: 'Operasional Penuh',
    progresPersen: 100,
  },
];

// DISTRIBUSI SPASIAL PER SWP (Untuk Monitoring Atasan Poin 7)
export const DISTRIBUSI_SWP_PESISIR_DATA = [
  {
    swp: 'Sekupang & Tg. Uncang',
    luasTotalHa: 412.5,
    jumlahProyek: 14,
    investasiT: 8.4,
    reklamasiHa: 295.0,
    pesisirHa: 117.5,
    kepatuhanPersen: 95.2,
  },
  {
    swp: 'Rempang & Galang',
    luasTotalHa: 476.2,
    jumlahProyek: 8,
    investasiT: 9.4,
    reklamasiHa: 310.0,
    pesisirHa: 166.2,
    kepatuhanPersen: 87.5,
  },
  {
    swp: 'Nongsa & Kabil',
    luasTotalHa: 234.4,
    jumlahProyek: 12,
    investasiT: 5.52,
    reklamasiHa: 112.4,
    pesisirHa: 122.0,
    kepatuhanPersen: 92.8,
  },
  {
    swp: 'Batu Ampar & Bengkong',
    luasTotalHa: 168.0,
    jumlahProyek: 7,
    investasiT: 6.2,
    reklamasiHa: 105.2,
    pesisirHa: 62.8,
    kepatuhanPersen: 96.0,
  },
  {
    swp: 'Batam Kota',
    luasTotalHa: 94.3,
    jumlahProyek: 4,
    investasiT: 3.4,
    reklamasiHa: 50.0,
    pesisirHa: 44.3,
    kepatuhanPersen: 94.0,
  },
  {
    swp: 'Batu Aji & Sagulung',
    luasTotalHa: 100.0,
    jumlahProyek: 3,
    investasiT: 3.99,
    reklamasiHa: 40.0,
    pesisirHa: 60.0,
    kepatuhanPersen: 91.0,
  },
];
