import {
  PaketPerencanaan,
  KpiSektorSummary,
  StageGateFunnelItem,
  PemanfaatanDokumenItem,
} from './types';

// DATASET NO. 1 S.D. 6: PAKET PERENCANAAN INFRASTRUKTUR BP BATAM
export const SEMUA_PAKET_PERENCANAAN: PaketPerencanaan[] = [
  // --- DATASET NO. 1: PERENCANAAN PEMBANGUNAN INFRASTRUKTUR GEDUNG (8 Paket) ---
  {
    id: 'DED-GDG-001',
    kodePaket: 'DPR-GDG-2025-01',
    namaKegiatan: 'DED Pembangunan Gedung Pusat Riset & Inkubator Digital KEK Nongsa',
    sektor: 'Gedung',
    datasetNo: 1,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Gedung',
    tahunAnggaran: '2025',
    lokasiKawasan: 'Nongsa & KEK',
    sumberDana: 'PNBP BP Batam',
    paguKonsultansi: 1850000000,
    estimasiCapexFisik: 145000000000,
    konsultanPerencana: 'PT Virama Karya (Persero)',
    waktuPelaksanaanBulan: 6,
    progresPenyusunanPersen: 100,
    statusKesiapan: 'Selesai (Siap Lelang Fisik)',
    statusUtilisasi: 'Telah Masuk Lelang Fisik TA 2025',
    readinessScore: 98,
    ringkasanTeknis: 'Perencanaan struktur bertingkat 8 lantai hemat energi (Green Building Gold), data center redundancy tier-3, dan co-working tech tenant.',
    outputDokumen: ['Laporan DED Arsitektur & Struktur', 'Gambar Kerja CAD/BIM', 'Spesifikasi Teknis & BoQ', 'HPS/RAB Terverifikasi'],
    kendalaDanCatatan: 'Seluruh perizinan PBG & AMDAL telah terbit lengkap.',
    rekomendasiAtasan: 'Siap dilanjutkan untuk lelang fisik oleh Dit. Pembangunan Triwulan I.',
  },
  {
    id: 'DED-GDG-002',
    kodePaket: 'DPR-GDG-2025-02',
    namaKegiatan: 'DED Pembangunan Gudang Konsolidasi Logistik Modern Batu Ampar',
    sektor: 'Gedung',
    datasetNo: 1,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Gedung',
    tahunAnggaran: '2025',
    lokasiKawasan: 'Batu Ampar & Bengkong',
    sumberDana: 'PNBP BP Batam',
    paguKonsultansi: 1200000000,
    estimasiCapexFisik: 88000000000,
    konsultanPerencana: 'PT Ciriajasa Engineering Consultants',
    waktuPelaksanaanBulan: 5,
    progresPenyusunanPersen: 85,
    statusKesiapan: 'Review & Asistensi Teknis',
    statusUtilisasi: 'Dianggarkan Renja TA 2026',
    readinessScore: 88,
    ringkasanTeknis: 'Gudang logistik berpendingin (Cold Storage) & dry storage seluas 12.000 m2 dengan loading dock otomatis terhubung ke sistem CFS Pelabuhan.',
    outputDokumen: ['Draft Gambar Kerja DED', 'Laporan Analisis Tanah Geoteknik', 'Kajian Beban Struktur Racking'],
    kendalaDanCatatan: 'Perlu finalisasi spesifikasi insulator cold storage sesuai standar HACCP.',
    rekomendasiAtasan: 'Lakukan asistensi teknis bersama Badan Usaha Pelabuhan sebelum penetapan HPS final.',
  },
  {
    id: 'DED-GDG-003',
    kodePaket: 'DPR-GDG-2025-03',
    namaKegiatan: 'DED Pembangunan Kantor Pelayanan Terpadu & PTSP Sub-Pusat Sekupang',
    sektor: 'Gedung',
    datasetNo: 1,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Gedung',
    tahunAnggaran: '2025',
    lokasiKawasan: 'Sekupang',
    sumberDana: 'PNBP BP Batam',
    paguKonsultansi: 950000000,
    estimasiCapexFisik: 42000000000,
    konsultanPerencana: 'PT Bina Karya (Persero)',
    waktuPelaksanaanBulan: 4,
    progresPenyusunanPersen: 100,
    statusKesiapan: 'Selesai (Siap Lelang Fisik)',
    statusUtilisasi: 'Telah Masuk Lelang Fisik TA 2025',
    readinessScore: 95,
    ringkasanTeknis: 'Gedung pelayanan terpadu 4 lantai ramah disabilitas, aula pertemuan 400 seat, dan fasilitas command center lokal Sekupang.',
    outputDokumen: ['DED Final', 'Dokumen Tender Fisik', 'Kajian Andalalin', 'Persetujuan Teknis Lingkungan'],
    kendalaDanCatatan: 'Kesiapan dokumen 100% lengkap.',
    rekomendasiAtasan: 'Serah terima dokumen DED ke Dit. Pembangunan untuk proses pemilihan vendor fisik.',
  },
  {
    id: 'DED-GDG-004',
    kodePaket: 'DPR-GDG-2025-04',
    namaKegiatan: 'DED Revitalisasi & Perluasan Gedung BIDA Batam Centre (Smart Office Integration)',
    sektor: 'Gedung',
    datasetNo: 1,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Gedung',
    tahunAnggaran: '2025',
    lokasiKawasan: 'Batam Centre',
    sumberDana: 'PNBP BP Batam',
    paguKonsultansi: 1450000000,
    estimasiCapexFisik: 65000000000,
    konsultanPerencana: 'PT Deta Decon',
    waktuPelaksanaanBulan: 6,
    progresPenyusunanPersen: 60,
    statusKesiapan: 'Penyusunan DED & RAB',
    statusUtilisasi: 'Dianggarkan Renja TA 2026',
    readinessScore: 72,
    ringkasanTeknis: 'Peremajaan fasad modern, retrofit MEP tata udara hemat energi VRV, dan smart access control gedung utama.',
    outputDokumen: ['Laporan Antara DED', 'Hasil Audit Struktur Eksisting'],
    kendalaDanCatatan: 'Pemeriksaan integritas beton struktur eksisting membutuhkan pengujian NDT tambahan.',
    rekomendasiAtasan: 'Pastikan operasional perkantoran tidak terganggu saat tahapan konstruksi direncanakan.',
  },
  {
    id: 'DED-GDG-005',
    kodePaket: 'DPR-GDG-2025-05',
    namaKegiatan: 'DED Pusat Workshop & Pelatihan Vokasi Tenaga Kerja Maritim Kabil',
    sektor: 'Gedung',
    datasetNo: 1,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Gedung',
    tahunAnggaran: '2025',
    lokasiKawasan: 'Kabil',
    sumberDana: 'APBN',
    paguKonsultansi: 800000000,
    estimasiCapexFisik: 38000000000,
    konsultanPerencana: 'PT Indokomas Buana Perkasa',
    waktuPelaksanaanBulan: 4,
    progresPenyusunanPersen: 100,
    statusKesiapan: 'Selesai (Siap Lelang Fisik)',
    statusUtilisasi: 'Telah Masuk Lelang Fisik TA 2025',
    readinessScore: 92,
    ringkasanTeknis: 'Hanggar workshop pengelasan bawah air (underwater welding), lab NDT, dan simulator crane pelabuhan.',
    outputDokumen: ['DED Final Arsitektur & Sipil', 'RAB & HPS', 'Spesifikasi Mesin & Utility'],
    kendalaDanCatatan: 'Clearance lahan BSW Kabil tuntas.',
    rekomendasiAtasan: 'Koordinasikan dengan Kemenaker untuk sinkronisasi kurikulum pelatihan.',
  },
  {
    id: 'DED-GDG-006',
    kodePaket: 'DPR-GDG-2025-06',
    namaKegiatan: 'DED Gedung Terminal Penumpang Terpadu Pelabuhan Domestik Punggur',
    sektor: 'Gedung',
    datasetNo: 1,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Gedung',
    tahunAnggaran: '2025',
    lokasiKawasan: 'Nongsa & KEK',
    sumberDana: 'PNBP BP Batam',
    paguKonsultansi: 1100000000,
    estimasiCapexFisik: 75000000000,
    konsultanPerencana: 'PT Yodya Karya (Persero)',
    waktuPelaksanaanBulan: 5,
    progresPenyusunanPersen: 78,
    statusKesiapan: 'Review & Asistensi Teknis',
    statusUtilisasi: 'Dianggarkan Renja TA 2026',
    readinessScore: 84,
    ringkasanTeknis: 'Terminal penumpang 3 lantai kapasitas 3.500 pax/hari terhubung langsung skybridge ke dermaga ponton baru.',
    outputDokumen: ['Gambar Rencana Arsitektur Nuansa Melayu', 'Rencana Mekanikal Elektrikal', 'Draft BoQ'],
    kendalaDanCatatan: 'Penyesuaian tata letak loket check-in tiket elektronik.',
    rekomendasiAtasan: 'Sinkronkan dengan rencana dermaga apung Dit. Pelabuhan.',
  },
  {
    id: 'DED-GDG-007',
    kodePaket: 'DPR-GDG-2025-07',
    namaKegiatan: 'DED Asrama Hunian Terpadu Pekerja Kawasan Industri Batamindo Tahap II',
    sektor: 'Gedung',
    datasetNo: 1,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Gedung',
    tahunAnggaran: '2024',
    lokasiKawasan: 'Batam Centre',
    sumberDana: 'KPBU / Mitra',
    paguKonsultansi: 900000000,
    estimasiCapexFisik: 52000000000,
    konsultanPerencana: 'PT Arkonin',
    waktuPelaksanaanBulan: 5,
    progresPenyusunanPersen: 100,
    statusKesiapan: 'Selesai (Siap Lelang Fisik)',
    statusUtilisasi: 'Dianggarkan Renja TA 2026',
    readinessScore: 90,
    ringkasanTeknis: 'Tower rusunawa 5 lantai (96 unit tipe 36) ramah lingkungan dilengkapi fasilitas komersial UMKM lantai dasar.',
    outputDokumen: ['DED Final Lengkap', 'Kajian Kelayakan Finansial KPBU', 'Perizinan Bangunan Gedung (PBG)'],
    kendalaDanCatatan: 'Menunggu penandatanganan skema pembiayaan mitra.',
    rekomendasiAtasan: 'Dukungan penuh untuk penyiapan lelang investor swasta/B2B.',
  },
  {
    id: 'DED-GDG-008',
    kodePaket: 'DPR-GDG-2025-08',
    namaKegiatan: 'Studi Kelayakan & Masterplan Gedung Arsip Digital & Data Disaster Recovery BP Batam',
    sektor: 'Gedung',
    datasetNo: 1,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Gedung',
    tahunAnggaran: '2025',
    lokasiKawasan: 'Sekupang',
    sumberDana: 'PNBP BP Batam',
    paguKonsultansi: 650000000,
    estimasiCapexFisik: 32000000000,
    konsultanPerencana: 'PT Surveyor Indonesia',
    waktuPelaksanaanBulan: 4,
    progresPenyusunanPersen: 40,
    statusKesiapan: 'Studi Kelayakan / FS',
    statusUtilisasi: 'Tahap Review Kelayakan Lahan',
    readinessScore: 55,
    ringkasanTeknis: 'Kajian pemilihan tapak bebas gempa & banjir, spesifikasi pengamanan kebakaran FM-200 gas suppression, dan ketahanan fisik.',
    outputDokumen: ['Laporan Pendahuluan FS', 'Analisis Multi-Kriteria Lokasi'],
    kendalaDanCatatan: 'Sedang penentuan titik alokasi lahan di BSW Sekupang bersama Dit. Lahan.',
    rekomendasiAtasan: 'Selesaikan pematokan batas lahan sebelum melangkah ke DED teknis rinci.',
  },

  // --- DATASET NO. 2: PERENCANAAN INFRASTRUKTUR UTILITAS DAN DRAINASE (7 Paket) ---
  {
    id: 'DED-UTL-001',
    kodePaket: 'DPR-UTL-2025-01',
    namaKegiatan: 'DED Master Drainage & Normalisasi Sungai Sub-DAS Batam Centre - Sei Nayon',
    sektor: 'Utilitas dan Drainase',
    datasetNo: 2,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Utilitas dan Drainase',
    tahunAnggaran: '2025',
    lokasiKawasan: 'Batam Centre',
    sumberDana: 'PNBP BP Batam',
    paguKonsultansi: 1600000000,
    estimasiCapexFisik: 125000000000,
    konsultanPerencana: 'PT Indra Karya (Persero)',
    waktuPelaksanaanBulan: 6,
    progresPenyusunanPersen: 100,
    statusKesiapan: 'Selesai (Siap Lelang Fisik)',
    statusUtilisasi: 'Telah Masuk Lelang Fisik TA 2025',
    readinessScore: 96,
    ringkasanTeknis: 'Pelebaran alur saluran drainase primer lebar 18-24 m, dinding penahan tanah sheet pile beton CCSP, dan kolam retensi penampung debit banjir kala ulang 50 tahun.',
    outputDokumen: ['DED Drainase Primer', 'Kajian Hidrologi & Pemodelan HEC-RAS', 'RAB & Gambar Teknis', 'Dokumen Tender'],
    kendalaDanCatatan: 'Selesai tanpa kendala teknis.',
    rekomendasiAtasan: 'Prioritas mendesak untuk antisipasi genangan musim hujan di simpang KDA.',
  },
  {
    id: 'DED-UTL-002',
    kodePaket: 'DPR-UTL-2025-02',
    namaKegiatan: 'DED Sistem Polder & Rumah Pompa Pengendali Banjir Kawasan Industri Batu Ampar',
    sektor: 'Utilitas dan Drainase',
    datasetNo: 2,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Utilitas dan Drainase',
    tahunAnggaran: '2025',
    lokasiKawasan: 'Batu Ampar & Bengkong',
    sumberDana: 'PNBP BP Batam',
    paguKonsultansi: 1350000000,
    estimasiCapexFisik: 95000000000,
    konsultanPerencana: 'PT Amarta Karya (Persero)',
    waktuPelaksanaanBulan: 5,
    progresPenyusunanPersen: 80,
    statusKesiapan: 'Review & Asistensi Teknis',
    statusUtilisasi: 'Dianggarkan Renja TA 2026',
    readinessScore: 82,
    ringkasanTeknis: 'Polder pasang surut dilengkapi 4 unit pompa axial submersible kapasitas 2,5 m3/detik dan pintu air otomatis (tide gate).',
    outputDokumen: ['Laporan DED Mekanikal Elektrikal Pompa', 'Desain Pintu Air Hidrolik', 'Draft BoQ'],
    kendalaDanCatatan: 'Sinkronisasi jalur buangan air laut dengan rencana dermaga peti kemas.',
    rekomendasiAtasan: 'Pastikan jalur buangan pipa tidak mengganggu alur putar kapal.',
  },
  {
    id: 'DED-UTL-003',
    kodePaket: 'DPR-UTL-2025-03',
    namaKegiatan: 'DED Saluran Utilitas Bersama / Multi-Utility Tunnel (MUT) Koridor Sudirman Tahap I',
    sektor: 'Utilitas dan Drainase',
    datasetNo: 2,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Utilitas dan Drainase',
    tahunAnggaran: '2025',
    lokasiKawasan: 'Batam Centre',
    sumberDana: 'PNBP BP Batam',
    paguKonsultansi: 1750000000,
    estimasiCapexFisik: 140000000000,
    konsultanPerencana: 'PT Witteveen+Bos Indonesia',
    waktuPelaksanaanBulan: 6,
    progresPenyusunanPersen: 65,
    statusKesiapan: 'Penyusunan DED & RAB',
    statusUtilisasi: 'Dianggarkan Renja TA 2026',
    readinessScore: 75,
    ringkasanTeknis: 'Tunnel bawah tanah terpadu dimensi 2,5 x 2,0 m untuk penempatan kabel fiber optik, pipa distribusi air bersih SPAM, dan kabel tegangan menengah PLN tanpa galian berulang.',
    outputDokumen: ['Laporan Antara DED MUT', 'Desain Manhole Akses Terpadu'],
    kendalaDanCatatan: 'Perlu komitmen tertulis operator telekomunikasi & PLN mengenai biaya sewa kompartemen ruang utilitas.',
    rekomendasiAtasan: 'Direktorat Perencanaan pimpin koordinasi tarif sewa ducting bersama Biro Hukum & Dit. Usaha.',
  },
  {
    id: 'DED-UTL-004',
    kodePaket: 'DPR-UTL-2025-04',
    namaKegiatan: 'DED Pipa Interkoneksi Transmisi Air Baku Waduk Tembesi menuju Waduk Mukakuning',
    sektor: 'Utilitas dan Drainase',
    datasetNo: 2,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Utilitas dan Drainase',
    tahunAnggaran: '2024',
    lokasiKawasan: 'Sagulung & Batu Aji',
    sumberDana: 'APBN',
    paguKonsultansi: 1200000000,
    estimasiCapexFisik: 82000000000,
    konsultanPerencana: 'PT Virama Karya (Persero)',
    waktuPelaksanaanBulan: 5,
    progresPenyusunanPersen: 100,
    statusKesiapan: 'Selesai (Siap Lelang Fisik)',
    statusUtilisasi: 'Telah Masuk Lelang Fisik TA 2025',
    readinessScore: 97,
    ringkasanTeknis: 'Pipa baja spiral diameter 1.000 mm sepanjang 4,2 km berikut stasiun pompa booster kapasitas 600 liter/detik guna menjaga ketahanan air baku pulau Batam.',
    outputDokumen: ['DED Final & BoQ', 'Spesifikasi Pompa Booster', 'Dokumen Tender Balai Wilayah Sungai'],
    kendalaDanCatatan: 'Kesiapan siap lelang 100%.',
    rekomendasiAtasan: 'Lanjutkan koordinasi dengan Kementerian PUPR / BWS Sumatera IV.',
  },
  {
    id: 'DED-UTL-005',
    kodePaket: 'DPR-UTL-2025-05',
    namaKegiatan: 'DED Pengolahan Air Limbah Terpadu (IPAL Terpusat) Kawasan Industri Kabil',
    sektor: 'Utilitas dan Drainase',
    datasetNo: 2,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Utilitas dan Drainase',
    tahunAnggaran: '2025',
    lokasiKawasan: 'Kabil',
    sumberDana: 'KPBU / Mitra',
    paguKonsultansi: 980000000,
    estimasiCapexFisik: 68000000000,
    konsultanPerencana: 'PT Envirocon Buana',
    waktuPelaksanaanBulan: 5,
    progresPenyusunanPersen: 50,
    statusKesiapan: 'Penyusunan DED & RAB',
    statusUtilisasi: 'Antrean Alokasi Anggaran',
    readinessScore: 68,
    ringkasanTeknis: 'Teknologi Moving Bed Biofilm Reactor (MBBR) kapasitas 100 liter/detik untuk mengolah air limbah domestik dan industri non-B3.',
    outputDokumen: ['Laporan DED Proses IPAL', 'Kajian AMDAL Effluent'],
    kendalaDanCatatan: 'Menunggu hasil uji lab karakteristik limbah cair inlet beberapa tenant baru.',
    rekomendasiAtasan: 'Pastikan baku mutu air olahan memenuhi Permen LHK No. P.68/2016.',
  },
  {
    id: 'DED-UTL-006',
    kodePaket: 'DPR-UTL-2025-06',
    namaKegiatan: 'DED Normalisasi Saluran Pembuang Utama Drainase Tanjung Sengkuang - Bengkong',
    sektor: 'Utilitas dan Drainase',
    datasetNo: 2,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Utilitas dan Drainase',
    tahunAnggaran: '2025',
    lokasiKawasan: 'Batu Ampar & Bengkong',
    sumberDana: 'PNBP BP Batam',
    paguKonsultansi: 750000000,
    estimasiCapexFisik: 34000000000,
    konsultanPerencana: 'PT Bina Mitra Artha',
    waktuPelaksanaanBulan: 4,
    progresPenyusunanPersen: 100,
    statusKesiapan: 'Selesai (Siap Lelang Fisik)',
    statusUtilisasi: 'Telah Masuk Lelang Fisik TA 2025',
    readinessScore: 92,
    ringkasanTeknis: 'Konstruksi saluran U-Ditch precast lebar 4 m sepanjang 2,1 km mengalirkan air limpasan menuju laut lepas.',
    outputDokumen: ['DED Final', 'RAB & HPS', 'Gambar Kerja Saluran U-Ditch'],
    kendalaDanCatatan: 'Selesai review teknis.',
    rekomendasiAtasan: 'Segera serahkan ke Pejabat Pembuat Komitmen (PPK) Drainase Dit. Pembangunan.',
  },
  {
    id: 'DED-UTL-007',
    kodePaket: 'DPR-UTL-2025-07',
    namaKegiatan: 'Studi Kelayakan & Masterplan Penerangan Jalan Umum (PJU) Smart LED Terpadu Pulau Batam',
    sektor: 'Utilitas dan Drainase',
    datasetNo: 2,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Utilitas dan Drainase',
    tahunAnggaran: '2025',
    lokasiKawasan: 'Batam Centre',
    sumberDana: 'PNBP BP Batam',
    paguKonsultansi: 600000000,
    estimasiCapexFisik: 45000000000,
    konsultanPerencana: 'PT Sucofindo (Persero)',
    waktuPelaksanaanBulan: 4,
    progresPenyusunanPersen: 35,
    statusKesiapan: 'Studi Kelayakan / FS',
    statusUtilisasi: 'Tahap Review Kelayakan Lahan',
    readinessScore: 50,
    ringkasanTeknis: 'Kajian modernisasi 8.500 titik lampu jalan ke teknologi Smart LED terhubung IoT metering dan solar cell hybrid.',
    outputDokumen: ['Laporan Pendahuluan FS PJU', 'Analisis Penghematan Daya Listrik'],
    kendalaDanCatatan: 'Sedang audit konsumsi daya listrik PLN eksisting.',
    rekomendasiAtasan: 'Targetkan efisiensi rekening tagihan listrik BP Batam minimal 40%.',
  },

  // --- DATASET NO. 3: PERENCANAAN FASILITAS WISATA DAN LINGKUNGAN (6 Paket) ---
  {
    id: 'DED-WIS-001',
    kodePaket: 'DPR-WIS-2025-01',
    namaKegiatan: 'DED Penataan Kawasan Destinasi Wisata Pesisir Dendang Melayu Jembatan 1 Barelang',
    sektor: 'Fasilitas Wisata dan Lingkungan',
    datasetNo: 3,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Fasilitas Wisata dan Lingkungan',
    tahunAnggaran: '2025',
    lokasiKawasan: 'Barelang & Rempang',
    sumberDana: 'PNBP BP Batam',
    paguKonsultansi: 1250000000,
    estimasiCapexFisik: 78000000000,
    konsultanPerencana: 'PT Pandu Persada',
    waktuPelaksanaanBulan: 5,
    progresPenyusunanPersen: 100,
    statusKesiapan: 'Selesai (Siap Lelang Fisik)',
    statusUtilisasi: 'Telah Masuk Lelang Fisik TA 2025',
    readinessScore: 95,
    ringkasanTeknis: 'Plaza pandang ikonik pemandangan Jembatan Barelang, amphiteater budaya Melayu, sentra kuliner seafood higienis, dan dermaga boat wisata.',
    outputDokumen: ['Masterplan & DED Kawasan', 'Gambar Kerja Lansekap & Struktur', 'BoQ dan HPS Final'],
    kendalaDanCatatan: 'Sudah disetujui dalam forum konsultasi publik masyarakat Barelang.',
    rekomendasiAtasan: 'Ikon wisata utama Batam, dorong tender fisik tepat waktu.',
  },
  {
    id: 'DED-WIS-002',
    kodePaket: 'DPR-WIS-2025-02',
    namaKegiatan: 'DED Pengembangan Ekowisata Mangrove Berkelanjutan Pandang Tak Jemu Nongsa',
    sektor: 'Fasilitas Wisata dan Lingkungan',
    datasetNo: 3,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Fasilitas Wisata dan Lingkungan',
    tahunAnggaran: '2025',
    lokasiKawasan: 'Nongsa & KEK',
    sumberDana: 'PNBP BP Batam',
    paguKonsultansi: 750000000,
    estimasiCapexFisik: 32000000000,
    konsultanPerencana: 'PT Transforma Cipta Mandiri',
    waktuPelaksanaanBulan: 4,
    progresPenyusunanPersen: 80,
    statusKesiapan: 'Review & Asistensi Teknis',
    statusUtilisasi: 'Dianggarkan Renja TA 2026',
    readinessScore: 85,
    ringkasanTeknis: 'Boardwalk kayu komposit ramah lingkungan sepanjang 1,8 km melintasi hutan bakau, menara pengamat burung (bird watching tower), dan pusat edukasi konservasi pesisir.',
    outputDokumen: ['Draft DED Boardwalk Komposit', 'Persetujuan Kesesuaian Ruang Laut (PKKPRL)'],
    kendalaDanCatatan: 'Perlu kehati-hatian pada sistem pondasi tiang pancang agar tidak merusak perakaran mangrove.',
    rekomendasiAtasan: 'Gunakan spesifikasi tiang pancang minipile dengan metode pemasangan non-ekskavator berat.',
  },
  {
    id: 'DED-WIS-003',
    kodePaket: 'DPR-WIS-2025-03',
    namaKegiatan: 'DED Revitalisasi Taman Kolam Sekupang & Jogging Track Kawasan Konservasi Wisata Rusa',
    sektor: 'Fasilitas Wisata dan Lingkungan',
    datasetNo: 3,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Fasilitas Wisata dan Lingkungan',
    tahunAnggaran: '2025',
    lokasiKawasan: 'Sekupang',
    sumberDana: 'PNBP BP Batam',
    paguKonsultansi: 850000000,
    estimasiCapexFisik: 42000000000,
    konsultanPerencana: 'PT Duta Graha Artha',
    waktuPelaksanaanBulan: 4,
    progresPenyusunanPersen: 100,
    statusKesiapan: 'Selesai (Siap Lelang Fisik)',
    statusUtilisasi: 'Telah Masuk Lelang Fisik TA 2025',
    readinessScore: 94,
    ringkasanTeknis: 'Jogging track sintetis 3,2 km keliling danau kolam, air mancur musikal bertenaga surya, penataan kandang rusa terbuka safari mini, dan toilet sanitasi standar internasional.',
    outputDokumen: ['DED Final & BoQ', 'Desain Air Mancur Menari', 'Dokumen Pengadaan Fisik'],
    kendalaDanCatatan: 'Dokumen teknis tuntas diverifikasi.',
    rekomendasiAtasan: 'Siap eksekusi fisik, menjadi ruang publik rekreasi keluarga Sekupang.',
  },
  {
    id: 'DED-WIS-004',
    kodePaket: 'DPR-WIS-2025-04',
    namaKegiatan: 'DED Waterfront Promenade & Dermaga Wisata Bahari Marina Sekupang',
    sektor: 'Fasilitas Wisata dan Lingkungan',
    datasetNo: 3,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Fasilitas Wisata dan Lingkungan',
    tahunAnggaran: '2025',
    lokasiKawasan: 'Sekupang',
    sumberDana: 'PNBP BP Batam',
    paguKonsultansi: 950000000,
    estimasiCapexFisik: 58000000000,
    konsultanPerencana: 'PT Arkonin',
    waktuPelaksanaanBulan: 5,
    progresPenyusunanPersen: 60,
    statusKesiapan: 'Penyusunan DED & RAB',
    statusUtilisasi: 'Dianggarkan Renja TA 2026',
    readinessScore: 70,
    ringkasanTeknis: 'Promenade tepi laut lebar 12 m dilengkapi revetment batu pecah pemecah ombak, jalur sepeda, dan dermaga ponton tambat yacht/kapal wisata.',
    outputDokumen: ['Laporan DED Geoteknik Laut', 'Gambar Rencana Revetment'],
    kendalaDanCatatan: 'Analisis gelombang pasang surut (bathymetry survey) sedang difinalkan di lapangan.',
    rekomendasiAtasan: 'Perhitungkan elevasi muka air pasang tertinggi (Highest Astronomical Tide) untuk mencegah overtopping gelombang.',
  },
  {
    id: 'DED-WIS-005',
    kodePaket: 'DPR-WIS-2025-05',
    namaKegiatan: 'DED Penataan Sentra Wisata Kuliner Pesisir & Heritage Kampung Tua Tanjung Riau',
    sektor: 'Fasilitas Wisata dan Lingkungan',
    datasetNo: 3,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Fasilitas Wisata dan Lingkungan',
    tahunAnggaran: '2024',
    lokasiKawasan: 'Sekupang',
    sumberDana: 'PNBP BP Batam',
    paguKonsultansi: 650000000,
    estimasiCapexFisik: 28000000000,
    konsultanPerencana: 'PT Cipta Sarana Mandiri',
    waktuPelaksanaanBulan: 4,
    progresPenyusunanPersen: 100,
    statusKesiapan: 'Selesai (Siap Lelang Fisik)',
    statusUtilisasi: 'Dianggarkan Renja TA 2026',
    readinessScore: 88,
    ringkasanTeknis: 'Kios kuliner apung higienis dengan sistem pengolahan limbah minyak (grease trap) terpadu dan pelantar beton ramah lingkungan.',
    outputDokumen: ['DED Final', 'RAB & HPS', 'Kajian Partisipasi Warga'],
    kendalaDanCatatan: 'Penyelarasan batas sempadan laut dengan persetujuan tokoh masyarakat kampung tua.',
    rekomendasiAtasan: 'Jaga keaslian budaya arsitektur panggung kayu Melayu tradisional.',
  },
  {
    id: 'DED-WIS-006',
    kodePaket: 'DPR-WIS-2025-06',
    namaKegiatan: 'Studi Kelayakan Kawasan Wisata Bahari Terpadu Pulau Abang & Gugusan Terumbu Karang',
    sektor: 'Fasilitas Wisata dan Lingkungan',
    datasetNo: 3,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Fasilitas Wisata dan Lingkungan',
    tahunAnggaran: '2025',
    lokasiKawasan: 'Barelang & Rempang',
    sumberDana: 'APBN',
    paguKonsultansi: 550000000,
    estimasiCapexFisik: 35000000000,
    konsultanPerencana: 'PT Surveyor Indonesia',
    waktuPelaksanaanBulan: 4,
    progresPenyusunanPersen: 30,
    statusKesiapan: 'Studi Kelayakan / FS',
    statusUtilisasi: 'Tahap Review Kelayakan Lahan',
    readinessScore: 48,
    ringkasanTeknis: 'Zonasi konservasi terumbu karang bawah laut (snorkeling/diving), lokasi dermaga apung ramah lingkungan, dan fasilitas desalinasi air bersih pulau kecil.',
    outputDokumen: ['Laporan Pendahuluan FS', 'Peta Batimetri Terumbu Karang'],
    kendalaDanCatatan: 'Cuaca laut bergelombang memperlambat survei bawah air biota laut.',
    rekomendasiAtasan: 'Pastikan status kawasan konservasi perairan daerah (KKPD) dihormati.',
  },

  // --- DATASET NO. 4: PERENCANAAN PERTANAMAN DAN PENGHIJAUAN (6 Paket) ---
  {
    id: 'DED-TNM-001',
    kodePaket: 'DPR-TNM-2025-01',
    namaKegiatan: 'DED Penataan Koridor Hijau & Lanskap Estetika Jalan Gajah Mada Tiban - Sekupang',
    sektor: 'Pertanaman dan Penghijauan',
    datasetNo: 4,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Pertanaman dan Penghijauan',
    tahunAnggaran: '2025',
    lokasiKawasan: 'Sekupang',
    sumberDana: 'PNBP BP Batam',
    paguKonsultansi: 650000000,
    estimasiCapexFisik: 24000000000,
    konsultanPerencana: 'PT Deta Decon',
    waktuPelaksanaanBulan: 4,
    progresPenyusunanPersen: 100,
    statusKesiapan: 'Selesai (Siap Lelang Fisik)',
    statusUtilisasi: 'Telah Masuk Lelang Fisik TA 2025',
    readinessScore: 96,
    ringkasanTeknis: 'Penataan median jalan sepanjang 5,6 km dengan pohon peneduh Tabebuya Rosea, Ketapang Kencana, sistem irigasi tetes otomatis (drip irrigation), dan penerangan aksen lanskap malam hari.',
    outputDokumen: ['DED Lanskap & Hardscape', 'Spesifikasi Vegetasi Tanaman', 'BoQ dan Analisis Harga Satuan', 'Dokumen Pengadaan'],
    kendalaDanCatatan: 'Tuntas tanpa hambatan.',
    rekomendasiAtasan: 'Segera laksanakan untuk mewujudkan citra Batam Kota Asri dan Nyaman.',
  },
  {
    id: 'DED-TNM-002',
    kodePaket: 'DPR-TNM-2025-02',
    namaKegiatan: 'DED Sabuk Hijau (Green Buffer Zone) Kawasan Industri Kabil & Pelabuhan Logistik',
    sektor: 'Pertanaman dan Penghijauan',
    datasetNo: 4,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Pertanaman dan Penghijauan',
    tahunAnggaran: '2025',
    lokasiKawasan: 'Kabil',
    sumberDana: 'PNBP BP Batam',
    paguKonsultansi: 720000000,
    estimasiCapexFisik: 28000000000,
    konsultanPerencana: 'PT Envirocon Buana',
    waktuPelaksanaanBulan: 4,
    progresPenyusunanPersen: 85,
    statusKesiapan: 'Review & Asistensi Teknis',
    statusUtilisasi: 'Dianggarkan Renja TA 2026',
    readinessScore: 86,
    ringkasanTeknis: 'Penanaman 8.000 pohon penyerap polusi udara dan peredam kebisingan (Bungur, Trembesi, Mahoni) mengelilingi perbatasan kawasan pemukiman warga.',
    outputDokumen: ['DED Buffer Zone', 'Rencana Penanaman Vegetasi', 'Draft HPS'],
    kendalaDanCatatan: 'Sinkronisasi jalur galian utilitas pipa gas PGN di sempadan sabuk hijau.',
    rekomendasiAtasan: 'Pohon berakar dalam tidak boleh ditanam di atas koridor galian pipa gas aktif.',
  },
  {
    id: 'DED-TNM-003',
    kodePaket: 'DPR-TNM-2025-03',
    namaKegiatan: 'DED Konservasi Sabuk Hijau Sempadan Daerah Tangkapan Air (DTA) Waduk Duriangkang',
    sektor: 'Pertanaman dan Penghijauan',
    datasetNo: 4,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Pertanaman dan Penghijauan',
    tahunAnggaran: '2025',
    lokasiKawasan: 'Batam Centre',
    sumberDana: 'PNBP BP Batam',
    paguKonsultansi: 850000000,
    estimasiCapexFisik: 35000000000,
    konsultanPerencana: 'PT Transforma Cipta Mandiri',
    waktuPelaksanaanBulan: 5,
    progresPenyusunanPersen: 70,
    statusKesiapan: 'Penyusunan DED & RAB',
    statusUtilisasi: 'Dianggarkan Renja TA 2026',
    readinessScore: 74,
    ringkasanTeknis: 'Reforestasi 45 hektar sempadan waduk utama penyuplai air Batam dengan tanaman endemik (Meranti, Gaharu, Bintaro) guna menekan sedimentasi lumpur erosi.',
    outputDokumen: ['Laporan Antara DED Konservasi', 'Peta Tutupan Lahan Sentinel'],
    kendalaDanCatatan: 'Adanya beberapa titik kebun liar yang memerlukan penertiban persuasif terpadu bersama Ditpam.',
    rekomendasiAtasan: 'Gandeng Dit. Pengamanan Aset sebelum penanaman fisik dimulai.',
  },
  {
    id: 'DED-TNM-004',
    kodePaket: 'DPR-TNM-2025-04',
    namaKegiatan: 'DED Penataan Taman Tematik Terbuka Hijau Bundaran Tuah Madani - Simpang Jam',
    sektor: 'Pertanaman dan Penghijauan',
    datasetNo: 4,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Pertanaman dan Penghijauan',
    tahunAnggaran: '2024',
    lokasiKawasan: 'Batam Centre',
    sumberDana: 'PNBP BP Batam',
    paguKonsultansi: 500000000,
    estimasiCapexFisik: 18000000000,
    konsultanPerencana: 'PT Bina Mitra Artha',
    waktuPelaksanaanBulan: 3,
    progresPenyusunanPersen: 100,
    statusKesiapan: 'Selesai (Siap Lelang Fisik)',
    statusUtilisasi: 'Telah Masuk Lelang Fisik TA 2025',
    readinessScore: 95,
    ringkasanTeknis: 'Taman bunga tematik multi-warna, rumput gajah mini, sculpture modern landmark Batam Maju, dan pencahayaan lampu sorot taman arsitektural.',
    outputDokumen: ['DED Final Lanskap', 'RAB & HPS', 'Kajian Keselamatan Lalu Lintas'],
    kendalaDanCatatan: 'Telah siap tender 100%.',
    rekomendasiAtasan: 'Prioritas keindahan pusat kota Batam Centre.',
  },
  {
    id: 'DED-TNM-005',
    kodePaket: 'DPR-TNM-2025-05',
    namaKegiatan: 'DED Penghijauan Median Jalan Trans Barelang Segmen 1 (Tembesi - Jembatan 1)',
    sektor: 'Pertanaman dan Penghijauan',
    datasetNo: 4,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Pertanaman dan Penghijauan',
    tahunAnggaran: '2025',
    lokasiKawasan: 'Barelang & Rempang',
    sumberDana: 'PNBP BP Batam',
    paguKonsultansi: 580000000,
    estimasiCapexFisik: 22000000000,
    konsultanPerencana: 'PT Pandu Persada',
    waktuPelaksanaanBulan: 4,
    progresPenyusunanPersen: 100,
    statusKesiapan: 'Selesai (Siap Lelang Fisik)',
    statusUtilisasi: 'Dianggarkan Renja TA 2026',
    readinessScore: 90,
    ringkasanTeknis: 'Median jalan selebar 4 meter ditanami rumput hias, tanaman perdu Bougenville aneka warna, dan pohon peneduh Pucuk Merah.',
    outputDokumen: ['DED Final Median Jalan', 'BoQ dan HPS', 'Gambar Teknis Potongan'],
    kendalaDanCatatan: 'Selesai verifikasi tim teknis.',
    rekomendasiAtasan: 'Menjadi koridor gerbang utama pariwisata Barelang.',
  },
  {
    id: 'DED-TNM-006',
    kodePaket: 'DPR-TNM-2025-06',
    namaKegiatan: 'Studi Kajian Urban Forest & Koridor Keanekaragaman Hayati Perkotaan Batam',
    sektor: 'Pertanaman dan Penghijauan',
    datasetNo: 4,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Pertanaman dan Penghijauan',
    tahunAnggaran: '2025',
    lokasiKawasan: 'Batam Centre',
    sumberDana: 'PNBP BP Batam',
    paguKonsultansi: 420000000,
    estimasiCapexFisik: 15000000000,
    konsultanPerencana: 'PT Surveyor Indonesia',
    waktuPelaksanaanBulan: 3,
    progresPenyusunanPersen: 45,
    statusKesiapan: 'Studi Kelayakan / FS',
    statusUtilisasi: 'Tahap Review Kelayakan Lahan',
    readinessScore: 52,
    ringkasanTeknis: 'Identifikasi potensi hutan kota seluas 30 hektar untuk penyerapan emisi karbon (carbon sink) dan penurunan suhu pulau panas (Urban Heat Island).',
    outputDokumen: ['Laporan Pendahuluan FS Hutan Kota', 'Peta Analisis Termal Satelit Landsat'],
    kendalaDanCatatan: 'Data inventarisasi pohon eksisting sedang dikompilasi.',
    rekomendasiAtasan: 'Integrasikan dengan target Net Zero Emission kawasan industri BP Batam.',
  },

  // --- DATASET NO. 5: PERENCANAAN PEMBANGUNAN INFRASTRUKTUR DARAT (9 Paket) ---
  {
    id: 'DED-DRT-001',
    kodePaket: 'DPR-DRT-2025-01',
    namaKegiatan: 'DED Pelebaran & Peningkatan Kapasitas Jalan Koridor Utama Simpang Kabil - Simpang Jam (5-6 Lajur)',
    sektor: 'Darat',
    datasetNo: 5,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Darat',
    tahunAnggaran: '2025',
    lokasiKawasan: 'Batam Centre',
    sumberDana: 'PNBP BP Batam',
    paguKonsultansi: 2400000000,
    estimasiCapexFisik: 285000000000,
    konsultanPerencana: 'PT Virama Karya (Persero)',
    waktuPelaksanaanBulan: 6,
    progresPenyusunanPersen: 100,
    statusKesiapan: 'Selesai (Siap Lelang Fisik)',
    statusUtilisasi: 'Telah Masuk Lelang Fisik TA 2025',
    readinessScore: 98,
    ringkasanTeknis: 'Pelebaran jalan dari 4 lajur menjadi 6 lajur dua arah terbagi sepanjang 6,8 km, rigid pavement tebal 30 cm untuk beban sumbu gandar 12 ton, trotoar pejalan kaki lebar 3 m terintegrasi jalur sepeda.',
    outputDokumen: ['DED Jalan Raya Arteri Primer', 'Kajian Lalu Lintas V/C Ratio', 'Gambar Detail Cross Section', 'BoQ dan HPS Final'],
    kendalaDanCatatan: 'Relokasi utilitas kabel bawah tanah telah dikoordinasikan dalam forum perizinan ROW.',
    rekomendasiAtasan: 'Jalur urat nadi utama logistik dan mobilitas Batam, pastikan lelang fisik segera tayang.',
  },
  {
    id: 'DED-DRT-002',
    kodePaket: 'DPR-DRT-2025-02',
    namaKegiatan: 'DED Pembangunan Flyover Simpang Kepri Mall / KDA Tahap I (Struktur Elevated 4 Lajur)',
    sektor: 'Darat',
    datasetNo: 5,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Darat',
    tahunAnggaran: '2025',
    lokasiKawasan: 'Batam Centre',
    sumberDana: 'APBN',
    paguKonsultansi: 3200000000,
    estimasiCapexFisik: 380000000000,
    konsultanPerencana: 'PT Yodya Karya (Persero) - KSO',
    waktuPelaksanaanBulan: 7,
    progresPenyusunanPersen: 88,
    statusKesiapan: 'Review & Asistensi Teknis',
    statusUtilisasi: 'Dianggarkan Renja TA 2026',
    readinessScore: 89,
    ringkasanTeknis: 'Flyover girder beton prategang (prestressed concrete box girder) bentang total 850 meter mengurai kemacetan parah di perempatan tersibuk Batam Centre.',
    outputDokumen: ['Draft DED Struktur Elevated', 'Hasil Boring Log Geoteknik Kedalaman 45m', 'Simulasi Mikro Vissim Lalu Lintas'],
    kendalaDanCatatan: 'Sedang proses asistensi Komisi Keamanan Jembatan dan Terowongan Jalan (KKJTJ) Kementerian PUPR.',
    rekomendasiAtasan: 'Kawal rekomendasi teknis KKJTJ agar DIPA APBN TA 2026 dapat dikucurkan tepat waktu.',
  },
  {
    id: 'DED-DRT-003',
    kodePaket: 'DPR-DRT-2025-03',
    namaKegiatan: 'DED Pembangunan Jalan Lingkar Luar (Outer Ring Road) Tanjung Piayu - Kawasan Industri Kabil',
    sektor: 'Darat',
    datasetNo: 5,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Darat',
    tahunAnggaran: '2025',
    lokasiKawasan: 'Kabil',
    sumberDana: 'PNBP BP Batam',
    paguKonsultansi: 1950000000,
    estimasiCapexFisik: 210000000000,
    konsultanPerencana: 'PT Bina Karya (Persero)',
    waktuPelaksanaanBulan: 6,
    progresPenyusunanPersen: 65,
    statusKesiapan: 'Penyusunan DED & RAB',
    statusUtilisasi: 'Dianggarkan Renja TA 2026',
    readinessScore: 76,
    ringkasanTeknis: 'Trase jalan baru 8,4 km membuka akses langsung kawasan industri galangan kapal Kabil ke arah selatan tanpa harus membebani jalan arteri perkotaan.',
    outputDokumen: ['Laporan Antara DED Trase Baru', 'Pengukuran Topografi Drone LiDAR', 'Analisis Potongan Cut & Fill'],
    kendalaDanCatatan: 'Terdapat trase memotong bukit berbatu keras yang memerlukan perhitungan peledakan terkontrol (controlled blasting).',
    rekomendasiAtasan: 'Hitung neraca galian dan timbunan (mass haul diagram) agar biaya cut & fill efisien.',
  },
  {
    id: 'DED-DRT-004',
    kodePaket: 'DPR-DRT-2025-04',
    namaKegiatan: 'DED Peningkatan Jalan Koridor Pelabuhan Batu Ampar Jalan Duyung - Harbour Bay (Khusus Angkutan Berat)',
    sektor: 'Darat',
    datasetNo: 5,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Darat',
    tahunAnggaran: '2024',
    lokasiKawasan: 'Batu Ampar & Bengkong',
    sumberDana: 'PNBP BP Batam',
    paguKonsultansi: 1400000000,
    estimasiCapexFisik: 135000000000,
    konsultanPerencana: 'PT Ciriajasa Engineering',
    waktuPelaksanaanBulan: 5,
    progresPenyusunanPersen: 100,
    statusKesiapan: 'Selesai (Siap Lelang Fisik)',
    statusUtilisasi: 'Telah Masuk Lelang Fisik TA 2025',
    readinessScore: 97,
    ringkasanTeknis: 'Rekonstruksi jalan perkerasan kaku beton FS-45 dengan tulangan anyaman kawat ganda untuk menampung lintasan kontainer 40 feet dari dermaga Batu Ampar.',
    outputDokumen: ['DED Final & BoQ', 'Spesifikasi Khusus Perkerasan Berat', 'RAB & HPS Terverifikasi'],
    kendalaDanCatatan: 'Dokumen lengkap siap lelang fisik.',
    rekomendasiAtasan: 'Segera umumkan tender fisik sebelum puncak arus logistik akhir tahun.',
  },
  {
    id: 'DED-DRT-005',
    kodePaket: 'DPR-DRT-2025-05',
    namaKegiatan: 'DED Pembangunan Jembatan Sei Ladi Tahap II (Duplikasi Jembatan Penyeberangan Sungai)',
    sektor: 'Darat',
    datasetNo: 5,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Darat',
    tahunAnggaran: '2024',
    lokasiKawasan: 'Sekupang',
    sumberDana: 'PNBP BP Batam',
    paguKonsultansi: 1250000000,
    estimasiCapexFisik: 95000000000,
    konsultanPerencana: 'PT Deta Decon',
    waktuPelaksanaanBulan: 5,
    progresPenyusunanPersen: 100,
    statusKesiapan: 'Selesai (Siap Lelang Fisik)',
    statusUtilisasi: 'Telah Masuk Lelang Fisik TA 2025',
    readinessScore: 96,
    ringkasanTeknis: 'Jembatan busur baja (steel arch bridge) bentang 65 m melintasi jurang Waduk Sei Ladi, menambah kapasitas lajur dari Sekupang ke Batam Centre.',
    outputDokumen: ['DED Struktur Jembatan Busur', 'Analisis Seismik Gempa Dinamis', 'Dokumen Lelang Konstruksi'],
    kendalaDanCatatan: 'Selesai asistensi keselamatan jembatan bentang panjang.',
    rekomendasiAtasan: 'Jembatan ini akan menjadi landmark baru jalur Sekupang.',
  },
  {
    id: 'DED-DRT-006',
    kodePaket: 'DPR-DRT-2025-06',
    namaKegiatan: 'DED Pelebaran Jalan Akses Pariwisata & Kawasan Ekonomi Khusus Nongsa (Jalan Hang Jebat)',
    sektor: 'Darat',
    datasetNo: 5,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Darat',
    tahunAnggaran: '2025',
    lokasiKawasan: 'Nongsa & KEK',
    sumberDana: 'PNBP BP Batam',
    paguKonsultansi: 1150000000,
    estimasiCapexFisik: 98000000000,
    konsultanPerencana: 'PT Indra Karya (Persero)',
    waktuPelaksanaanBulan: 5,
    progresPenyusunanPersen: 75,
    statusKesiapan: 'Review & Asistensi Teknis',
    statusUtilisasi: 'Dianggarkan Renja TA 2026',
    readinessScore: 83,
    ringkasanTeknis: 'Pelebaran jalan dari 2 lajur menjadi 4 lajur dua arah sepanjang 5,2 km dilengkapi lampu PJU tematik dan trotoar wisata menuju resort Nongsa.',
    outputDokumen: ['Draft DED Jalan Wisata', 'Laporan Geometrik Tikungan', 'Draft BoQ'],
    kendalaDanCatatan: 'Perlu relokasi beberapa tiang penerangan eksisting milik PLN.',
    rekomendasiAtasan: 'Koordinasikan biaya kompensasi relokasi utilitas dengan PLN.',
  },
  {
    id: 'DED-DRT-007',
    kodePaket: 'DPR-DRT-2025-07',
    namaKegiatan: 'DED Pembangunan Jembatan Penyeberangan Orang (JPO) Terintegrasi Halte BRT Batam Centre',
    sektor: 'Darat',
    datasetNo: 5,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Darat',
    tahunAnggaran: '2025',
    lokasiKawasan: 'Batam Centre',
    sumberDana: 'PNBP BP Batam',
    paguKonsultansi: 650000000,
    estimasiCapexFisik: 28000000000,
    konsultanPerencana: 'PT Cipta Sarana Mandiri',
    waktuPelaksanaanBulan: 4,
    progresPenyusunanPersen: 100,
    statusKesiapan: 'Selesai (Siap Lelang Fisik)',
    statusUtilisasi: 'Telah Masuk Lelang Fisik TA 2025',
    readinessScore: 94,
    ringkasanTeknis: 'JPO modern beratap kanopi membran arsitektural dengan lift kaca ramah lansia & disabilitas menghubungkan Kantor Walikota, Mega Mall, dan Masjid Agung.',
    outputDokumen: ['DED Final JPO Arsitektural', 'Spesifikasi Lift Outdoor', 'RAB & HPS'],
    kendalaDanCatatan: 'Lengkap dan siap lelang.',
    rekomendasiAtasan: 'Tingkatkan kenyamanan pejalan kaki di pusat pemerintahan Batam.',
  },
  {
    id: 'DED-DRT-008',
    kodePaket: 'DPR-DRT-2025-08',
    namaKegiatan: 'DED Peningkatan Jalur Akses Logistik Pulau Galang & Jembatan 6 Barelang',
    sektor: 'Darat',
    datasetNo: 5,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Darat',
    tahunAnggaran: '2025',
    lokasiKawasan: 'Barelang & Rempang',
    sumberDana: 'APBN',
    paguKonsultansi: 950000000,
    estimasiCapexFisik: 78000000000,
    konsultanPerencana: 'PT Pandu Persada',
    waktuPelaksanaanBulan: 5,
    progresPenyusunanPersen: 55,
    statusKesiapan: 'Penyusunan DED & RAB',
    statusUtilisasi: 'Dianggarkan Renja TA 2026',
    readinessScore: 69,
    ringkasanTeknis: 'Preservasi rekonstruksi jalan sepanjang 9,8 km dan perkuatan lereng tebing rawan longsor (soil nailing / retaining wall).',
    outputDokumen: ['Laporan DED Stabilitas Lereng', 'Desain Perkuatan Bronjong'],
    kendalaDanCatatan: 'Menunggu hasil pengujian stabilitas lereng geoteknik musim basah.',
    rekomendasiAtasan: 'Prioritaskan mitigasi longsor pada ruas rawan perbukitan Galang.',
  },
  {
    id: 'DED-DRT-009',
    kodePaket: 'DPR-DRT-2025-09',
    namaKegiatan: 'Studi Kelayakan Sistem Transportasi Massal Terpadu (LRT / Autonomous Rail Transit - ART) Koridor Batam',
    sektor: 'Darat',
    datasetNo: 5,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Darat',
    tahunAnggaran: '2025',
    lokasiKawasan: 'Batam Centre',
    sumberDana: 'KPBU / Mitra',
    paguKonsultansi: 1800000000,
    estimasiCapexFisik: 4200000000000,
    konsultanPerencana: 'KSO PT Mott MacDonald Indonesia - PT Virama Karya',
    waktuPelaksanaanBulan: 6,
    progresPenyusunanPersen: 40,
    statusKesiapan: 'Studi Kelayakan / FS',
    statusUtilisasi: 'Tahap Review Kelayakan Lahan',
    readinessScore: 56,
    ringkasanTeknis: 'Kajian kelayakan teknis, ekonomi, dan skema KPBU transit koridor Bandara Hang Nadim - Batam Centre - Harbour Bay sepanjang 24 km.',
    outputDokumen: ['Laporan Antara FS LRT', 'Analisis Demand & Ridership Forecasting'],
    kendalaDanCatatan: 'Penyelarasan ruang milik jalan (ROW) arteri dengan pilar jalur elevated LRT.',
    rekomendasiAtasan: 'Proyek strategis masa depan Batam, bentuk tim gabungan asistensi KPBU.',
  },

  // --- DATASET NO. 6: PERENCANAAN INFRASTRUKTUR LAUT DAN UDARA (7 Paket) ---
  {
    id: 'DED-LTD-001',
    kodePaket: 'DPR-LTD-2025-01',
    namaKegiatan: 'DED Perpanjangan Dermaga Peti Kemas Utara Pelabuhan Batu Ampar 800 Meter & Pendalaman Alur -14 mLWS',
    sektor: 'Laut dan Udara',
    datasetNo: 6,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Laut dan Udara',
    tahunAnggaran: '2025',
    lokasiKawasan: 'Batu Ampar & Bengkong',
    sumberDana: 'PNBP BP Batam',
    paguKonsultansi: 3500000000,
    estimasiCapexFisik: 450000000000,
    konsultanPerencana: 'PT Virama Karya (Persero) - Royal Haskoning KSO',
    waktuPelaksanaanBulan: 7,
    progresPenyusunanPersen: 100,
    statusKesiapan: 'Selesai (Siap Lelang Fisik)',
    statusUtilisasi: 'Telah Masuk Lelang Fisik TA 2025',
    readinessScore: 98,
    ringkasanTeknis: 'Konstruksi dermaga quay deck struktur tiang pancang baja tubular pile diameter 1.200 mm, rel Ship-to-Shore (STS) crane kapasitas 65 ton, pengerukan alur kolam pelabuhan -14 meter LWS untuk melayani kapal kontainer 5.000 TEUs.',
    outputDokumen: ['DED Pelabuhan Laut Lengkap', 'Kajian Pemodelan Gelombang & Sedimentasi Mike-21', 'RAB & Spesifikasi Teknis Maritim', 'Dokumen Pengadaan'],
    kendalaDanCatatan: 'Izin Persetujuan Lingkungan Amdal Maritim dan izin keruk Ditjen Hubla tuntas.',
    rekomendasiAtasan: 'Prioritas tertinggi BP Batam untuk mewujudkan Hub Logistik Internasional bersaing dengan Singapura.',
  },
  {
    id: 'DED-LTD-002',
    kodePaket: 'DPR-LTD-2025-02',
    namaKegiatan: 'DED Pembangunan Apron Kargo Udara & Taxiway Paralel Bandara Hang Nadim Batam (E-Commerce Logistics Hub)',
    sektor: 'Laut dan Udara',
    datasetNo: 6,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Laut dan Udara',
    tahunAnggaran: '2025',
    lokasiKawasan: 'Nongsa & KEK',
    sumberDana: 'KPBU / Mitra',
    paguKonsultansi: 2800000000,
    estimasiCapexFisik: 320000000000,
    konsultanPerencana: 'PT Angkasa Pura Sarana KSO PT Yodya Karya',
    waktuPelaksanaanBulan: 6,
    progresPenyusunanPersen: 90,
    statusKesiapan: 'Review & Asistensi Teknis',
    statusUtilisasi: 'Dianggarkan Renja TA 2026',
    readinessScore: 91,
    ringkasanTeknis: 'Apron perkerasan kaku PCN 85 luas 45.000 m2 kapasitas 4 parking stand pesawat wide body Boeing 777F/Airbus A330-300F terhubung sistem kargo udara modern.',
    outputDokumen: ['Draft DED Apron & Taxiway', 'Perhitungan Ketebalan Pavement FAARFIELD', 'Desain Drainage Airfield'],
    kendalaDanCatatan: 'Sedang penyesuaian izin rancang bangun Direktorat Bandar Udara Kemenhub.',
    rekomendasiAtasan: 'Percepat asistensi Kemenhub untuk sinkronisasi operasi konsorsium pengelola bandara.',
  },
  {
    id: 'DED-LTD-003',
    kodePaket: 'DPR-LTD-2025-03',
    namaKegiatan: 'DED Pembangunan Dermaga Tambat Kapal Ro-Ro Telaga Punggur Tahap II',
    sektor: 'Laut dan Udara',
    datasetNo: 6,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Laut dan Udara',
    tahunAnggaran: '2024',
    lokasiKawasan: 'Nongsa & KEK',
    sumberDana: 'PNBP BP Batam',
    paguKonsultansi: 1350000000,
    estimasiCapexFisik: 95000000000,
    konsultanPerencana: 'PT Bina Karya (Persero)',
    waktuPelaksanaanBulan: 5,
    progresPenyusunanPersen: 100,
    statusKesiapan: 'Selesai (Siap Lelang Fisik)',
    statusUtilisasi: 'Telah Masuk Lelang Fisik TA 2025',
    readinessScore: 96,
    ringkasanTeknis: 'Dermaga movable bridge hidrolik kapasitas 50 ton, trestle sepanjang 140 m, dan dolphin penahan benturan kapal feri antar-pulau Kepri.',
    outputDokumen: ['DED Final Dermaga Ro-Ro', 'Desain Hidrolik Movable Bridge', 'Dokumen Tender Fisik'],
    kendalaDanCatatan: 'Kesiapan dokumen 100% tuntas.',
    rekomendasiAtasan: 'Solusi mengurangi antrean muatan logistik kendaraan dari Batam ke Bintan dan Tanjung Uban.',
  },
  {
    id: 'DED-LTD-004',
    kodePaket: 'DPR-LTD-2025-04',
    namaKegiatan: 'DED Pengerukan Alur Pelayaran & Kolam Labuh Pelabuhan Domestik Sekupang (-8 mLWS)',
    sektor: 'Laut dan Udara',
    datasetNo: 6,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Laut dan Udara',
    tahunAnggaran: '2025',
    lokasiKawasan: 'Sekupang',
    sumberDana: 'PNBP BP Batam',
    paguKonsultansi: 980000000,
    estimasiCapexFisik: 62000000000,
    konsultanPerencana: 'PT Surveyor Indonesia',
    waktuPelaksanaanBulan: 4,
    progresPenyusunanPersen: 70,
    statusKesiapan: 'Penyusunan DED & RAB',
    statusUtilisasi: 'Dianggarkan Renja TA 2026',
    readinessScore: 78,
    ringkasanTeknis: 'Pengerukan 450.000 m3 endapan lumpur alur navigasi kapal cepat dan penempatan material buangan keruk (dumping area) resmi izin KKP.',
    outputDokumen: ['Laporan DED Batimetri Alur', 'Kajian Dampak Lingkungan Keruk'],
    kendalaDanCatatan: 'Menunggu rekomendasi titik dumping area laut dari KSOP Batam & Ditjen PRL KKP.',
    rekomendasiAtasan: 'Pastikan titik buangan tidak mencemari terumbu karang dan jalur kabel pipa bawah laut.',
  },
  {
    id: 'DED-LTD-005',
    kodePaket: 'DPR-LTD-2025-05',
    namaKegiatan: 'DED Dermaga Penunjang Logistik & Jetty Nelayan Pulau Galang Baru',
    sektor: 'Laut dan Udara',
    datasetNo: 6,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Laut dan Udara',
    tahunAnggaran: '2024',
    lokasiKawasan: 'Barelang & Rempang',
    sumberDana: 'PNBP BP Batam',
    paguKonsultansi: 800000000,
    estimasiCapexFisik: 42000000000,
    konsultanPerencana: 'PT Duta Graha Artha',
    waktuPelaksanaanBulan: 4,
    progresPenyusunanPersen: 100,
    statusKesiapan: 'Selesai (Siap Lelang Fisik)',
    statusUtilisasi: 'Dianggarkan Renja TA 2026',
    readinessScore: 90,
    ringkasanTeknis: 'Dermaga pendaratan ikan struktur beton bertulang tiang pancang spun pile, panjang 90 m lebar 6 m terhubung trestle.',
    outputDokumen: ['DED Final Dermaga', 'BoQ dan HPS', 'Gambar Kerja Lengkap'],
    kendalaDanCatatan: 'Siap diajukan ke proses pemilihan kontraktor.',
    rekomendasiAtasan: 'Dukung penguatan ketahanan pangan perikanan wilayah pulau-pulau penyangga.',
  },
  {
    id: 'DED-LTD-006',
    kodePaket: 'DPR-LTD-2025-06',
    namaKegiatan: 'DED Fasilitas Maintenance, Repair, and Overhaul (MRO) Pesawat Hang Nadim Tahap III',
    sektor: 'Laut dan Udara',
    datasetNo: 6,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Laut dan Udara',
    tahunAnggaran: '2025',
    lokasiKawasan: 'Nongsa & KEK',
    sumberDana: 'KPBU / Mitra',
    paguKonsultansi: 1950000000,
    estimasiCapexFisik: 240000000000,
    konsultanPerencana: 'PT Mott MacDonald Indonesia',
    waktuPelaksanaanBulan: 6,
    progresPenyusunanPersen: 60,
    statusKesiapan: 'Penyusunan DED & RAB',
    statusUtilisasi: 'Dianggarkan Renja TA 2026',
    readinessScore: 72,
    ringkasanTeknis: 'Hanggar pemeliharaan pesawat berkapasitas 2 pesawat wide-body, sistem crane overhead 20 ton, dan proteksi deluge foam kebakaran.',
    outputDokumen: ['Laporan Antara DED Hanggar', 'Desain MEP & Foam Fire Protection'],
    kendalaDanCatatan: 'Koordinasi perizinan ketinggian Kawasan Keselamatan Operasi Penerbangan (KKOP).',
    rekomendasiAtasan: 'Pastikan elevasi atap hanggar memenuhi ambang batas batas KKOP runway 04-22.',
  },
  {
    id: 'DED-LTD-007',
    kodePaket: 'DPR-LTD-2025-07',
    namaKegiatan: 'Studi Kelayakan Pengembangan Pangkalan Kapal Patroli & Stasiun VTS Maritim BP Batam',
    sektor: 'Laut dan Udara',
    datasetNo: 6,
    datasetName: 'Perencanaan Pembangunan Infrastruktur Laut dan Udara',
    tahunAnggaran: '2025',
    lokasiKawasan: 'Batu Ampar & Bengkong',
    sumberDana: 'PNBP BP Batam',
    paguKonsultansi: 750000000,
    estimasiCapexFisik: 48000000000,
    konsultanPerencana: 'PT Sucofindo (Persero)',
    waktuPelaksanaanBulan: 4,
    progresPenyusunanPersen: 35,
    statusKesiapan: 'Studi Kelayakan / FS',
    statusUtilisasi: 'Tahap Review Kelayakan Lahan',
    readinessScore: 50,
    ringkasanTeknis: 'Kajian penempatan dermaga apung kapal patroli Ditpam/Laut, menara radar pengawasan alur pelayaran Vessel Traffic Service (VTS), dan integrasi CCTV Selat Malaka/Singapura.',
    outputDokumen: ['Laporan Pendahuluan FS VTS', 'Analisis Radar Coverage Range'],
    kendalaDanCatatan: 'Sedang penentuan alokasi koordinat menara radar di tanjung Sengkuang.',
    rekomendasiAtasan: 'Tingkatkan kedaulatan pengawasan maritim dan penanganan kecelakaan kapal.',
  },
];

// 6 INDIKATOR KINERJA UTAMA (BAN METRICS) SESUAI PERMINTAAN USER (DATASET NO 1 - 6)
export const KPI_SEKTOR_LIST: KpiSektorSummary[] = [
  {
    sektor: 'Gedung',
    datasetNo: 1,
    datasetTitle: 'Perencanaan Pembangunan Infrastruktur Gedung',
    iconName: 'Building2',
    totalPaket: 8,
    totalPaguDED: 8900000000,
    totalEstimasiCapexFisik: 540000000000,
    waktuPelaksanaanAvgBulan: 5.1,
    persenSelesaiSiapLelang: 50.0, // 4 dari 8 paket selesai
    paketSiapLelangCount: 4,
    paketDalamProsesCount: 4,
    readinessAvg: 85.3,
    deskripsi: 'Penyusunan DED gedung perkantoran, pusat riset digital KEK Nongsa, fasilitas PTSP Sekupang, dan logistik warehouse Batu Ampar.',
  },
  {
    sektor: 'Utilitas dan Drainase',
    datasetNo: 2,
    datasetTitle: 'Perencanaan Pembangunan Infrastruktur Utilitas dan Drainase',
    iconName: 'Boxes',
    totalPaket: 7,
    totalPaguDED: 8230000000,
    totalEstimasiCapexFisik: 589000000000,
    waktuPelaksanaanAvgBulan: 5.9,
    persenSelesaiSiapLelang: 42.9, // 3 dari 7 paket selesai
    paketSiapLelangCount: 3,
    paketDalamProsesCount: 4,
    readinessAvg: 80.4,
    deskripsi: 'Penyusunan DED normalisasi master drainage DAS Batam Centre, polder banjir, Multi-Utility Tunnel (MUT), dan pipa transmisi air baku.',
  },
  {
    sektor: 'Fasilitas Wisata dan Lingkungan',
    datasetNo: 3,
    datasetTitle: 'Perencanaan Pembangunan Infrastruktur Fasilitas Wisata dan Lingkungan',
    iconName: 'Palmtree',
    totalPaket: 6,
    totalPaguDED: 5000000000,
    totalEstimasiCapexFisik: 273000000000,
    waktuPelaksanaanAvgBulan: 5.0,
    persenSelesaiSiapLelang: 50.0, // 3 dari 6 paket selesai
    paketSiapLelangCount: 3,
    paketDalamProsesCount: 3,
    readinessAvg: 81.5,
    deskripsi: 'Penyusunan DED destinasi pesisir Dendang Melayu Barelang, ekowisata mangrove Nongsa, dan revitalisasi taman kolam Sekupang.',
  },
  {
    sektor: 'Pertanaman dan Penghijauan',
    datasetNo: 4,
    datasetTitle: 'Perencanaan Pembangunan Infrastruktur Pertanaman dan Penghijauan',
    iconName: 'Trees',
    totalPaket: 6,
    totalPaguDED: 3720000000,
    totalEstimasiCapexFisik: 142000000000,
    waktuPelaksanaanAvgBulan: 4.3,
    persenSelesaiSiapLelang: 50.0, // 3 dari 6 paket selesai
    paketSiapLelangCount: 3,
    paketDalamProsesCount: 3,
    readinessAvg: 82.2,
    deskripsi: 'Penyusunan DED koridor hijau estetika kota (Tabebuya), sabuk hijau industri Kabil, dan konservasi sempadan Waduk Duriangkang.',
  },
  {
    sektor: 'Darat',
    datasetNo: 5,
    datasetTitle: 'Perencanaan Pembangunan Infrastruktur Darat',
    iconName: 'Route',
    totalPaket: 9,
    totalPaguDED: 14750000000,
    totalEstimasiCapexFisik: 1464000000000, // Rp 1,46 T
    waktuPelaksanaanAvgBulan: 6.7,
    persenSelesaiSiapLelang: 55.6, // 5 dari 9 paket selesai
    paketSiapLelangCount: 5,
    paketDalamProsesCount: 4,
    readinessAvg: 85.8,
    deskripsi: 'Penyusunan DED pelebaran arteri Simpang Kabil - Simpang Jam, flyover KDA, jembatan Sei Ladi II, dan jalan lingkar luar Kabil.',
  },
  {
    sektor: 'Laut dan Udara',
    datasetNo: 6,
    datasetTitle: 'Perencanaan Pembangunan Infrastruktur Laut dan Udara',
    iconName: 'Ship',
    totalPaket: 7,
    totalPaguDED: 13080000000,
    totalEstimasiCapexFisik: 1259000000000, // Rp 1,26 T
    waktuPelaksanaanAvgBulan: 6.7,
    persenSelesaiSiapLelang: 42.9, // 3 dari 7 paket selesai
    paketSiapLelangCount: 3,
    paketDalamProsesCount: 4,
    readinessAvg: 82.1,
    deskripsi: 'Penyusunan DED perpanjangan dermaga peti kemas Batu Ampar 800m, apron kargo logistik Hang Nadim, dermaga Ro-Ro Punggur, dan MRO pesawat.',
  },
];

// DATA STAGE-GATE / READINESS CRITERIA FUNNEL (Executive Analytics - Req 7)
export const STAGE_GATE_FUNNEL_DATA: StageGateFunnelItem[] = [
  {
    stage: 'Studi Kelayakan / FS',
    count: 5,
    percentage: 11.6,
    totalCapexMiliar: 4330, // Termasuk kajian ART/LRT
    description: 'Tahap pengujian kelayakan teknis, trase, analisis ekonomi, dan kelayakan finansial KPBU.',
    color: '#64748b', // slate
  },
  {
    stage: 'Penyusunan DED & RAB',
    count: 10,
    percentage: 23.3,
    totalCapexMiliar: 858,
    description: 'Penyusunan gambar teknik detail, hitungan kekuatan struktur, spesifikasi teknis, dan BoQ.',
    color: '#0284c7', // sky
  },
  {
    stage: 'Review & Asistensi Teknis',
    count: 7,
    percentage: 16.3,
    totalCapexMiliar: 828,
    description: 'Pemeriksaan kesesuaian standar Bina Marga/Cipta Karya, asistensi tim ahli, dan review HPS.',
    color: '#f59e0b', // amber
  },
  {
    stage: 'Selesai (Siap Lelang Fisik)',
    count: 21,
    percentage: 48.8,
    totalCapexMiliar: 1845,
    description: 'Dokumen DED, RAB, HPS, spesifikasi teknis, dan izin lingkungan 100% tuntas siap tender Dit. Pembangunan.',
    color: '#10b981', // emerald
  },
];

// TINGKAT UTILISASI & ADOPSI HASIL PERENCANAAN (Handover to Construction - Req 7)
export const UTILISASI_DOKUMEN_SUMMARY = {
  totalDokumenTuntas: 21,
  telahMasukLelangFisik: 14, // 66.7%
  dianggarkanRenjaDepan: 7, // 33.3%
  utilisasiFisikPersen: 66.7,
  totalCapexTelahDitenderkanMiliar: 1285.0,
  totalCapexAntreRenjaMiliar: 560.0,
  catatanDirektur:
    'Rasio serap dokumen DED ke lelang fisik mencapai 66,7%, menunjukkan tingkat pemanfaatan dokumen perencanaan sangat tinggi dan terhindar dari pemborosan anggaran kajian (arsip mangkrak).',
};

// BOTTLENECK & EARLY WARNING KENDALA PERENCANAAN UNTUK PIMPINAN (Req 7)
export const EXECUTIVE_EARLY_WARNING_ITEMS = [
  {
    id: 'EW-01',
    isu: 'Sinkronisasi Batas Trase Outer Ring Road Kabil dengan Hutan Lindung',
    sektor: 'Darat',
    tingkatRisiko: 'Tinggi',
    dampak: 'Potensi penundaan lelang fisik TA 2026 jika izin Persetujuan Penggunaan Kawasan Hutan (PPKH) dari KLHK terlambat.',
    instruksiPimpinan: 'Direktur Perencanaan segera surati Biro Hukum & Dit. Lahan untuk percepatan pengajuan PPKH terpadu ke Ditjen PKTL KLHK.',
  },
  {
    id: 'EW-02',
    isu: 'Rekomendasi Komisi Keamanan Jembatan (KKJTJ) Flyover KDA Simpang Kepri Mall',
    sektor: 'Darat',
    tingkatRisiko: 'Sedang',
    dampak: 'Penetapan spesifikasi box girder elevated memerlukan review dinamis respon spektrum gempa SNI 2833:2016.',
    instruksiPimpinan: 'Jadwalkan sidang pleno asistensi virtual bersama sekretariat KKJTJ Ditjen Bina Marga pekan depan.',
  },
  {
    id: 'EW-03',
    isu: 'Penetapan Titik Buangan Pengerukan (Dumping Area) Pelabuhan Sekupang',
    sektor: 'Laut dan Udara',
    tingkatRisiko: 'Sedang',
    dampak: 'Survei batimetri sudah 100%, namun dokumen lelang fisik pengerukan menunggu persetujuan lokasi buangan lumpur dari KKP.',
    instruksiPimpinan: 'Fasilitasi koordinasi tripartit BP Batam, KSOP Khusus Batam, dan Balai Pengelolaan Sumberdaya Pesisir & Laut (BPSPL) Padang.',
  },
];

// DATASET NO. 7 S.D. 9: PERSENTASE PEMANFAATAN DOKUMEN PERENCANAAN TEKNIS OLEH UNIT/INSTANSI LAIN (Satu Data Hal. 53)
export const PEMANFAATAN_DOKUMEN_LIST: PemanfaatanDokumenItem[] = [
  {
    datasetNo: 7,
    kategori: 'Bangunan',
    namaDataset: 'Persentase Pemanfaatan Dokumen Perencanaan Teknis Bangunan oleh Unit/Instansi Lain',
    persentasePemanfaatan: 75.0, // 6 dari 8 DED bangunan dimanfaatkan instansi/unit lain
    nilaiDedDimanfaatkan: 6675000000, // Rp 6,67 Miliar
    totalNilaiDed: 8900000000, // Rp 8,90 Miliar
    tahunPembuatanDed: '2023 - 2025',
    jumlahUnitPengguna: 5,
    daftarUnitPengguna: [
      'Direktorat Pembangunan Infrastruktur BP Batam',
      'Badan Usaha Rumah Sakit BP Batam (RSBP)',
      'Badan Usaha Fasilitas dan Lingkungan',
      'PT Bandara Internasional Batam (PT BIB)',
      'Kementerian Ketenagakerjaan RI (Balai Pelatihan Vokasi)',
    ],
    sifatData: 'TERBUKA',
    keterangan: 'Dokumen DED gedung perkantoran, pusat riset digital KEK Nongsa, klinik kesehatan, dan workshop vokasi maritim diadopsi langsung untuk eksekusi konstruksi fisik.',
  },
  {
    datasetNo: 8,
    kategori: 'Infrastruktur Perhubungan',
    namaDataset: 'Persentase Pemanfaatan Dokumen Perencanaan Teknis Infrastruktur Perhubungan oleh Unit/Instansi Lain',
    persentasePemanfaatan: 81.3, // 13 dari 16 DED darat, laut & udara dimanfaatkan
    nilaiDedDimanfaatkan: 22630000000, // Rp 22,63 Miliar
    totalNilaiDed: 27830000000, // Rp 27,83 Miliar
    tahunPembuatanDed: '2023 - 2025',
    jumlahUnitPengguna: 6,
    daftarUnitPengguna: [
      'Direktorat Pembangunan Infrastruktur BP Batam',
      'Badan Usaha Pelabuhan BP Batam (BUP)',
      'Balai Pelaksanaan Jalan Nasional (BPJN) Kepulauan Riau',
      'Dinas Bina Marga & Sumber Daya Air Kota Batam',
      'PT Bandara Internasional Batam (BIB Hang Nadim)',
      'Kantor Kesyahbandaran & Otoritas Pelabuhan (KSOP) Khusus Batam',
    ],
    sifatData: 'TERBUKA',
    keterangan: 'Dokumen DED pelebaran arteri jalan nasional, flyover, dermaga curah dermaga peti kemas Batu Ampar, dan apron kargo Bandara Hang Nadim digunakan bersama secara lintas instansi.',
  },
  {
    datasetNo: 9,
    kategori: 'Lingkungan',
    namaDataset: 'Persentase Pemanfaatan Dokumen Perencanaan Teknis Lingkungan oleh Unit/Instansi Lain',
    persentasePemanfaatan: 68.4, // 13 dari 19 DED utilitas, drainase & penghijauan dimanfaatkan
    nilaiDedDimanfaatkan: 11590000000, // Rp 11,59 Miliar
    totalNilaiDed: 16950000000, // Rp 16,95 Miliar
    tahunPembuatanDed: '2023 - 2025',
    jumlahUnitPengguna: 4,
    daftarUnitPengguna: [
      'Badan Usaha SPAM BP Batam',
      'Direktorat Pembangunan Infrastruktur BP Batam',
      'Dinas Lingkungan Hidup (DLH) Pemerintah Kota Batam',
      'Balai Pengelolaan Daerah Aliran Sungai (BPDAS) Sei Jang Duriangkang',
    ],
    sifatData: 'TERBUKA',
    keterangan: 'Dokumen DED masterplan drainase pengendali banjir, polder DAS Batam Centre, Multi-Utility Tunnel (MUT), dan sabuk hijau sempadan waduk digunakan untuk program ketahanan lingkungan perkotaan.',
  },
];
