import {
  BangunanLiarRecord,
  PersonilPengamananRecord,
  PengamananLingkunganObvitRecord,
  PenindakanKawasanAsetRecord,
  UnjukRasaRecord,
  BencanaAlamRecord,
  PenertibanRutinRecord,
} from './types';

// ==========================================
// DATASET NO. 1: PENERBITAN / PENEMUAN BANGUNAN LIAR
// Sumber: Satu Data Hal. 17 - 1'030 Total Entri Terdata
// ==========================================
export const BANGUNAN_LIAR_SUMMARY = {
  totalEntriTerdata: 1030,
  totalBangunanDitertibkan: 874,
  dalamProsesSp: 156,
  luasTotalTerdataHa: 142.8,
  lokasiTerbanyak: 'Sidomulyo & Tembesi Lama',
  kategoriDominan: 'Rumah / Kebun Liar',
};

export const BANGUNAN_LIAR_SAMPLES: BangunanLiarRecord[] = [
  {
    id: 1,
    tanggal: '2023-03-16',
    semester: 1,
    tahun: 2023,
    lokasi: 'Sidomulyo',
    swp: 'Batam Kota',
    jenisBangunan: 'Rumah',
    lamaMenghuni: '30 Tahun',
    caraMendapatkanLokasi: 'Tebas/Buka Sendiri',
    jumlah: 8,
    luasM2: 640,
    statusPenertiban: 'Ditertibkan',
  },
  {
    id: 2,
    tanggal: '2023-03-16',
    semester: 1,
    tahun: 2023,
    lokasi: 'Sidomulyo',
    swp: 'Batam Kota',
    jenisBangunan: 'Rumah / Kebun',
    lamaMenghuni: '10 Tahun',
    caraMendapatkanLokasi: 'Sewa',
    jumlah: 1,
    luasM2: 120,
    statusPenertiban: 'Ditertibkan',
  },
  {
    id: 3,
    tanggal: '2023-03-16',
    semester: 1,
    tahun: 2023,
    lokasi: 'Sidomulyo',
    swp: 'Batam Kota',
    jenisBangunan: 'Rumah / Kebun',
    lamaMenghuni: '20 Tahun',
    caraMendapatkanLokasi: 'Beli',
    jumlah: 1,
    luasM2: 180,
    statusPenertiban: 'Ditertibkan',
  },
  {
    id: 4,
    tanggal: '2023-03-16',
    semester: 1,
    tahun: 2023,
    lokasi: 'Sidomulyo',
    swp: 'Batam Kota',
    jenisBangunan: 'Rumah / Kebun',
    lamaMenghuni: '20 Tahun',
    caraMendapatkanLokasi: 'Beli',
    jumlah: 2,
    luasM2: 240,
    statusPenertiban: 'Ditertibkan',
  },
  {
    id: 5,
    tanggal: '2023-03-16',
    semester: 1,
    tahun: 2023,
    lokasi: 'Sidomulyo',
    swp: 'Batam Kota',
    jenisBangunan: 'Rumah / Kebun',
    lamaMenghuni: '20 Tahun',
    caraMendapatkanLokasi: 'Sewa',
    jumlah: 1,
    luasM2: 150,
    statusPenertiban: 'Ditertibkan',
  },
  {
    id: 6,
    tanggal: '2023-03-16',
    semester: 1,
    tahun: 2023,
    lokasi: 'Sidomulyo',
    swp: 'Batam Kota',
    jenisBangunan: 'Rumah / Kebun',
    lamaMenghuni: '25 Tahun',
    caraMendapatkanLokasi: 'Sewa',
    jumlah: 1,
    luasM2: 110,
    statusPenertiban: 'Ditertibkan',
  },
  {
    id: 7,
    tanggal: '2023-03-16',
    semester: 1,
    tahun: 2023,
    lokasi: 'Sidomulyo',
    swp: 'Batam Kota',
    jenisBangunan: 'Rumah / Kebun',
    lamaMenghuni: '25 Tahun',
    caraMendapatkanLokasi: 'Sewa',
    jumlah: 1,
    luasM2: 130,
    statusPenertiban: 'Ditertibkan',
  },
  {
    id: 8,
    tanggal: '2023-03-16',
    semester: 1,
    tahun: 2023,
    lokasi: 'Sidomulyo',
    swp: 'Batam Kota',
    jenisBangunan: 'Rumah / Kebun',
    lamaMenghuni: '25 Tahun',
    caraMendapatkanLokasi: 'Sewa',
    jumlah: 3,
    luasM2: 360,
    statusPenertiban: 'Ditertibkan',
  },
  {
    id: 9,
    tanggal: '2023-03-16',
    semester: 1,
    tahun: 2023,
    lokasi: 'Sidomulyo',
    swp: 'Batam Kota',
    jenisBangunan: 'Rumah / Kebun',
    lamaMenghuni: '30 Tahun',
    caraMendapatkanLokasi: 'Beli',
    jumlah: 2,
    luasM2: 260,
    statusPenertiban: 'Ditertibkan',
  },
  {
    id: 10,
    tanggal: '2023-03-16',
    semester: 1,
    tahun: 2023,
    lokasi: 'Sidomulyo',
    swp: 'Batam Kota',
    jenisBangunan: 'Rumah / Kebun / Kandang',
    lamaMenghuni: '10 Tahun',
    caraMendapatkanLokasi: 'Sewa',
    jumlah: 1,
    luasM2: 200,
    statusPenertiban: 'Ditertibkan',
  },
  {
    id: 11,
    tanggal: '2023-03-16',
    semester: 1,
    tahun: 2023,
    lokasi: 'Sidomulyo',
    swp: 'Batam Kota',
    jenisBangunan: 'Rumah/ Berkebun',
    lamaMenghuni: '32 Tahun',
    caraMendapatkanLokasi: 'Orang tua',
    jumlah: 1,
    luasM2: 175,
    statusPenertiban: 'Ditertibkan',
  },
  {
    id: 12,
    tanggal: '2023-03-16',
    semester: 1,
    tahun: 2023,
    lokasi: 'Sidomulyo',
    swp: 'Batam Kota',
    jenisBangunan: 'Rumah/ Usaha Jamur',
    lamaMenghuni: '6 Tahun',
    caraMendapatkanLokasi: 'Orang tua',
    jumlah: 3,
    luasM2: 450,
    statusPenertiban: 'Ditertibkan',
  },
  {
    id: 13,
    tanggal: '2023-03-16',
    semester: 1,
    tahun: 2023,
    lokasi: 'Sidomulyo',
    swp: 'Batam Kota',
    jenisBangunan: 'Rumah/ Berkebun',
    lamaMenghuni: '10 Tahun',
    caraMendapatkanLokasi: 'Tebas/Buka Sendiri',
    jumlah: 1,
    luasM2: 140,
    statusPenertiban: 'Ditertibkan',
  },
  {
    id: 14,
    tanggal: '2023-03-16',
    semester: 1,
    tahun: 2023,
    lokasi: 'Sidomulyo',
    swp: 'Batam Kota',
    jenisBangunan: 'Rumah/ Berkebun',
    lamaMenghuni: '22 Tahun',
    caraMendapatkanLokasi: 'Sewa',
    jumlah: 1,
    luasM2: 120,
    statusPenertiban: 'Ditertibkan',
  },
  {
    id: 15,
    tanggal: '2023-03-16',
    semester: 1,
    tahun: 2023,
    lokasi: 'Sidomulyo',
    swp: 'Batam Kota',
    jenisBangunan: 'Rumah/ Berkebun',
    lamaMenghuni: '24 Tahun',
    caraMendapatkanLokasi: 'Sewa',
    jumlah: 1,
    luasM2: 160,
    statusPenertiban: 'Ditertibkan',
  },
  {
    id: 16,
    tanggal: '2023-03-16',
    semester: 1,
    tahun: 2023,
    lokasi: 'Sidomulyo',
    swp: 'Batam Kota',
    jenisBangunan: 'Rumah/ Berkebun',
    lamaMenghuni: '25 Tahun',
    caraMendapatkanLokasi: 'Sewa',
    jumlah: 2,
    luasM2: 240,
    statusPenertiban: 'Ditertibkan',
  },
  {
    id: 17,
    tanggal: '2023-03-16',
    semester: 1,
    tahun: 2023,
    lokasi: 'Sidomulyo',
    swp: 'Batam Kota',
    jenisBangunan: 'Rumah/ Berkebun',
    lamaMenghuni: '32 Tahun',
    caraMendapatkanLokasi: 'Sewa',
    jumlah: 1,
    luasM2: 110,
    statusPenertiban: 'Ditertibkan',
  },
  {
    id: 18,
    tanggal: '2023-03-16',
    semester: 1,
    tahun: 2023,
    lokasi: 'Sidomulyo',
    swp: 'Batam Kota',
    jenisBangunan: 'Rumah/ Berkebun',
    lamaMenghuni: '5 Tahun',
    caraMendapatkanLokasi: 'Beli',
    jumlah: 1,
    luasM2: 90,
    statusPenertiban: 'Ditertibkan',
  },
  {
    id: 19,
    tanggal: '2023-03-16',
    semester: 1,
    tahun: 2023,
    lokasi: 'Sidomulyo',
    swp: 'Batam Kota',
    jenisBangunan: 'Rumah/ Berkebun/ Berjualan',
    lamaMenghuni: '12 Tahun',
    caraMendapatkanLokasi: 'Orang tua/Tebasan Sendiri',
    jumlah: 1,
    luasM2: 130,
    statusPenertiban: 'Ditertibkan',
  },
  {
    id: 20,
    tanggal: '2023-03-16',
    semester: 1,
    tahun: 2023,
    lokasi: 'Tembesi Lama',
    swp: 'Sagulung',
    jenisBangunan: 'Rumah / Kandang',
    lamaMenghuni: '20 Tahun',
    caraMendapatkanLokasi: 'Beli',
    jumlah: 1,
    luasM2: 210,
    statusPenertiban: 'Ditertibkan',
  },
  {
    id: 21,
    tanggal: '2023-08-11',
    semester: 2,
    tahun: 2023,
    lokasi: 'Tanjung Piayu DTA',
    swp: 'Sei Beduk',
    jenisBangunan: 'Pondok Liar Kebun',
    lamaMenghuni: '4 Tahun',
    caraMendapatkanLokasi: 'Tebas/Buka Sendiri',
    jumlah: 5,
    luasM2: 450,
    statusPenertiban: 'Ditertibkan',
  },
  {
    id: 22,
    tanggal: '2023-10-05',
    semester: 2,
    tahun: 2023,
    lokasi: 'Buffer Zone Sei Ladi',
    swp: 'Sekupang',
    jenisBangunan: 'Kios & Hunian Liar ROW',
    lamaMenghuni: '8 Tahun',
    caraMendapatkanLokasi: 'Sewa Liar',
    jumlah: 12,
    luasM2: 960,
    statusPenertiban: 'Ditertibkan',
  },
  {
    id: 23,
    tanggal: '2024-02-20',
    semester: 1,
    tahun: 2024,
    lokasi: 'Bengkong Sadai',
    swp: 'Bengkong',
    jenisBangunan: 'Rumah Papan Semi Permanen',
    lamaMenghuni: '15 Tahun',
    caraMendapatkanLokasi: 'Beli Liar',
    jumlah: 6,
    luasM2: 540,
    statusPenertiban: 'Ditegur (SP 1-3)',
  },
  {
    id: 24,
    tanggal: '2024-05-14',
    semester: 1,
    tahun: 2024,
    lokasi: 'ROW Jalan Mukakuning',
    swp: 'Sei Beduk',
    jenisBangunan: 'Lapak Liar & Kontainer',
    lamaMenghuni: '3 Tahun',
    caraMendapatkanLokasi: 'Buka Sendiri',
    jumlah: 9,
    luasM2: 380,
    statusPenertiban: 'Ditertibkan',
  },
];

// ==========================================
// DATASET NO. 3: JUMLAH PERSONIL PENGAMANAN (DITPAM BP BATAM)
// Total: 684 Personil Terlatih & Bersertifikasi
// ==========================================
export const PERSONIL_PENGAMANAN_DATA: PersonilPengamananRecord[] = [
  {
    id: 'pers-1',
    subdit: 'Subdit Pengamanan Hutan & DAS',
    tugasPokok: 'Patroli hutan lindung, pencegahan illegal logging, proteksi DTA waduk air baku',
    jumlahPersonil: 186,
    statusKesiapsiagaan: 'Siaga 1',
    poskoUtama: 'Posko Sei Ladi & Duriangkang',
    armadaPatroli: 18,
    persentaseKesiapan: 98.4,
  },
  {
    id: 'pers-2',
    subdit: 'Subdit Pengamanan Aset & Objek Vital',
    tugasPokok: 'Sterilisasi aset lahan BP Batam, pengamanan Gedung BIFZA, Pelabuhan & Bandara',
    jumlahPersonil: 215,
    statusKesiapsiagaan: 'Siaga 1',
    poskoUtama: 'Mako Ditpam Batam Centre',
    armadaPatroli: 24,
    persentaseKesiapan: 99.1,
  },
  {
    id: 'pers-3',
    subdit: 'Subdit Penindakan & Ketertiban Umum',
    tugasPokok: 'Operasi penertiban bangunan liar, tim terpadu penegakan Kepka, penertiban ROW',
    jumlahPersonil: 148,
    statusKesiapsiagaan: 'Siaga 2',
    poskoUtama: 'Mako Ditpam Batam Centre',
    armadaPatroli: 16,
    persentaseKesiapan: 96.6,
  },
  {
    id: 'pers-4',
    subdit: 'Tim Rescue, Damkar & Kesiapsiagaan Bencana',
    tugasPokok: 'Pemadaman karhutla, evakuasi bencana alam, pohon tumbang & pertolongan darurat air',
    jumlahPersonil: 135,
    statusKesiapsiagaan: 'Siaga 1',
    poskoUtama: 'Posko Damkar Duriangkang & Nongsa',
    armadaPatroli: 14,
    persentaseKesiapan: 97.8,
  },
];

export const TOTAL_PERSONIL_DITPAM = 684;

// ==========================================
// DATASET NO. 12: TOTAL PENGAMANAN LINGKUNGAN, HUTAN, ASET DAN OBJEK VITAL
// Total: 4.820 Kegiatan Pengamanan Terlaksana
// ==========================================
export const PENGAMANAN_OBVIT_DATA: PengamananLingkunganObvitRecord[] = [
  {
    id: 'obvit-1',
    namaObjekVital: 'Waduk & DTA Air Minum Sei Ladi',
    kategori: 'Waduk & DTA Air Baku',
    lokasi: 'Sekupang',
    totalKegiatanPengamanan: 1240,
    personilTerlibat: 186,
    statusKondisi: 'Aman Terkendali',
    titikPosko: 4,
    patroliPerHari: 4,
  },
  {
    id: 'obvit-2',
    namaObjekVital: 'Waduk & DTA Duriangkang',
    kategori: 'Waduk & DTA Air Baku',
    lokasi: 'Sei Beduk',
    totalKegiatanPengamanan: 1120,
    personilTerlibat: 154,
    statusKondisi: 'Aman Terkendali',
    titikPosko: 5,
    patroliPerHari: 4,
  },
  {
    id: 'obvit-3',
    namaObjekVital: 'Gedung Pusat Pemerintahan BIFZA',
    kategori: 'Gedung Pemerintahan',
    lokasi: 'Batam Centre',
    totalKegiatanPengamanan: 730,
    personilTerlibat: 95,
    statusKondisi: 'Aman Terkendali',
    titikPosko: 3,
    patroliPerHari: 6,
  },
  {
    id: 'obvit-4',
    namaObjekVital: 'Bandara Internasional Hang Nadim',
    kategori: 'Infrastruktur Transportasi',
    lokasi: 'Batu Besar, Nongsa',
    totalKegiatanPengamanan: 480,
    personilTerlibat: 78,
    statusKondisi: 'Aman Terkendali',
    titikPosko: 3,
    patroliPerHari: 3,
  },
  {
    id: 'obvit-5',
    namaObjekVital: 'Pelabuhan Domestik & Internasional Sekupang & Batu Ampar',
    kategori: 'Infrastruktur Transportasi',
    lokasi: 'Batu Ampar & Sekupang',
    totalKegiatanPengamanan: 510,
    personilTerlibat: 65,
    statusKondisi: 'Aman Terkendali',
    titikPosko: 3,
    patroliPerHari: 3,
  },
  {
    id: 'obvit-6',
    namaObjekVital: 'Kawasan Hutan Lindung Sei Harapan & Tiban',
    kategori: 'Kawasan Hutan Lindung',
    lokasi: 'Sekupang',
    totalKegiatanPengamanan: 420,
    personilTerlibat: 56,
    statusKondisi: 'Pengawasan Khusus',
    titikPosko: 2,
    patroliPerHari: 2,
  },
  {
    id: 'obvit-7',
    namaObjekVital: 'Kawasan Ekonomi Khusus Batam Aero Technic & Nongsa Digital',
    kategori: 'Kawasan Industri & KEK',
    lokasi: 'Nongsa',
    totalKegiatanPengamanan: 320,
    personilTerlibat: 50,
    statusKondisi: 'Aman Terkendali',
    titikPosko: 2,
    patroliPerHari: 2,
  },
];

export const TOTAL_GIAT_PENGAMANAN_OBVIT = 4820;

// ==========================================
// DATASET NO. 10: LUAS DATA PENINDAKAN KAWASAN ASET DAN OBJEK VITAL
// Total: 348.5 Hektar (3.485.000 m²) Lahan Aset Berhasil Ditindak/Diamankan
// ==========================================
export const PENINDAKAN_ASET_DATA: PenindakanKawasanAsetRecord[] = [
  {
    id: 'tindak-1',
    lokasiAset: 'Catchment Area Waduk Duriangkang',
    swp: 'Sei Beduk',
    luasPenindakanHa: 112.4,
    luasM2: 1124000,
    jenisAset: 'Buffer Zone Waduk',
    tahun: 2023,
    semester: 2,
    statusPenindakan: 'Selesai Disterilisasi',
    potensiKerugianDiamankanMiliar: 480.2,
  },
  {
    id: 'tindak-2',
    lokasiAset: 'Buffer Zone & DAS Waduk Sei Ladi',
    swp: 'Sekupang',
    luasPenindakanHa: 86.8,
    luasM2: 868000,
    jenisAset: 'Buffer Zone Waduk',
    tahun: 2023,
    semester: 1,
    statusPenindakan: 'Selesai Disterilisasi',
    potensiKerugianDiamankanMiliar: 390.5,
  },
  {
    id: 'tindak-3',
    lokasiAset: 'Kawasan Hutan Lindung Tiban & Bukit Senyum',
    swp: 'Batu Ampar',
    luasPenindakanHa: 54.2,
    luasM2: 542000,
    jenisAset: 'Hutan Lindung / Tangkapan Air',
    tahun: 2022,
    semester: 2,
    statusPenindakan: 'Pemasangan Plang BP Batam',
    potensiKerugianDiamankanMiliar: 220.0,
  },
  {
    id: 'tindak-4',
    lokasiAset: 'Koridor Pelebaran ROW 200 Jalan Mukakuning - Batu Aji',
    swp: 'Sagulung',
    luasPenindakanHa: 43.6,
    luasM2: 436000,
    jenisAset: 'ROW Jalan Protokol',
    tahun: 2023,
    semester: 2,
    statusPenindakan: 'Selesai Disterilisasi',
    potensiKerugianDiamankanMiliar: 310.8,
  },
  {
    id: 'tindak-5',
    lokasiAset: 'Lahan Alokasi Strategis Sidomulyo & Tembesi',
    swp: 'Batam Kota',
    luasPenindakanHa: 32.5,
    luasM2: 325000,
    jenisAset: 'Lahan Alokasi Strategis',
    tahun: 2023,
    semester: 1,
    statusPenindakan: 'Selesai Disterilisasi',
    potensiKerugianDiamankanMiliar: 275.4,
  },
  {
    id: 'tindak-6',
    lokasiAset: 'Catchment Area Waduk Tembesi & Sei Harapan',
    swp: 'Sekupang',
    luasPenindakanHa: 19.0,
    luasM2: 190000,
    jenisAset: 'Buffer Zone Waduk',
    tahun: 2024,
    semester: 1,
    statusPenindakan: 'Dalam Proses Penertiban',
    potensiKerugianDiamankanMiliar: 145.0,
  },
];

export const TOTAL_LUAS_PENINDAKAN_HA = 348.5;

// ==========================================
// DATASET NO. 7: REKAP PENGAMANAN UNJUK RASA
// Sumber: Satu Data Hal. 18 - 35 Entri Lengkap
// Menampilkan: Tanggal, Permasalahan, dan Jumlah Personil (serta Lokasi, Aliansi)
// ==========================================
export const UNJUK_RASA_DATA: UnjukRasaRecord[] = [
  {
    id: 1,
    tanggal: '2023-08-02',
    semester: 2,
    tahun: 2023,
    lokasi: 'Gedung BIFZA Batam Centre',
    aliansiMasyarakat: 'Warga Kelurahan Bukit Belian Kecamatan Batam Kota',
    permasalahan: 'Sering terjadi mati Air bersih dan gangguan suplai SPAM',
    jumlahPersonil: 120,
    estimasiMassa: 350,
    statusKeamanan: 'Kondusif',
  },
  {
    id: 2,
    tanggal: '2023-08-07',
    semester: 2,
    tahun: 2023,
    lokasi: 'Gedung BIFZA Batam Centre',
    aliansiMasyarakat: 'Gerakan Bersama Rakyat (GEBRAK)',
    permasalahan: 'Terkait pelebaran jalan ROW 200 dan ganti rugi bangunan warga',
    jumlahPersonil: 150,
    estimasiMassa: 500,
    statusKeamanan: 'Negosiasi Tertib',
  },
  {
    id: 3,
    tanggal: '2023-02-09',
    semester: 1,
    tahun: 2023,
    lokasi: 'Gedung BIFZA Batam Centre',
    aliansiMasyarakat: 'Warga Sei Nayon',
    permasalahan: 'Pembebasan Lahan dan kejelasan kavling siap bangun (KSB)',
    jumlahPersonil: 110,
    estimasiMassa: 400,
    statusKeamanan: 'Kondusif',
  },
  {
    id: 4,
    tanggal: '2023-08-14',
    semester: 2,
    tahun: 2023,
    lokasi: 'Gedung BIFZA Batam Centre',
    aliansiMasyarakat: 'Gerakan Bersama Rakyat (GEBRAK)',
    permasalahan: 'Terkait pelebaran jalan protokol dan mediasi kompensasi',
    jumlahPersonil: 140,
    estimasiMassa: 450,
    statusKeamanan: 'Kondusif',
  },
  {
    id: 5,
    tanggal: '2023-09-11',
    semester: 2,
    tahun: 2023,
    lokasi: 'Gedung BIFZA Batam Centre',
    aliansiMasyarakat: 'Aliansi Pemuda Melayu',
    permasalahan: 'Relokasi warga Rempang Eco-City dan penataan kawasan pesisir',
    jumlahPersonil: 450,
    estimasiMassa: 2500,
    statusKeamanan: 'Pengamanan Ketat',
  },
  {
    id: 6,
    tanggal: '2023-06-25',
    semester: 2,
    tahun: 2023,
    lokasi: 'Bandara Hang Nadim',
    aliansiMasyarakat: 'Taxi Online dan Taxi Konvensional',
    permasalahan: 'Ketentuan dan wilayah operasi penjemputan penumpang di bandara',
    jumlahPersonil: 85,
    estimasiMassa: 200,
    statusKeamanan: 'Negosiasi Tertib',
  },
  {
    id: 7,
    tanggal: '2023-09-15',
    semester: 2,
    tahun: 2023,
    lokasi: 'Gedung BIFZA Batam Centre',
    aliansiMasyarakat: 'Mahasiswa Kota Batam',
    permasalahan: 'Relokasi warga Rempang dan transparansi investasi PSN',
    jumlahPersonil: 380,
    estimasiMassa: 1200,
    statusKeamanan: 'Pengamanan Ketat',
  },
  {
    id: 8,
    tanggal: '2023-02-13',
    semester: 1,
    tahun: 2023,
    lokasi: 'Gedung BIFZA Batam Centre',
    aliansiMasyarakat: 'Warga Sei Nayon',
    permasalahan: 'Pembebasan Lahan dan penolakan penggusuran tanpa relokasi',
    jumlahPersonil: 125,
    estimasiMassa: 350,
    statusKeamanan: 'Kondusif',
  },
  {
    id: 9,
    tanggal: '2023-02-15',
    semester: 1,
    tahun: 2023,
    lokasi: 'Gedung BIFZA Batam Centre',
    aliansiMasyarakat: 'Warga Tangki 1000',
    permasalahan: 'Pembebasan Lahan dan kejelasan relokasi permukiman',
    jumlahPersonil: 175,
    estimasiMassa: 600,
    statusKeamanan: 'Pengamanan Ketat',
  },
  {
    id: 10,
    tanggal: '2023-02-10',
    semester: 1,
    tahun: 2023,
    lokasi: 'BIFZA Batam Centre',
    aliansiMasyarakat: 'Sei Nayon, Kelurahan Bengkong Sadai',
    permasalahan: 'Pembebasan Lahan dan perlindungan hak tinggal warga',
    jumlahPersonil: 130,
    estimasiMassa: 320,
    statusKeamanan: 'Kondusif',
  },
  {
    id: 11,
    tanggal: '2023-09-15',
    semester: 1,
    tahun: 2023,
    lokasi: 'BIFZA Batam Centre',
    aliansiMasyarakat: 'Mahasiswa Batam Bersatu',
    permasalahan: 'Relokasi Rempang dan hak-hak masyarakat adat pulau',
    jumlahPersonil: 290,
    estimasiMassa: 800,
    statusKeamanan: 'Negosiasi Tertib',
  },
  {
    id: 12,
    tanggal: '2023-03-15',
    semester: 1,
    tahun: 2023,
    lokasi: 'BIFZA Batam Centre',
    aliansiMasyarakat: 'Tangki 1000 Bukit Villa',
    permasalahan: 'Pembebasan Lahan dan ganti rugi tanaman serta bangunan',
    jumlahPersonil: 190,
    estimasiMassa: 650,
    statusKeamanan: 'Negosiasi Tertib',
  },
  {
    id: 13,
    tanggal: '2023-08-07',
    semester: 1,
    tahun: 2023,
    lokasi: 'BIFZA Batam Centre',
    aliansiMasyarakat: 'Gerakan Bersama Masyarakat',
    permasalahan: 'ROW Jalan 200 m dan kepastian penetapan batas patok',
    jumlahPersonil: 160,
    estimasiMassa: 480,
    statusKeamanan: 'Kondusif',
  },
  {
    id: 14,
    tanggal: '2023-08-14',
    semester: 1,
    tahun: 2023,
    lokasi: 'BIFZA Batam Centre',
    aliansiMasyarakat: 'Gerakan Bersama Masyarakat',
    permasalahan: 'ROW Jalan 200 m dan kelanjutan verifikasi faktual lapangan',
    jumlahPersonil: 160,
    estimasiMassa: 450,
    statusKeamanan: 'Kondusif',
  },
  {
    id: 15,
    tanggal: '2023-08-02',
    semester: 1,
    tahun: 2023,
    lokasi: 'BIFZA Batam Centre',
    aliansiMasyarakat: 'Bukit Raya, Kelurahan Belian, Kecamatan Batam Kota',
    permasalahan: 'Air Tidak lancar dan desakan normalisasi pipa transmisi',
    jumlahPersonil: 95,
    estimasiMassa: 280,
    statusKeamanan: 'Kondusif',
  },
  {
    id: 16,
    tanggal: '2024-03-12',
    semester: 1,
    tahun: 2024,
    lokasi: 'Gedung BIFZA Batam Centre',
    aliansiMasyarakat: 'Aliansi Serikat Buruh & Pekerja Batam (FSPMI)',
    permasalahan: 'Kebijakan Ketenagakerjaan Kawasan Industri & Fasilitas Pekerja',
    jumlahPersonil: 210,
    estimasiMassa: 850,
    statusKeamanan: 'Kondusif',
  },
  {
    id: 17,
    tanggal: '2024-06-20',
    semester: 1,
    tahun: 2024,
    lokasi: 'Pelabuhan Batu Ampar',
    aliansiMasyarakat: 'Asosiasi Logistik & Angkutan Pelabuhan Batam',
    permasalahan: 'Penataan Alur Truk Petikemas & Waktu Layanan Gate Pelabuhan',
    jumlahPersonil: 115,
    estimasiMassa: 250,
    statusKeamanan: 'Kondusif',
  },
];

// ==========================================
// DATASET NO. 6: REKAP KEJADIAN BENCANA ALAM & PENANGGULANGAN RESCUE DITPAM
// Sumber: Satu Data Hal. 18
// Menampilkan: Jenis Kegiatan dan Jumlah Kejadian
// ==========================================
export const BENCANA_ALAM_SUMMARY: {
  jenisKegiatan: string;
  kategoriBencana: string;
  jumlah: number;
  totalPersonilRescue: number;
  statusPenanganan: string;
  keterangan: string;
}[] = [
  {
    jenisKegiatan: 'Evakuasi & Pembersihan Pohon Tumbang di Jalan Protokol & Jalur Obvit',
    kategoriBencana: 'Pohon Tumbang',
    jumlah: 58,
    totalPersonilRescue: 174,
    statusPenanganan: '100% Selesai Ditangani',
    keterangan: 'Pembersihan jalan akses Sudirman, Hang Tuah, dan koridor Bandara',
  },
  {
    jenisKegiatan: 'Pemadaman Kebakaran Hutan dan Lahan (Karhutla) Hutan Lindung & Buffer',
    kategoriBencana: 'Kebakaran Hutan & Lahan',
    jumlah: 42,
    totalPersonilRescue: 320,
    statusPenanganan: '100% Dipadamkan & Didinginkan',
    keterangan: 'Buffer zone Waduk Duriangkang, Sei Ladi, dan Bukit Senyum',
  },
  {
    jenisKegiatan: 'Penanganan Tanah Longsor Lereng Tanggul & Penahan DTA Waduk',
    kategoriBencana: 'Longsor Tanggul',
    jumlah: 19,
    totalPersonilRescue: 135,
    statusPenanganan: '100% Selesai (Bronjong Terpasang)',
    keterangan: 'Pemasangan sandbag & bronjong kawat di lereng rawan Sei Ladi',
  },
  {
    jenisKegiatan: 'Penyelamatan & Evakuasi Banjir/Genangan di Wilayah Buffer Tangkapan Air',
    kategoriBencana: 'Banjir & Genangan',
    jumlah: 24,
    totalPersonilRescue: 192,
    statusPenanganan: '100% Tuntas Dievakuasi',
    keterangan: 'Normalisasi saluran outlet waduk dan penyelamatan aset warga',
  },
  {
    jenisKegiatan: 'Operasi SAR / Penyelamatan Korban Kecelakaan Air di Perairan Waduk',
    kategoriBencana: 'Penyelamatan Air',
    jumlah: 15,
    totalPersonilRescue: 105,
    statusPenanganan: '100% Berhasil Diselamatkan / Dievakuasi',
    keterangan: 'Patroli perahu karet Ditpam terhadap pemancing ilegal waduk',
  },
];

export const TOTAL_BENCANA_ALAM_KEJADIAN = 158;

// ==========================================
// DATASET NO. 9: REKAP DATA KEGIATAN PENERTIBAN RUTIN TIM TERPADU DITPAM
// Sumber: Satu Data Hal. 18 - 604 Entri Lengkap
// Menampilkan: Jenis Kegiatan dan Jumlah (serta Objek Penertiban, Tanggal, dll.)
// ==========================================
export const PENERTIBAN_RUTIN_DATA: PenertibanRutinRecord[] = [
  {
    id: 398,
    jenisKegiatan: 'Pendampingan Penertiban',
    objekPenertiban: 'Bangunan Bermasalah',
    kategori: 'Bangunan Liar',
    tanggal: '2022-02-07',
    semester: 1,
    tahun: 2022,
    jumlah: 75,
    satuan: 'Unit Bangunan',
    lokasi: 'Kawasan Tanjung Uma & Bengkong',
  },
  {
    id: 399,
    jenisKegiatan: 'Pendampingan dan Pengamanan',
    objekPenertiban: 'Waduk Sei Ladi',
    kategori: 'Waduk & Air Baku',
    tanggal: '2022-01-01',
    semester: 1,
    tahun: 2022,
    jumlah: 1500,
    satuan: 'Meter Buffer Zone',
    lokasi: 'Buffer Area Sei Ladi Sekupang',
  },
  {
    id: 400,
    jenisKegiatan: 'Patroli dan Monitoring',
    objekPenertiban: 'Pondok / Garapan Baru',
    kategori: 'Bangunan Liar',
    tanggal: '2022-04-08',
    semester: 1,
    tahun: 2022,
    jumlah: 4,
    satuan: 'Titik Pondok',
    lokasi: 'DTA Duriangkang',
  },
  {
    id: 401,
    jenisKegiatan: 'Patroli dan Monitoring',
    objekPenertiban: 'Pembersihan eceng gondok',
    kategori: 'Waduk & Air Baku',
    tanggal: '2022-04-14',
    semester: 1,
    tahun: 2022,
    jumlah: 1,
    satuan: 'Hamparan Luas (2 Ha)',
    lokasi: 'Genangan Waduk Sei Harapan',
  },
  {
    id: 402,
    jenisKegiatan: 'Patroli, Monitoring dan Himbauan',
    objekPenertiban: 'Sosialisasi / Kayu Bulat',
    kategori: 'Illegal Logging',
    tanggal: '2022-07-05',
    semester: 2,
    tahun: 2022,
    jumlah: 50,
    satuan: 'Batang Batang Kayu',
    lokasi: 'Hutan Lindung Tiban',
  },
  {
    id: 403,
    jenisKegiatan: 'Patroli dan Monitoring',
    objekPenertiban: 'Pendataan rumah / pondok',
    kategori: 'Bangunan Liar',
    tanggal: '2023-07-28',
    semester: 2,
    tahun: 2023,
    jumlah: 52,
    satuan: 'Pondok Terdata',
    lokasi: 'Sidomulyo & Tembesi',
  },
  {
    id: 404,
    jenisKegiatan: 'Patroli, Monitoring, Sosialisasi serta Penertiban',
    objekPenertiban: 'Tanam Tumbuh',
    kategori: 'Tanam Tumbuh & Kebun',
    tanggal: '2022-09-05',
    semester: 2,
    tahun: 2022,
    jumlah: 520,
    satuan: 'Batang Pohon Liar',
    lokasi: 'Buffer Waduk Sei Ladi',
  },
  {
    id: 405,
    jenisKegiatan: 'Patroli dan Monitoring',
    objekPenertiban: 'Sisa Pondok / bekas terpal',
    kategori: 'Bangunan Liar',
    tanggal: '2023-02-14',
    semester: 1,
    tahun: 2023,
    jumlah: 2,
    satuan: 'Titik Terpal',
    lokasi: 'Kawasan Tangki 1000',
  },
  {
    id: 406,
    jenisKegiatan: 'Patroli dan Monitoring',
    objekPenertiban: 'Pengamanan Kegiatan Aksi Milenial',
    kategori: 'Aksi Massa',
    tanggal: '2022-04-17',
    semester: 1,
    tahun: 2022,
    jumlah: 2000,
    satuan: 'Peserta Diamankan',
    lokasi: 'Alun-Alun Engku Putri Batam Centre',
  },
  {
    id: 407,
    jenisKegiatan: 'Patroli dan Monitoring',
    objekPenertiban: 'Tanam Tumbuh',
    kategori: 'Tanam Tumbuh & Kebun',
    tanggal: '2023-05-23',
    semester: 1,
    tahun: 2023,
    jumlah: 500,
    satuan: 'Batang Pohon Liar',
    lokasi: 'DTA Waduk Tembesi',
  },
  {
    id: 408,
    jenisKegiatan: 'Patroli dan Monitoring',
    objekPenertiban: 'Tanam Tumbuh',
    kategori: 'Tanam Tumbuh & Kebun',
    tanggal: '2022-10-20',
    semester: 2,
    tahun: 2022,
    jumlah: 810,
    satuan: 'Batang Pohon Liar',
    lokasi: 'Hutan Lindung Sei Harapan',
  },
  {
    id: 409,
    jenisKegiatan: 'Patroli dan Monitoring',
    objekPenertiban: 'Tangkul',
    kategori: 'Waduk & Air Baku',
    tanggal: '2023-08-04',
    semester: 2,
    tahun: 2023,
    jumlah: 1,
    satuan: 'Unit Jaring Besar',
    lokasi: 'Waduk Sei Ladi',
  },
  {
    id: 410,
    jenisKegiatan: 'Patroli dan Monitoring',
    objekPenertiban: 'Tanam Tumbuh',
    kategori: 'Tanam Tumbuh & Kebun',
    tanggal: '2022-09-02',
    semester: 2,
    tahun: 2022,
    jumlah: 200,
    satuan: 'Batang Pohon Liar',
    lokasi: 'ROW Jalan Trans Barelang',
  },
  {
    id: 411,
    jenisKegiatan: 'Patroli dan Monitoring',
    objekPenertiban: 'Pelaku Illegal Loging',
    kategori: 'Illegal Logging',
    tanggal: '2022-11-28',
    semester: 2,
    tahun: 2022,
    jumlah: 1,
    satuan: 'Kasus Ditindak Pidana',
    lokasi: 'Hutan Lindung Duriangkang',
  },
  {
    id: 412,
    jenisKegiatan: 'Patroli dan Monitoring',
    objekPenertiban: 'Tanam Tumbuh',
    kategori: 'Tanam Tumbuh & Kebun',
    tanggal: '2023-07-11',
    semester: 2,
    tahun: 2023,
    jumlah: 500,
    satuan: 'Batang Pohon Liar',
    lokasi: 'DTA Waduk Mukakuning',
  },
  {
    id: 413,
    jenisKegiatan: 'Patroli dan Monitoring',
    objekPenertiban: 'Bak bekas pencucian pasir/pondok/pelampung',
    kategori: 'Tambang Pasir Ilegal',
    tanggal: '2023-05-16',
    semester: 1,
    tahun: 2023,
    jumlah: 14,
    satuan: 'Unit Instalasi Pasir',
    lokasi: 'Kawasan Nongsa & Tembesi',
  },
  {
    id: 414,
    jenisKegiatan: 'Patroli dan Monitoring',
    objekPenertiban: 'Tanam Tumbuh',
    kategori: 'Tanam Tumbuh & Kebun',
    tanggal: '2023-07-13',
    semester: 2,
    tahun: 2023,
    jumlah: 100,
    satuan: 'Batang Pohon Liar',
    lokasi: 'Catchment Area Waduk Duriangkang',
  },
  {
    id: 415,
    jenisKegiatan: 'Patroli dan Monitoring',
    objekPenertiban: 'Kayu Bulat',
    kategori: 'Illegal Logging',
    tanggal: '2022-07-15',
    semester: 2,
    tahun: 2022,
    jumlah: 40,
    satuan: 'Batang Kayu Sitaan',
    lokasi: 'Perbatasan Hutan Lindung Nongsa',
  },
  {
    id: 416,
    jenisKegiatan: 'Patroli dan Monitoring',
    objekPenertiban: 'Pendampingan Pengukuran Lahan',
    kategori: 'Bangunan Liar',
    tanggal: '2023-07-26',
    semester: 2,
    tahun: 2023,
    jumlah: 2525,
    satuan: 'Meter Panjang Batas',
    lokasi: 'Batam Kota & Sagulung',
  },
  {
    id: 417,
    jenisKegiatan: 'Patroli dan Monitoring',
    objekPenertiban: 'Bubu/ Tanam Tumbuh',
    kategori: 'Waduk & Air Baku',
    tanggal: '2022-12-23',
    semester: 2,
    tahun: 2022,
    jumlah: 51,
    satuan: 'Perangkap Bubu Ikan',
    lokasi: 'Waduk Duriangkang',
  },
];

// Aggregat Jenis Kegiatan Penertiban untuk Visualisasi Rekap
export const PENERTIBAN_BY_JENIS_KEGIATAN = [
  {
    jenisKegiatan: 'Patroli dan Monitoring Tanam Tumbuh & Perambahan',
    jumlahKegiatan: 248,
    totalObjekDitertibkan: 3850,
    kategori: 'Tanam Tumbuh',
  },
  {
    jenisKegiatan: 'Pendampingan & Penertiban Bangunan Liar/Bermasalah',
    jumlahKegiatan: 165,
    totalObjekDitertibkan: 1030,
    kategori: 'Bangunan Liar',
  },
  {
    jenisKegiatan: 'Pendampingan Pengamanan Waduk & Alat Tangkap Ilegal',
    jumlahKegiatan: 94,
    totalObjekDitertibkan: 2680,
    kategori: 'Waduk & Obvit',
  },
  {
    jenisKegiatan: 'Penertiban Tambang Pasir Ilegal & Pencucian Pasir',
    jumlahKegiatan: 48,
    totalObjekDitertibkan: 62,
    kategori: 'Tambang Ilegal',
  },
  {
    jenisKegiatan: 'Pencegahan & Tindak Pidana Illegal Logging',
    jumlahKegiatan: 32,
    totalObjekDitertibkan: 185,
    kategori: 'Illegal Logging',
  },
  {
    jenisKegiatan: 'Pendampingan Pengukuran & Pematokan Lahan Aset',
    jumlahKegiatan: 17,
    totalObjekDitertibkan: 4850,
    kategori: 'Aset BP Batam',
  },
];

// ==========================================
// DATASET KHUSUS POIN 8: RANCANGAN MONITORING ATASAN
// Visualisasi Analitik Strategis untuk Pimpinan
// ==========================================

// 1. Tren Beban Operasi & Personil Dikerahkan per Bulan
export const TREND_BULANAN_OPERASI_DITPAM = [
  { bulan: 'Jan', unjukRasa: 2, penertiban: 42, bencanaAlam: 14, personilTerjun: 580 },
  { bulan: 'Feb', unjukRasa: 4, penertiban: 55, bencanaAlam: 18, personilTerjun: 620 },
  { bulan: 'Mar', unjukRasa: 3, penertiban: 48, bencanaAlam: 12, personilTerjun: 590 },
  { bulan: 'Apr', unjukRasa: 2, penertiban: 50, bencanaAlam: 8, personilTerjun: 540 },
  { bulan: 'Mei', unjukRasa: 1, penertiban: 62, bencanaAlam: 10, personilTerjun: 560 },
  { bulan: 'Jun', unjukRasa: 3, penertiban: 58, bencanaAlam: 15, personilTerjun: 610 },
  { bulan: 'Jul', unjukRasa: 2, penertiban: 65, bencanaAlam: 11, personilTerjun: 640 },
  { bulan: 'Agu', unjukRasa: 6, penertiban: 70, bencanaAlam: 22, personilTerjun: 680 },
  { bulan: 'Sep', unjukRasa: 5, penertiban: 60, bencanaAlam: 20, personilTerjun: 684 },
  { bulan: 'Okt', unjukRasa: 3, penertiban: 54, bencanaAlam: 16, personilTerjun: 630 },
  { bulan: 'Nov', unjukRasa: 2, penertiban: 44, bencanaAlam: 14, personilTerjun: 570 },
  { bulan: 'Des', unjukRasa: 2, penertiban: 46, bencanaAlam: 18, personilTerjun: 600 },
];

// 2. Matriks Indeks Kerawanan 6 Sektor Strategis Wilayah Batam
export const SEKTOR_KERAWANAN_STRATEGIS = [
  {
    sektor: 'Batam Centre & Kantor BIFZA',
    fokusUtama: 'Pusat Pemerintahan, Unjuk Rasa & Obvit',
    levelRisiko: 'Tinggi',
    skorRisiko: 88,
    alokasiPersonil: 215,
    poskoAktif: 3,
    kejadianTahunIni: 48,
    statusKondisi: 'Siaga 1',
  },
  {
    sektor: 'Duriangkang & Sei Beduk',
    fokusUtama: 'Waduk Utama (Air Bersih 70% Batam) & Buffer Zone',
    levelRisiko: 'Tinggi',
    skorRisiko: 85,
    alokasiPersonil: 154,
    poskoAktif: 5,
    kejadianTahunIni: 72,
    statusKondisi: 'Siaga 1',
  },
  {
    sektor: 'Sekupang & Sei Ladi',
    fokusUtama: 'DTA Waduk Sei Ladi & Hutan Lindung Sei Harapan',
    levelRisiko: 'Sedang-Tinggi',
    skorRisiko: 79,
    alokasiPersonil: 186,
    poskoAktif: 4,
    kejadianTahunIni: 65,
    statusKondisi: 'Siaga 2',
  },
  {
    sektor: 'Nongsa & Bandara Hang Nadim',
    fokusUtama: 'Gerbang Udara Internasional & KEK Nongsa Digital',
    levelRisiko: 'Sedang',
    skorRisiko: 62,
    alokasiPersonil: 78,
    poskoAktif: 3,
    kejadianTahunIni: 28,
    statusKondisi: 'Rutin Operasional',
  },
  {
    sektor: 'Batu Ampar & Pelabuhan',
    fokusUtama: 'Gerbang Logistik Petikemas & Pelabuhan Penumpang',
    levelRisiko: 'Sedang',
    skorRisiko: 68,
    alokasiPersonil: 65,
    poskoAktif: 3,
    kejadianTahunIni: 34,
    statusKondisi: 'Rutin Operasional',
  },
  {
    sektor: 'Sagulung, Tembesi & Rempang',
    fokusUtama: 'ROW Jalan 200, Relokasi Lahan & Waduk Tembesi',
    levelRisiko: 'Tinggi',
    skorRisiko: 92,
    alokasiPersonil: 148,
    poskoAktif: 4,
    kejadianTahunIni: 85,
    statusKondisi: 'Siaga 1',
  },
];
